### ISSUE TITLE
VALIDATION_ERROR: "None is not of type 'string'"

### ISSUE THREAD

**Issue by tonybadguy** [Yelp/yelp-fusion#100]
I get a 400 Bad Request error with some phone numbers of businesses even though the format is correct.

For example:
This call always fails:
```https://api.yelp.com/v3/businesses/search/phone?phone=+16192311515```

Sometimes I get this error:
```
{
  "error": {
    "description": "None is not of type 'string'",
    "field": 2,
    "code": "VALIDATION_ERROR"
  }
}
```

Sometimes it says field 3
```
{
  "error": {
    "code": "VALIDATION_ERROR",
    "description": "None is not of type 'string'",
    "field": 3
  }
}
```

**Comment by mittonk** [comment]
Reproduced issue, definitely a bug.

Several business listings related to the San Diego Zoo all share that number:
* https://www.yelp.com/biz/san-diego-zoo-san-diego
* https://www.yelp.com/biz/sabertooth-grill-san-diego
* https://www.yelp.com/biz/tuskers-trunk-san-diego
...

We'll have a look.

**Comment by mittonk** [comment]
@tonybadguy : Looks like we resolved this as part of another bug fix.  Works now!
