### ISSUE TITLE
Overall Rating

### ISSUE THREAD

**Issue by cloud251** [Yelp/yelp-fusion#102]
Hi , its possible from this API to get the info that is displayed on Overall Rating ? or monthly trend?  don't need the text of reviews just the Total Reviews and what stars has every Review

Thanks

**Comment by mittonk** [comment]
Sounds like you're asking about the graphs in the "Rating Details" pop-up; those aren't available in the API, sorry.

(For other readers: We do provide the single-number overall `rating`.)
