### ISSUE TITLE
How to get business website url

### ISSUE THREAD

**Issue by NikitaTurakhia** [Yelp/yelp-fusion#103]
Hello,

Is it possible to get the business website url in yelp AI v3?

Thanks,

**Comment by mittonk** [comment]
Sorry, that's not yet available in the API!

**Comment by mbrahimi617** [comment]
@mittonk I've been wondering this myself, but from what I can tell, Yelp is trying to purposefully return their own business pages in the JSON responses instead of the actual websites belonging to these businesses. This may be to increase their own CPA value or SEO presence via redirects.

**Comment by zirubak** [comment]
@mittonk Do you have a plan to support this function?

**Comment by WilliamColmenares** [comment]
+1 for this.
