### ISSUE TITLE
Inconsistent coordinates returned for some POI

### ISSUE THREAD

**Issue by cledra** [Yelp/yelp-fusion#104]
Hello,

Maybe I'm missing something, but some of the POI returned by Yelp have geographical coordinates that look wrong to me. Hereafter I describe a way to reproduce what I have observed.

I run the following command to get a list of businesses matching the keyword "pizza" near location 35.587878, 139.730947 (somewhere in Japan) :
curl -H "Authorization: bearer my-token" https://api.yelp.com/v3/businesses/search?term=pizza\&latitude=35.587878\&longitude=139.73094

So I get a business list as response. Among those places, no less than 5 have the exact same geographical coordinates :
"coordinates": {"longitude": 135.7523651, "latitude": 35.0002708}

This point is located hundreds of kms away from the location I gave as input, which is unexpected.
Furthermore, it is inconsistent with the "distance" field of those places, which contain short distance as expected (4km, 7km...)

Please see attached file if you cannot reproduce the problem.

[yelp-result.txt](https://github.com/Yelp/yelp-fusion/files/592134/yelp-result.txt)

**Comment by mittonk** [comment]
@cledra : Hm, looking.

**Comment by mittonk** [comment]
Reproduced issue, traced it to some of our location data.  Looking into what we can do about it.

**Comment by bstrobach** [comment]
Any updates on this one? I have the same issue for the "servicestations" category.

**Comment by mittonk** [comment]
Still discussing here; this is a data quality issue, rather than a code bug, so there's not a quick bug fix solution.

This can affect a variety of categories and geographical areas.

**Comment by mittonk** [comment]
@cledra , @bstrobach : We've resolved this data issue.  Location data (especially in Japan and the UK) is now more reliable.

If you see other problems, please report them as fresh GIthub issues --- there's a lot of data in the world and not all of it is perfect, but this particular set of issues is now resolved.
