### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Phenix972** [Yelp/yelp-fusion#106]
Hello, using the application API "https://api.yelp.com/v3/businesses/search …" 
I have an error: {"error": { "description": "Something went wrong internally, please try again later "," code ":" INTERNAL_ERROR "}} when using the offset 999.Url: https://api.yelp.com/v3/businesses/search?location=Paris&term=Restaurants&limit=50&offset=999 …

**Comment by tomelm** [comment]
Hey @Phenix972! That's likely being caused because your offset and limit are too high. The API only allows a maximum of 1000 businesses to be returned per query which you've hit with that limit and offset.

The error message isn't helpful though, we'll get a fix going to make that more obvious.

**Comment by Phenix972** [comment]
Ok Thanks for the reply.
It means that I can not recover the other data presented in the response of the request?

**Comment by tomelm** [comment]
Correct, the combined offset and limit has to be under 1000 or the entire request will fail.

**Comment by adnan-wahab** [comment]
hi im still running into this issue with this request 

```
payload = {'location': 'nyc', 'radius': '4000', 'limit': 50}
headers = {'Authorization': 'bearer %s' % app_secret}
places = requests.get(url, params=payload, headers=headers) # (your url)

```
