### ISSUE TITLE
No data access

### ISSUE THREAD

**Issue by cendelinova** [Yelp/yelp-fusion#108]
Hello, 
I am trying to get data by this url https://api.yelp.com/v3/businesses/search?categories=petstore&location=Brno and I dont get any data. According to this page https://www.yelp.com/search?find_loc=Brno&start=0&cflt=pets there are some petstores. If I change the location to Prague, it works. Do you know where problem is?

Thanks

Petra

**Comment by mittonk** [comment]
@cendelinova : Looks like none of those businesses have reviews.

* https://www.yelp.com/developers/documentation/v3/business_search
> Note: at this time, the API does not return businesses without any reviews.

Sorry!
