### ISSUE TITLE
User images not returned, Star rating not returned

### ISSUE THREAD

**Issue by ARYP** [Yelp/yelp-fusion#109]
I'm only getting 1 user image returned and no star ratings. The image can be in position 1, 2 or 3 but is mostly in position 1.  No Star Rank for the businesses are being returned. See my images uploaded. 
![yelp-showing-second-image](https://cloud.githubusercontent.com/assets/627015/20468895/623f79fe-af3f-11e6-90ef-9b84126b985e.PNG)
![yelp-showing-third-image](https://cloud.githubusercontent.com/assets/627015/20468898/6e081fca-af3f-11e6-88a7-31927b7608d0.PNG)

**Comment by ARYP** [comment]
![yelp-showing-first-image](https://cloud.githubusercontent.com/assets/627015/20468957/d2c70dcc-af3f-11e6-947c-eeef88390157.PNG)

**Comment by mittonk** [comment]
@ARYP : I can reproduce part of this.  Here's what I see for Main Auto Body:

* https://api.yelp.com/v3/businesses/main-auto-body-garland/reviews

```
{
  "total": 3,
  "reviews": [
    {
      "text": "WOW. I am beyond excited to be writing this review. I brought my car here to Main Auto Body to get some body work done. I wasn't sure how it would turn out...",
      "rating": 5,
      "user": {
        "image_url": "https://s3-media3.fl.yelpcdn.com/photo/njYetG-dzjvQDuAqiSYSpg/o.jpg",
        "name": "Elizabeth H."
      },
      "url": "https://www.yelp.com/biz/main-auto-body-garland?hrid=1BixgnFMOWraijzSxkT3UA&adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ssWONR4BhYiARowH3vsVEA",
      "time_created": "2015-08-21 11:03:43"
    },
    {
      "text": "I highly recommend Main Auto Body! The hood and trunk were getting pretty tired on my 93 Caprice, so I decided to take it over to Main Auto Body. They gave...",
      "rating": 5,
      "user": {
        "image_url": null,
        "name": "Matt T."
      },
      "url": "https://www.yelp.com/biz/main-auto-body-garland?hrid=uZDMuoqmoDj4FvQIh2KaQA&adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ssWONR4BhYiARowH3vsVEA",
      "time_created": "2016-03-27 20:54:12"
    },
    {
      "text": "I am impressed.  I came upon Main Auto Body after I had a wreck on a Friday evening and I left my car in a valet lot to deal with on Saturday.  I found them...",
      "rating": 4,
      "user": {
        "image_url": null,
        "name": "Diana D."
      },
      "url": "https://www.yelp.com/biz/main-auto-body-garland?hrid=qGR6BiteknFint4avjmzdA&adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ssWONR4BhYiARowH3vsVEA",
      "time_created": "2014-09-26 09:38:51"
    }
  ]
}
```

1. Reproduced photo issue: I see two of the users are missing photos, but they appear on
* https://www.yelp.com/biz/main-auto-body-garland

I'll dig into that.

2. However, I don't see what you mean by 
> No Star Rank for the businesses are being returned

What are you expecting?  Fusion provides the `rating` key, which is a change from V2's `rating_img_url` (https://www.yelp.com/developers/documentation/v2/business).  

For Fusion, we usually suggest hosting the assets from https://www.yelp.com/developers/display_requirements on your own site.

**Comment by ARYP** [comment]
My programmer was able to get the 'star ratings' to render. He figured that out. Thank you for the quick reply!

**Comment by mittonk** [comment]
Still happening to the same set of users.  That rules out a few possibilities, need to dig deeper.

**Comment by mittonk** [comment]
Found the problem, working on a fix.

**Comment by mittonk** [comment]
Fixed, sorry for the complications!  For our favorite three reviews:
```
        "image_url": "https://s3-media3.fl.yelpcdn.com/photo/njYetG-dzjvQDuAqiSYSpg/o.jpg",
...
        "image_url": "https://s3-media2.fl.yelpcdn.com/photo/6y6UPpHZy91oBBWn74S7Sg/o.jpg",
...
        "image_url": "https://s3-media4.fl.yelpcdn.com/photo/iS4GAtsCwluRtBfO0Ktr9w/o.jpg",
```

@ARYP , @OrrYakobi : Thanks for the bug reports!

**Comment by ARYP** [comment]
YES!   Images are there!   Thank you!  You rock!
