### ISSUE TITLE
Examples 

### ISSUE THREAD

**Issue by DZuz14** [Yelp/yelp-fusion#110]
Are you guys willing to take pull requests for documentation help and what not? Reason being, I think the docs for getting up in running could be improved a bit. I will be hacking away on getting it up and running with Node this week. Already have a simple version setup, but needs more work.

Appreciate the work you guys are doing, otherwise I'd be building my data feed myself, which would be comical to see.

**Comment by mittonk** [comment]
We're definitely looking at writing some examples ourself.

I'd enjoy seeing a pull request --- but we're still figuring out the best practices, so don't know exactly what we're aiming for in these examples yet.

**Comment by mittonk** [comment]
@DZuz14 : I've started the ball rolling with a Python example:
* https://github.com/Yelp/yelp-fusion/tree/master/fusion/python

If you'd like to take a swing at Node:
# Please follow the same overall approach as the Python sample ("search then drill into first result" functionality, directory placement, README, etc)
# Please fork the repository to your account, make changes, push, and open a pull request.

**Comment by mittonk** [comment]
(And as to documentation changes: Please file an issue.  If the code is managed under Github you can also file a pull request, but most of yelp.com/developers isn't.)

**Comment by mittonk** [comment]
@tonybadguy contributed a Node example in #126 , calling this done.
