### ISSUE TITLE
Error creating Access Token with Postman 

### ISSUE THREAD

**Issue by donaghhealy** [Yelp/yelp-fusion#112]
Get this error when I attempt to create an access token through Postman: "
"Error getting access token from client_credentials flow: SyntaxError: Unexpected token < in JSON at position 0"
I've also tried it directly in the browser: https://api.yelp.com/oauth2/token?client_id=[.....]&client_secret=[.....]&grant_type=client_credentials 
and get an error "{"error": {"description": "/oauth2/token", "code": "VALIDATION_ERROR"}}"

All help appreciated. Really looking forward to getting started with the Yelp API but have hit this stumbling block.

Many thanks,
Donagh.

**Comment by mittonk** [comment]
@donaghhealy : I've got a couple ideas.
1. "Unexpected token <" sounds like an HTTP error message somewhere in the middle of the flow --- is that still happening every time?

2. Did you add header "Content-Type: application/x-www-form-urlencoded"?

3. The `client_id etc should be in the request body; your "directly in the browser" looks like the args are in the query string.  (Also, most browsers would send a GET for that, rather than the required POST).

**Comment by donaghhealy** [comment]
Hi Ken,
Thanks for getting back to me. I tried it again on a different network (the other networks might have been a  bit flaky?) and got through this time with Postman, so all setup to go now.

Many thanks for your helpful suggestions.
Donagh.

**Comment by mittonk** [comment]
Great, glad things sorted themselves out!

**Comment by anujrohila** [comment]
Hello Mittonk,

Thanks for this help.

My issue is : Browser sending wrong request POST to get.
 $.ajax({
        url: "https://api.yelp.com/oauth2/token",
        type: "POST",
        headers: {
            "cache-control": "no-cache",
            "content-type": "application/x-www-form-urlencoded",
        },
        data: {
            "client_id": yelpClientId,
            "client_secret": yelpClientSecret,
            "grant_type": "client_credentials"
        },
        success: function (accessTokenResponse, textStatus, request) {
            
        },
        error: function (textStatus, errorThrown) {
            //alert("An error has occured, please try again.");
        }
    });

This synatx work perfectly in all case to get token
