### ISSUE TITLE
Incorrect info returned from Search API when location=Dublin & locale=en_IE

### ISSUE THREAD

**Issue by donaghhealy** [Yelp/yelp-fusion#113]
Hi,

The API is picking up Dublin, Ohio not Dublin, Ireland, even though the locale is set to Ireland.

https://api.yelp.com/v3/businesses/search?term=restaurants&location=Dublin&locale=en_IE

Thanks,
Donagh.

**Comment by tomelm** [comment]
Hey @donaghhealy,

Locale does not affect the search location. Using a more specific search location here should resolve it pulling businesses from the location you want.
