### ISSUE TITLE
Getting Access token

### ISSUE THREAD

**Issue by harrykrish** [Yelp/yelp-fusion#114]
uauth = OAuth1('consumer_key', 'consumer_secret',
                  'token_key', 'token_secret,')
requests.get('https://api.yelp.com/oauth2/token',auth=uauth).json()

getting validation error. 

How do i get access token. I am able to do search in yelp but not get business specific data. error says access token not specified

**Comment by harrykrish** [comment]
Please give me a solution to implement in python

**Comment by tomelm** [comment]
Hey @harrykrish, it looks like you're trying to gain access to the Fusion API using v2's OAuth client credentials. Those credentials are not compatible with Fusion's auth system (OAuth 2) so you'll either need to use the Fusion client credentials found here (https://www.yelp.com/developers/v3/manage_app) or auth using your OAuth 1 credentials for v2 (code samples here: https://github.com/Yelp/yelp-api)

**Comment by tomelm** [comment]
For Python specifically, you should use your v2 client library: https://github.com/Yelp/yelp-python

**Comment by mittonk** [comment]
(And for other readers looking for a Fusion setup: check out the small Python example at https://github.com/Yelp/yelp-fusion/tree/master/fusion/python .  

Both V2 and Fusion work --- but creds, endpoints, and code all need to be the same system, you can't mix-and-match.)

**Comment by mittonk** [comment]
Based on #117 , looks like @harrykrish got things working!  Closing this.

**Comment by harrykrish** [comment]
Yes. I passed client id and secret to get the token. I used that along with request url to gain access. Thank you!
