### ISSUE TITLE
Unable to write a review using the Yelp api?

### ISSUE THREAD

**Issue by oliverlewis** [Yelp/yelp-fusion#116]
Will I be able to write a review using the API?

**Comment by tomelm** [comment]
No, that's not functionality we currently plan to expose through the API.

**Comment by oliverlewis** [comment]
That's functionality that I require to use urgently for my class project.
Is there a better way to implement this from my side?

**Comment by tomelm** [comment]
Unfortunately not, we don't provide ways to write reviews outside of the site or mobile apps.

**Comment by oliverlewis** [comment]
Is it possible for me to store the url of the restaurant that I wanted to
write a review for on a hardcoded link? Or is this URL dynamic and does it
change every few days?

Much appreciated feedback. Thanks in advance.

Regards,
Oliver Lewis

**Comment by oliverlewis** [comment]
I mean a URL that I see when I go to write a review for a restaurant is
below:

https://www.yelp.com/writeareview/biz/<dummy
link>?return_url=%2Fbiz%2<dummy link>.

Regards,
Oliver Lewis

**Comment by thenoelman** [comment]
I have this same question.  I want to build an app that will allow for a user to login to Yelp and post a review (my app also does other non-Yelp related things).  Is this functionality still unavailable?

**Comment by dlgallagher** [comment]
Hi @thenoelman - we still do not provide the ability to write reviews using only the API.

**Comment by SofteyeZs** [comment]
Post a review on Yelp . Is this functionality still unavailable?

**Comment by brian-1123** [comment]
Hi @SofteyeZs. Thanks for your interest in this feature. This is not functionality we currently offer as part of the API. If it is something we decide to implement, it will be noted in the API documentation.
