### ISSUE TITLE
Provide thumbnails of business images

### ISSUE THREAD

**Issue by rbnio** [Yelp/yelp-fusion#119]
The search+business API currently returns URLs to hi-res business images/photos, e.g.:
`"image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/xWqeLEXSkEI_4aFregoBUQ/o.jpg",`

Looking at the Yelp website, it seems that these images are also available as resized thumbnails, e.g.: 
https://s3-media3.fl.yelpcdn.com/bphoto/xWqeLEXSkEI_4aFregoBUQ/30s.jpg
https://s3-media3.fl.yelpcdn.com/bphoto/xWqeLEXSkEI_4aFregoBUQ/60s.jpg
https://s3-media2.fl.yelpcdn.com/bphoto/xWqeLEXSkEI_4aFregoBUQ/90s.jpg
https://s3-media3.fl.yelpcdn.com/bphoto/xWqeLEXSkEI_4aFregoBUQ/120s.jpg

Can you provide these thumbnail URLs via the API or is it safe for me as a developer to just "build" these thumbnail URLs myself and use them in my application?

Thank you!

**Comment by mittonk** [comment]
Same issue as #115 .

1. We'll look into providing thumbnails along with the full-resolution images --- sounds like several people are reaching for that.

2. In the meantime: "120s.jpg" or "300s.jpg" aren't part of the API, may change without notice, etc.  They'll work today, they'll probably work tomorrow, but they aren't guaranteed to keep working.

**Comment by rbnio** [comment]
Thank you for your feedback, we look forward to have this feature in the future.
