### ISSUE TITLE
User Data

### ISSUE THREAD

**Issue by tomarush** [Yelp/yelp-fusion#12]
Why isn't user data able to be pulled at all?  At a minimum can the check-ins and ratings be available to developers, at least on a case by case basis that's reviewed by the API team?

Reviews or at least portions of reviews and user searches would also be swell.  This would open up your api to be utilized by a wider range of developers and for interesting possibilities.  This of course will also allow for more press, utilization of Yelp, etc.

**Comment by guangyang** [comment]
This would be an interesting area to explorer. How are you thinking about using such data? Any particular ideas in mind?

**Comment by tomarush** [comment]
Yes!  :)

**Comment by dan98765** [comment]
Update: this enhancement has not been added, but is still under consideration so I'm leaving this issue open.
