### ISSUE TITLE
Reviews API returns null user_image for 2 out of the 3 comments returned during each call

### ISSUE THREAD

**Issue by OrrYakobi** [Yelp/yelp-fusion#121]
Every time I call the Reviews API, only one out of the three user comments returns a user image the isn't null. Is there anyway around this issue?

**Comment by OrrYakobi** [comment]
Same issue as https://github.com/Yelp/yelp-fusion/issues/109

**Comment by mittonk** [comment]
Yep, follow #109  for status.
