### ISSUE TITLE
Yelp fusion user data

### ISSUE THREAD

**Issue by harrykrish** [Yelp/yelp-fusion#122]
I am trying to understand if i can get yelp fusion user data. For example data on users who are in yelp, what reviews they posted etc. As far as i can see, there is only a name associated with a review with a image url. Is there a way to get user data in yelp? Thanks in advance!

**Comment by tomelm** [comment]
Hey @harrykrish! At the moment there's no way to do that, the only user data we return is what you mentioned for the reviews we provide.
