### ISSUE TITLE
How to get check-in and user related data from yelp fusion api

### ISSUE THREAD

**Issue by chauhanu** [Yelp/yelp-fusion#127]
Hi,

I want to get deals information for businesses, Check-ins data and user related data such as "elite", 'yelping_since' , 'compliments' etc. 

Please guide me on how to fetch this information by accessing yelp fusion api

**Comment by tomelm** [comment]
Hey @chauhanu, this data is not available through the Fusion API at the moment.

**Comment by chauhanu** [comment]
hi @tomelm Can i get it using yelp api v2? If so then how?

**Comment by tomelm** [comment]
v2 does not return this data either, it's not available through any of our APIs.

**Comment by matt321** [comment]
Hi Tomelm, 

I still don't see that check in data is available through yelp's API but I wanted to ask to make sure... any way to get check in data?  total checkins, check -in by yelper, etc...

Thanks,

Matt
