### ISSUE TITLE
Activities 

### ISSUE THREAD

**Issue by kakenzua98** [Yelp/yelp-fusion#129]
Can Yelp Fusion return activities (such as parks, museums, tourist attarctions, etc.) or just businesses like restaurants?

If the former is true, how can I go about doing that?

Thank you.

**Comment by tomelm** [comment]
The API will return any sort of "business" that you can find on the regular site (includes parks, museums, etc). You do this the same way you find restaurants, through search terms or the category filter. Full list of supported categories here: https://www.yelp.com/developers/documentation/v3/all_category_list

**Comment by mittonk** [comment]
Try searching for "central park" in "new york", for example.
