### ISSUE TITLE
Trying to use v2 and fusion to return price

### ISSUE THREAD

**Issue by kakenzua98** [Yelp/yelp-fusion#130]
I'm currently using v2 but need to return price with fusion. I tried to do the following but it is not working:

`

from flask import Flask, render_template, request
from yelp.client import Client, Business
from yelp.oauth1_authenticator import Oauth1Authenticator
from array import *
import oauth2

app = Flask(__name__)

auth = Oauth1Authenticator(
    #yelp
    consumer_key="9uOjbV2So3UmsBHhVYIEXw",
    consumer_secret="9oo9F8v2sOG_s9t-75bOMZdaDQE",
    token="5rk--RHbWWbwvucUt6oY2qfftTZNxN9v",
    token_secret="x3jS4pIsgT6PwjBVE8CeyuX1WAE"
)

client = Client(auth)

def search():
       # scaled down copy of code with request.methods, html templates, etc.
        response = client.search(city_name)
        biz_id = response.businesses[0].id
        r = GET https://api.yelp.com/v3/businesses/{biz_id}
        price = r.price
'

And if I need to switch completely to fusion, I'm not sure what code or call sites to change. For example, how to I make a POST call to the endpoint specific on the Yelp fusion page?

**Comment by mittonk** [comment]
@kakenzua98 : If you need price, I'd suggest getting rid of your V2 code entirely and starting over with:
* https://www.yelp.com/developers/documentation/v3/get_started for documentation
* https://www.yelp.com/developers/v3/manage_app for Fusion credentials
* https://github.com/Yelp/yelp-fusion/tree/master/fusion/python for a Python code sample

You can't use `Oauth1Authenticator()` or `consumer_key` with Fusion, that won't work with any `api.yelp.com/v3` endpoints.

Sorry for the version confusion, we'll work on making things clearer.
