### ISSUE TITLE
Yelp Fusion business api is giving blank response

### ISSUE THREAD

**Issue by oswal04** [Yelp/yelp-fusion#131]
I am using business api of fusion but after two request I get blank response.

Any help is really appreciated!!

Below is the code

import sys

def get_businesses_test(business_name,location):
    
    listofbusiness=[]
    listofbusinessnames=[]
    offset =0
    fn.new_folder(location.split(',')[0])
    foldname=location.split(',')[0]
    while 1000 > offset :
        print(offset)
        params = {'location': location,
              'term': business_name,
              'offset':offset    }
        resp = requests.get(url=searchurl, params=params, headers=headers)   
        #print('1',resp)
        try:
            jsn=resp.json()['businesses']
        
            if 'name' in json.dumps(jsn):
                print('Json len',len(jsn))        
                for x in range(0,len(jsn)):
                    id_new=jsn[x].get('id',0)          
                    id_new=id_new.replace('|',"")
                    id_new=''.join(e for e in id_new if e.isalnum())
                    business_id=jsn[x].get('id',0)
                    business_name=jsn[x].get('name',0)                         
                    listofbusiness.append(business_id)
                    listofbusinessnames.append(business_name)
                    #print(business_id)
                    business_url=businessurl+'/'+str(business_id)
                    busresp = requests.get(url=business_url,  headers=headers)  
                              
                    busnisses_jsn=busresp.json()                
                    #name_new=re.sub(r"</?\[\d+>", "", jsn[x].get('name',0))            
                    fname=foldname+'/'+id_new 
                    with open(fname+'.json','w') as fn2:
                        json.dump(busnisses_jsn, fn2)
                    print('files 1:',x    )
        except: break; 
        offset= offset+10  
        
    with open(foldname+'_businessids.csv', "w") as businesses:
            
        writer = csv.writer(businesses, lineterminator='\n')
        writer.writerow( ('id', 'name' ))
            
        rows = zip([listofbusiness[x] for x in range(0,len(listofbusiness))],
        [listofbusinessnames[x] for x in range(0,len(listofbusinessnames))]) 
            #print(rows)
        for row in rows: 
            writer.writerow(row)   
ᐧ

**Comment by mittonk** [comment]
@oswal04 : What actual location and search term are you using?

The results should look similar to the same search on www.yelp.com --- there won't be 1000 businesses matching the term "Starbucks" in "Salt Lake City", for example.

**Comment by mittonk** [comment]
Sounds to me like we're successfully enumerating tens of matches here, clsing.
