### ISSUE TITLE
Can you please provide individual rating stars image? 

### ISSUE THREAD

**Issue by NikitaTurakhia** [Yelp/yelp-fusion#138]
hello,

Instead of single 3.5, 4 stars can you lease provide a group of stars like below?

E.g. for 4 stars : 
![4](https://cloud.githubusercontent.com/assets/21182650/21112244/0ee95fb4-c073-11e6-9ad8-34c2bd68a97e.jpg)

for 5 stars :
![5](https://cloud.githubusercontent.com/assets/21182650/21112251/19767692-c073-11e6-946e-38e00dbf027e.png)

Thanks

**Comment by tomelm** [comment]
Hey @NikitaTurakhia! We're looking into this but don't have an ETA right now.

**Comment by NikitaTurakhia** [comment]
Hello @tomelm ,

It's okay no problem.

Thanks

**Comment by NikitaTurakhia** [comment]
Hey,

Any updates on this issue?

**Comment by StevenU8** [comment]
any updates on this?

**Comment by tomelm** [comment]
I've just updated all the stars on the display requirements, they should reflect our current stylings and be much easier to user now. https://www.yelp.com/developers/display_requirements
