### ISSUE TITLE
businesses search in Fusion: categories appears not to be working

### ISSUE THREAD

**Issue by froggygoesadrivin** [Yelp/yelp-fusion#139]
For a Fusion businesses/search call, I am setting the categories attribute to "restaurants,italian", and leaving the term field empty. The response does not contain italian restaurants, but does contain what appears to be an arbitrary selection of restaurants. What am I doing wrong?

**Comment by d9chen** [comment]
@froggygoesadrivin We perform a logical OR based on the list of categories provided. In your case the filter would effectively be restaurants OR italian hence why you are seeing an arbitrary list of restaurants.

**Comment by froggygoesadrivin** [comment]
Great! Thanks.
