### ISSUE TITLE
Add Deals to /businesses/search

### ISSUE THREAD

**Issue by arun4444** [Yelp/yelp-fusion#14]
Looks like the /businesses/search endpoint no longer includes deals information? Are there plans to add this to the APIv3? We were planning to use it to direct users to businesses with deals and would be great if v3 returned it.

**Comment by guangyang** [comment]
v2 has a deal filter on search and also return deals detail information in the response. Do you really need the deals detail from search? It's a pretty big object which can slow things down. Will it be good enough if we just bring back the filter itself without addition to the response body?

**Comment by arun4444** [comment]
We were looking to display the actual deal info with the search results, as Yelp allows commissions on deals that originate from external applications. This was essential to our revenue model. It seems as though Deals info does not appear in either the search or business info endpoints. We would like it preferably with the search results, with perhaps a flag that displays them if requested.

**Comment by vkman** [comment]
Is there any priority for this request?  I would also like to have access to the deals object as it was in version 2, and would like to avoid using both API versions just to include prior functionality.  If data size is an issue, I agree with the above suggestion requiring a flag to includeDeals set to true.  
Would it be preferable if the deals object is returned in the business details call? 
_/businesses/{id}_

**Comment by vladimirzoyan** [comment]
Same here.. please include the deal search functionality  in v3.

**Comment by algoMan1** [comment]
Deals info is crucial for Yelp affiliates (those who publish Yelp Deals). If it does not get included in V3, API V2 cannot be dropped unless Yelp intends to stop its affiliate program. If that is indeed Yelp's long term plan, please let us know. Thanks

**Comment by rchall-gladly** [comment]
+1

**Comment by sfatfarma** [comment]
+1

**Comment by srivathsar** [comment]
Any updates on this?

**Comment by tiandingding2** [comment]
the deal info is important. pls push the process. thanks

**Comment by tomelm** [comment]
Hi all, we're not going to be adding deals to the Fusion API so I'm going to close this issue.
