### ISSUE TITLE
'Bad Request' trying to get access token in Postman

### ISSUE THREAD

**Issue by itsthecheat** [Yelp/yelp-fusion#140]
I followed the steps on [https://www.yelp.com/developers/documentation/v3/get_started](https://www.yelp.com/developers/documentation/v3/get_started). I entered the client_id and secret (assuming they are the same as the app id and secret that come up after creating an app) but it doesn't seem to be working. Here's a screen shot:
![screen shot 2016-12-18 at 10 52 15 pm](https://cloud.githubusercontent.com/assets/17536124/21300788/2acc811e-c575-11e6-8ebb-fe6ad474f054.png)
Is there anything I'm doing wrong? Thanks in advance!

**Comment by mittonk** [comment]
@itsthecheat : Looks like there's a space at the beginning of your `client_secret`.  Try deleting that!
