### ISSUE TITLE
passing two values to cll parameter when wanting to give optional longitude / latitude values to GET request calls

### ISSUE THREAD

**Issue by denniskkim** [Yelp/yelp-fusion#141]
Hey I was wondering if I could get some assistance with passing two values for the cll parameter. 
So I am using AJAX promises to make request calls using JSONP; and I am passing in the parameters using OAUTH to query my parameters. (grabbing the latLngString from a different function) 
    var parameters = [];
    parameters.push(['term', term]);
    parameters.push(['location', location]);
    parameters.push(['limit', limit]);
    parameters.push(['cll', latLngString]);   //latLngString = lat.toString() + "," +lng.toString();
    ......
    var parameterMap = OAuth.getParameterMap(message.parameters);

These lat lngs are 10 different points along a route. However, I dont believe that my lat lng coordinates provided is being recognized/being used instead of the generic location that I put because the response that I get are the same lat lng for each separate request call I am making with different lat lng coordinates that I am passing in. 

So I was wondering if the way I am passing the two lat lng values for the cll parameter is correct, and if it isnt, how would I go upon passing two values to one parameter key. 
Also I was wondering that if you make a request call with passing the location and the optional longitude latitude coordinates, then would it be safe to say that the request call will make a search based on the lat lng coordinates instead of the generic location i.e. San Francisco.

Thanks!

**Comment by mittonk** [comment]
@denniskkim : "cll" only takes one location; the API does not support searching 10 different locations (or along a route defined by 10 different points).

I'd suggest doing multiple searches.

**Comment by mittonk** [comment]
Actually, "cll" is a V2 argument:
* https://www.yelp.com/developers/documentation/v2/search_api
Only one value is supported.

The current Yelp Fusion search doesn't take "cll" at all:
* https://www.yelp.com/developers/documentation/v3/business_search
