### ISSUE TITLE
Do you support CSV or XML formats?

### ISSUE THREAD

**Issue by timwis** [Yelp/yelp-fusion#143]
Hey folks, we're trying to help a newer developer import yelp data into a google sheet to demonstrate what's possible with APIs. Google sheets unfortunately only supports importing CSV, TSV, HTML, and XML data -- there's no JSON support without a custom "Google Apps Script." Is there a way to get Yelp's API data in CSV or XML format? Thanks!

**Comment by mittonk** [comment]
@timwis : Yelp Fusion only supports JSON output --- and more seriously, setting up the OAuth authentication will probably require a custom script anyways. 

I'd suggest writing some code to make the API calls, and write out a CSV file which you can import into Google Sheets.

**Comment by timwis** [comment]
Makes sense. Thanks!
