### ISSUE TITLE
Yelp Return Wrong Results

### ISSUE THREAD

**Issue by channelnet123** [Yelp/yelp-fusion#145]
When I go to yelp.com and search "All About the Windows", near "Mobile, AL" I can find the store and the reviews just fine.

Using the API Console I enter in the following fields
Search: All About the Windows
Near: mobile, al

The results I get is "Maids à la Mode", which is obviously incorrect.

What's going on here? Using the API gives me incorrect results while the web page provides correct results.

What do I need to do? 

Thank you.

**Comment by mittonk** [comment]
@channelnet123 : Looks like the businesses you're interested in have 0 reviews:
* https://www.yelp.com/biz/all-about-the-windows-mobile-5
* https://www.yelp.com/biz/all-about-the-windows-mobile-7

Businesses with 0 reviews aren't returned by Yelp Fusion:
* https://www.yelp.com/developers/documentation/v3/business_search
> Note: at this time, the API does not return businesses without any reviews.

("Maids à la Mode" also shows up in the www.yelp.com results --- looks like the maids in question clean windows.  It's the first in that list with any reviews, so shows up at the top of the API results.)

**Comment by channelnet123** [comment]
Thanks @mittonk  for your response.

If I am understanding you correctly that if you ask for "XYZ" company's reviews you may get "ABC" company's review? 

I guess what I was expecting is "0 reviews found". I don't mind receiving that if the company I am searching for doesn't have any results.

**Comment by mittonk** [comment]
@channelnet123 : No, you won't see reviews for a different business.  Actually trying to list reviews shows an error message:
* https://api.yelp.com/v3/businesses/all-about-the-windows-mobile-5/reviews
```
{
  "error": {
    "code": "VALIDATION_ERROR",
    "description": "{'error': {'code': 'BUSINESS_UNAVAILABLE', 'description': 'We may not be able to provide details for certain businesses, for example if they do not have any reviews yet.'}}"
  }
}
```

Remember that Business Search is listing businesses related to certain terms --- "Show me businesses related to 'windows', 'about', 'all'."  It is not an exact name match.

**Comment by mittonk** [comment]
(Also, it looks like you're using the older V2 API supported over at https://github.com/Yelp/yelp-api , rather than Yelp Fusion --- but the same rules apply to each.)
