### ISSUE TITLE
Reviews v.3 API suggestion: URL for user_details page

### ISSUE THREAD

**Issue by jeffehobbs** [Yelp/yelp-fusion#146]
It would be handy to have a URL for the user_details "profile" page returned as key/value inside the Reviews v.3 payload, much like "name" and "image_url" are returned for the user when a review is surfaced in the API.

That's all!

**Comment by mittonk** [comment]
Yep, fine idea.

**Comment by sashagim** [comment]
@mittonk Ken, any news on this? This is something that was available in v2 (it was possible to construct the profile url from the user ID provided by the API), so I would actually call this a bug, not an enhancement request :)

**Comment by dan98765** [comment]
@sashagim adding the profile url as its own attribute in the response is under consideration, but adding the user ID appears more likely to happen in the short term. Would you be unblocked with the user ID?

**Comment by sashagim** [comment]
@dan98765 - sure, that would be perfect! I didn't find a way to query the API to get a profile URL from the user ID, so in the meanwhile this can be constructed by a simple string manipulation, but if you do add it in the future - we'll have the user ID available already for each review.
Thank you for looking into this!

**Comment by Valectar** [comment]
Both the user ID and user profile URL have been added to the reviews endpoint, as well as the User object in GraphQL.
