### ISSUE TITLE
Bad Request on Phone search

### ISSUE THREAD

**Issue by deshymers** [Yelp/yelp-fusion#147]
Hello I am getting a Bad Request when I use your phone search. 

full response:
{"error": {"description": "Bad Request", "code": "CLIENT_ERROR"}}

Request Header, 
GET /v3/businesses/search/phone?phone=+13348773700 HTTP/1.1
Host: api.yelp.com
Accept: */*
Authorization: Bearer [REMOVED]

I am trying to query for this business as an example, https://www.yelp.com/biz/dollar-general-selma

This is the url, https://api.yelp.com/v3/businesses/search/phone?phone=+13348773700

I am preforming the OAuth request to get my Bearer Token first, and setting the Auth header correctly, I tested by swapping out the above phone number with the one with the number from the example, (+14157492060) it works properly. 

I'm not sure if I'm missing something, or if there is something with my account. 

App ID: Cx7t4jy7a3ksl_oWgiHgZg

**Comment by mittonk** [comment]
@deshymers : Looks like https://www.yelp.com/biz/dollar-general-selma doesn't have any reviews yet.  At this time, the API does not return businesses without any reviews.  Sorry!
* https://www.yelp.com/developers/documentation/v3/business_search_phone
