### ISSUE TITLE
"code": "NOT_FOUND",     "description": "Resource could not be found" out put getting 

### ISSUE THREAD

**Issue by sajinairoglobal** [Yelp/yelp-fusion#148]
I have called api https://api.yelp.com/v3/businesses/search/*my_access_token*/?term=bar&location=boston,
but output is getting
{
  "error": {
    "code": "NOT_FOUND",
    "description": "Resource could not be found"
  }
}

how to solve this ?

**Comment by mittonk** [comment]
@sajinairoglobal : Your access token goes in the "Authorization" header, not the URL.  See
* https://www.yelp.com/developers/documentation/v3/get_started
* https://www.yelp.com/developers/documentation/v3/business_search

**Comment by jagadeesh583** [comment]
Hi, how to retrieve/query for to get  hotel true prices in yelp v3
