### ISSUE TITLE
How to get data from business search api from yelp with curl function in php

### ISSUE THREAD

**Issue by sajinairoglobal** [Yelp/yelp-fusion#149]
i have tried in v3 business search api from yelp with curl function to get data,
following below is my code , the out put not getting.
please help me to sort out the issue

require_once ('OAuth.php');

$CONSUMER_KEY = 'XXXXXXXXXXXXXXX';
$CONSUMER_SECRET = 'XXXXXXXXXXXXXX';
$TOKEN = 'Bearer';
$TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXX';
$API_HOST = 'api.yelp.com';
$DEFAULT_TERM = 'dinner';
$DEFAULT_LOCATION = 'San Francisco, CA';
$SEARCH_LIMIT = 3;
$SEARCH_PATH = '/v3/search/';
$BUSINESS_PATH = '/v3/business/';

function request($host, $path)
	{
	$unsigned_url = "https://" . $host . $path;
	$token = new OAuthToken($GLOBALS['TOKEN'], $GLOBALS['TOKEN_SECRET']);
	$consumer = new OAuthConsumer($GLOBALS['CONSUMER_KEY'], $GLOBALS['CONSUMER_SECRET']);
	$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
	$oauthrequest = OAuthRequest::from_consumer_and_token($consumer, $token, 'GET', $unsigned_url);
	$oauthrequest->sign_request($signature_method, $consumer, $token);
	$signed_url = $oauthrequest->to_url();
	$ch = curl_init($signed_url);
	if (FALSE === $ch) curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_HEADER, 0);
	$data = curl_exec($ch);
	if (FALSE === $data) $http_status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
	if (200 != $http_status) curl_close($ch);
	return $data;
	}

function search($term, $location)
	{
	$url_params = array();
	$url_params['term'] = $term ? : $GLOBALS['DEFAULT_TERM'];
	$url_params['location'] = $location ? : $GLOBALS['DEFAULT_LOCATION'];
	$url_params['limit'] = $GLOBALS['SEARCH_LIMIT'];
	$search_path = $GLOBALS['SEARCH_PATH'] . "?" . http_build_query($url_params);
	return request($GLOBALS['API_HOST'], $search_path);
	}

function get_business($business_id)
	{
	$business_path = $GLOBALS['BUSINESS_PATH'] . urlencode($business_id);
	return request($GLOBALS['API_HOST'], $business_path);
	}

function query_api($term, $location)
	{
	$response = json_decode(search($term, $location));
	$business_id = $response->businesses[0]->id;
	print sprintf("%d businesses found, querying business info for the top result \"%s\"\n\n", count($response->businesses) , $business_id);
	$response = get_business($business_id);
	print sprintf("Result for business \"%s\" found:\n", $business_id);
	print "$response\n";
	}

$longopts = array(
	"term::",
	"location::"
);
$options = getopt("", $longopts);
$term = $options['term'] ? : '';
$location = $options['location'] ? : '';
query_api($term, $location);

**Comment by mittonk** [comment]
@sajinairoglobal : That looks like old V2 example code, and won't work with V3.

I'd suggest starting with the Postman instructions here, then using Postman to generate some PHP code:
* https://www.yelp.com/developers/documentation/v3/get_started

We'll work on getting V3 PHP example code.

**Comment by mittonk** [comment]
@sajinairoglobal : We've now got a PHP example at 
* https://github.com/Yelp/yelp-fusion/tree/master/fusion/php

Have a look at that, see if it works for you and makes things clearer!
