### ISSUE TITLE
A return of location.cross_streets?

### ISSUE THREAD

**Issue by ericestes** [Yelp/yelp-fusion#151]
This data is present in v2 and is super useful in cities, but it's apparently not included in v3. Will this be returning at some point? Thanks!

**Comment by mittonk** [comment]
Good point, we'll have a look.

**Comment by mittonk** [comment]
@ericestes : We've added cross street data (where available) to the Business endpoint:
* https://www.yelp.com/developers/documentation/v3/business

We don't know cross streets for every business --- but where we do, you can now get that info via the Fusion API.  Enjoy!
