### ISSUE TITLE
Business ID Label & Business ID

### ISSUE THREAD

**Issue by DigitalRev2017** [Yelp/yelp-fusion#152]
Hello

Sorry, Newbie here.

I am trying to connect a reporting software platform to Yelps API but have been unsuccessful in obtaining the correct info to do so.

Where can I find the following information for an existing Yelp Business:
1. Business ID Label
2. Business ID

Thank you in advance for any help you may able to offer.

**Comment by mittonk** [comment]
@DigitalRev2017 : 
1. If you know the yelp.com link for a business, the Business ID is part of that URL.

Using the example from
* https://www.yelp.com/developers/documentation/v3/business

For the business Gary Danko:
* https://www.yelp.com/biz/gary-danko-san-francisco

The Business ID is `gary-danko-san-francisco`.

2. I'm not sure what you mean by "Business ID Label" --- where are you reading that?

3. If you don't know the www.yelp.com link for the business in question, it'll take a few more steps (like using the Search endpoint first).  If you're in this case, what info do you have about the business?

**Comment by DigitalRev2017** [comment]
@mittonk 👍 

Thanks for the response. This is the exact information I needed. 

I was using this information to connect a third party reporting system called  "TapClicks"  that would retrieve the Yelp Analytics data for inclusion with other reporting software.

**Comment by mittonk** [comment]
Wonderful!
