### ISSUE TITLE
Yelp Fusion OAuth2

### ISSUE THREAD

**Issue by BoehmerSusanne** [Yelp/yelp-fusion#153]
Is there a example how i can use yelp fusion with OAuth2 on android?

**Comment by tomelm** [comment]
We don't have anything specifically targeting OAuth2 and Android yet. There are a few general examples online:

* https://developer.android.com/training/id-auth/authenticate.html
* http://techblog.constantcontact.com/software-development/implementing-oauth2-0-in-an-android-app/

Our Getting Started guide covers the steps you need to take to authenticating and making requests (https://www.yelp.com/developers/documentation/v3/get_started)

**Comment by jriz1982** [comment]
When attempting to use the GET NEW ACCESS TOKEN using OAuth2 in Postman, using Yelp Fusion API v3 collection.

What is the Auth URL and Access Token URL that are to populate the fields?
Is grant type set to Client Credentials?
Is "request access token locally" to be checked?
I am using:  https://api.yelp.com/v3/oauth2/authorize    and   https://api.yelp.com/v3/oauth2/token
I get the following error in a pink banner on top of screen.
 "Error getting access from client_credential flow, could not send request."

Thank you for your time!

**Comment by NYCJacob** [comment]
Any chance of a javascript example?

**Comment by tomelm** [comment]
@NYCJacob if you're looking for Node examples, we have one here: https://github.com/Yelp/yelp-fusion/tree/master/fusion/node

If you're looking for front-end Javascript, we don't have any as the API does not support CORS currently.

**Comment by NYCJacob** [comment]
@tomelm ok, right now I need a pure front end solution, but thanks for the reply.

**Comment by NYCJacob** [comment]
@tomelm btw, I was using yelp api v1 but it hasn't seem to be working for the past few weeks and some people I know are having the same problem.

**Comment by tomelm** [comment]
@NYCJacob do you mean API v2? There was an issue last week that was resolved: https://github.com/Yelp/yelp-fusion/issues/169

v1 has been disabled for over a year now.

**Comment by NYCJacob** [comment]
@tomelmoh yes v2;l I suddenly started getting 400 errors recently using v2 and Oauth 1.0

**Comment by tomelm** [comment]
What is the 400 error you're seeing.

**Comment by NYCJacob** [comment]
@tomelm I figured it out, thanks

**Comment by dan98765** [comment]
I'm closing out some older issues that appear stale. This one appears to be resolved. Please comment if that's not the case.
