### ISSUE TITLE
little mistake in your YELP API V.3 Get Started Doc

### ISSUE THREAD

**Issue by hello2u** [Yelp/yelp-fusion#154]
Hi guys,
be carefull, there's a little mistake in your brand new YELP API V.3 Get Started Doc : 
(https://www.yelp.com/developers/documentation/v3/get_started)

section "Get an access token" / "Response body" : 
> **expries_in**  _int_  Represents the number of seconds after which this access [...]

instead of:
> **expires_in**  _int_  Represents the number of seconds after which this access [...]

**Comment by tomelm** [comment]
Thanks for letting us know! We'll get this fixed.

**Comment by mittonk** [comment]
@hello2u : Whoops, thanks for the catch!  Fixed now.
