### ISSUE TITLE
Are there plans on a Java client?

### ISSUE THREAD

**Issue by cpaika** [Yelp/yelp-fusion#157]
Looking to consume the Yelp Fusion API in a java project, I was wondering if there is plans to develop a java client?  Saw that there was a Java client for the v2 api but our project requires using autocomplete which seems to be a feature only available in the fusion api.

**Comment by tomelm** [comment]
We have plans to do so but do not currently have a timeline for it. We'll keep you posted!

**Comment by ranga543** [comment]
Please see here for accessing yelp fusion API using [yelp-fusion-android](https://github.com/ranga543/yelp-fusion-android)
