### ISSUE TITLE
is_overnight  and start-end confusion

### ISSUE THREAD

**Issue by mmplisskin** [Yelp/yelp-fusion#158]
Thanks for the easy to use api. I am a little confused in regards to business hours that are 24/7 and is_overnight:

According to the Docs: 

is_overnight:
```Whether the business opens overnight or not. When this is true, the end time will be lower than the start time.```

Is it possible to explain the following response discrepancy?

https://api.yelp.com/v3/businesses/pacific-dining-car-los-angeles
```
"hours"=>
  [{"is_open_now"=>true,
    "open"=>
     [{"end"=>"0600", "start"=>"0600", "is_overnight"=>true, "day"=>0},
      {"end"=>"0600", "start"=>"0600", "is_overnight"=>true, "day"=>1},
      {"end"=>"0600", "start"=>"0600", "is_overnight"=>true, "day"=>2},
      {"end"=>"0600", "start"=>"0600", "is_overnight"=>true, "day"=>3},
      {"end"=>"0600", "start"=>"0600", "is_overnight"=>true, "day"=>4},
      {"end"=>"0600", "start"=>"0600", "is_overnight"=>true, "day"=>5},
      {"end"=>"0600", "start"=>"0600", "is_overnight"=>true, "day"=>6}],
    "hours_type"=>"REGULAR"}],
```

https://api.yelp.com/v3/businesses/fred-62-los-angeles
```
"hours"=>
  [{"is_open_now"=>true,
    "hours_type"=>"REGULAR",
    "open"=>
     [{"start"=>"0000", "end"=>"0000", "day"=>0, "is_overnight"=>false},
      {"start"=>"0000", "end"=>"0000", "day"=>1, "is_overnight"=>false},
      {"start"=>"0000", "end"=>"0000", "day"=>2, "is_overnight"=>false},
      {"start"=>"0000", "end"=>"0000", "day"=>3, "is_overnight"=>false},
      {"start"=>"0000", "end"=>"0000", "day"=>4, "is_overnight"=>false},
      {"start"=>"0000", "end"=>"0000", "day"=>5, "is_overnight"=>false},
      {"start"=>"0000", "end"=>"0000", "day"=>6, "is_overnight"=>false}]}]
```

I would assume that businesses that are marked is_overnight always end on the next day but this is not the case above? 

It seems like if something is 24/7 the best solution to just check if end == start ? As it can not be said that all events that are 24/7 are  0 - 0.

**Comment by tomelm** [comment]
Huh, that's peculiar. We'll dig into this and see if we can get an answer or identify a bug.

**Comment by watterso** [comment]
Hi @mmplisskin I pushed out a change, and this should be fixed now.
