### ISSUE TITLE
Postman Access Token

### ISSUE THREAD

**Issue by jriz1982** [Yelp/yelp-fusion#159]
When attempting to use the GET NEW ACCESS TOKEN using OAuth2 in Postman, using Yelp Fusion API v3 collection.

What is the Auth URL and Access Token URL that are to populate the fields?
Is grant type set to Client Credentials?
Is "request access token locally" to be checked?
I am using: https://api.yelp.com/v3/oauth2/authorize and https://api.yelp.com/v3/oauth2/token
I get the following error in a pink banner on top of screen.
"Error getting access from client_credential flow, could not send request."

Thank you for your time!

**Comment by cpaika** [comment]
I am also unable to get an access token through the Postman OAuth 2.0 flow.  Instead, I send a POST request to the https://api.yelp.com/oauth2/token endpoint, with the headers client_id, client_secret and grant_type directly and use the access_token that is returned

**Comment by mittonk** [comment]
I'd agree.

@jriz1982 : I'd suggest manually choosing the POST entry from the collection to /oauth2/token , and copying the resulting access_token.

There are many configuration options in Postman's OAuth helpers, I've found them more confusing than helpful.

**Comment by jriz1982** [comment]
Thank you @cpaika and @mittonk for your responses. This is embarrassing, I'm an intermediate c++ programmer but absolute beginner with API's. It turns out I've already completed the POST request using postmen and have obtained the access token, but thought I needed a NEW access_token. However from my elementary knowledge of the API process, it seems the issues are within my JavaScript code and how I'm attempting to query the server rather than not having the right access token. I thought it would be as simple as using JSON with function setup(){
 data =loadJSON("https://api.yelp.com/v3/businesses/search&Authorization =0101010101010accesstoken0101",getData);}  (It works on some API's that Dont require authorization I guess) Then just simply manipulating the data. Is their a template for this process? While doing a bit more research, I also came across a few more terms to study like "Cross Domain Request"...maybe i'm still going the wrong direction, i'm not sure yet. But thank you again for helping shine light on my problem and if you know of any software and/or websites that will get me up to speed, I'm all Eyes and Ears!

**Comment by afhaque** [comment]
@jriz1982 you are missing the word bearer. Your correct syntax should be  `/search&Authorization= **bearer** TOKEN...`

**Comment by mittonk** [comment]
@jriz1982 : I see two issues --- one's hard to fix, the other's easy.

Most importantly --- it does look like your request from Javascript is going to be denied by Same Origin Policy rules: https://en.wikipedia.org/wiki/Same-origin_policy .  The best workaround is to create a small back-end service (Node, Python, Ruby, etc) --- you can see some discussion in #64 and #44.

@jriz1982 , @afhaque : As a side issue --- "Authorization: Bearer abc123..." is a _header_ --- it doesn't go into the URL at all.  In Javascript, you can add headers to requests with `$.ajax(..., "headers": {"Authorization": "Bearer abc123..."...` or `xhr.setRequestHeader("Authorization", "Bearer abc123...")` but that won't be enough to fix your issues here.

**Comment by afhaque** [comment]
Thanks for the correction @mittonk. It's funny, it took me a while last night to discover that the `authorization` bit was only a header and not in the URL as well. Documentation can definitely be cleaned up on this -- but was a cinch to use the API once authentication was done. Thanks for the responsiveness!

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
