### ISSUE TITLE
Yelp API down?

### ISSUE THREAD

**Issue by peterpeterparker** [Yelp/yelp-fusion#160]
Hi,

Could the Yelp API be down right now?

Can't fetch any data from Yelp anymore in my productive app and I detect no other errors except that one.

Best regards

P.S.: Sorry if it's not strictly a GitHub issue but I didn't know where to ask my question or where to get the response...thx you in advance for your answer

**Comment by peterpeterparker** [comment]
Well then it seems it was down for 10min, now the data are back.

I gonna close the task, but before I do, in such cases, is there any available monitors I could had check to answer such a question? or did I miss an information?

**Comment by tomelm** [comment]
The API was down for a few minutes but everything has been resolved. We don't have any monitors or status pages available but we'll investigate adding some.
