### ISSUE TITLE
Location autocomplete

### ISSUE THREAD

**Issue by cpaika** [Yelp/yelp-fusion#161]
Looking to use the autocomplete endpoint with a location string versus the lat/long requirement.  Is there anyway to get the lat/long from a location string using the Fusion API?  Or does tis require a third party api. The Business Search endpoint takes a location parameter

**Comment by tomelm** [comment]
We currently do not have a way to get a lat/lng from a location in the Fusion API. We've been looking at expanding the autocomplete endpoint to accept a location but don't have a timeline on that.

**Comment by cpaika** [comment]
@tomelm While not documented online, I've found that sending a request like this: https://api.yelp.com/v3/businesses/search?term=&location=Boston
While give me a lat long under the region section which seems to be a best guess at the location you are talking about.  Am I safe to consume this feature, or will this change since it is undocumented?

**Comment by tomelm** [comment]
Yep, you could use that but that'll only provide an approximation for a best fit on a map, it's not actually attempting doing a reverse geocode. The feature won't change, we have this documented on the search page (towards the bottom): https://www.yelp.com/developers/documentation/v3/business_search
