### ISSUE TITLE
Yelp search API returns (0.0, 0.0) latitude and longitude for some business

### ISSUE THREAD

**Issue by iRaam** [Yelp/yelp-fusion#162]
Why does yelp returns (0.0, 0.0) latitude and longitude for some business ?

**Comment by tomelm** [comment]
Could you give example of businesses that do that?

**Comment by iRaam** [comment]
Well I don't have that data as it is a user reported issue. But it happens for below latitude, longitude search
40.7414584,-73.99324

**Comment by tomelm** [comment]
It's possible there might be some bad data but I'm able to reproduce this at the moment. @iRaam if you could get any example businesses or sample data where this is happening that would be very helpful.

**Comment by mittonk** [comment]
@tomelm : Do you mean you can or can't repro?

**Comment by tomelm** [comment]
Can't

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
