### ISSUE TITLE
Reviews v.3 API Request

### ISSUE THREAD

**Issue by ScottB2017** [Yelp/yelp-fusion#163]
We would really like to be able to spotlight recent 5 star reviews for our staff in an automated way.  If the Reviews API allowed us to request the 3 most recent reviews, or sort by date or star rating this would be pretty easy and would be a big hit with our staff.  I've read the FAQ and am familiar the following:

_How can I get access to full review text?
The Yelp API does not return full review text. Three review excerpts of 160 characters are provided by default.

Can I change which reviews are returned for an API query?
In order to maintain a consistent Yelp experience across all platforms, the Yelp API uses a variation of factors to determine and return a business’s top review excerpts. The sort order is determined by recency, user voting, and other review quality factors to help consumers make informed decisions. The Yelp API cannot be configured to return alternative or hand-picked review excerpts._

I would really appreciate it if there was a enhancement to this aspect of the API that would allow us to hi light our best reviews in an easily automated fashion. 

Thanks!

Scott

**Comment by tomelm** [comment]
Hey Scott! I've talked this over with a few people and unfortunately this is not an improvement we're planning on making at the moment. I've noted this feedback though and will let you know if we reconsider in the future.
