### ISSUE TITLE
Uncaught SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by jvilaikeo** [Yelp/yelp-fusion#164]
Hi,

I'm trying to use the api v3 and pull a basic search. I was able to pull the access_token but I'm having a bit of trouble.

Here's some of the code I'm using. The problem is I'm not able to get the data into my object. I get stuck with "Uncaught SyntaxError: Unexpected token :" which is blocking my results. 

When I try to pull json data I run into CORS errors. What's the best way to get the results? 

$.ajax({
  url: yelp_url,
  method:'GET',
  dataType: 'jsonp',
  headers:  {
    'Authorization': 'Bearer token',
      },
  data: {
    term: 'Tacos',
    location: 'San Francisco'
  },
  success: function(data) {
    console.log('here!');
    console.log(data);
    }
  });

**Comment by tomelm** [comment]
Hey @jvilaikeo, I'm not sure about the syntax error but the API doesn't support CORS. I know some people have been getting around it by setting up simple backends.

**Comment by jvilaikeo** [comment]
Are there any code examples with JavaScript? I was able to get around the CORS but then I run into the syntax error when using jsonp. Is there a simple method to pull json?

**Comment by tomelm** [comment]
We don't have any for client-side Javascript (I know there are some unofficial Node libraries). Do you know if the request is succeeding? All of the data coming from the API should be valid JSON.

**Comment by jvilaikeo** [comment]
I get a 200 response but because the data is coming back jsonp I'm running into the syntax error : the payload/results are in the body but it's just not getting into the object. The example code should spit out the error. So the API is mainly meant for server side?

**Comment by tomelm** [comment]
At the moment, that's been our focus. I know other people have managed to get around it with JSONP but I've never used it so I don't have a lot of experience with it.

I know on JSONP the data gets wrapped as a function when it's returned. Have you tried inspecting the data that comes back?

**Comment by jvilaikeo** [comment]
The issue I'm having is I can't get the data out of that wrapper, that is where the syntax error is happening but the response data looks formatted correctly. Hmm

**Comment by jvilaikeo** [comment]
var data = {
    term: 'tacos',
    location: 'San Franscisco',
  };
var yelp_url="https://api.yelp.com/v3/businesses/search?callback=?" ;

$.getJSON(yelp_url, data, function(json){
  console.log(json);
});

I tried to minimize the client side code as much as possible and pass the response right into the function for jsonp to render but it still gives syntax error. 

I think the problem is the return is in regular JSON and not JSONP.  Does the API support JSONP callbacks? or do I need to setup as you mentioned a simple backend?

{"businesses": [{"phone": "+xxxx", "distance": 509.94284317719996, "price": "$", "review_count": 407, "location": {"country": "US", "city": "San Francisco", "zip_code":

**Comment by tomelm** [comment]
The API itself does not have any JSONP functionality built it so that could be the problem here.

**Comment by jvilaikeo** [comment]
ahh. No CORS or JSONP, that makes it very difficult to use the API client side. Thanks for the responses.

**Comment by tomelm** [comment]
Sure! Closing this for now
