### ISSUE TITLE
Problem when searching for breakfast and brunch with yelp fusion V3

### ISSUE THREAD

**Issue by tlss94** [Yelp/yelp-fusion#165]
Hi,

when searching with the yelp fusion V3 with categories 
'categories' : 'Breakfast & Brunch'

I have the following answer:
{'error': {'code': 'INVALID_CATEGORY',
  'description': 'The category alias you specified is not valid'}}

and when I am searching in 'term' it outputs me everything.

Thanks

**Comment by tomelm** [comment]
You need to use the alias. Look for the lowercase version with no spaces here: https://www.yelp.com/developers/documentation/v3/all_category_list

In this case it should be "breakfast_brunch"

**Comment by tlss94** [comment]
Thank you very much it worked!
the categories pages is so large
fortunately 'Ctrl+F' is your friend :)
