### ISSUE TITLE
Neighborhood in V2 but not in V3??

### ISSUE THREAD

**Issue by tldoan** [Yelp/yelp-fusion#166]
Hi,

Is it normal that in version V2 we can have access to the neighborhood through location.neighborhood
whereas it is missing for yelp fusion (V3)??

Thanks!

**Comment by tomelm** [comment]
Might've missed adding that, will see about getting it back in

**Comment by kdonovan** [comment]
👍 Adding Neighborhood data back would be much appreciated!

**Comment by maclark999** [comment]
I am very late to this party, but I was wondering if there was any word on getting neighborhood data added back in to v3? Specifically the ability to query for a list of all neighborhoods.
