### ISSUE TITLE
Business not found

### ISSUE THREAD

**Issue by bizmate** [Yelp/yelp-fusion#168]
Although this business is visible, it has reviews and a very specific name the search api is not returning it.

Steps

1 - visit business page -https://www.yelp.com/biz/backyard-imagination-richardson 
2 - Search on Yelp.com with term - Backyard Imagination and Location = Richardson, TX 75080
You will get the result '1. Dallas Landscape Lighting' but this is not the right business
3 - Try on the api ang get the result as per attachment 
[backyard_imagination_search.json.txt](https://github.com/Yelp/yelp-fusion/files/778586/backyard_imagination_search.json.txt)

Please note i have also tried with several other variations of the business but I am still unable to find it 

As you can see both are not consistent but most importantly the search is not returning that business. Could you please confirm what is going wrong?

**Comment by bizmate** [comment]
Any chance this could be looked into?

**Comment by tomelm** [comment]
Hey, sorry about not responding, this slipped through the cracks. I've ticketed this internally and we'll have someone look into it.

**Comment by FlawaCLV** [comment]
Same issue for this business : https://www.yelp.fr/biz/empreinte-h%C3%B4tel-orl%C3%A9ans-2 If you check the results I get : https://www.spart-job.com/recherche/Empreinte%20H%C3%B4tel/Orl%C3%A9ans%2C%20France The business does not come out.

The query hits `terms` and `location`.

Any idea ? A restriction from the business owner ?

**Comment by bizmate** [comment]
Hi folks, any updates on this. It has been almost a month now.

**Comment by tomelm** [comment]
Hey @bizmate, so the specific biz you're asking about is an online-only business and we generally don't display those results in search (see eligibility: https://www.yelp-support.com/article/What-are-the-guidelines-for-adding-a-business-to-Yelp?l=en_US).

@FlawaCLV that business does not have any reviews, we only return businesses with reviews in the API.

**Comment by bizmate** [comment]
@tomelm where does it say that this is an online business only? https://www.yelp.com/biz/backyard-imagination-richardson. This business was displayed correctly in previous version of the API.

**Comment by quytennis** [comment]
@bizmate The previous version of the API does not return this business either.  We don't publicly display the actual reason when businesses are ineligible.

**Comment by bizmate** [comment]
@quytennis the business owner claims they had an integration of their Yelp reviews with v1 of the API. This is not with our integration and they were very disappointed that their buseness is no where to be found. Regardless, how can we establish when a business can be used through the API?  It is clear that businesses without reviews cannot be found but how about other use cases without asking Yelp everytime?

**Comment by quytennis** [comment]
@bizmate Can you give me a little more background about your use of the Yelp API? Do you have a mobile app or website that is currently using the API?

**Comment by bizmate** [comment]
@quytennis I am running reviews integration solution . A solution to integrate business reviews on no coding website builders PAAS at the moment. The reason why i raised the issue is because this business owner contacted me complaining that they had Yelp working before. Wix had an old integration with the first version of the API, so I assume this was implemented and working for this business back then. I hope this gives enough background as to why both I and the user did not expect such a problem. Please ask further questions if you need more details
