### ISSUE TITLE
Refused to execute script

### ISSUE THREAD

**Issue by jjcuzz** [Yelp/yelp-fusion#169]
Has anyone encountered this and found a solution?

Refused to execute script from 'https://api.yelp.com/v2/search?***' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

**Comment by tomelm** [comment]
We're aware of the problem and working to fix it but don't have an ETA at the moment.

**Comment by jjcuzz** [comment]
Thank you!

**Comment by lglaves** [comment]
I have just encountered this issue also, awaiting resolution.

**Comment by tomelm** [comment]
We've put a fix out, everything should be functional again. If anything else comes up please let us know!

**Comment by jjcuzz** [comment]
Confirmed, thank you for the quick turn around.
