### ISSUE TITLE
Having the *adjusted rating value* in search responses when using `sort_by=rating`

### ISSUE THREAD

**Issue by sp00m** [Yelp/yelp-fusion#17]
When using `sort_by=rating` for a search, it is said that _the rating sort is not strictly sorted by the rating value, but by an adjusted rating value that takes into account the number of ratings, similar to a bayesian average_ (in V2 as well). This is a very good idea, but could it be possible to expose these _adjusted rating value_ into the search responses?

I'm playing with depth (z-index) when there are too many businesses in the same area on Google Maps (displaying the best rated businesses on top), but I believe it would be more accurate to use your _adjusted rating value_.

**Comment by mittonk** [comment]
Hm, we don't usually show that; that's getting into some of the more internal data.  Not sure we'll be able to release that, but leaving this issue open for now.

**Comment by dan98765** [comment]
Thanks for the enhancement request. After consideration, we will not be adding this to the search response.
