### ISSUE TITLE
Does Fusion Api's return any information on businesses with no reviews?

### ISSUE THREAD

**Issue by cpaika** [Yelp/yelp-fusion#177]
Been trying to find out what happens if a business has no reviews on yelp, it seems like the business search api don't return the business if it hasn't been reviewed before?

**Comment by tomelm** [comment]
Correct, we don't return data for businesses without reviews. This is mentioned at the top of the documentation page: https://www.yelp.com/developers/documentation/v3/business_search, "Note: at this time, the API does not return businesses without any reviews."

**Comment by dineshgautam22** [comment]
Hi Yelp 

According to you **"we don't return data for businesses without reviews. This is mentioned at the top of the documentation page: https://www.yelp.com/developers/documentation/v3/business_search, "Note: at this time, the API does not return businesses without any reviews."**

But I just run the yelp api, I am not getting review list for the business in V3 api version, but in the V2 I was getting the review list.

Please let me know if there is special parameter need to add in request to get review in the response?

**Comment by dineshgautam22** [comment]
@tomelm  Please reply

**Comment by tomelm** [comment]
@dineshgautam22 I am not longer involved with the API, please wait for someone else to respond.

**Comment by watterso** [comment]
@dineshgautam22 Your issue does not appear to be related to the original question here, please open a new issue
