### ISSUE TITLE
Search API V3 

### ISSUE THREAD

**Issue by vjujjavarapu** [Yelp/yelp-fusion#180]
Hi, 
I have recently started using the v3 of the API and it works perfectly fine for 20 and 50 results by limit parameter however i would like to know why haven't a page operator implemented on your end so that all I need to do is page = 1 for first 20, page = 2 for the second 20 and so on. Is this on the roadmap or what is the expected approach to retrieve the second page of the search response after fetching the initial 20.

**Comment by tomelm** [comment]
We don't have plans to do this, limit/offset gives the user more control than paging and we're not planning on changing that at the moment.

**Comment by vjujjavarapu** [comment]
Thank you for your reply. I have utilized limit : 50 in my first request to the Businesses search URL and it works like a charm, I would love to know what would be the criteria for requesting the second page of 50 more businesses.

**Comment by tomelm** [comment]
@vjujjavarapu set the offset to be 50. Offset indicates where in the list you are and skips the first N businesses.

**Comment by Francisco1620** [comment]
Hi, I have my limit set at 50 and offset at 50 and I still only get 50 results back. How can I return more than the max limit of 50 using offset? I'm using php.
thanks!

**Comment by vjujjavarapu** [comment]
@Francisco1620 
![screen shot 2017-09-14 at 11 55 10 am](https://user-images.githubusercontent.com/10272760/30440109-9b95cf7a-9943-11e7-8f87-bf850243e300.png)

**Comment by tomelm** [comment]
@Francisco1620 you can't get more than 50 businesses returned per request. 50 is our maximum but with paging you can make multiple requests to get the other businesses.

**Comment by Francisco1620** [comment]
Thanks for the responses, I understand what I need to do now.
