### ISSUE TITLE
Can anyone make a Swift example on how to authenticate?

### ISSUE THREAD

**Issue by pratoa** [Yelp/yelp-fusion#181]
I have my access token which I obtained from doing the POST call from Postman. I don't even use the accessToken anywhere, since the method doesn't ask for it?

YLPClient.authorize(withAppId: appID, secret: appSecret) { (client, err) in
            if (err != nil){
                print(err ?? "")
            } else {
                self.client = client
            }
        }

Thanks

**Comment by tomelm** [comment]
There is a work in progress review for Swift here: https://github.com/Yelp/yelp-fusion/pull/172

**Comment by mittonk** [comment]
@pratoa : Have a look at https://github.com/Yelp/yelp-fusion/tree/master/fusion/swift , does that point you in the right direction?

**Comment by pratoa** [comment]
@mittonk Thanks! That pointed me to the right direction.

**Comment by Linger-Software** [comment]
I'm sure you guys are hard at work. BUT I am having the most insane time trying to simply authenticate the client. I've tried following the swift YelpAPISample for swift, but it seems to just fail. 

I have all the pods and dependencies I need, I just don't know where to start. The Android API is insanely simple to both integrate and use. I'm sorry if I seem like a noob. I literally just started iOS this past Saturday.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

(see https://github.com/Yelp/yelp-fusion/tree/master/fusion/swift)
