### ISSUE TITLE
yelp-fusion radius issue.

### ISSUE THREAD

**Issue by nyerunkar** [Yelp/yelp-fusion#184]
Hello,

   i'm using yelp fusion api.. using Latitude and Location and radius i'm getting place listing..
but some places are out of that radius..
  So i'm confused ..guide me please.

Thanks,
Nilesh.

**Comment by tomelm** [comment]
Could you provide example queries and responses showing the problem?

**Comment by nyerunkar** [comment]
hello,
 have a look on this url 
https://api.yelp.com/v3/businesses/search?latitude=37.785077704177695&longitude=-122.43744894862176&limit=10&categories=bars&offset=0&radius=1315&sort_by=best_match

some places are beyond 1315 mtr.

So i'm confuse is anything wrong at my side or something.

Thanks,
Nilesh.

**Comment by donaghhealy** [comment]
I have the same issue. When I specify in the Search call that i want locations with a radius<1000, it still get locations where the radius is higher, say 3000 or 2500 etc.

**Comment by donaghhealy** [comment]
Apologies, correction- there was a typo in my call!!

**Comment by mittonk** [comment]
@nyerunkar : Reproduced issue, `hollow-cow-san-francisco` is at  1534.3145647816 m.

We'll have a look.

**Comment by tbryan** [comment]
+1

**Comment by hcliff** [comment]
any follow up on this?

**Comment by mittonk** [comment]
Repro steps:
* https://api.yelp.com/v3/businesses/search?latitude=37.785077704177695&longitude=-122.43744894862176&limit=10&categories=bars&offset=0&radius=1315&sort_by=best_match
includes
* "noc-noc-san-francisco" at "distance": 1569.2024166639999

We've fixed a few radius issues since this was originally filed, but doesn't look like any of those fixes covered this case.  We'll look further.

**Comment by hcliff** [comment]
"unsorted" example
"https://api.yelp.com/v3/businesses/search?latitude=40.574125375783&limit=50&longitude=-73.85684981373954&offset=0&radius=10" returns "marina-at-city-styles-brooklyn-3" with a distance of 6500

**Comment by jstumpges** [comment]
Is there any progress on this? I'm getting similar issues using Yelp Fusion's v3/business/search endpoint.
Here is an example request:
https://api.yelp.com/v3/businesses/search?latitude=45.362155597121941&longitude=-122.6099240140652&location=West Linn, OR&maxresults=3&categories=restaurants&offset=0&radius=32000&locale=en_US&term=restaurants

Notice that both the `locale` and valid `latitude`\`longitude` params are located in West Linn, OR, but the first business listing returned in the results is Giuseppes's Italian Street Food in South Bend, IN (over 2,000 miles away). 

In that request, the radius is set to 32,000 meters (approx 20 miles), so the max radius is clearly not being honored. However, if I set the radius to a much smaller value then it does seem to work. I've narrowed that value down to 1681 meters (approx 1 mile) - anything over that doesn't seem to work. 

It's not appropriate in our app to limit results to that small of a radius, so any help/update on this issue would be appreciated.

**Comment by jstumpges** [comment]
@mittonk Any update on this issue?

**Comment by mittonk** [comment]
@teekwak , want to weigh in here?

**Comment by JakeEllis** [comment]
Have there been any updates to this radius issue? @mittonk @teekwak @nyerunkar

**Comment by olvinbolanos** [comment]
Same problema, I set the radius to 10000 and left out the longitude because I was getting cities way outside my approximate 8 mile radius and it worked for me.

**Comment by JakeEllis** [comment]
As a work around, I ended up using the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) to calculate the distance between the user's location and the business' location. If the distance between the two locations is longer than the set radius then I drop the business from my results list. It is annoying to have to do it for each business, however it helps to ensure you are only showing correct results to the user.

Here is a github repo that helps with using the Haversine calculation: https://github.com/rcvrgs/Haversine-Android

**Comment by olvinbolanos** [comment]
Thanks bro, I'm working on this project that's going to be on my portfolio, its a icecream shop app and I'm just putting it together.
thanks,Olvin
    On Thursday, September 5, 2019, 10:58:07 AM PDT, Jake Ellis <notifications@github.com> wrote:  
 
 
As a work around, I ended up using the Haversine formula to calculate the distance between the user's location and the business' location. If the distance between the two locations is longer than the set radius then I drop the business from my results list. It is annoying to have to do it for each business, however it helps to ensure you are only showing correct results to the user.

Here is a github repo that helps with using the Haversine calculation: https://github.com/rcvrgs/Haversine-Android
