### ISSUE TITLE
Undocumented fields "display_phone" and "display_address" in Search API

### ISSUE THREAD

**Issue by wldaunfr** [Yelp/yelp-fusion#186]
[Search API Documentation](https://www.yelp.com/developers/documentation/v3/business_search) lacks description of existing fields `businesses[x].display_phone` and `businesses[x].location.display_address`.

**Comment by mittonk** [comment]
Whoops!

**Comment by watterso** [comment]
Hi @wldaunfr , just updated the docs with these feels on both the following pages:

- [business](https://www.yelp.com/developers/documentation/v3/business) docs
- [business search](https://www.yelp.com/developers/documentation/v3/business_search) docs

Thanks for reporting this!
