### ISSUE TITLE
cross_streets like API v2

### ISSUE THREAD

**Issue by platerocm** [Yelp/yelp-fusion#189]
Is it possible to receive **"cross_streets"** using **/search** like API v2? I consider it very important.

[https://www.yelp.com/developers/documentation/v2/search_api](https://www.yelp.com/developers/documentation/v2/search_api)

Many thanks in advance!

**Comment by mittonk** [comment]
@platerocm : We've now got `cross_streets` in the Business endpoint.

Do you display cross streets in a high-level search-only view, or are you already calling the Business endpoint for your view?

**Comment by platerocm** [comment]
**@mittonk**  :  Im using [/businesses/search](https://www.yelp.com/developers/documentation/v3/business_search). I want show cross_streets using this endpoint. If they could add this property would be perfect.

Unfortunately this endpoint does not help me [/business](https://www.yelp.com/developers/documentation/v3/business)
