### ISSUE TITLE
Some businesses doesn't have a latitude and longitude

### ISSUE THREAD

**Issue by razola** [Yelp/yelp-fusion#191]
Hi,

I'm using the Search and Business API and just got back a business that doesn't have a latitude or longitude. The Yelp id is "fried-chicken-and-pizza-kissimmee". [Here's the json](https://gist.github.com/razola/083f2f8557a3266659348ad491a2870d) I got back from the Business API.

**Comment by tomelm** [comment]
That's correct, some businesses might not have a lat/lng based on our data availability.
