### ISSUE TITLE
receiving 502 bad gateway on business detail call

### ISSUE THREAD

**Issue by tmuelle1** [Yelp/yelp-fusion#192]
I call the API with this and I get everything:
https://api.yelp.com/v3/businesses/le-temps-des-cerises-paris-5

But when I call on this ID I get a 502 Bad Gateway error:
https://api.yelp.com/v3/businesses/le-bistro-du-périgord-paris-3

Does it have something to do with the é character?

**Comment by tomelm** [comment]
@tmuelle1 502 wouldn't usually indicate an error like that on our side. I'm also unable to reproduce this, are you still experiencing this error?

**Comment by mittonk** [comment]
@tmuelle1 : For comparison, could you also try with `é` URL-encoded?

* https://api.yelp.com/v3/businesses/le-bistro-du-p%C3%A9rigord-paris-3

In my test setup, both `é` and `%C3%A9` work --- let's see if that's also true for yours.

**Comment by tmuelle1** [comment]
Hello @mittonk thanks for the advice. I did URL encode and that worked.
