### ISSUE TITLE
Using API

### ISSUE THREAD

**Issue by MohammedSaleh12** [Yelp/yelp-fusion#194]
I'm having trouble using the API I just wanted to know if anyone can point me in the right direction to use the API

**Comment by tomelm** [comment]
Hey @MohammedSaleh12! You should check out our [getting started page](https://www.yelp.com/developers/documentation/v3/get_started). That'll walk you through some of the steps you need to take to get going.

Are there any specific problems you're having?

**Comment by MohammedSaleh12** [comment]
@tomelm 
Right now I'm trying to make a Web application using the yelp fusion api and I don't really know where to start can you point in the right direction?

**Comment by mittonk** [comment]
@MohammedSaleh12 : 

1. Have you already chosen a language (Python, Ruby, etc)?

If so, see if there's a matching code example at https://github.com/Yelp/yelp-fusion#code-samples .  That should help you get started.

2. Is this your first web app?  If so, I'd suggest getting a very simple "Hello World" working before trying to add Yelp data --- that'll make it much easier.  Your favorite Python / Ruby / Java / whatever resources can help there, before tackling the Yelp aspect.

3. Have you been able to make simple Yelp API request using Postman or curl, following 
* https://www.yelp.com/developers/documentation/v3/get_started
? Trying that manually first often makes it easier to write a web app.
