### ISSUE TITLE
Search API docs clarification

### ISSUE THREAD

**Issue by razola** [Yelp/yelp-fusion#196]
If I do a search with the category filter "restaurants" + some keyword I'll only get back results that are tagged with a category that has "restaurants" as its root category. Right?

And if I do a search with the category filter "restaurants,food" + some keyword. I'll only get back results that a tagged with a category that has "restaurants" or "food" and its root category, or both.

So basically I just wanted to double-check my assumptions:

1. The category filter works with a root level category
2. Multiple categories are treated as an OR statement

Thanks!

**Comment by tomelm** [comment]
1. The category filter applies to all explicitly listed categories on the business. I'm not entirely sure what you mean by "root category".
2. It should be doing a logical AND, not an OR.

**Comment by razola** [comment]
1. By "root category" I mean the top-level categories that doesn't have any parents, such as "restaurants", "food" and "active". But never mind, it seems to work like I assumed..

2. Does it really though? The below request returns places with subcategories of "restaurants" OR "active" (the last result).

https://api.yelp.com/v3/businesses/search?term=pizza&categories=restaurants%2Cactive&radius=1000&latitude=38.452689607773834&longitude=-122.75137692518068&sort_by=best_match

**round-table-pizza-santa-rosa-5**
Pizza

**pizza-hut-santa-rosa-2**
Pizza, Italian, Chicken Wings

**papa-murphys-santa-rosa**
Pizza

**finley-aquatic-center-santa-rosa**
Swimming Pools, Swimming Lessons/Schools

...

**Comment by tomelm** [comment]
Sorry, I was wrong for #2. Double checked, they are in fact OR'd so you're right!

**Comment by razola** [comment]
Oki. Thanks! 🙌🙌
