### ISSUE TITLE
No hours returned from businesses query

### ISSUE THREAD

**Issue by dmikesell** [Yelp/yelp-fusion#199]
I'm searching for business info, but none of the businesses returned include hours data.  If I visit their pages on Yelp, I see the hours so I would think it should be available.

My search endpoint is v3/businesses/search?radius=8046&sort_by=distance&categories=coffee&latitude=38.1688781&longitude=-79.1044844

None of the businesses returned include any hours data.

**Comment by tomelm** [comment]
@dmikesell the search endpoint does not return hours data, only the business endpoint does.

**Comment by mittonk** [comment]
I'd suggest doing a search, then for the hits you want to display, calling the Business endpoint for each.

The Search endpoint gives enough info for most basic search-results flows, but doesn't cover everything available in the Business endpoint.

**Comment by dmikesell** [comment]
Excellent, thank you for the speedy response.
