### ISSUE TITLE
Difference between token and token secret?

### ISSUE THREAD

**Issue by jchavis06** [Yelp/yelp-fusion#200]
When I used postman to get my access_token, all I was given was the token_type and the access_token. But according to the coding examples in the github, I have to provide the token and the token secret? Is the token just "Bearer" and then the token secret is the access token? I cant figure this out so help would be much appreciated.

**Comment by mittonk** [comment]
@jchavis06 : Try the detailed instructions in this other discussion:
Step 1: https://github.com/Yelp/yelp-api/issues/184#issuecomment-273236300
Step 2: https://github.com/Yelp/yelp-api/issues/184#issuecomment-273503618

We're working on including that level of detail in the main Get Started document:
* https://www.yelp.com/developers/documentation/v3/get_started

Does that help?

**Comment by mittonk** [comment]
@jchavis06 : Also, make sure you're looking at the Fusion examples in 
* https://github.com/Yelp/yelp-fusion#code-samples

not the older V2 examples in
* https://github.com/Yelp/yelp-api --- those are for an older version of the API, and won't work with Fusion.

**Comment by venkata03** [comment]
@mittonk: How to get Token Secret for Old V2 Code. I want to call API through JS. 
Even in CSharp code Token Secret is mentioned: https://github.com/Yelp/yelp-api/tree/master/v2/csharp/YelpAPI 

Please help me in getting Token Secret. 

Also if possible can you please share Yelp Fusion V3 Javascript code for business search.

**Comment by venkata03** [comment]
@mittonk It will be very helpful if we can have something similar to this link for Yelp Fusion V3: https://github.com/levbrie/mighty_marks/blob/master/yelp-search-sample.html

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

([node sample probably works for javascript](https://github.com/Yelp/yelp-fusion/tree/master/fusion/node))
