### ISSUE TITLE
Export Response

### ISSUE THREAD

**Issue by chandanbaidwan** [Yelp/yelp-fusion#204]
Hello all,

I am new to this and I want to export a response into a json file. It will be great if you get some help.
Thanks in advance.

c.

**Comment by skrinik** [comment]
I second this, I used node.js and retrieved results  but need to store the json data as model data (using MVVM) for a web app. Thank you for any help!

**Comment by tomelm** [comment]
Hey, we don't have any built in way to do that. The API already returns all responses as JSON so all you'll need to do is write it to your local file system.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
