### ISSUE TITLE
Trouble with setup

### ISSUE THREAD

**Issue by gcurbelo123** [Yelp/yelp-fusion#205]
I am having trouble calling the API using the URL and my app ID/secret. Can somebody help me out please? I wasn't able to correctly make the POST call using them both. How do you do it? Thank you for any responses!

**Comment by tomelm** [comment]
Hey @gcurbelo123! You should check out our getting started guide and see if that helps you get going: https://www.yelp.com/developers/documentation/v3/get_started

**Comment by gcurbelo123** [comment]
Hey, thanks for the reply! I've checked out the guide, but am still having trouble. I'm not sure how to make the POST call using the App ID and the App Password. I'm using requests, but it's not working. Sorry for the late reply.

**Comment by gcurbelo123** [comment]
Nevermind, now I feel silly. I got it after fixing my simple mistakes. Thank you!
