### ISSUE TITLE
Getting Internal error while trying to get token with Fusion(v3)

### ISSUE THREAD

**Issue by rrengav** [Yelp/yelp-fusion#208]
When I try to get oAuth2 token using the POST request with Fusion api, I get the following error.
I have been getting this for 2 days. 

{u'error': {u'code': u'INTERNAL_ERROR', u'description': u'Something went wrong internally, please try again later'}}

How do I solve this issue ?

**Comment by mittonk** [comment]
@rrengav : 
1. What is your App ID from https://www.yelp.com/developers/v3/manage_app ?
2. How many characters long is your App Secret, and what are the first 3 characters?  (Don't reveal your whole App Secret, it's like a password).

**Comment by rrengav** [comment]
Hi Ken,

Please find below the information that was requested.

App ID: wOT_Nl3hu2z2HbvZUAXGNA
App Secret: Length: 62 and First 3 characters: KBx

**Comment by mittonk** [comment]
@rrengav : Hm, I'd expect the "App Secret" to be 64 characters long, not 62.  Could you double-check that?

**Comment by thecookieorg** [comment]
I'm experiencing the same problem.

App ID: _Duznji9V8WEOsnOo-lE_A
App secret: 64 characters long

**Comment by thecookieorg** [comment]
Secret first 3 characters: o0Y

**Comment by thecookieorg** [comment]
It's working now on my end.

**Comment by rrengav** [comment]
Hi Ken,

You are correct. I missed out two characters in the end. It is 64. It works
now. Thanks a lot for your help.

Regards,
Renga

**Comment by mittonk** [comment]
@rrengav : Wonderful, that explains it.

@thecookieorg : I saw an email that yours was working again, please open a fresh issue if you have more problems.
