### ISSUE TITLE
Does yelp-python only work with API V2, not Fusion?

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-fusion#209]
From an email:
>Hi Ken,
>
>I am a Computer Science graduate student at the Arizona State University.
>
>I have been studying Yelp's Fusion APIs for self learning, and have studied different API responses by sending requests via Postman. Signing up on Yelp Fusion provided me App ID, App Secret, using which I was able to generate the access token for authentication.
>
>I recently discovered yelp-python on GitHub and am in the process of building a simple application in Python 2.7 that helps me pick my current location and randomly chooses (applying custom filters) a nearby restaurant for me to have lunch.
>
>I am faced with a slight dilemma that I was hoping you could guide me with:
>
>The Yelp API library uses Oauth1 and requires the parameter "token_secret", whereas Postman uses OAuth2 for authentication, and does not require "token_secret" to make Fusion API calls. 
>
>I do not have a token_secret, without which I am unable to make any API calls via yelp-python library.
>
>Does this mean that the python library works only for Yelp API v2 calls (the sign up for which has been discontinued since 1st April 2017) and not with Yelp Fusion API calls?
>
>Thank you so much for taking time to read my email!
>
>Kind regards,
>Shruti Sonawane

**Comment by mittonk** [comment]
Shruti,

You're correct --- https://github.com/Yelp/yelp-python is only for the older V2 API, and does not work with Fusion.

We'll put a big loud deprecation notice on it to make that more clear.

For Fusion with Python, have a look at our Fusion code example:
* https://github.com/Yelp/yelp-fusion/tree/master/fusion/python

Following that example will be easier than hand-translating your Postman calls.

Does that give you enough to run with?

**Comment by ssonawane0909** [comment]
That makes sense Ken, thank you so much for pointing me in the right direction.

Kind regards,
Shruti Sonawane

**Comment by mittonk** [comment]
Great!
