### ISSUE TITLE
APIto search reviews?

### ISSUE THREAD

**Issue by zoomski** [Yelp/yelp-fusion#212]
Any chance this is in the roadmap? I see I currently can retrieve 3 full reviews. But I was wondering if I can return a search query on the text in the reviews.

Use Case: I enjoy "pour over" coffee. But Yelp coffee shop searches often return establishments that don't offer it (e.g. Starbucks). The way I find shops that offer it is to:
1) search for nearby coffee shops on Yelp
2) open shop reviews
3) search for "pour over" in review 
4) if not null, verify they have it.

I was hoping to write a program to automate that process.

**Comment by tomelm** [comment]
Hey @zoomski, we don't currently have plans to provide an API to search through reviews. The regular search does take review data into account when searching though, but other factors will also play into the list of businesses returned.

Have you experienced cases where you search for pour over and get businesses that don't offer that?

**Comment by zoomski** [comment]
@tomelm Yes unfortunately all the time. I can search for "single origin" or "third wave coffee" or "pour over" or "chemex" (all "third wave coffee" keywords) and it will always return everything from Dunkin Donuts to Starbucks to Wawa. All of which don't offer those options. So I end up incrementally going through each individual business that *may* be an establishment of this type and then search in the reviews.

**Comment by tomelm** [comment]
Could you send me the queries? I can pass that forward to some of the teams here to investigate.

**Comment by zoomski** [comment]
@tomelm Here are a couple example searches using the web interface below. I've found mixed results. Additionally in this quick test, I found "Third Wave Coffee" to return better results for the most part. It may just be from a more generic perspective, it's a bit too much to ask for distinction between regular coffee shops and "Third Wave" at this point in time.

Here they are:

(1) Searching "Pour Over Coffee" in Crystal City, NJ (Note: I noticed that phrase auto-completes with yelp, cool!)
[Query](https://www.yelp.com/search?find_desc=Pour+Over+Coffee&find_loc=crystal+city%2C+va&ns=1)
- First return is "Expressamente Illy" which isn't Third Wave
- Second return is Commonwealth which is correct.
- Third is SOCCi which isn't a coffee shop
- Fourth and Fifth are Starbucks
- Sixth is a diner

(2) Searching "Third Wave Coffee" in Crystal City, NJ. (Map zoom) (Also autocompletes, cool!)
[Query](https://www.yelp.com/search?find_desc=Third+Wave+Coffee&start=0&l=g:-77.03311987666649,38.86979242612124,-77.08702154902977,38.836371797813264)
- Similar results

(3) Searching "Third Wave Coffee" in Princeton, NJ
[Query](https://www.yelp.com/search?find_desc=Third+Wave+Coffee&find_loc=Princeton,+NJ)
- This actually does a GREAT job. It returns Rojo's, Small World, Greenstreet, Elixr, etc which are all Third Wave.
- It does however expand the search to ~50-100 miles around Princeton to get them (which is fine by me)

(4) Searching "Pour Over Coffee" in Princeton, NJ
[Query](https://www.yelp.com/search?find_desc=Pour+Over+Coffee&find_loc=Princeton,+NJ)
- This one works for the first two (Rojo's and Small World)
- But third onwards are ice cream shops, pastry shops, diners, etc.

(5) Searching "Third Wave Coffee" in Collingswood, NJ
[Query](https://www.yelp.com/search?find_desc=Third+Wave+Coffee&find_loc=Collingswood,+NJ)
- First two are accurate (Greenstreet, Elixr. But following are mixed.

(6) Searching "Pour Over Coffee" in Collingswood, NJ
[Query](https://www.yelp.com/search?find_desc=Pour+Over+Coffee&find_loc=Collingswood,+NJ)
- The first hit, Revolution Roasters, is actually the optimal result since it is the closest, and only, Third Wave shop in or immediately near Collingswood. In my opinion, it would have been optimal first hit for query 5 above.
- The rest aren't too great. For example it has Krispy Kreme and Pop Shop.

**Comment by tomelm** [comment]
Thanks @zoomski! I'll share this with our search teams. I'm going to close out this ticket in the meantime since we've unfortunately don't have any plans for a review search right now.
