### ISSUE TITLE
Get distance when retrieving individual business

### ISSUE THREAD

**Issue by Pinski** [Yelp/yelp-fusion#213]
Hello,

Currently the only way to get a distance to a business is when a search is preformed.  I have a situation where I have an Id for a business and I know where the user is located.  It would be nice if I could send the location information to the [Business API](https://www.yelp.com/developers/documentation/v3/business) just like I would the [Search API](https://www.yelp.com/developers/documentation/v3/business_search) and get the distance back in the response object.

Are there any plans to add functionality like this?  Or am I being ridiculous and I should just calculate it myself?

Thanks.

**Comment by tomelm** [comment]
There are not plans to do this and I don't think it makes sense to add it to the business API. It's pretty strictly for data retrieval based on 1 business, the location of the user isn't really involved. This is something you should be able to calculate on your side :)

**Comment by Pinski** [comment]
Makes total sense to me.  Thanks for being so responsive, I appreciate it.
