### ISSUE TITLE
Business API takes list of businesses

### ISSUE THREAD

**Issue by Pinski** [Yelp/yelp-fusion#214]
Hello,

So I have a case where I have a list of Ids for business that I want to retrieve all at once.  Of course, I can do this asynchronously and make multiple calls.  But it would be nice if I could submit a list of Ids to your [Business API endpoint](https://www.yelp.com/developers/documentation/v3/business).

Are there any plans for creating something like this?

Thanks.

**Comment by tomelm** [comment]
We don't have anything planned to do this exactly but we should have something in a few weeks that'll let you do something similar. I can't share more information at the moment though.

**Comment by Pinski** [comment]
I understand, look forward to whatever you have in mind.

**Comment by tomelm** [comment]
Hey @Pinski! We released a GraphQL that can let you emulate this functionality by passing multiple queries in 1 request. Check it out, it should solve your problem:
https://www.yelp.com/developers/graphql/guides/basic_usage
https://www.yelp.com/developers/graphql/query/business (search for "Load a businesses in bulk")

**Comment by Pinski** [comment]
This looks great.  Basically what I had in mind, but better.  Thanks!
