### ISSUE TITLE
How do I make the choices Random?

### ISSUE THREAD

**Issue by mattw114862** [Yelp/yelp-fusion#215]
I have the Yelp API integrated into my mobile app I am working on. It's a random restaurant generator that will randomly select a place to eat based on gps location. 

My question is how do I make the choices random instead of it being the same selections every time? The API seems to generate the selection based on Yelp rating but I want to have it completely randomized to where every time I hit the button to generate a result its something different everytime.

**Comment by tomelm** [comment]
The API doesn't support that use case, it's not something that comes up on our side, but this is also why we make the API available :D

You'll have to figure out how best you prefer to handle this, maybe pulling ~100-200 restaurants or making a few searches and then randomly picking one.

**Comment by mattw114862** [comment]
So how do I pull 100-200 restaurants but only have, lets say 5 of those, randomly selected from that pull?

**Comment by tomelm** [comment]
You'll want to use the paging and offset params in search: https://www.yelp.com/developers/documentation/v3/business_search

You can make a number of requests and keep using the offset to page from the initial result list.

**Comment by mattw114862** [comment]
Alright I see the offset parameters and I have that set to 5 on my App and that works, it shows 5 selections but I don't see 'paging' and I don't understand how to have the API randomly select 5 out of the 100s listed.

**Comment by mattw114862** [comment]
Here is a website I found that is basically what I want for my App. Every time I enter my zip code and hit go it picks a different restaurant for me. [http://www.restaurantgenerator.com/](url)

**Comment by tomelm** [comment]
@mattw114862 sorry, I meant to say limit (fixed my comment). The key one specifically if offset. Give it offset=20 or offset=40 to pull the next page of results. The number is just the count of businesses you want to start from so you can enter whatever values you want (up until around 1000)

**Comment by mattw114862** [comment]
I see..do you think this will provide me with what I want? Does the offset randomly choose from the limit pool?

**Comment by tomelm** [comment]
It should but you'll still need to do the work to randomly pick one. The offset only lets you move through the list. Imagine it being like the page number (scroll down to the bottom here: https://www.yelp.com/search?find_loc=San+Francisco%2C+CA) but in counts of 20.

**Comment by mattw114862** [comment]
I sent you an email with some screenshots.

**Comment by tomelm** [comment]
Tried to respond to your email but it didn't work.

So, like I said you need to use the offset parameter, make a bunch of requests, and then randomly pick them. It'll look roughly like this:

GET /search?offset=0 => get first 20 businesses, total 20
GET /search?offset=20 => get next 20 businesses, total 40
GET /search?offset=40 => get next 20 businesses, total 60
GET /search?offset=60 => get next 20 businesses, total 80
GET /search?offset=80 => get next 20 businesses, total 100

Once you have 100 businesses, randomly pick 5. You need to over pull data to make the a good random selection.

**Comment by mattw114862** [comment]
Well I think I may have it. Am I able to link my app here to have someone review? Would love Yelp to place it on their developers web page!

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

(Random return in search won't be added to the API, but you can achieve it yourself by iterating through the paginated search results and providing the random logic yourself.)

**Comment by kona808** [comment]
> Well I think I may have it. Am I able to link my app here to have someone review? Would love Yelp to place it on their developers web page!

Hello, I am trying to do a very similar thing and I don't know where to begin was wondering if you had solved your issue and even made a random choice. If you could lend some knowledge on how I may be able to do this myself.
