### ISSUE TITLE
YELP API TOKEN AND TOKEN SECRET

### ISSUE THREAD

**Issue by barleigh** [Yelp/yelp-fusion#217]
Hi , We are trying add YELP in our website , we generate the APP with API user and secret code, but we dont know how generate TOKEN user and SECRET code, can you help ?

**Comment by tomelm** [comment]
Hey @barleigh, you should check out our authentication guide: https://www.yelp.com/developers/documentation/v3/authentication

It should explain what you need to do.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
