### ISSUE TITLE
WordPress user-agent results in 403

### ISSUE THREAD

**Issue by kevinwhoffman** [Yelp/yelp-fusion#218]
I am making a request to the Business API using the  `https://api.yelp.com/v3/businesses/{id}` endpoint. I have a bearer token and the request is successful in Postman. When attempting to recreate that request in WordPress, I came across some unexpected behavior.

## Not Working - 403

When I attempt to make the request with WordPress using [`wp_remote_get()`](https://developer.wordpress.org/reference/functions/wp_remote_get/), a `403` status is returned.

```php
$response = wp_remote_get( $this->request_url, array(
	'headers' => array(
		'authorization' => 'Bearer ' . $bearer_token,
	)
) );
```

## Working - 200

When I override the `user-agent`, then the request is successful and a `200` status is returned.

```php
$response = wp_remote_get( $this->request_url, array(
	'user-agent' => '',
	'headers' => array(
		'authorization' => 'Bearer ' . $bearer_token,
	)
) );
```

## Background

Note: When calling `wp_remote_get()`, WordPress sets a default `user-agent` that looks like this: `WordPress/4.7.4`.

If I override the `user-agent` value by providing a blank value or _any other string_ that does not include `WordPress`, then the request is successful and returns `200` status.

However, if I do not override the `user-agent` value and allow WordPress to use `WordPress/4.7.4`, then the request results in a 403.

## Possible Explanation

Can anyone confirm whether the Fusion API blocks the `WordPress` user-agent? Is there another explanation?

**Comment by tomelm** [comment]
hey @kevinwhoffman, we do block the `WordPress` user agent across the entire site. That's definitely the cause here.

**Comment by kevinwhoffman** [comment]
@tomelm Thanks for confirming. Can you share why `WordPress` is blocked as a user-agent? I was making this request from a standalone WordPress installation downloaded from WordPress.org. This was not a site on the WordPress.com platform.

**Comment by tomelm** [comment]
I can't share too much other than we've had issues with Wordpress blogs in the past and have had to block them completely.

**Comment by n0ttsweet** [comment]
I am having the same issue, I believe. I purchased a WordPress plugin to return star rating and top reviews, but my domain has been blocked. I am hoping there is an exceptions list I can get on?
Or wondering if @kevinwhoffman figured out a work-around.

Thanks!

**Comment by raajtram** [comment]
Hey @tomelm! is the reason still a secret? I'm curious why WordPress requests would be blocked entirely. @kevinwhoffman's suggested `user-agent` hack does the trick (thanks!) but one still wonders!
