### ISSUE TITLE
display_address field is no longer in /businesses/search

### ISSUE THREAD

**Issue by vkman** [Yelp/yelp-fusion#22]
Is it possible to re-introduce the nicely formatted display_address field in the location object within the results for business/search or business/{id}?

**Comment by tomelm** [comment]
@vkman could you tell me a little bit about your use case? We provide all the data for you to be able to reconstruct it yourself based on the specific information you'd like to display

**Comment by vkman** [comment]
The use case is that different countries use different components of the location object to construct an address.  Sometimes the state is needed (e.g. - U.S.), sometimes not.  The country  code is not the full country name.  We are using the properly formatted address to generate directions from a mapping API.

**Comment by mittonk** [comment]
(Showing some of the non-trivial "nice formatting" might explain how this was useful in V2, I'll see if I can dig up some good examples.  I remember using this for Japan and Hong Kong in particular.)

**Comment by mittonk** [comment]
@vkman : We've added `display_address` similar to the one in V2:
* https://api.yelp.com/v3/businesses/menton-boston
```
  "location": {
    "display_address": [
      "354 Congress St",
      "Boston, MA 02210"
    ],
```

* https://api.yelp.com/v3/businesses/menton-boston?locale=fr_FR
```
  "location": {
    "display_address": [
      "354 Congress St",
      "Boston, MA 02210",
      "États-Unis"
    ],
```
