### ISSUE TITLE
Yelp Fusion (Android Studio) help!

### ISSUE THREAD

**Issue by iforgotmybrain** [Yelp/yelp-fusion#220]
So I’ve been running into a number of problems all of which force my app to crash the first being when i make a call to the YelpFusionApiFactory’s createAPI function passing the appID and the AppSecret. I was able to get around this by going to a third party (i.e. Rapid) which generated the access token. i know use the …Factory’s createAPI function passing in the access token. however this does not fix the original problem i was having the next few problems all occur when trying to use the actual api for instance calling execute on the response object....i am a newbie to yelp and android studio...though i feel i have come accustom to android studio .....THANK YOU IN ADVANCE FOR ANY HELP
the app itself doesn't  do anything.. at the moment I'm just trying to get comfortable with api
<img width="697" alt="screen shot 2017-05-09 at 9 02 55 am" src="https://cloud.githubusercontent.com/assets/28038100/25860652/0fac81c2-3497-11e7-8b80-7d5ef3e5fba3.png">

**Comment by tzuhanwu** [comment]
Hey, the YelpFusionFactory is from a 3rd party library so we don't provide support for it. You should try to open an issue on the repository of that library to see if the original author can help out.

**Comment by iforgotmybrain** [comment]
wow! my apologies
