### ISSUE TITLE
graph QL can't search categories

### ISSUE THREAD

**Issue by DaGebster** [Yelp/yelp-fusion#222]
i think something is up with the category search, I no expert on graphql (yet)...
but every time I query categories... I get the following:

{
  "data": null,
  "errors": [
    "Expected list like type for <class 'str'>: mexican"
  ]
}

syntax should be pretty straight forward...

see snippets below Remindered out with atttempts that failed on multiple tries through the (very useful!) test console

 { search( 
  #categories:"cafe",
  #categories:"hair"
  #categories:hair,
    # categories: "[hair,barber]",  
     # categories:["title:barber,title:hair"],
    #[categories:hair,categories:barber],  
  #[categories:"hair,barber"],  
  #categories:ALIAS["hair,BARBER"],
  #categories:"[hair,BARBER]",

  #categories:"mexican",
  		#term:"hair"  
  			location: "san francisco",
  			limit: 10,
  
)
       {
    total
    business {
      is_closed
      phone
      name
      rating
      reviews {
        rating
        text
        time_created
        url
      }
      url
      categories {
        #title: "hair"
        alias
      }
      review_count
      location {
        address1
        city
        state
        country
      }
    }
  }
  }

**Comment by tomelm** [comment]
Thanks for the report! Filed a ticket and will have someone look at this.

**Comment by mittonk** [comment]
This was indeed a bug in our categories-argument parsing!  Using the `categories: "bars,french"` syntax from https://www.yelp.com/developers/graphql/query/search : 
```
{
  search(term: "appetizer", location: "san francisco", categories: "bars,french", limit: 3) {
    business {
      id
    }
  }
}
```

```
{
  "data": {
    "search": {
      "business": [
        {
          "id": "hogwash-san-francisco"
        },
        {
          "id": "the-social-study-san-francisco"
        },
        {
          "id": "the-view-san-francisco-2"
        }
      ]
    }
  }
}
```

@DaGebster : Thanks for reporting this!
