### ISSUE TITLE
GraphQL failure when adding coordinate's latitude and longitude field to query

### ISSUE THREAD

**Issue by razola** [Yelp/yelp-fusion#223]
[This query](https://www.yelp.com/developers/graphiql?query=%7B%0A%20%20search(term%3A%20%22banana%20bread%22%2C%20latitude%3A%2030.307890996115315%2C%20longitude%3A%20-97.75379601852251%2C%20radius%3A%2029283%2C%20sort_by%3A%20%22best_match%22%2C%20limit%3A%2050%2C%20offset%3A%200)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20rating%0A%20%20%20%20%20%20url%0A%20%20%20%20%20%20review_count%0A%20%20%20%20%20%20coordinates%20%7B%0A%20%20%20%20%20%20%20%20latitude%0A%20%20%20%20%20%20%20%20longitude%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) returns an error if the coordinate's latitude and longitude field are included. [Without them](https://www.yelp.com/developers/graphiql?query=%7B%0A%20%20search(term%3A%20%22banana%20bread%22%2C%20latitude%3A%2030.307890996115315%2C%20longitude%3A%20-97.75379601852251%2C%20radius%3A%2029283%2C%20sort_by%3A%20%22best_match%22%2C%20limit%3A%2050%2C%20offset%3A%200)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20rating%0A%20%20%20%20%20%20url%0A%20%20%20%20%20%20review_count%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), it works fine.

**Comment by tomelm** [comment]
Thanks! Looking into this.

**Comment by tomelm** [comment]
@razola are you still having problems with this? It's working for me.

**Comment by razola** [comment]
That search query works now, but the underlying issue isn't solved yet. I narrowed it down and found that I get that error when a business without a lat/lng is returned.

[Here's an example](https://www.yelp.com/developers/graphiql?query=%7B%0A%20%20business(id%3A%20%2218-folds-nashville%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20coordinates%20%7B%0A%20%20%20%20%20%20latitude%0A%20%20%20%20%20%20longitude%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).

**Comment by tomelm** [comment]
Thanks @razola, that's helpful! I'll take another look at this.

**Comment by mittonk** [comment]
@razola : OK, tracked this to businesses where we don't know an exact lat-lng, and fixed how we return that error.
```
{
  business(id: "18-folds-nashville") {
    id
    name
    coordinates {
      latitude
      longitude
    }
  }
}
```
now gives:
```
{
  "data": {
    "business": {
      "id": "18-folds-nashville",
      "name": "18 Folds",
      "coordinates": null
    }
  }
}
```

That lines up with the question-mark on the map in https://www.yelp.com/biz/18-folds-nashville --- you might want to do something similar in your integration.  (Most, but not all, businesses will have lat-lngs.)

(I suspect a similar business was showing up in some, but not all, of the "banana bread" queries that worked some days but not others.)

Does that give you enough to work with?

**Comment by razola** [comment]
Perfect! Thank you Ken \o/
