### ISSUE TITLE
Wrong type of quotes in documentation for GraphQL

### ISSUE THREAD

**Issue by Pinski** [Yelp/yelp-fusion#225]
Minor nitpick, not even sure if it's a browser issue (using FF) or what.  But on this page:
https://www.yelp.com/developers/graphql/guides/basic_usage

The quotes used on that page in your examples don't seem to work with your GraphQL API.  When I copy and pasted the examples into Postman, I would get a 500 error.  When I changed the quotes to whatever Postman uses natively for quotes, the calls worked correctly.

Just FYI.

**Comment by tomelm** [comment]
Ah, heh. Will get that fixed. Thanks for reporting!
