### ISSUE TITLE
How increase limit number? 

### ISSUE THREAD

**Issue by francesco1119** [Yelp/yelp-fusion#228]
on line 61 I set `SEARCH_LIMIT = 10` but it still returns me 1 bar for San Francisco

**Comment by mittonk** [comment]
@francesco1119 : The Python example first does a search, then prints more data about the first search result.

Sounds like you want to look at all the results --- so you should have a look at the "businesses" results on https://github.com/Yelp/yelp-fusion/blob/master/fusion/python/sample.py#L166 .

Does that give you something to work with?

**Comment by francesco1119** [comment]
...uhhh... not much, I just can see `businesses = response.get('businesses')` on line 166.
Is the limitation managed by Yelp or by sample.py? 
If it's managed by sample.py at what line is that value?

**Comment by joomango** [comment]
Hi I have the same issue. When I try to set the default variable 'SEARCH_LIMIT' over 50, it throws an error and returns no result. But the document specifies I could get 1,000 business data. How should I modify the sample.py script for more results?

**Comment by mittonk** [comment]
@joomango : Check out the `offset` parameter in 
* https://www.yelp.com/developers/documentation/v3/business_search

`offset=50` gets you results 51, 52, ...

**Comment by francesco1119** [comment]
There is no `offset `in the sample.py. I will use Postman. Thank you anyway

**Comment by mittonk** [comment]
You're correct --- `sample.py` only demonstrates a few of the most common arguments, not every one.

If Postman is easier for you, great.

**Comment by francesco1119** [comment]
Cool, this is what I needed to know

**Comment by mittonk** [comment]
And if you do end up using Python, adding an offset to the search call would look about like:
```python
    url_params = {
        'term': term.replace(' ', '+'),
        'location': location.replace(' ', '+'),
        'limit': SEARCH_LIMIT,
        'offset': 20,
    }
    return request(API_HOST, SEARCH_PATH, bearer_token, url_params=url_params)
```

**Comment by francesco1119** [comment]
You are a Dev with a big heart. 
So if Yelp limit is 25000 I can set offset to 24999? 
Sounds too good to be true to me but I'm ready to have a look at Yelp's price. I just wonder what is the piratical limit

**Comment by tomelm** [comment]
@francesco1119 the global limited is 1000. We don't allow a higher limit.

**Comment by mittonk** [comment]
(25000 is API requests per day.)
