### ISSUE TITLE
GET to https://api.yelp.com/v3/businesses/<id> returns UNAUTHORIZED_ACCESS_TOKEN

### ISSUE THREAD

**Issue by eliantonioni** [Yelp/yelp-fusion#229]
I'm making GET https://api.yelp.com/v3/businesses/glenas-san-francisco 
with header  {"Authorization":"Bearer <access_token>"}

and that was fine a week ago, but now I get 
{
  "error": {
    "code": "UNAUTHORIZED_ACCESS_TOKEN",
    "description": "The access token provided is not currently able to query this endpoint"
  }
}

Also I tried to get new access token by making POST https://api.yelp.com/oauth2/token
grant_type:client_credentials
client_id:<my clientid>
client_secret:<my secret>

but have no luck with this either:
{
  "error": {
    "code": "UNAUTHORIZED_CLIENT",
    "description": "Specified client is not authorized."
  }
}

What was happened with my yelp account? I can log in but don't see nothing bad there, and I haven't found any clues in documentation regarding these error descriptions.

**Comment by tomelm** [comment]
What's your client_id? (don't share your client_secret)

**Comment by eliantonioni** [comment]
client_id=kSTu1W9ZjAFAb-W9CtON5A

**Comment by ipetukhov** [comment]
Hi @tomelm 
I have a similar issue now. My client_id=NhHgulkfIPnCqO0vyzne2w

**Comment by tomelm** [comment]
@ipetukhov when did you create your access token? Has it expired?

**Comment by NeyLanjewar** [comment]
Hi! Facing the same problem. Please help! client_id = sgKks4tgj19lAS1UHIRnog

**Comment by dellbell2016** [comment]
@tomelm 

1) This is how I create access token in Python 

data = {'grant_type': 'client_credentials',
        'client_id': app_id,
        'client_secret': app_secret}
token = requests.post('https://api.yelp.com/oauth2/token', data=data)
        access_token = token.json()['access_token']
        print(access_token)
url = 'https://api.yelp.com/v3/business/' + id.strip()
        Bear = 'bearer' + ' ' + access_token
        head = {'Authorization': Bear}
url = url + '?' + urllib.parse.urlencode(payload)
        print(url)
        resp = requests.get(url, headers=head)
        print(resp)
        result = resp.json()

and this is my client Id = 2qib1d4R-an5q2ZagKJ3Pg 

When I use this client id, I am able to use search API(that is, https://api.yelp.com/v3/businesses/search'  ) , but not businesses API (that is https://api.yelp.com/v3/business/{id}  ). 

Could some one look into this issue as soon as possible. Please. 

2) Also How to cache access token (as suggested here https://www.yelp.com/developers/documentation/v3/authentication ) 
Thanks

**Comment by dellbell2016** [comment]
@NeyLanjewar @ipetukhov @eliantonioni - Did you guys got this resolved?

**Comment by FlawaCLV** [comment]
Same problem for me ! client_id = sppAVb-Gu-of_9lKalp5KQ

**Comment by FlawaCLV** [comment]
I've personally found my issue. When my server starts I get an ACCESS_TOKEN but it expires after 3 months. I've just restarted my production server instances and got a new ACCESS_TOKEN. I had a similar issue with the Instagram API.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

**Comment by Mike-Wood** [comment]
I just made a new app and I'm getting the same `UNAUTHORIZED_ACCESS_TOKEN` error

**Comment by FlawaCLV** [comment]
@Mike-Wood since Decembre 7, 2017 Yelp now uses an **API Key** / **API Secret** authentication protocol. See documentation [here](https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going).

**Comment by Mike-Wood** [comment]
@FlawaCLV thanks for the fast reply although I'm already using api keys how it said in the documentation, I'm not sure what I did to make this happen, all i did was delete my app and make it again (I'm sure I'm using the new api key now)
