### ISSUE TITLE
Follow user?

### ISSUE THREAD

**Issue by rcurrier666** [Yelp/yelp-fusion#230]
Is it possible to get a list of a user's reviews (given their ID) so one could "follow" a reviewer that one trusts? Doesn't need to return the actual review, just the review ID and creation date (maybe a snippet, but that is just sugar for what we have in mind). We could then open the review in yelp.com,

**Comment by mittonk** [comment]
Not yet!

**Comment by LifeisaJourney** [comment]
Any updates?

**Comment by KCJwhite** [comment]
Is this something that can be handled on a special use case?  I actually want to grab my own reviews to build links to the Yelp pages of businesses that I've liked.  The Atom/RSS feed would even work, if it went all the ways back to my first review.

**Comment by LifeisaJourney** [comment]
> Is this something that can be handled on a special use case? I actually want to grab my own reviews to build links to the Yelp pages of businesses that I've liked. The Atom/RSS feed would even work, if it went all the ways back to my first review.

It's not that big of an issue that this feature needs to be implemented.

**Comment by KCJwhite** [comment]
> > Is this something that can be handled on a special use case? I actually want to grab my own reviews to build links to the Yelp pages of businesses that I've liked. The Atom/RSS feed would even work, if it went all the ways back to my first review.
> 
> It's not that big of an issue that this feature needs to be implemented.

Sorry, that question for was @mittonk.

**Comment by dan98765** [comment]
Thanks for the interest, everyone. The request to "get reviews by user ID" is tracked internally, but it has not been selected for development. Also being considered (as a separate issue, but related to the discussion here) is enabling users who authenticate as the owner a Yelp User account (3-legged OAuth) to get all reviews by their own Yelp account. 

For anyone wishing to chime in on this issue, it would be helpful to describe your use case & clarify which of the proposed features would best fit your use case.

**Comment by KCJwhite** [comment]
My apologies.  Once I started thinking about all of the ways someone could monetize the reviews outside of Yelp using my use case, I realized my angle is not in Yelp's best interest.
