### ISSUE TITLE
graphql: Open_at won't take string or integer

### ISSUE THREAD

**Issue by zmbc** [Yelp/yelp-fusion#232]
I want to search businesses that are open at a particular time. [First I tried this](https://www.yelp.com/developers/graphiql?query={%0A%20search(term%3A%20"coffee%20shop"%2C%0A%20%09%09%09%20location%3A%20"Seattle"%2C%0A%20%09%09%09%20open_at%3A%201495828800)%20{%0A%20business%20{%0A%20name%0A%20}%0A%20}%0A}), but got:

```
{
  "data": null,
  "errors": [
    "Argument \"open_at\" has invalid value 1495828800.\nExpected type \"String\", found 1495828800."
  ]
}
```

So [I tried this](https://www.yelp.com/developers/graphiql?query={%0A%20search(term%3A%20"coffee%20shop"%2C%0A%20%09%09%09%20location%3A%20"Seattle"%2C%0A%20%09%09%09%20open_at%3A%20"1495828800")%20{%0A%20business%20{%0A%20name%0A%20}%0A%20}%0A}) (the same thing, with quotes around the `open_at`, and now I get:

```
{
  "data": null,
  "errors": [
    "'1495828800' is not of type 'integer'\n\nFailed validating 'type' in schema:\n    {'description': 'UTC timestamp for open time filter',\n     'in': 'query',\n     'name': 'open_time',\n     'required': False,\n     'type': 'integer'}\n\nOn instance:\n    '1495828800'"
  ]
}
```

**Comment by mittonk** [comment]
Hm, does smell like a bug to me.

**Comment by tomelm** [comment]
@zmbc this should be fixed now! Sorry for the delay.
