### ISSUE TITLE
Yelp Fusion Search API - returning incorrect data?

### ISSUE THREAD

**Issue by azaleas** [Yelp/yelp-fusion#234]
I'm playing with Yelp Fusion Search API and noticed that search request with location parameter set to something like "xxx" or "sss" returns results:

Example:
**Query**: https://api.yelp.com/v3/businesses/search?location=zzz&limit=3

**Returns**: 
```
{
  "businesses": [
    {
      "id": "bella-italia-ennis",
      "name": "Bella Italia",
      "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/LDqmzU2Y-nhSvPmr7yc4Tw/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/bella-italia-ennis?adjust_creative=jos-y9cCoGyrA2dE3OOVrg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=jos-y9cCoGyrA2dE3OOVrg",
      "review_count": 30,
      "categories": [
        {
          "alias": "italian",
          "title": "Italian"
        },
        {
          "alias": "bars",
          "title": "Bars"
        }
      ],
      "rating": 4.5,
      "coordinates": {
        "latitude": 32.32835,
        "longitude": -96.62451
      },
      "transactions": [],
      "price": "$",
      "location": {
        "address1": "105 S Kaufman",
        "address2": "",
        "address3": "",
        "city": "Ennis",
        "zip_code": "75119",
        "country": "US",
        "state": "TX",
        "display_address": [
          "105 S Kaufman",
          "Ennis, TX 75119"
        ]
      },
      "phone": "+19728757571",
      "display_phone": "(972) 875-7571",
      "distance": 2495.06682311
    },
    {
      "id": "pop-top-coffee-shop-ennis",
      "name": "Pop Top Coffee Shop",
      "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/e-eCf7dw56sJnNo3JZ6cyQ/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/pop-top-coffee-shop-ennis?adjust_creative=jos-y9cCoGyrA2dE3OOVrg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=jos-y9cCoGyrA2dE3OOVrg",
      "review_count": 13,
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "rating": 5,
      "coordinates": {
        "latitude": 32.3280982971191,
        "longitude": -96.6283950805664
      },
      "transactions": [],
      "price": "$",
      "location": {
        "address1": "120 N Dallas St",
        "address2": "",
        "address3": "",
        "city": "Ennis",
        "zip_code": "75119",
        "country": "US",
        "state": "TX",
        "display_address": [
          "120 N Dallas St",
          "Ennis, TX 75119"
        ]
      },
      "phone": "+14693830617",
      "display_phone": "(469) 383-0617",
      "distance": 2768.8728496139997
    },
    {
      "id": "firehouse-grill-ennis",
      "name": "Firehouse Grill",
      "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/kRSm06fo4wk4StHlgS6O8A/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/firehouse-grill-ennis?adjust_creative=jos-y9cCoGyrA2dE3OOVrg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=jos-y9cCoGyrA2dE3OOVrg",
      "review_count": 70,
      "categories": [
        {
          "alias": "tradamerican",
          "title": "American (Traditional)"
        }
      ],
      "rating": 4,
      "coordinates": {
        "latitude": 32.326306,
        "longitude": -96.626218
      },
      "transactions": [],
      "price": "$$",
      "location": {
        "address1": "219 SW Main St",
        "address2": "",
        "address3": "",
        "city": "Ennis",
        "zip_code": "75119",
        "country": "US",
        "state": "TX",
        "display_address": [
          "219 SW Main St",
          "Ennis, TX 75119"
        ]
      },
      "phone": "+19728758353",
      "display_phone": "(972) 875-8353",
      "distance": 2486.062243942
    }
  ],
  "total": 257,
  "region": {
    "center": {
      "latitude": 32.312949751648766,
      "longitude": -96.60484313964844
    }
  }
}
```

Is this a normal behavior of the API or am I missing something from the documentations? Ideally, I would expect **LOCATION_NOT_FOUND** error to be returned.

**Comment by mittonk** [comment]
LOCATION_NOT_FOUND would be a more helpful answer here, but I suspect trying to tweak geo-location parameters to reject "fff" would end up giving LOCATION_NOT_FOUND for some little town as well --- perhaps "Ffawyddog" (in Wales, UK).  Unfortunately, human location addresses aren't as easy to enumerate and validate as IP addresses.

(https://en.wikipedia.org/wiki/Precision_and_recall goes into some detail on this tradeoff.)

So... not exactly normal, but maybe not a solvable bug either.

**Comment by azaleas** [comment]
I used the API to create a search by the cities, so my work around was to check the returned results (business.location.city) with my search input. 

I would understand the issue with "fff" and "Ffawyddog" (cool name for a town btw:) ).  But the above query with "zzz" returns a not so normal result (why exactly it's returning Ennis/Texas/USA? )

Maybe it's not a solvable bug, but I guess an explanation of some sort in the documentations would be a good thing.

**Comment by mittonk** [comment]
More explanations could be helpful ---
 https://en.wikipedia.org/wiki/Geocoding#Complicating_factors might be a good starting point.

Geocoding is a heuristic based on a large pile of data.  Someone, somewhere, once referred to a location like "1 Main St, Apt zzz, Ennis, TX" or similar; I can't dig deep enough to find who, when, or exactly what the address was.  For comparison, Google Maps thinks "zzz"
 might be someone's garage in Pennsylvania (https://www.google.com/maps/search/zzz), which doesn't seem like a much better answer.  

("YYY" is definitely Mont-Joli Airport in Canada, though: https://www.yelp.com/search?find_desc=&find_loc=yyy .)

**Comment by azaleas** [comment]
@mittonk Thanks for the link and details

**Comment by watterso** [comment]
glenas-san-francisco

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
