### ISSUE TITLE
Why fusion returns max 50 businesses?

### ISSUE THREAD

**Issue by francesco1119** [Yelp/yelp-fusion#235]
I created a Python script 

```
app_id = 'MYAPPID'													
app_secret = 'MYAPPSECRET'		
data = {'grant_type': 'client_credentials',											
        'client_id': app_id,														
        'client_secret': app_secret}												
token = requests.post('https://api.yelp.com/oauth2/token', data=data)				
access_token = token.json()['access_token']											
url = 'https://api.yelp.com/v3/businesses/search'									
headers = {'Authorization': 'bearer %s' % access_token}								
# Yelp v3 API: https://nz.yelp.com/developers/documentation/v3                      
params = {'cc': args.country,														
		  'location': args.location,												
		  'categories': args.category,												
		  'limit': args.limit}														
response = requests.get(url=url, params=params, headers=headers)					

results = response.json()['businesses']
for business in results:
     print(business['name'])

print '\nTotal Cinemas retrieved: ' , len(results)
```

that works fine withinput:   `--country FR --location Paris --category movietheaters --limit 50` and indeed I can return 50 cinemas in Paris.
But if I set 51 as limit Python says:
```
Traceback (most recent call last):
  File "./VISTA.py", line 52, in <module>
    results = response.json()['businesses']
KeyError: 'businesses'
```
This is a mystery to me as Postman can return 149 businnesses with the query `https://api.yelp.com/v3/businesses/search?cc=FR&location=Paris&categories=movietheaters`

![149](https://cloud.githubusercontent.com/assets/3397477/26373343/470ff3a0-4055-11e7-990c-72f229627af4.PNG)

**Comment by tomelm** [comment]
The API doesn't allow more than 50 per request. You need to use the offset parameter to get the next page of results.

**Comment by francesco1119** [comment]
Cool, your API [documentation ](https://nz.yelp.com/developers/documentation/v2/search_api)just says "Offset the list of returned business results by this amount".

Is there any example about how to use it? It's a bit confusing.

And why Postman can return all the 149 without `offset`?

**Comment by tomelm** [comment]
Postman isn't returning all 149 without an offset. The total you see is the total number of businesses represented in your specific query, that doesn't mean it's returning 149 of them.

For using offset, give it any number. If you have limit=50, that means you're getting results 1-50, so give it offset 51 and you'll get 51-100.

**Comment by francesco1119** [comment]
Thank you, please specify this on the documentation.

Basically is the same as `next_page_token` for google-API

**Comment by mittonk** [comment]
(It's also very similar to MySQL or PostgreSQL's `limit` and offset` parameters.)

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

**Comment by inameandy** [comment]
I want to make some correction on the previous comment 

> For using offset, give it any number. If you have limit=50, that means you're getting results 1-50, so give it offset=51 and you'll get 51-100.

The offset should be 50 and not 51 for you to get 51-100.

**Comment by nateofspades** [comment]
I had the same problem as the OP. Now I'm trying to look at coffee shops in NYC, which has 13800 results, but it seems I'm restricted to limit+offset<=1000. Is it not possible to get all of them?

**Comment by AdiBev** [comment]
I'm having same problem as @nateofspades. I'm using graphql api to get data everytime I give offset of 1000 or above get this error       `"message": "Something went wrong internally, please try again later.",`. Seems like you can't get all the businesses data
