### ISSUE TITLE
graphQL: Can't use a query variable for search location property

### ISSUE THREAD

**Issue by zmbc** [Yelp/yelp-fusion#237]
I'm trying to search businesses by location using query variables using [this query](https://www.yelp.com/developers/graphiql?operationName=SearchForBusinesses&query=query%20SearchForBusinesses(%0A%20%20%20%20%20%20%24category%3A%20String%2C%0A%20%20%20%20%20%20%24radius%3A%20Float%2C%0A%20%20%20%20%20%20%24generalLocation%3A%20String)%20%7B%0A%20%20search(term%3A%20%24category%2C%0A%20%20%20%20%20%20%20%20%20radius%3A%20%24radius%2C%0A%20%20%20%20%09%09%20location%3A%20%24generalLocation%2C%0A%20%20%20%20%20%20%20%20%20)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20location%20%7B%0A%20%20%20%20%20%20%20%20formatted_address%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%22category%22%3A%20%22coffee%22%2C%20%22radius%22%3A%203000.0%2C%20%22generalLocation%22%3A%20%22U%20District%22%7D). The response I get is:
```
{
  "data": null,
  "errors": [
    "The server could not comply with the request since it is either malformed or otherwise incorrect."
  ]
}
```

What's odd about this is that [this almost-identical query](https://www.yelp.com/developers/graphiql?operationName=SearchForBusinesses&query=query%20SearchForBusinesses(%0A%20%20%20%20%20%20%24category%3A%20String%2C%0A%20%20%20%20%20%20%24radius%3A%20Float)%20%7B%0A%20%20search(term%3A%20%24category%2C%0A%20%20%20%20%20%20%20%20%20radius%3A%20%24radius%2C%0A%20%20%20%20%09%09%20location%3A%20%22U%20District%22%2C%0A%20%20%20%20%20%20%20%20%20)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20location%20%7B%0A%20%20%20%20%20%20%20%20formatted_address%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%22category%22%3A%20%22coffee%22%2C%20%22radius%22%3A%203000.0%2C%20%22generalLocation%22%3A%20%22U%20District%22%7D) works fine. The problem appears to only happen when passing the location property as a query variable.

Any idea why this might be?

**Comment by mittonk** [comment]
Reproduced failure.

@zmbc : Nice repro steps, we'll have a look.

**Comment by aleksdao** [comment]
@mittonk Did you get a chance to look into this? Seems like @zmbc's query is still erroring due to the `location` query variable

**Comment by mittonk** [comment]
Not yet!

We're now giving a more helpful error message indicating a problem with the `location` parameter:
```
{
  "errors": [
    {
      "message": "{'error': {'code': 'LOCATION_MISSING', 'description': 'You must specify either a location or a latitude and longitude to search.'}}",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ]
    }
  ],
  "data": {
    "search": null
  }
}
```

But, using a query variable for `location` still fails.

**Comment by mittonk** [comment]
Also affects `latitude` and `longitude` parameters, which is a good lead.

**Comment by aleksdao** [comment]
After looking into this a bit more, seems query variables for `term` are broken. Results aren't filtering by the `term` query variable. See the queries below. 

The first two use query variables and result in the same dataset. The third hardcodes a query parameter for `term`

[search term w/ query variable: dolphins](https://www.yelp.com/developers/graphiql?operationName=SearchForBusinesses&query=query%20SearchForBusinesses(%0A%20%20%20%20%20%20%24category%3A%20String%2C%0A%20%20%20%20%20%20%24radius%3A%20Float)%20%7B%0A%20%20search(term%3A%20%24category%2C%0A%20%20%20%20%20%20%20%20%20radius%3A%20%24radius%2C%0A%20%20%20%20%09%09%20location%3A%20%22U%20District%22%2C%0A%20%20%20%20%20%20%20%20%20)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20location%20%7B%0A%20%20%20%20%20%20%20%20formatted_address%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22category%22%3A%20%22dolphins%22%2C%0A%20%20%22radius%22%3A%203000%2C%0A%20%20%22generalLocation%22%3A%20%22U%20District%22%0A%7D)

[search term w/ query variable: coffee](https://www.yelp.com/developers/graphiql?operationName=SearchForBusinesses&query=query%20SearchForBusinesses(%0A%20%20%20%20%20%20%24category%3A%20String%2C%0A%20%20%20%20%20%20%24radius%3A%20Float)%20%7B%0A%20%20search(term%3A%20%24category%2C%0A%20%20%20%20%20%20%20%20%20radius%3A%20%24radius%2C%0A%20%20%20%20%09%09%20location%3A%20%22U%20District%22%2C%0A%20%20%20%20%20%20%20%20%20)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20location%20%7B%0A%20%20%20%20%20%20%20%20formatted_address%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22category%22%3A%20%22coffee%22%2C%0A%20%20%22radius%22%3A%203000%2C%0A%20%20%22generalLocation%22%3A%20%22U%20District%22%0A%7D)

[search term w/o query variable: coffee](https://www.yelp.com/developers/graphiql?operationName=SearchForBusinesses&query=query%20SearchForBusinesses(%0A%20%20%20%20%20%20%24radius%3A%20Float)%20%7B%0A%20%20search(term%3A%20%22coffee%22%2C%0A%20%20%20%20%20%20%20%20%20radius%3A%20%24radius%2C%0A%20%20%20%20%09%09%20location%3A%20%22U%20District%22%2C%0A%20%20%20%20%20%20%20%20%20)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20location%20%7B%0A%20%20%20%20%20%20%20%20formatted_address%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22category%22%3A%20%22coffee%22%2C%0A%20%20%22radius%22%3A%203000%2C%0A%20%20%22generalLocation%22%3A%20%22U%20District%22%0A%7D)

**Comment by mittonk** [comment]
@aleksdao : Nice catch, agreed.  Does look like all query variables are broken.

**Comment by dan98765** [comment]
I'm circling back on some older issues that I believe have been fixed in the past several months to close them out. 

Setting term to 'coffee' returns only coffee restaurants, 'dolphin' returns some random apartment complex with the word 'Dolphin' in it, etc. Closing out this issue.
