### ISSUE TITLE
business not found

### ISSUE THREAD

**Issue by bizmate** [Yelp/yelp-fusion#238]
Local business 
https://www.yelp.co.uk/biz/oral-design-dental-care-implant-and-aesthetic-clinic-peebles-2

Not found 

Call : 
`https://api.yelp.com/v3/businesses/search?term=Oral+Design+Dental&location=Peebles&limit=20`
I tried other variations

Response: 
`{"businesses":[],"total":0,"region":{"center":{"latitude":38.947124514618,"longitude":-83.409404754639}}}`

This is not an online only business and it has reviews so it should be returned.

**Comment by mittonk** [comment]
@bizmate : Looks like that is the same business as https://www.yelp.co.uk/biz/oral-design-dental-care-peebles , and it has no active reviews.

It does have "5 reviews that are not currently recommended" as linked at the bottom of the page --- those aren't counted for business star rating (or API access).

So, this falls under:
https://www.yelp.com/developers/documentation/v3/business
> Note: at this time, the API does not return businesses without any reviews.

**Comment by bizmate** [comment]
Hi @mittonk 

this is strange. I would not have opened an issue here if I had thought that no reviews was there. Also the owner thought he had a review as per his words

---
I only have one review on my yelp account
---
I hope there is no problem with his business or on Yelp. In the meantime the only thing I could do is to ask them to contact you if he thinks there is any problem with his lost review. Thank you in the meantime

**Comment by mittonk** [comment]
@bizmate : I suspect one of the reviews was showing when you and the business owner first looked, but has since been tagged as "not recommended" by our automated system.

There's a video in the "5 reviews that are not currently recommended" link that describes the system; I have a hunch the review the owner is remembering is listed in that category.

**Comment by bizmate** [comment]
@mittonk thank you for the explaination
