### ISSUE TITLE
graphQL doesn't allow search by price

### ISSUE THREAD

**Issue by jiop77a** [Yelp/yelp-fusion#240]
I'm having trouble adding a price argument to the search in GraphQL.  All of the other arguments listed in the [docs](https://www.yelp.com/developers/graphql/query/search) work as expected, though entering a price value exactly as indicated returns the following error: 
```javascript
{
  "data": null,
  "errors": [
    "Expected list like type for <class 'str'>: 1, 2, 3"
  ]
}
```
Here is the query I'm using on graphiql:
```javascript
{
  search(term: "Restaurants",
    latitude: 37.791145,
    longitude: -122.394024,
    radius: 1000,
    open_now: "true",
    limit: 50,
    price: "1, 2, 3") {
    total
    business {
      name
      price
      }
    }
  }
```
Thanks for your help!

**Comment by tomelm** [comment]
That's peculiar. Will take a look, thanks for reporting!

**Comment by dlgallagher** [comment]
This was a bug; fixed just now.
Can be [checked on graphiql](https://www.yelp.com/developers/graphiql?query=%7B%0A%20%20search(location%3A%20%22san%20francisco%22%2C%20price%3A%20%221%2C%202%2C%203%22)%20%7B%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20price%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).

Which uses input that used to fail before:
```
{
  search(location: "san francisco", price: "1, 2, 3") {
    business {
      name
      price
    }
  }
}
```
