### ISSUE TITLE
List of supported categories?

### ISSUE THREAD

**Issue by nickfl** [Yelp/yelp-fusion#241]
The **Search API** doc for **categories** parameter reads: "_See the list of_ _supported_ _categories_."
So, where do I see this **list**?

**Comment by tomelm** [comment]
They're in the additional resources page, the link is here: https://www.yelp.com/developers/documentation/v3/all_category_list

**Comment by nickfl** [comment]
Thanks.


Nick Floussov
nfloussov@live.com
(647)268-0855
________________________________

**Comment by mittonk** [comment]
We should make this a hyperlink, like we do for "list of supported locales".

**Comment by dlgallagher** [comment]
Added link to categories list page to:
https://www.yelp.com/developers/documentation/v3/business_search
https://www.yelp.com/developers/graphql/query/search
