### ISSUE TITLE
How does location based search works?

### ISSUE THREAD

**Issue by nickfl** [Yelp/yelp-fusion#242]
OK,
location structure has several fields:
country,
state,
city,
address1/2/3
zip_code
Consider user inputs all of them (BTW, it would be good to have a sample, because I spent lots of time trying to figure out url format): location=@(country=fr, state=ca, city=san, zip_code=94103).
What should I expect?
I mean, there is no California (CA) state in France (fr), say nothing about zipcode (95103)!?

**Comment by tomelm** [comment]
@nickfl I'm not sure I understand, the search endpoint only takes in a generic "location" parameter. We don't need a user to enumerate country, state, city, address 1/2/3, etc.

https://www.yelp.com/developers/documentation/v3/business_search

**Comment by nickfl** [comment]
@tomelm 
Here is what confuses me: "Specifies the **combination** of "address, neighborhood, city, state or zip, optional country".
Not just one of them but **COMBINATION**!?
How do I create this combination to pass into url?

**Comment by tomelm** [comment]
It's an OR combination so they're not all required. You can provide just a city and state (sometimes even just a city if it's big enough).

**Comment by nickfl** [comment]
@tomelm 
Could you provide sample?

**Comment by tomelm** [comment]
Sure, try something like https://api.yelp.com/v3/businesses/search?location=san francisco&term=burrito

**Comment by nickfl** [comment]
@tomelm 
Not good, I asked about **combination** of **LOCATION** items: 'country' AND/OR 'state' AND/OR 'address' AND/OR...
In your sample you have ONLY 'address', but doc reads about '_combination of .._'
How 'location' value will look like for **combination**?

**Comment by mittonk** [comment]
@nickfl : Is
`https://api.yelp.com/v3/businesses/search?location=706+Mission+St,+San+Francisco,+CA,+US&term=burrito` more like what you mean?

If not --- what country, state, and address are you searching for?  It might be helpful to have a concrete example to work with.

**Comment by nickfl** [comment]
@mittonk 
Thanks, that's exactly what I wanted to see; hope you'll add it to the docs for other guys.
Now a small Q: Do I have to use '**+**' or '**%20**' will do the job as well?

**Comment by mittonk** [comment]
On one hand: `https://api.yelp.com/v3/businesses/search?location=706%20Mission%20St,%20San%20Francisco,%20CA,%20US&term=burrito` also works for me.

On the other hand: https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20 suggests "+" is more correct, and that's what my favorite few URL-encoding libraries use for GET query strings.

So, `%20` works, but I'd prefer `+` for style.

We'll have a look at adding some more examples.

**Comment by Porubay** [comment]
This is a broad question and it depends on the application or social article that is implied. My favorite is of course a [Waze](https://www.cleveroad.com/blog/location-based-services-applications-like-waze-development-secrets), it uses [GPS](https://en.wikipedia.org/wiki/Global_Positioning_System), but there are those that use the [Bluetooth](https://en.wikipedia.org/wiki/Bluetooth_low_energy_beacon) definition, [Wi-Fi](https://en.wikipedia.org/wiki/Wi-Fi_positioning_system) definition and definition by mobile operators through towers.

**Comment by ma-za-kpe** [comment]
The Yelp API gives you access to search for over 50,000,000 businesses in 32 countries. from this link https://github.com/Yelp/yelp-api. 
So does yelp cater for african countries? like Kenya- Nairobi?
