### ISSUE TITLE
Yelp API returns data from other countries 

### ISSUE THREAD

**Issue by francesco1119** [Yelp/yelp-fusion#243]
In the last 2 weeks I found many problems using your API.

**EXAMPLE:**

There is a town in New Zealand called Blackburn (Lon:-39.86666700, Lat:176.28333300).
So I search all cinemas for that town on Postman specifying `Country, City, Latitude and Longitude` this way:

`https://api.yelp.com/v3/businesses/search?categories=movietheaters&cc=nz&location=blackburn&ll=-39.86666700,176.28333300`

Yelp gives me a cinema in GB, from a town with the same name 'Blackburn'

![black](https://cloud.githubusercontent.com/assets/3397477/26770982/39419b98-4a0f-11e7-8488-d81569bf24ca.PNG)

I specified the country: `cc=nz`
I specified the location: `location=blackburn`
I specified latitude and longitude: `ll=-39.86666700,176.28333300`
But the result is wrong!

At the end of the day I counted **26 different countries in my databse**? 

![lost](https://cloud.githubusercontent.com/assets/3397477/26771317/8b014292-4a11-11e7-91d6-5a972ac00eb6.PNG)

Why? Yelp is returning me more data from US, GB, CA than New Zealand.

My research should be restricted to New Zealand as I used `cc=nz`!

**Comment by francesco1119** [comment]
Alternatively, is there a way to search just by category, latitude and longitude?
Like this:

`https://api.yelp.com/v3/businesses/search?categories=movietheaters&cll=-39.86666700,176.28333300`

I don't want to use `text` search because how can I search for Cinema, Bar or Restaurants in countries like Taiwan, Philippines or Japan? Who knows how to say that in all your 32 languages!
`category` is the input I want to use, that's why you made it, to avoid to use `text`search

**Comment by francesco1119** [comment]
Alright, even following your [guide](https://nz.yelp.com/developers/documentation/v2/search_api), if I try to search by term, location, latitude and longitude:

`https://api.yelp.com/v3/businesses/search?term=cinema&location=blackburn&cll=-39.86666,176.28333`

your API keeps returning cinemas in Blackburn, GB

**Comment by nickfl** [comment]
Hi francesco1119,
sorry to bother you with such silly question, but how do I specify 'location'?
I mean, it has 5 fields: Country, State(?), City, Address, Zip(?)
In Postman I can use format like: location=@(country=us, state=ca, city=san, address1=main str, zip_code=19401),
but it does not work in iOS!?

**Comment by tomelm** [comment]
@francesco1119 I think you're getting our two APIs confused. You're making requests to v3 which does not have the parameters cc or cll. Could you take a look at the docs for v3 and use the latitude and longitude parameters and see if that helps? https://www.yelp.com/developers/documentation/v3/business_search

Make sure to not use the location parameter if you're passing in a latitude and longitude.

**Comment by francesco1119** [comment]
@tomelm following your v3 guide it says that `location`, `latitude `and `longitude `are **required** fields

![guide](https://cloud.githubusercontent.com/assets/3397477/26805632/f10336f6-4aa0-11e7-8bd6-f38207fdf8ab.PNG)

**Comment by francesco1119** [comment]
@tomelm , but, alright, **I will follow your advice**, I will pass just `latitude `and `longitude` this way:

`https://api.yelp.com/v3/businesses/search?categories=movietheaters&ll=-39.86666,176.28333`

![ll](https://cloud.githubusercontent.com/assets/3397477/26805815/e80d4e28-4aa1-11e7-97c3-01d73fd77bbe.PNG)

Not working

**Comment by francesco1119** [comment]
@tomelm so I taught I maybe have to specify `cll `instead: 

`https://api.yelp.com/v3/businesses/search?categories=movietheaters&cll=-39.86666,176.28333`

![cll](https://cloud.githubusercontent.com/assets/3397477/26805856/26a511fc-4aa2-11e7-9b11-d85328a502b9.PNG)

Again not working

**Comment by francesco1119** [comment]
@tomelm so let's try to specify the country code with `cc `(this is also an example for @nickfl which asked this question few post above: 

`https://api.yelp.com/v3/businesses/search?categories=movietheaters&cc=nz&ll=-39.86666,176.28333`

![cc](https://cloud.githubusercontent.com/assets/3397477/26805967/b0e73fb6-4aa2-11e7-9a20-7c84967a2662.PNG)

I tried also with `location `and with and with `cll `and `ll`.
I don't want to keep going in this childish way, me posting screenshot and you replying in a cryptic way, telling me to dig deeper and deeper in your v3 documentation. 
Please, @tomelm , just paste here the URL I need to use to search for `categories=movietheaters`, in the town called `blackburn` in New Zealand and not in US or GB or whatever. 
The response code I need to see is:

```
{
  "error": {
    "code": "LOCATION_NOT_FOUND",
    "description": "Could not execute search, try specifying a more exact location."
  }
}
```
This is the response that Yelp API gives when the town is not in your database. "code": "VALIDATION_ERROR" means I'm doing things wrong. 
Just tell me where I'm wrong, please.

**Comment by francesco1119** [comment]
JEEEEEEZ guys, I had to find the solution by myself thanks to [this post](https://github.com/Yelp/yelp-fusion/issues/15)

`https://api.yelp.com/v3/businesses/search?categories=movietheaters&latitude=-36.86666700&longitude=174.76666700&radius=5000`

...so latitude and longitude are now passed as separate values. 
Please write a few examples on your documentation.
Thank you

**Comment by mittonk** [comment]
@francesco1119 : Yes, that's a good way to pass latitude and longitude.

Maybe I can say more about the "Required" text you highlighted in https://cloud.githubusercontent.com/assets/3397477/26805632/f10336f6-4aa0-11e7-8bd6-f38207fdf8ab.PNG  : 
```
location : Required if either latitude or longitude is not provided. 
latitude : Required if location is not provided.
longitude : Required if location is not provided.
```

We're trying to say you can use either `location` like:
https://api.yelp.com/v3/businesses/search?location=Auckland
or `latitude` and `longitude` like:
https://api.yelp.com/v3/businesses/search?latitude=-36.9&longitude=174.8

but you have to use one of those approaches and can't search the entire world --- every search must include some kind of "where to search" parameter.  Is that any clearer?

**Comment by francesco1119** [comment]
Now, yes, please add a few examples to your documentation

**Comment by francesco1119** [comment]
Sorry, something is still not clear.
I try to search for a town called 'atawhai', (-41.23333300,173.31666700) 
So I search this way: 

`https://api.yelp.com/v3/businesses/search?categories=movietheaters&latitude=-41.23333300&longitude=173.31666700&radius=25000`

```
categories=movietheaters
latitude=-41.23333300
longitude=173.31666700
radius=25000 (quite a big radius)
```
The result is:

```
{
  "businesses": [],
  "total": 0,
  "region": {
    "center": {
      "latitude": -41.233333,
      "longitude": 173.316667
    }
  }
}
```
But there is a cinema just at 5Km distance:

![just](https://cloud.githubusercontent.com/assets/3397477/26817434/b0f90988-4aea-11e7-958a-1c654c205051.PNG)

And yes is on Yelp!

![yes](https://cloud.githubusercontent.com/assets/3397477/26817486/ec801f00-4aea-11e7-995b-727f24657aaa.PNG)

So why I cannot see it?

**Comment by tomelm** [comment]
@francesco1119 none of those businesses have reviews so they're not returned on the API. It's stated at the top of the docs "Note: at this time, the API does not return businesses without any reviews."

**Comment by francesco1119** [comment]
I used "cc", "cll", and "ll" because they were online on the v2 Documentation. 
You should put such documentation offline as is deprecated but is the fist thing that Google shows you when you search for "Yelp Documentation'.

Will Yelp return business also without reviews in the future?

**Comment by tomelm** [comment]
Nope.

**Comment by francesco1119** [comment]
Good to know. Thank you for your patience.
