### ISSUE TITLE
API and HTML Questions

### ISSUE THREAD

**Issue by tactacr** [Yelp/yelp-fusion#244]
Hello,

I am a complete newbie to coding; however, I have an idea that has garnered support across my network. Since I am fresh out of college and broke, I am attempting to code a mobile site in HTML, which I then plan to convert into an iOS and Android app. Excuse my ignorance, but can I call the API using HTML? If so, how do I "get an access token using [my] client id and secret" and "authenticate API calls with the access token"? I read the instructions on your website; however, they were too complex for me. Furthermore, would you please access my app page (PickIt) and privately offer me any other helpful advice?

Best,
tactacr

**Comment by mittonk** [comment]
@tactacr ,

HTML is great for making human-readable web pages, but it's really not very capable for calling APIs.  Most big web sites have a "back-end" component written in another language like Ruby, Java, etc (Yelp uses mostly Python).

https://www.codecademy.com/skills/make-an-interactive-website might make for some good reading, and would be enough to call some very simple APIs using Javascript --- but that won't be enough to use the Yelp Fusion API.  For that, you will need some back-end programming experience so you can follow
* https://www.yelp.com/developers/documentation/v3/get_started

Good luck!

**Comment by tactacr** [comment]
Thank you, Ken!
