### ISSUE TITLE
Why won't it return the reviews along with a doctor's profile ?

### ISSUE THREAD

**Issue by ubaskota** [Yelp/yelp-fusion#245]
Hi all, first of all I am new to APIs.
I am trying to collect the ratings and reviews of few physicians in Yelp for research purpose. I have the access key but when I use this link (https://api.yelp.com/v3/businesses/dale-l-pearlman-md-menlo-park?start=40/reviews&Authorization=Bearer [with access key])in Postman to GET response . I only get a response that contains few of the physician's information  even though this physician has more than 50 reviews. But, I want the reviews and ratings along with physician's information. Am I missing anything here, what is the solution ?
Thanks

**Comment by tomelm** [comment]
Hey @ubaskota, we don't return all reviews for a business through the API only the top 3 reviews in the form of excerpts: https://www.yelp.com/developers/documentation/v3/business_reviews

Is there any other data you were looking for?

**Comment by ubaskota** [comment]
Well, I was trying to collect ratings and reviews of physicians. But the problem is I don't even get a single review with the process I am trying. Again, I am new to Apis so my approach might sound stupid too.
This is what I have done so far, 
-   I have the access token.
- Now, I use this request " https://api.yelp.com/v3/businesses/search?term=Physicians&location=California&Authorization=Bearer (this is where I put my access key)
- It works fine till here, I get the the profiles of roughly 30-50 physicians and their average ratings.(may be more then that).
- But I need the physician's individual profile with the ratings and comments they have received.
- So, I use the id(which is the url) of individual physician and run it the same way. The request looks like this "https://api.yelp.com/v3/businesses/bruce-chung-md-new-york?osq=physicians/reviews&Authorization=Bearer (access key)"
- Now I get this Physician(Bruce Chung)'s profile only with his average rating and some information about him. But I also want all the ratings and comments about him in yelp. I have tried all methods that are available online.
Do you have any suggestions to solve this problem ? Or, What is your idea ? I would love to get any suggestions from you.
Thanks,

**Comment by tomelm** [comment]
@ubaskota could you remove the ?osq=physicians from your second request? It's causing you to go to the wrong endpoint.

**Comment by ubaskota** [comment]
Now, it gives me this error.
{
  "error": {
    "code": "NOT_FOUND",
    "description": "Resource could not be found"
  }
}

**Comment by tomelm** [comment]
You're making a request to https://api.yelp.com/v3/businesses/bruce-chung-md-new-york/reviews, correct?

**Comment by ubaskota** [comment]
correct. But there is sth more after that it looks like this https://api.yelp.com/v3/businesses/bruce-chung-md-new-york/reviews&Authorization=Bearer (here is my access token).

**Comment by tomelm** [comment]
@ubaskota the & is not how you want to send parameters. The first url parameter on a query needs to be ?, every subsequent url parameter should be &

Also, you shouldn't be sending the authorization in the URL, it needs to go in the header (check out the guide: https://www.yelp.com/developers/documentation/v3/authentication)

**Comment by ubaskota** [comment]
I have been struggling and googling here and there since one week. So, please allow me to harass you more here. I still don't get what's going on.  
1) Why do I have to specify parameter1 and parameter2 if I know the name of business/person I am looking for ? What do I put in the place of parameter if the name of physician I am looking is already in the url ? 
2) In my  get request (in postman) I have included access token in both url and Header. If I take the access token out from the request url it gives me an error "Bad gateway".
3) Can you please show me a sample get request with the place where I have to put the access token in it ?

**Comment by ubaskota** [comment]
@tomelm I figured it out. Thank you very much.
