### ISSUE TITLE
Review query error only on graph api

### ISSUE THREAD

**Issue by fmello-cit** [Yelp/yelp-fusion#246]
I am trying to get reviews using this query:

`{
  b1: reviews(business: "el-burrito-express-2-san-francisco") {
    total
    review {
      rating
      text
      user {
        name
        image_url
      }
    }
  }
  b2: reviews(business: "veridiana-são-paulo-2") {
    total
    review {
      rating
      text
      user {
        name
        image_url
      }
    }
  }
}`
And I am getting a lot of html code with errors. However, if I use this query:
`{
  b1: reviews(business: "el-burrito-express-2-san-francisco") {
    total
    review {
      rating
      text
      user {
        name
        image_url
      }
    }
  }
  b2: reviews(business: "kung-food-san-francisco") {
    total
    review {
      rating
      text
      user {
        name
        image_url
      }
    }
  }
}`
It works. Note that I only changed the business id of the second query. I think this may be related to special chars on "são-paulo". I also tried to encode as url, no success. Initially I thought it has something to do with the country, but, using another brazilian city without accent, like "pizza-hut-campinas", it also works.
What can I do? Or this is a known issue?
Thanks.

**Comment by mittonk** [comment]
@fmello-cit : Definitely a bug, we'll look into it!

**Comment by mittonk** [comment]
Looks like this affects only the interactive GraphQL console at:
* https://www.yelp.com/developers/graphiql

As a workaround, you can `POST` directly to the underlying
* https://api.yelp.com/v3/graphql
using `curl` or a similar tool --- see https://www.yelp.com/developers/graphql/guides/intro for details.

**Comment by fmello-cit** [comment]
Thanks for quick reply.
About your workaround, I am not sure.
Look:

First attempt, with são-paulo
curl -X POST -H "Authorization: Bearer MY_TOKEN" https://api.yelp.com/v3/graphql --data '
> {
> b1: reviews(business: "el-burrito-express-2-san-francisco"){ total review{ rating text user{ name image_url } } }
> b2: reviews(business: "el-burrito-express-2-san-francisco"){ total review{ rating text user{ name image_url } } }
> b3: reviews(business: "veridiana-são-paulo-2"){ total review{ rating text user{ name image_url } } }
> }'
{"data": null, "errors": ["Constructing an ObjectID out of a non-integer doesn't make sense. The type is <class 'NoneType'>"]}

Second attempt, without são-paulo:
curl -X POST -H "Authorization: Bearer MY_TOKEN" https://api.yelp.com/v3/graphql --data '
{
b1: reviews(business: "el-burrito-express-2-san-francisco"){ total review{ rating text user{ name image_url } } }
b2: reviews(business: "el-burrito-express-2-san-francisco"){ total review{ rating text user{ name image_url } } }
}'                                                                                                  
{"data": {"b1": {"total": 579, "review": [{"rating": 5, "text": "This place is amazing!! Literally, the only bad thing is it is too close to my house which is dangerous. \n\nIt is order at the window, then sit down kind of...", "user": {"name": "Jennifer A.", "image_url": "https://s3-media3.fl.yelpcdn.com/photo/ahljSWf2DZntQJNJak1nuA/o.jpg"}}, {"rating": 3, "text": "So this was my first time here after the recent renovation to this location. I love the new decor and there food. \n\nWhere my problem starts is when I get to...", "user": {"name": "Elizabeth G.", "image_url": "https://s3-media2.fl.yelpcdn.com/photo/izgVj4V6XCl4p6504CIIPg/o.jpg"}}, {"rating": 4, "text": "I can feel it, I'm gonna be a regular here. Not only because it's one of the few meals in the area well below $10. I did enjoy their Spicy Chicken Burrito,...", "user": {"name": "Katja S.", "image_url": "https://s3-media3.fl.yelpcdn.com/photo/Th048hLXwTv9sWkoGFjeaQ/o.jpg"}}]}, "b2": {"total": 579, "review": [{"rating": 5, "text": "This place is amazing!! Literally, the only bad thing is it is too close to my house which is dangerous. \n\nIt is order at the window, then sit down kind of...", "user": {"name": "Jennifer A.", "image_url": "https://s3-media3.fl.yelpcdn.com/photo/ahljSWf2DZntQJNJak1nuA/o.jpg"}}, {"rating": 3, "text": "So this was my first time here after the recent renovation to this location. I love the new decor and there food. \n\nWhere my problem starts is when I get to...", "user": {"name": "Elizabeth G.", "image_url": "https://s3-media2.fl.yelpcdn.com/photo/izgVj4V6XCl4p6504CIIPg/o.jpg"}}, {"rating": 4, "text": "I can feel it, I'm gonna be a regular here. Not only because it's one of the few meals in the area well below $10. I did enjoy their Spicy Chicken Burrito,...", "user": {"name": "Katja S.", "image_url": "https://s3-media3.fl.yelpcdn.com/photo/Th048hLXwTv9sWkoGFjeaQ/o.jpg"}}]}}}

**Comment by mittonk** [comment]
@fmello-cit : Found a workaround for the interactive GraphiQL console.  

Looks like GraphiQL expects `\u...`. escaped Unicode:
* `ã` => `\u00E3` (from http://www.fileformat.info/info/unicode/char/e3/index.htm , format "C/C++/Java source code")

```
{
  b2: reviews(business: "veridiana-s\u00E3o-paulo-2") {
    total
    review {
      rating
      text
      user {
        name
        image_url
      }
    }
  }
}
```
```
{
  "data": {
    "b2": {
      "total": 32,
      "review": [
        {
          "rating": 5,
          "text": "Oh holy sweet goodness...
```
That should help with your original question.

I'll keep digging to see if we can simplify this, and what's going on with that `curl` error.

**Comment by mittonk** [comment]
The "Constructing an ObjectID..." error is coming from trying to build an `image_url` link for reviewer "Andrew S", who doesn't have a photo.  Not related to the Unicode issues at all --- filing a separate bug #261 for that.

**Comment by mittonk** [comment]
@fmello-cit : Fixed!
```
{
  b2: reviews(business: "veridiana-são-paulo-2") {
    total
    review {
      rating
      text
      user {
        name
        image_url
      }
    }
  }
}
```

```
{
  "data": {
    "b2": {
      "total": 32,
      "review": [...
```

You don't need to manually encode `ã` as `\u00E3` any more.

Thanks for reporting this!

**Comment by fmello-cit** [comment]
Thanks!
