### ISSUE TITLE
GraphQL api returns 500 for a valid query

### ISSUE THREAD

**Issue by aadithyabk** [Yelp/yelp-fusion#248]
I am trying to use Yelp's graphql api in a react native app but I get a 500 even though the query and access token are valid. The same query works from the command line using curl and when I run the same curl command using fetch in javascript, I get back a 500. 

This is the graphql query that I am trying to run
`query Search($term: String!, $location: String!)  {
      search (term: $term, location: $location) {
        total
        business {
          name
          url
          rating
        }
    }
  }`

And this is the curl command that works
`curl -X POST -H "Authorization: Bearer xxxxxx" https://api.yelp.com/v3/graphql --data '
{ 
	search (term: "los angeles", location: "los angeles") 
       { 
              total
              business
              { 
                      name
                      url 
                      rating 
              } 
        } 
}'`

<img width="339" alt="screen shot 2017-06-14 at 9 29 54 am" src="https://user-images.githubusercontent.com/6628680/27143696-1329ac76-50e4-11e7-859d-c18df76a5075.png">

Can I get some help in addressing this?

**Comment by tomelm** [comment]
Hey @aadithyabk, if you're using fetch/Javascript you're likely being blocked by the fact that we don't support CORS. There is no easy workaround at the moment outside of implementing some simple backend.

Also, for future reference, please don't post your entire access token. We're going to disable your client, could you delete and recreate it?

**Comment by aadithyabk** [comment]
My bad. I hid the token but I think I pasted it again but forgot to remove it. I will recreate it. Thanks

**Comment by mittonk** [comment]
#44  is one good CORS request, marking this as a duplicate as the same "create a simple backend" advice applies.
