### ISSUE TITLE
Businesses hours time zones

### ISSUE THREAD

**Issue by sp00m** [Yelp/yelp-fusion#25]
`hours[x].open[x]` object in `/businesses/search` provides hours, but based on which time zone? The one of the business' location?

Could it be possible to have the time zone in the response as well, e.g. next to `hours[x].hours_type`?

Moreover, `hours[x].is_open_now` seems to be bugged, as it's monday 10:46 PM (here in France), and the flag is `false` while the open hours imply the opposit (business id = `fat-cat-toulouse`):

```
{
  "hours_type": "REGULAR",
  "open": [{
    "day": 0, // means Monday from your doc
    "is_overnight": true,
    "start": "1900",
    "end": "0200"
  }, {
    ...
  }],
  "is_open_now": false // should be true, right?
}
```

**Comment by tomelm** [comment]
The timezone should be based on that of the businesses location. I'll see about adding a field to make it explicit.

We ran into the open now bug and are looking into a fix. Thanks for the heads up!

**Comment by tomelm** [comment]
@sp00m we've fixed the is_open_now issue, could you confirm if you're seeing it resolved?

**Comment by sp00m** [comment]
@tomelm Yes, good job! Do you have any news about making the time zone available in the response?

**Comment by guangyang** [comment]
@sp00m, could you please help me understand how you are planning to use the timezone information? Most of them time, users look at the business hours information because they want to go to the business. And since you need to physically be there if you want to go, only local time matters. This is why in Yelp itself, we don't really show timezone.

**Comment by mars271** [comment]
Another vote for timezone. This would allow us to generate messages like "Closing in 30 minutes" etc. which depend on timezone.

**Comment by sp00m** [comment]
@guangyang Just like @mars271, I would like to display "Closing at XX:XX", which depends on the business time zone and the user time zone. And more generally speaking, a time without its time zone is as usable as an API without its documentation :)

**Comment by guangyang** [comment]
Got it. That makes sense. Thanks for the explanation. We'll look into this.

**Comment by MRSharff** [comment]
+1 for timezone. Any time frame for this?
