### ISSUE TITLE
Please add a root ancestor field to autocomplete category results

### ISSUE THREAD

**Issue by russellharvey** [Yelp/yelp-fusion#250]
It would very useful for filtering autocomplete results if the category objects returned also included a field containing the alias of their ultimate ancestor.  E.g., category "cardioclasses" would have a root ancestor of "active."

That way, if I'm building an app based around food, I could quickly ignore any category result whose ancestor was not "food" or "restaurants," rather than having to maintain a complete internal copy of the category hierarchy in order to figure out if I'm interested in displaying a particular category result.  Also saves the trouble of having to periodically update said internal hierarchy.

**Comment by mittonk** [comment]
Adding the root-category-for-this-category would indeed help your use case --- but what about a user who wants to exclude results under a second-level category like `fitness`?  I wouldn't want to return the full-depth stack of categories in each response.

As a workaround, the Categories documentation:
* https://www.yelp.com/developers/documentation/v3/all_category_list

links to a JSON version of the Category tree:
* https://www.yelp.com/developers/documentation/v3/all_category_list/categories.json
