### ISSUE TITLE
Is there any way to get all the reviews of a business ?

### ISSUE THREAD

**Issue by ubaskota** [Yelp/yelp-fusion#252]
Hi, we are currently doing a research that requires the information of Urologists from 20 states of USA. But, Yelp only provides 3 reviews of each business and the length of each review is limited to 160 characters. Is there any way to get all the reviews of a business? 
Thanks,

**Comment by tomelm** [comment]
Hey @ubaskota, there's no way to do that as we do not make this information readily available through the API and have no plans to do so.
