### ISSUE TITLE
v3 Yelp Fusion API returns way less results than web search.

### ISSUE THREAD

**Issue by chouckz** [Yelp/yelp-fusion#256]
https://www.yelp.com/search?find_desc=Interior%20designers&find_loc=Kirkland,+Quebec
returns total 45 results
however 
https://api.yelp.com/v3/businesses/search?limit=50&radius=40000&&location=Kirkland,+Quebec&term=Interior%20designers
total only 21
I've tried to compare different locations in US and Canada. 
I've tried to use ZIP, lat lon etc with the same strange results difference. 
At some places API gives few times less than web.

**Comment by mittonk** [comment]
@chouckz : Many of the matches in
* https://www.yelp.com/search?find_desc=Interior%20designers&find_loc=Kirkland,+Quebec

( for example https://www.yelp.com/biz/bois-franc-steve-lavallee-kirkland-2 and https://www.yelp.com/biz/cuisines-west-island-kirkland)
don't have any reviews, so they're visible on www.yelp.com but not via the Fusion API.

* https://www.yelp.com/developers/documentation/v3/business_search
> Note: at this time, the API does not return businesses without any reviews.
