### ISSUE TITLE
Typo on documentation website

### ISSUE THREAD

**Issue by lawrnce** [Yelp/yelp-fusion#258]
On the [/businesses/search](https://www.yelp.com/developers/documentation/v3/business_search) api page, there is a typo for the price parameter description.    

> For example, "1, 2, 3" will filter the results to show the ones that are $, $$, or $$$.

Notice that in the description there are spaces between the numbers "1,[space]2,[space]3"; however, this is incorrect as having spaces between the commas will result in a failed response. 

Namely: 
`{
    "error": {
        "code": "VALIDATION_ERROR",
        "description": "Invalid price filter provided"
    }
}`

Having the description as 

> For example, "1,2,3" will filter the results to show the ones that are $, $$, or $$$.

rids any source of confusion.

**Comment by mittonk** [comment]
Good catch!  We'll get that fixed.

**Comment by dlgallagher** [comment]
@lawrnce thanks for the good bug report. 👍

**Comment by dlgallagher** [comment]
Updated the service code to treat "1, 2, 3" the same as "1,2,3".
