### ISSUE TITLE
How To: Obtain Query Results and Export to Excel

### ISSUE THREAD

**Issue by New2YelpAPI** [Yelp/yelp-fusion#259]
Hi, I am brand new to using Yelp API and APIs in general so I apologize if this is the incorrect spot for this question...

I am trying to make a list of businesses in certain cities and export these results to excel. Is this possible? 

Thank you.

**Comment by mittonk** [comment]
@New2YelpAPI : 
1. The Yelp API is meant for adding Yelp data to your own programming projects --- you'll need to write code (Python, Ruby, or similar) to run searches, format the data the way you want (maybe as a CSV-file), and save it to disk so you can import it into Excel.  There's not a simple Excel export button.

You can use the example code as a starting point:
* https://github.com/Yelp/yelp-fusion#code-samples

2. Depending on what you're doing, you might also want to look at the Yelp Academic Dataset:
* https://www.yelp.com/dataset

That's got easy-to-download JSON data files of a snapshot of Yelp data; it's not live-updating, and only has a few cities, but if you're trying to do a prototype or demo it might work for you.  For Excel import, you can use the JSON-to-CSV example at
* https://github.com/Yelp/dataset-examples

Does one of those approaches sound promising?
