### ISSUE TITLE
business search returning `VALIDATION_ERROR`

### ISSUE THREAD

**Issue by rabidaudio** [Yelp/yelp-fusion#260]
Some api calls are returning what looks like a server error, similar to #100 

    https://api.yelp.com/v3/businesses/search?latitude=37.9751925742223&longitude=-122.297700355799&limit=20&categories=autorepair&radius=20000&offset=0

```
{"error"=>{"code"=>"VALIDATION_ERROR", "description"=>"[{'accuracy': 9.5, 'business_id': 24572572, 'is_shareable': True, 'latitude': 37.8307191849109, 'longitude': -122.268334094443}] is not of type 'object'", "field"=>4}}
```

Also seen it on `34.2385136398404, -118.442655851201` and `45.0323077818011,  -93.0965719171044`. First one was around 10:30 am EDT today, if that helps.

**Comment by loomtronic** [comment]
I have this one as well...

https://api.yelp.com/v3/businesses/search?limit=20&longitude=33.802727&latitude=-118.133568&is_closed=0

Any ideas on a fix?  I'd like to start using the new API but this blocks me from continuing down this route.

**Comment by mittonk** [comment]
Fixed 2017-07-24.  Query now works:
```
{
	"businesses": [
		{
			"id": "steves-auto-care-el-cerrito",
			"name": "Steve's Auto Care",
...
```

@rabidaudio : Thanks for the report!
