### ISSUE TITLE
Full review text

### ISSUE THREAD

**Issue by martinpruss** [Yelp/yelp-fusion#262]
Hi,

I don't see any way to retrieve the full review text - just the excerpt.  Is this possible?

Thanks,

**Martin**

**Comment by mittonk** [comment]
@martinpruss : Sorry, only excerpts are available via the Fusion API.

**Comment by martinpruss** [comment]
why is that - what use is not being able to obtain the full text?

**Comment by martinpruss** [comment]
are the full review comments available through a different API?

**Comment by quytennis** [comment]
Please check out our Yelp Knowledge page for access to full text reviews:
https://www.yelp.com/knowledge
