### ISSUE TITLE
business/search API - not deterministc total value depends on limit param

### ISSUE THREAD

**Issue by TomaszKolek** [Yelp/yelp-fusion#264]
When I send a search request without limit param I have a response with 55 as `total` param value,  when I add a limit `limit=50` I receive a response with more than 1700 as `total` param value.

Is it a feature or a bug? :-)

**Comment by tomelm** [comment]
Hmm, sounds like some post-processing gone wrong. Will ticket for someone to take a look

**Comment by TomaszKolek** [comment]
Request details to investigate:
`{'latitude': '37.781555', 'term': 'Walmart', 'longitude': '-122.393990', 'limit': 50}` result: `total = 1821`

`{'longitude': '-122.393990', 'latitude': '37.781555', 'term': 'Walmart'}` result: `total=66`

**Comment by mittonk** [comment]
Also noticed in #307 , more good repro steps over there.
