### ISSUE TITLE
Internal Error for GET request on business match API but not on business API

### ISSUE THREAD

**Issue by BugsForDays** [Yelp/yelp-fusion#265]
Hi,

I am receiving an internal error every time I send a GET request to the business match API. However, when I send a request to the business API, I get an expected response. Here is the response body when I send a GET request to the business match API:
`{
"error": {
"code": "INTERNAL_ERROR",
"description": "Something went wrong internally, please try again later"
}
}`
 Can anyone find out why this is?

Thank You!

**Comment by tomelm** [comment]
@BugsForDays what's the request you're making to the bizmatch API?

**Comment by BugsForDays** [comment]
Hey @tomelm 

I'll attach my request in a screenshot.
![inkedinternal error](https://user-images.githubusercontent.com/24444266/28145039-12b4e5a2-6724-11e7-92e3-0ecb414a905c.jpg)

**Comment by tomelm** [comment]
@BugsForDays our documentation is wrong, city, state, and country are all required. Could you add those in and see if it works?

**Comment by BugsForDays** [comment]
Hi @tomelm 

Thank you for your reply. After adding the extra parameters, I am finally getting a list called businesses. However, this list is empty. Do I need to be more specific with the name of the business? I have attached a screenshot.
![image](https://user-images.githubusercontent.com/24444266/28180085-e85f5b30-67b8-11e7-84c7-1ad816696d07.png)

**Comment by tomelm** [comment]
@BugsForDays could you try country="usa"?

**Comment by BugsForDays** [comment]
@tomelm 

I get a VALIDATION_ERROR. "usa" is greater than the acceptable length: 2

![image](https://user-images.githubusercontent.com/24444266/28188512-44ee33da-67d7-11e7-8aff-f8bcf95f3f79.png)

**Comment by tomelm** [comment]
@BugsForDays alright, filed a ticket internally. Will have someone take a look

**Comment by BugsForDays** [comment]
@tomelm 

Alright. Thank you very much for your help.

**Comment by mittonk** [comment]
@BugsForDays : I've found a few issues that are definitely bugs (with workarounds, and eventually fixes), and a few that may just be limitations in our business match infrastructure.

1. Country and State codes should be capitalized --- we want "US", not "us".
2. Having `address1` helps significantly, especially in larger cities --- try "333 O'Farrell St" or "750 Kearny St".  An empty `address1` means the algorithm has to consider some poorly-specified business listings with unknown or non-existent street addresses.
3. A more specific name might help a little, but isn't a major factor here.

We'll get working on some bug fixes around documentation and validation!

* https://api.yelp.com/v3/businesses/matches/lookup?name=hilton&address1=333 O'Farrell St&city=San Francisco&country=US&state=CA
```
{
    "businesses": [
        {
            "id": "hilton-san-francisco-union-square-san-francisco-5",
            "name": "Hilton San Francisco Union Square",
...
```

**Comment by BugsForDays** [comment]
@mittonk 

Ok, thanks for looking at this issue. So for clarification, address1 must be a parameter in order to get a populated response?

**Comment by mittonk** [comment]
Not exactly --- it is optional, but very helpful.  Queries without address1 are allowed, but much less likely to find the business you want.

**Comment by BugsForDays** [comment]
Ok, I see. However, when I don't include an address parameter, I get an empty business list in the response.

**Comment by mittonk** [comment]
That varies by what you're searching for.  Here's a search that doesn't supply `address1` but does find a matching business:

* https://api.yelp.com/v3/businesses/matches/best?name=Los+Compadres+Taco+Truck&city=San+Francisco&state=CA&country=US
```
{
    "businesses": [
        {
            "id": "los-compadres-taco-truck-san-francisco-2",
            "name": "Los Compadres Taco Truck",
            "coordinates": {
                "latitude": 37.7886352539062,
                "longitude": -122.393890380859
            },
            "location": {
                "address1": "",
                "address2": null,
                "address3": "",
                "city": "San Francisco",
                "zip_code": "94105",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "San Francisco, CA 94105"
                ]
            },
            "phone": "",
            "display_phone": ""
        }
    ]
}
```

**Comment by BugsForDays** [comment]
In the future, do you guys plan on implementing a feature that makes including an address optional?

**Comment by BugsForDays** [comment]
I believe your case worked, because the business you used in your example doesn't really have a set location since it is a food truck, so there is not really an address associated with it.

**Comment by mittonk** [comment]
In general terms: We'd love to boost recall, but don't want to reduce precision.  

We don't have any specific timeline for increasing the fuzziness on address1.

Depending on how much information you know about your target business, you may also want to try the Search endpoint

And yes --- fair point about my no-address1 example.

**Comment by mittonk** [comment]
(We're no longer HTTP 500ing, and now into which queries provide useful matches and which ones don't --- calling this ticket closed.)

**Comment by mittonk** [comment]
(Nevermind, got ahead of myself.)

**Comment by mittonk** [comment]
@BugsForDays : We're now giving more helpful error messages when requests don't include `city`, `state`, or `country`.  That should help others from running into similar issues.

(Leaving `address1` as optional.)

Calling this done.

**Comment by BugsForDays** [comment]
@mittonk 

Ok, thanks.

**Comment by tlc** [comment]
IMHO, the address1 detail should have a warning in the documentation.  That's not really what most people will think "optional" means.
