### ISSUE TITLE
Reviews API returns empty response for the business with reviews

### ISSUE THREAD

**Issue by cackle** [Yelp/yelp-fusion#267]
Hi,

I have an issue with Yelp reviews API https://www.yelp.com/developers/documentation/v3/business_reviews

I tried to get 3 reviews for the business https://www.yelp.nl/biz/desmet-studios-amsterdam-amsterdam via call of the GET method Yelp reviews API:

**https://api.yelp.com/v3/businesses/desmet-studios-amsterdam-amsterdam/reviews**

With authorization header:

**Authorization: Bearer REMOVED**

But instead of 3 reviews, I see empty reviews section in the response:

**{"reviews": [], "total": 4}**

What can be the problem and how to fix it?

PS: For other businesses with reviews, it should work without any problems.

Thanks!

**Comment by tomelm** [comment]
Hey @cackle! In the future, please don't post your access token as that gives everyone access to the API using your credentials. I'm going to revoke your token, please create a new one.

As far as your issue goes, we've got it tracked internally but at the moment there's no solution. The API is only returning English reviews which is why you're seeing the total count as 4 but not getting any data back.

**Comment by cackle** [comment]
Hi Tomelm,

But if I pass the language parameter to the API, does it solve the problem? If not, do you have a bug for this issue?

PS: Many thanks for the super fast response!

Thanks!

**Comment by tomelm** [comment]
Right now it doesn't accept a language parameter. We have a ticket internally to add one but we don't have an ETA on it.

**Comment by nlxdodge** [comment]
Did you include the locale? 
For dutch you need:

array("locale"=> "nl-NL") 

See [Review Yelp page](https://www.yelp.com/developers/documentation/v3/business_reviews)
and [Yelp Locales](https://www.yelp.com/developers/documentation/v3/supported_locales)

Because if you don't set the GET variable it return nothing (Your case).

**Comment by mittonk** [comment]
@cackle : Yes, the `locale` parameter @nlxdodge pointed will get you these reviews:
* https://api.yelp.com/v3/businesses/desmet-studios-amsterdam-amsterdam/reviews?locale=nl_NL
```
{
    "reviews": [
        {
            "url": "https://www.yelp.com/biz/desmet-studios-amsterdam-amsterdam?hrid=3HZlktPyjNVYo7G5guowcA&adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ssWONR4BhYiARowH3vsVEA",
            "text": "Super plek voor een eigen feest! Enige nadeel is dat de bar in een andere ruimte is dan de \"dansvloer\" en het podium. Als je dat van te voren weet kan je de...",
            "rating": 4,
            "user": {
                "image_url": "https://s3-media1.fl.yelpcdn.com/photo/QrYu_nZGbfFYViugmzkfaw/o.jpg",
                "name": "Sanneke R."
            },
            "time_created": "2011-06-29 09:18:21"
        },
        {
            "url": "https://www.yelp.com/biz/desmet-studios-amsterdam-amsterdam?hrid=xihRnWGXMxCkMlas2aUtRw&adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ssWONR4BhYiARowH3vsVEA",
            "text": "Het is een ideale lokatie voor bruiloften en feesten. \n\nDe begeleiding van het personeel is geweldig. Er zijn aparte kamers achterin waar je je kunt...",
            "rating": 5,
            "user": {
                "image_url": "https://s3-media2.fl.yelpcdn.com/photo/Vp5XpJNaDvyLKSCekk20jw/o.jpg",
                "name": "Pieter B."
            },
            "time_created": "2012-07-19 06:53:36"
        },
        {
            "url": "https://www.yelp.com/biz/desmet-studios-amsterdam-amsterdam?hrid=bUQ2JT-k425fH5GBxoqdHA&adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ssWONR4BhYiARowH3vsVEA",
            "text": "Desmet was het podium van 3voor12/gastenlijst concerten. Elke donderdag stond ik hier weer gratis naar de meest onbekende, maar ook de bekendste bands te...",
            "rating": 4,
            "user": {
                "image_url": "https://s3-media4.fl.yelpcdn.com/photo/dox1CHsg7vqys_ZsaEr8tQ/o.jpg",
                "name": "Sophie T."
            },
            "time_created": "2010-10-09 03:21:53"
        }
    ],
    "total": 4
}
```

The Reviews endpoint gives you reviews in one language (in the language specified by `locale`) and defaults to English reviews.  If you want Dutch reviews you'll need to specify `locale=nl_NL` (with an underscore).

There's not yet a "give me reviews in any language, whatever exists" option, which is what @tomelm  was talking about.
