### ISSUE TITLE
How do you set up GraphQl API in React-Native

### ISSUE THREAD

**Issue by huffdesign** [Yelp/yelp-fusion#268]
I'm new to programming. I'm building a lunch finder app and I'm using React-Native for my project. 

I can't figure out how to hook up the Yelp GraphQL Api. I don't know what to call the file or how to set it up. If someone could send me to a tutorial or even help me with the hookup code. 

I don't know where to put the Secret code. 

Thanks,

**Comment by mittonk** [comment]
@huffdesign : We're looking into a tutorial.

**Comment by tomelm** [comment]
Hey @huffdesign, we put out a [small guide](https://www.yelp.com/developers/graphql/guides/requests) on how to make requests but it doesn't but it doesn't cover the end-to-end of getting up and running.

For React Native, you should checkout the [React Apollo](http://dev.apollodata.com/react/) clientlib that'll give you the functionality you need. We don't have any actual tutorials on getting that up and running but there are a lot of resources online:
* http://dev.apollodata.com/react/react-native.html
* https://www.learnapollo.com/tutorial-react-native/react-native-01/
* https://medium.com/react-native-training/react-native-with-apollo-part-2-apollo-client-8b4ad4915cf5

Hope that helps!

**Comment by huffdesign** [comment]
Thank you so much!!

I ended up using the Fusion API, but I really want to use the GraphQl one.
I will look over your resources and I will figure it out.

Thanks again.
