### ISSUE TITLE
Is it possible to get the date a restaurant was marked closed?

### ISSUE THREAD

**Issue by choj** [Yelp/yelp-fusion#269]
https://www.yelp.com/biz/red-hot-lovers-ann-arbor clearly marks the restaurant as closed, but does not seem to indicate the associated date of the status change. The Business API provides the value `is_closed`, is there a way to get the date on which it was marked closed?

This 2017 paper https://goo.gl/G2rhqA mentions that Yelp restaurant reported closing dates may be more accurate than that reported to government agencies, but doesn't disclose how they got that information. I've emailed the authors but haven't heard back from them.

**Comment by mittonk** [comment]
@choj : Sorry, that data's not available through the Fusion API.

Are you looking at creating an academic paper, your own app, or something else?

**Comment by choj** [comment]
It was going to be for a personal project. Switched gears though, and no longer doing that.

One of the authors of that paper said they got the closing dates through a data use agreement with Yelp, so that is figured out.
