### ISSUE TITLE
Business ID from Autocomplete API does not match ID from Search API

### ISSUE THREAD

**Issue by russellharvey** [Yelp/yelp-fusion#271]
Per the documentation, Autocomplete business results currently return an "encoded ID" while the Search API returns businesses with a "friendly ID."

This is problematic for the case of attempting to determine if a result that was present in an autocomplete search is then present in a subsequent business search.

Say your use case calls for searches to be filtered on the Food category.  Autocomplete doesn't accept filters, so it is possible to get back a business which isn't in the Food category.  Say the user taps that business, and now expects to see it in their search results.  Unfortunately, it won't appear there because the search API accepts the Food filter and will correctly exclude it.

This could be solved on the client side by checking to ensure that a tapped autocomplete business winds up appearing in the search results (if it doesn't, you just do another search, without the filter).  Unfortunately, with the ID mismatch, I can't compare IDs.  

I'm making due with a Name comparison for now, but ID would be safer.

**Comment by mittonk** [comment]
Hm, our setup is tuned for some more common use cases --- this is indeed tricky.

**Comment by dan98765** [comment]
On March 29, 2018 we updated most of our endpoints to output both an 'id' (which is the encoded ID you mentioned @russellharvey) as well as an 'alias' (which was formerly the 'friendly ID'). Most of our endpoints will also accept either the 'id' or 'alias' as input wherever an endpoint asks for a 'business_id'. 

Check out the changelog entry: https://www.yelp.com/developers/v3/changelog#changelog-20180329
