### ISSUE TITLE
How can I get the price range of a business?

### ISSUE THREAD

**Issue by e-jam** [Yelp/yelp-fusion#273]
I apologize for asking this here, but I have already asked [this question](https://stackoverflow.com/questions/45416031/does-ylpbusiness-class-have-a-property-indicating-the-price-range-of-a-busines) on Stackoverflow to no avail. I have been looking around in the documentation, but haven't found any mention of how to get the price range of a particular business. YLPBusiness does not have a "price range" instance property. Any help would be much appreciated!

**Comment by tomelm** [comment]
Hey @e-jam! Both our business and search endpoints provide the price of the business:
https://www.yelp.com/developers/documentation/v3/business_search
https://www.yelp.com/developers/documentation/v3/business

Are you using the iOS clientlib? It might be missing there.

**Comment by e-jam** [comment]
Hello @tomelm! Yes, I am using the official client lib installed through Cocoapods, and the class `YLPBusiness` does not have a "price range" variable.

**Comment by tomelm** [comment]
Could you open an issue on that repo? It'll be easier to track the bug

**Comment by e-jam** [comment]
@tomelm There is already one issue concerning missing fields in `YLPBusiness` open on the the original repository. I decided to open an additional issue here because the original issue was not resolved. This is the link to the issue: [missing YLPBusiness fields](https://github.com/Yelp/yelp-ios/issues/61)

**Comment by mittonk** [comment]
Great, let's track this in https://github.com/Yelp/yelp-ios/issues/61 .
