### ISSUE TITLE
Auto Fill Review

### ISSUE THREAD

**Issue by rezzmk** [Yelp/yelp-fusion#275]
Hello, I was wondering if it would be possible to have a button on my website that link to a specific business new review page, and then auto fill the textbox with text written on my website? 

Because I have a review system in place on a website, but I would love for clients to be able to write once and post everywhere, and since yelp api is only read-only I am trying to figure out another way of accomplishing this.

Thank you in advance.

**Comment by tomelm** [comment]
Hey @rezzmk, this is not a use case that is supported or doable by the API and as far as I know nothing something that the site allows you to do in general.
