### ISSUE TITLE
Obtaining access token returning 400

### ISSUE THREAD

**Issue by steelow** [Yelp/yelp-fusion#276]
Making api call to the Yelp Fusion for access token returns 400. The following is an excerpt of the logged error object  
`headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.16.2',
        'Content-Length': 155 },
     method: 'post',
     url: 'https://api.yelp.com/oauth2/token',
     data: '{"client_id":"xxxxxxxxx","client_secret":"xxxxxxxxx","grant_type":"client_credentials"}' }`

**Comment by tomelm** [comment]
What's the error response you're getting?

**Comment by steelow** [comment]
Status message says Bad Request.

**Comment by mittonk** [comment]
@steelow : It looks like you're using a JSON body --- this endpoint requires `application/x-www-form-encoded`.

See https://www.yelp.com/developers/documentation/v3/authentication .

**Comment by steelow** [comment]
Nice. thanks @mittonk. It's now working.
