### ISSUE TITLE
Why doesn't the business API response contain a business website url?

### ISSUE THREAD

**Issue by e-jam** [Yelp/yelp-fusion#277]
I have been looking through the JSON response of  `https://api.yelp.com/v3/businesses/{id}` and there doesn't seem to be a url associated with the business website (I am not referring to the Yelp page). Has it always been like this?

**Comment by tomelm** [comment]
Yep, it's always been like this. We've never provided the non-Yelp url in the API response.

**Comment by e-jam** [comment]
@tomelm is it possible to also provide / include the business website in the API response? Because when navigating to a business' Yelp page, the business's website is listed...so the information is there.
