### ISSUE TITLE
Yelp Fusion Category filter response

### ISSUE THREAD

**Issue by itsnotafake** [Yelp/yelp-fusion#279]
On the Business Search API page is states that, "The category filter can be a list of comma delimited categories. For example, "bars,french" will filter by Bars and French." Is it possible to instead have it filter by Bars OR French?

**Comment by mittonk** [comment]
It actually does filter by "bars OR french".  We'll fix the documentation!

**Comment by mittonk** [comment]
(Using this issue to track clarifying that documentation).
