### ISSUE TITLE
Hours not appearing when querying API

### ISSUE THREAD

**Issue by AnnaDanielle** [Yelp/yelp-fusion#282]
## Overview
- **Client ID:** __
- **Issue type:** _bug_
- **Summary:** _just simply query business id with yelp api_
- **Platform:** _desktop_

## Description
queried business API for arbys-alhambra, and returned some data, but not all. hours were not in there. when I got to the website (https://www.yelp.com/biz/arbys-alhambra?osq=Arby%27s), there they are in plain sight. What's with the discrepancy?

here are my results, expected them to be the same as the website:
![image](https://user-images.githubusercontent.com/24233531/29430241-91ded410-8348-11e7-8cca-d5b725d4473b.png)

### Endpoint
_Fusion Business API_

### More info
Also, just queried again, and they appeared! what is going on?

**Comment by tomelm** [comment]
Filed a ticket internally, I don't have a great answer right now. We pull business hours from a different data source and the fact that it's working now means that other data source has a slight outage and we succeeded the request with out or there was a gap in caching.

We'll try to look a little more.

**Comment by aleksdao** [comment]
@AnnaDanielle Fwiw, I'm able to get `hours` data via the Yelp GraphQL API (if it's something you want to explore!)

[https://www.yelp.com/developers/graphiql?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20starts%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button%20above)%0A%23%0A%23%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0A%0A%20%20query%20%7B%0A%20%20%20%20business(id%3A%20%22arbys-alhambra%22)%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20coordinates%20%7B%0A%20%20%20%20%20%20%20%20latitude%0A%20%20%20%20%20%20%20%20longitude%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20price%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rating%0A%20%20%20%20%20%20url%0A%20%20%20%20%20%20photos%0A%20%20%20%20%20%20reviews%20%7B%0A%20%20%20%20%20%20%20%20rating%0A%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20location%20%7B%0A%20%20%20%20%20%20%20%20formatted_address%0A%20%20%20%20%20%20%20%20address1%0A%20%20%20%20%20%20%20%20address2%0A%20%20%20%20%20%20%20%20address3%0A%20%20%20%20%20%20%20%20city%0A%20%20%20%20%20%20%20%20state%0A%20%20%20%20%20%20%20%20zip_code%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20categories%20%7B%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20hours%20%7B%0A%20%20%20%20%20%20%20%20is_open_now%0A%20%20%20%20%20%20%20%20open%20%7B%0A%20%20%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%20%20%20%20start%0A%20%20%20%20%20%20%20%20%20%20end%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D](query here)

**Comment by mittonk** [comment]
@aleksdao : I suspect the same occasional-rare-failure will hit both traditional Fusion and GraphQL endpoints, switching APIs may not help much.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
