### ISSUE TITLE
Geographical Bounding Box

### ISSUE THREAD

**Issue by system-pioneer** [Yelp/yelp-fusion#284]
In v2, we can specify a location by Geographical Bounding Box for a search request as follows.

https://api.yelp.com/v2/search?term=food&bounds=37.900000,-122.500000|37.788022,-122.399797&limit=3

In Yelp Fusion, is it possible to specify a location by Geographical Bounding Box for a search request?
If possible, an example search request URL, please.
Thanks.

**Comment by mittonk** [comment]
@system-pioneer : I'd suggest using `latitude`, `longitude`, and `radius`.

It's a slightly simpler syntax, but ends up using a very similar back-end query as the V2 bounding-box syntax.

* https://api.yelp.com/v3/businesses/search?term=food&latitude=37.85&longitude=-122.45&radius=3000&limit=3

Does that give you something to work with?

**Comment by system-pioneer** [comment]
It is clear now that the following parameters do not work in Fusion API.
bounds=sw_latitude, sw_longitude | ne_latitude, ne_longitude
Thanks for the info.

**Comment by system-pioneer** [comment]
Closing the thread.
Thanks.
