### ISSUE TITLE
GraphQL queries resulting in a 500 error (using graphql-request)

### ISSUE THREAD

**Issue by dhavalchaudhary** [Yelp/yelp-fusion#286]
## Overview
- **Client ID:** _dy1JtGW-RyfkiouLE3h7jQ_
- **Issue type:** _bug_
- **Summary:** _All requests are resulting in 500 errors._
- **Platform:** _IOS Simulator_

## Description

I'm using a [graphql-request](https://github.com/graphcool/graphql-request) in a react-native app to interact with the Yelp GraphQL API. While this library works perfectly fine with other GraphQL APIs, all the requests made to Yelp's API have resulted in a 500 error. The requests work fine in postman but return _"The server has either erred or is incapable of performing the requested operation."_ as the error message when used in the react-native code. I've written more on this in an [another issue](https://github.com/graphcool/graphql-request/issues/19). Is there anything that can be done to fix this behaviour?

### Endpoint
_Yelp GraphQL API endpoint (https://api.yelp.com/v3/graphql)_

**Comment by tomelm** [comment]
Hey @dhavalchaudhary! Any chance you could get the headers (minus the authorization header) and the request it's sending us?

**Comment by dhavalchaudhary** [comment]
Found my solution [here](https://github.com/Yelp/yelp-fusion/issues/278#issuecomment-323489182). Just like the apollo-client, graphql-request also calls JSON.stringify on the query before sending it to the server. After removing ```content-type: application/graphql``` from the headers, the query works as expected. Thank you.

**Comment by tomelm** [comment]
@dhavalchaudhary since this has happened twice, out of curiosity do you know if the library is sending both application/json and application/graphql content types?

**Comment by dhavalchaudhary** [comment]
The library was sending application/json by default which is correct as it calls JSON.stringify on the query before sending it.
