### ISSUE TITLE
Yelp universal link supported parameters

### ISSUE THREAD

**Issue by kerenk1** [Yelp/yelp-fusion#287]
## Question
Possible distances supported at filters on Yelp site:  
- **Bird’s-eye biew** 
- **Driving**
- **Biking**
- **Walking**
- **Within 4 blocks**

1) How can I use any of the above as a filter query param passed to Yelp universal link?
The param added to the query string when clicking on any available distance category above is of the following form: “&l:g:long,lat,long,lat”.
What exactly is the logic I should use in order calculate the coordinates that will enable filtering by any of the distance categories listed above?

2) What does ytp_st=delivery or ytp_loc=null (more query string params, added once I filter businesses supporting delivery) mean?

**Comment by mittonk** [comment]
@kerenk1 : 

1. For location: I'd suggest the `latitude`, `longitude`, and `radius` parameters.

Pick some appropriate `radius` values for your application!

2. For delivery:  Have a look at
* https://www.yelp.com/developers/documentation/v3/transactions_search

The Yelp website parameters don't exactly match the API parameters --- you should use `delivery` in the URL path instead of adding a `ytp_st` query parameter, for example.

**Comment by kerenk1** [comment]
Hi mittonk,

Thanks for your answer.
I am aware of the long, lat & radius parameters for the API. I'm asking specifically about Yelp website since every url is actually a universal link that I can also use inside Yelp app. I am seeking for a way to filter the results by distance/radius using a query param. Are you familiar with any way of performing this filtering?

**Comment by mittonk** [comment]
@kerenk1 : Ah, thanks for clarifying.

Let me investigate --- I suspect some of these parameters may change without warning, as they're not part of a published API.

**Comment by ENuge** [comment]
@kerenk1 : @mittonk is accurate - Yelp website query params are not part of a published API, and may change without warning. Some website query params are supported in-app from universal links, but not all (and these may change with any app version). In this case, the query param `&l:g:long,lat,long,lat` will unfortunately not work in-app. In general, I wouldn't suggest relying on these params.

As for the logic for calculating the coordinates, I believe that's internal to Yelp. If you'd like to try reproducing it, I believe it's getting some lat/lng distance corresponding to "walking distance"/"bird's eye", etc. The two values in the query param are the top-left and bottom-right points of a square that has your actual search location at its center. Hope that helps!
