### ISSUE TITLE
Error Getting Token- Client Credentials

### ISSUE THREAD

**Issue by lindosninos** [Yelp/yelp-fusion#288]
Having an issue getting/generating a token for YELP Fusion V3 API. 

Here is the error:
"error": {
        "code": "BAD_CLIENT_ID_OR_SECRET",
        "description": "Invalid combination of client_id and client_secret."

I am adding correct clientID and secret generated for me.
I am using Postman to generate the POST call.

**Comment by mittonk** [comment]
@lindosninos : 
1. What is your `client_id`?  (That's safe to share.)

2. How many characters long is your `client_secret`, and what are the first three characters?

**Comment by lindosninos** [comment]
Hi- here it is:
client_id = N5h2F01X_7bC6wWNpmySdQ and looks like about 65 characters long for client_secret
****************************************************************

Thanks

**Comment by mittonk** [comment]
`client_secret` should be exactly 64 characters --- check if you've got a leading or trailing space, newline, etc.

**Comment by lindosninos** [comment]
so I have exact 64 character and no spaces or new line or anything like that. 
What else can I check?

**Comment by lindosninos** [comment]
I was able to get it. Thanks.  I deleted the app and got another one. The new one worked. Thanks

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
