### ISSUE TITLE
Business Search with term for partial business names not returning matches

### ISSUE THREAD

**Issue by johnpolacek** [Yelp/yelp-fusion#289]
## Overview
- **Client ID:** xytT6qN7P9tibv_uEOLqNw
- **Issue type:** bug
- **Summary:** Doing a search with a partial business name returns no matches
- **Platform:** Web

## Description
For example, if you search `?term=Starbu` one would expect to see a result set of Starbucks locations. Instead it returns an empty results array. Additionally, a search I did for `?term=Starbuc` inexplicably returned no Starbucks but did return `elijahs-specialty-coffee-and-tea-elmhurst`

See sample requests below.

### Endpoint
/businesses/search

### Parameters or Sample Request
Search for Starbu
```
https://api.yelp.com/v3/businesses/search/?term=Starbu&cat=coffee&lat=41.8781136&lng=-87.62979819999998
```

### Response
Expect Starbucks locations, actual:
```
{
  "results": [
    
  ]
}
```

### Parameters or Sample Request
Search for Starbuc
```
https://api.yelp.com/v3/businesses/search/?term=Starbu&cat=coffee&lat=41.8781136&lng=-87.62979819999998
```

### Response
Expect Starbucks locations, actual:
```

  "results": [
    {
      "id": "elijahs-specialty-coffee-and-tea-elmhurst",
      "name": "Elijah's Specialty Coffee & Tea",
      ...
  ]
}
```

### Parameters or Sample Request
Search for Starbuck
```
https://api.yelp.com/v3/businesses/search/?term=Starbuck&cat=coffee&lat=41.8781136&lng=-87.62979819999998
```

### Response
Returns Starbucks locations as expected:
```
{
  "results": [
    {
      "id": "starbucks-chicago-150",
      "name": "Starbucks",
```

**Comment by mittonk** [comment]
Hm, this isn't great typo / substring coverage.  Looking at a few different angles:

1. I can at least explain the Elijah's involvement on "Starbuc" --- the review from "Maddie M." uses exactly that spelling:
* https://www.yelp.com/biz/elijahs-specialty-coffee-and-tea-elmhurst?hrid=rGiyKW5IFuKYWLZRvRBELQ

2. Not specific to the API.  On the more-interactive www.yelp.com site, searching for "Starbu" in this area suggests a closer typo "starbux":
* https://www.yelp.com/search?find_desc=Starbu&find_loc=elmhurst,+il

Clicking "Search instead for: Starbu" shows no results, as with the API:
* https://www.yelp.com/search?find_desc=Starbu&find_loc=elmhurst,+il&dt=1

3. @johnpolacek : Are you by any chance trying to do "search-as-you-type"?  If so, the Autocomplete endpoint is better tuned for getting only the first part of a search term:
* https://www.yelp.com/developers/documentation/v3/autocomplete

It's not as flexible for general search, though.

4. Taking a step back --- was "Starbu" really your original problem, or is this the simplest-similar-issue?  I want to make sure we're debugging the case you care about.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

**Comment by johnpolacek** [comment]
@mittonk Sorry to not reply. Yes, the use case is autocomplete. I'll give that Autocomplete endpoint a go as suggested. Thanks!
