### ISSUE TITLE
Search by attribute does not work

### ISSUE THREAD

**Issue by raduiacovete** [Yelp/yelp-fusion#290]
## Overview
- **Client ID:** _(Don't know where to look for it)_
- **Issue type:** _(BUG)_
- **Summary:** _(Trying to search using attributes)_
- **Platform:** _(Web)_

## Description
_(I am trying to filter down the results on some attributes and I get a generic error)_

## More information
This is the query that I am using 
{
  search(term: "burito", location: "san francisco", attributes:"hot_and_new") {
    total
    business {
      name
      reviews {
        text
        rating
        time_created
        url
      }
    }
  }
}

This is the error that I receive 

message": "Expected list like type for <class 'str'>: hot_and_new",

### Endpoint
_(Fusion Search API)_

### Parameters or Sample Request

```
https://www.yelp.com/developers/graphiql?query=%7B%0A%20%20search(term%3A%20%22burito%22%2C%20location%3A%20%22san%20francisco%22%2C%20attributes%3A%22hot_and_new%22)%20%7B%0A%20%20%20%20total%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20reviews%20%7B%0A%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20rating%0A%20%20%20%20%20%20%20%20time_created%0A%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "errors": [
    {
      "message": "Expected list like type for <class 'str'>: hot_and_new",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ],
  "data": {
    "search": null
  }
}
```

## Extra information
_(Not sure maybe some parsing problems)_

**Comment by tomelm** [comment]
Yep, this looks like it's broken. Thanks for letting us know! Will ticket internally and look at getting this fixed.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
