### ISSUE TITLE
Not found location returns INTERNAL_ERROR

### ISSUE THREAD

**Issue by Liad91** [Yelp/yelp-fusion#293]
## Overview
- **Client ID:** Npo_RHMB2HYw-Zue5lpiRQ
- **Issue type:** bug
- **Summary:** not found location returns `INTERNAL_ERROR`
- **Platform:** Desktop/web

## Description
I'm sending a request to `https://api.yelp.com/v3/businesses/search?location=Tel%20Aviv%2C%20Israel`,
and instead of `LOCATION_NOT_FOUND` I'm getting `INTERNAL_ERROR`.

### Endpoint
Fusion Search API

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?location=Tel%20Aviv%2C%20Israel
```

### Response

```
{
    "error": {
        "code": "INTERNAL_ERROR",
        "description": "Something went wrong internally, please try again later."
    }
}
```

**Comment by tomelm** [comment]
Hey @Liad91, that's a bug for sure. We'll get someone to look at this soon!

**Comment by tomelm** [comment]
We've fixed this bug. Closing!
