### ISSUE TITLE
I need help with finding my Token Secret, I was able to get my Client ID, Client Secret, and Token

### ISSUE THREAD

**Issue by brucejamesrealty** [Yelp/yelp-fusion#295]
I need help with finding my Token Secret, I was able to get my Client ID, Client Secret, and Token

The documentation for Yelp Fusion (Authentication) is incomplete, please help

**Comment by tomelm** [comment]
@brucejamesrealty there is no token secret on the Fusion API. What are you trying to do? token secret was needed for v2 but Fusion and v2 are not compatible.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
