### ISSUE TITLE
Businesses api bug

### ISSUE THREAD

**Issue by yuyaukong** [Yelp/yelp-fusion#296]
## Overview
- **Client ID: H2XkgrUsG3d49wWDBTA7pQ
- **Issue type: bug
- **Summary: When I try to call businesses api with id, it return 'BUSINESS_NOT_FOUND'
- **Platform: web

## Description
1. Firstly, I have call the search api with my location.
eg: https://api.yelp.com/v3/businesses/search?categories=petstore&latitude=22.3120123&limit=50&longitude=114.2193281&locale=en_US
2. Then I get the business ID. eg: "id": "喵犬号-香港"
3. Then I try to get the detail information for this business, eg: https://api.yelp.com/v3/businesses/喵犬号-香港
4. It return BUSINESS_NOT_FOUND

## More information
The main reason I think is relate to the language, since the id return is chinese, I think it has some problem in encoding.

### Endpoint
1. Fusion Search API
2. Business API

### Parameters or Sample Request
```
1. https://api.yelp.com/v3/businesses/search?categories=petstore&latitude=22.3120123&limit=50&longitude=114.2193281&locale=en_US
2. https://api.yelp.com/v3/businesses/喵犬号-香港
```

### Response
```
{
    "error": {
        "code": "BUSINESS_NOT_FOUND",
        "description": "The requested business could not be found."
    }
}
```

## Extra information
The main reason I think is relate to the language, since the id return is in chinese format, I think it has some problem in encoding.

Beside, I can call api:
https://api.yelp.com/v3/businesses/喵犬号-香港/reviews
the id is correct, but I only can get reviews but can not get details

**Comment by yuyaukong** [comment]
Any one can give me some suggestion?

**Comment by mittonk** [comment]
Hm, that's not expected.  I can reproduce the issue.

We'll have a look.

**Comment by Pinski** [comment]
I'm having the same issue with encoding.  If a business's id contains a letter with an accent mark, it throws as well.

https://api.yelp.com/v3/businesses/limón-rotisserie-burlingame-2

Thanks.

**Comment by mittonk** [comment]
@Pinski : Thanks, that's a simpler repro case.

**Comment by parisbutterfield** [comment]
I'm also experiencing this in my application. Another example:
https://api.yelp.com/v3/businesses/peña-pachamama-san-francisco-2

Is there an ETA for this?

I noticed you can unaccent (ñ -> n) the characters and it works. I'd prefer not to do this because it may lead to unexpected results in uniqueness.

**Comment by tomelm** [comment]
Hey everyone, apologies for not updating this earlier but we found the bug and have fixed the issue. All the businesses here correctly return data for me when I request them through the API.

@parisbutterfield that business is working for me when I test with an API client using the accented character:

<img width="1036" alt="screen shot 2017-09-29 at 11 20 27 am" src="https://user-images.githubusercontent.com/153050/31029897-4986d5e6-a508-11e7-8f5e-d22b86b96bac.png">

Is it possible there's something that changing the encoding on your side? Could you give me your client id so I can check the request logs?

**Comment by parisbutterfield** [comment]
@tomelm I don't think anything is changing the encoding. I'm using postman. 

My client id is:
aocHT47b76zgXGWeRtisCg

The response headers:

GET
https://api.yelp.com/v3/businesses/peña-pachamama-san-francisco-2

Headers(12)
Tests
Status:502 Bad Gateway
Time:125 ms
Size:431 B
Accept-Ranges →bytes
Cache-Control →no-cache
Connection →keep-alive
Content-Type →text/html
Date →Fri, 29 Sep 2017 21:04:03 GMT
Server →nginx
Transfer-Encoding →chunked
Via →1.1 varnish
X-Cache →MISS
X-Cache-Hits →0
X-Proxied →10-65-0-124-useast1aprod
X-Served-By →cache-dfw18631-DFW

<img width="1283" alt="screen shot 2017-09-29 at 5 04 07 pm" src="https://user-images.githubusercontent.com/6758500/31036000-4ca967b8-a538-11e7-820b-314839ddafa3.png">

**Comment by tomelm** [comment]
@parisbutterfield yea it looks like you're not even reaching our service, the failed requests are not even showing up in our logs. Is the 502 happening consistently on just that request?

**Comment by parisbutterfield** [comment]
@tomelm. Yes that request and anything that has accented characters. Requests without accents complete find. I get the same error in AWS and locally on my machine. I just made a few requests that were successful.

**Comment by parisbutterfield** [comment]
@tomelm I figured it out. Implicitly, the REST client you're using is URL Encoding the path variable that contains the businessID. Most web browsers do this implicitly as well. As per [RFC3986](https://tools.ietf.org/html/rfc3986#section-2) a URI can only contain [US-ASCII](http://www.columbia.edu/kermit/ascii.html).

Postman and the Yelp V3 library I forked, don't url encode the businessID. This caused the requests to fail. I updated my [library](https://github.com/parisbutterfield/node-yelp) to URL encode before making those requests. Any url params were already being encoded.

Is it possible to update the Yelp documentation for the endpoints below? This way the user is aware of the possibility of having non-US-ASCII for a businessID.

https://www.yelp.com/developers/documentation/v3/business
https://www.yelp.com/developers/documentation/v3/business_reviews

**Comment by tomelm** [comment]
@parisbutterfield thanks for explaining what happened! I'll file a ticket internally to update out docs to reflect that business ids can be unicode.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
