### ISSUE TITLE
Is it possible in passing multiple business ids in Fusion API 

### ISSUE THREAD

**Issue by Budheshwar** [Yelp/yelp-fusion#297]
Hi,
I have a specific requirement for our website local.USAOnline.us where we show list of businesses (with paging,per page 20 business list). Now I want to integrate Yelp Fusion API to get only Rating & Reviews (count only) to show Rating & Review against each business . How can I better do that?

 One possibility is that when ever the page loads, I make 20 APIs call for the businesses to get data. But I think that will not be a good user experience. 

 So is there any possibility that i can make a bulk request i.e. passing multiple business ids to get data?

Thanks

**Comment by tomelm** [comment]
The Fusion API itself doesn't have any way to handle this. You could do this using the GraphQL API by building a query that passes in multiple businesses at once. The query itself would look something like:

```
{
  b1: business(some-business-id) {
    rating
    review_count
  }
  b2: business(some-other-business-id) {
    rating
    review_count
  }
  b3: business(some-third-business-id) {
    rating
    review_count
  }
  ...
}
```

You can read more about GraphQL here:
* https://www.yelp.com/developers/graphql/guides/intro
* https://www.yelp.com/developers/graphql/guides/basic_usage

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.

**Comment by JakeEllis** [comment]
@watterso  has this feature been updated in Fusion API?
