### ISSUE TITLE
Search API issues

### ISSUE THREAD

**Issue by David201705** [Yelp/yelp-fusion#298]
## Overview
- **Client ID:** _(e.g. jO7FkmyPhUkuDm8uD3-6gA)_
- **Issue type:** _(Bug)_
- **Summary:** _(I am using v3 search api for get businesses with its category, but i cannot get correct result i want
- **Platform:** _(in iOS, call Rest API)_

## Description
Used this api
https://api.yelp.com/v3/businesses/search?categories=restaurants,spanish&latitude=10.315699&longitude=123.885437
for getting spanish restaurants
And it gives me nearly 150 restaurants, but most of them are not Spanish Restaurant Category

id": "zubuchon-cebu-city",
"name": "Zubuchon",
"image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/7F3B5-2LfivkII9d5i8iaA/o.jpg",
"is_closed": false,
"url": "https://www.yelp.com/biz/zubuchon-cebu-city?adjust_creative=jO7FkmyPhUkuDm8uD3-6gA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=jO7FkmyPhUkuDm8uD3-6gA",
"review_count": 13,
"categories":[
{"alias": "filipino", "title": "Filipino"},
{"alias": "seafood", "title": "Seafood"},
{"alias": "soup", "title": "Soup"}
],
"rating": 4,
"coordinates":{"latitude": 10.317542, "longitude": 123.894127},
"transactions":[],
"price": "₱₱",
"location":{"address1": "N Escario Street", "address2": "Escario Central", "address3": "", "city": "Cebu City",…},
"phone": "+63322540247",
"display_phone": "+63 32 254 0247",
"distance": 972.4964813519999

...

How can i filter only Spanish Restaurants?
Please help me, thanks

**Comment by tomelm** [comment]
Hey @David201705, I believe categories are using a logical OR instead of an AND. Since restaurants is a top-level category it's going to include way more results. What happens if you search just "spanish"?

**Comment by David201705** [comment]
Thanks for your rejply @tomelm 
I have tried only Spanish, and it gives one 
"id": "hala-paella-cebu-city",
"name": "Hala Paella",
"image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/xloQH-J4g54OLCGyFbe48w/o.jpg",
"is_closed": false,
"url": "https://www.yelp.com/biz/hala-paella-cebu-city?adjust_creative=jO7FkmyPhUkuDm8uD3-6gA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=jO7FkmyPhUkuDm8uD3-6gA",
"review_count": 2,
"categories":[
{"alias": "spanish", "title": "Spanish"},
{"alias": "foodstands", "title": "Food Stands"}
],
"rating": 4.5,
"coordinates":{"latitude": 10.3413800046365, "longitude": 123.911539725959},
"transactions":[],
"location":{"address1": "Banilad Town Center", "address2": "Banilad", "address3": "", "city": "Cebu City",…},
"phone": "+63323444252",
"display_phone": "+63 32 344 4252",
"distance": 4038.161882558

Then is there way to use logic AND?

**Comment by tomelm** [comment]
As of right now there's not. You would need to make 2 queries with each category you want and merge them on your side.

**Comment by David201705** [comment]
@tomelm But Yelp apps works properly
It means they use their own API? if yes, then i think that is not fair

**Comment by tomelm** [comment]
@David201705 the Yelp apps use a custom API that's tailor built towards specific use cases. It's not always possible for us to expose the same API from the Yelp app publicly. Some of the use cases are very different.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
