### ISSUE TITLE
An example of websites that implements Yelp API & showing Data (Reviews & Ratings)

### ISSUE THREAD

**Issue by cmaji** [Yelp/yelp-fusion#299]
Hi,
I would like to know the some of the websites which are showing reviews & ratings on their websites.
Cause it will give me some idea how to display Yelp data on website.

Thanks

**Comment by mittonk** [comment]
@cmaji : Check out the Developer Showcase!
* https://www.yelp.com/developers/v3/showcase

There are several good screenshots there.

(You can find that page from https://www.yelp.com/fusion).
