### ISSUE TITLE
"locale" parameter doesn't actually affect reviews returned

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-fusion#3]
`https://api.yelp.com/v3/businesses/gary-danko-san-francisco/reviews?locale=fr_FR`

should probably return French reviews, but it doesn't: 
```
{
  "reviews": [
    {
      "url": "https://www.yelp.com/biz/gary-danko-san-francisco?hrid=OtEqx7ZndmJGqi_XR83MVQ",
      "text": "best place to dine in a city known for gourmet cuisine",
      "user": {
        "image_url": "http://s3-media4.fl.yelpcdn.com/photo/JkdZsw_ASWWPYIsA2W5fsQ/o.jpg",
        "name": "Jared K."
      },
      "rating": 5
    },
...
```

**Comment by mittonk** [comment]
For comparison, `https://api.yelp.com/v3/autocomplete?text=Caf&latitude=40&longitude=-110&locale=fr_FR` works as expected.

**Comment by guangyang** [comment]
This is a known limitation. In https://github.com/Yelp/yelp-api-v3/blob/master/docs/api-references/businesses-id-reviews.md, there is no mention about locale parameter. We do plan to support it for all endpoints. Please leave comments below if you also want to see this fixed.

Thanks.

**Comment by mittonk** [comment]
Looks like we got this working at some point:
* https://api.yelp.com/v3/businesses/gary-danko-san-francisco/reviews?locale=zh_HK

```
{
  "total": 3,
  "reviews": [
    {
      "rating": 5,
      "user": {
        "image_url": "https://s3-media1.fl.yelpcdn.com/photo/GTcCEyW2kgE6sAacC_VBGw/o.jpg",
        "name": "Chen P."
      },
      "text": "三番的米其林餐馆里，Gary Danko是印象特别好的一个，性价比很高。任选5道菜，分量比较足，不至于像有些tasting menu吃了十多道菜感觉还没饱。第一道菜点的一个risotto，第一口吃下去就感觉太惊艳了，西餐还可以做的这么好吃。每道菜都相当不错，最后的一份creme...",
      "time_created": "2015-09-20 22:45:54",
      "url": "https://www.yelp.com/biz/gary-danko-san-francisco?hrid=-viDdRjcm7TgjCMcCr1oEw&adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ssWONR4BhYiARowH3vsVEA"
    }
  ]
}
```
(There are not currently any French reviews of that business, so can't use my original query.)

Now we just need to update the documentation at:
* https://www.yelp.com/developers/documentation/v3/business_reviews

**Comment by mittonk** [comment]
`locale` is not listed on 
* https://www.yelp.com/developers/documentation/v3/business_reviews

Calling this done.

**Comment by bizmate** [comment]
is the default locale _en_ if none is specified?

**Comment by mittonk** [comment]
It is `en_US`.  Filed #73 to document that more clearly.

**Comment by smflanag** [comment]
This still doesn't seem to be working: https://api.yelp.com/v3/businesses/search?location=Grafton+Street&term=pub&radius=1000&limit=20&locale=en_IE
The above defaults to returning results from MA, USA, even with locale for Ireland selected.

**Comment by bizmate** [comment]
@smflanag why are you using the locale with the search endpoint?

**Comment by dan98765** [comment]
@smflanag if we changed it to something like "Specify the locale to localize the business information to." do you think you would have made more sense to you?

**Comment by smflanag** [comment]
@dan98765 I think that would have made more sense to me, yes.

**Comment by dan98765** [comment]
OK I've just updated the text to say "Specify the locale into which to localize the business information."
I hope that will help others avoid confusion as to what the parameter does.
