### ISSUE TITLE
Request: Add business website to business search response

### ISSUE THREAD

**Issue by gunmetalremy** [Yelp/yelp-fusion#30]
Hello, I would like to request an additional field to the search response: the business's website. My use case is that I would like to find all the local businesses in a certain category that have a website. Some of these businesses have info regarding B2B as well as listing any relevant emails. 

Thanks!

**Comment by guangyang** [comment]
So you want a search filter for having website and the actual website URL in the response? Just to double check.

**Comment by mochidusk** [comment]
Yes, that is correct.
