### ISSUE TITLE
Business search returning nulls for latitude where previously they weren't null

### ISSUE THREAD

**Issue by derekclevenger** [Yelp/yelp-fusion#300]
## Overview
- **Issue type:** Bug
- **Summary:** While working on my client application I noticed that the program was breaking.  While digging into it I found I was getting returned 
{"Error converting value {null} to type 'System.Double'. Path 'businesses[40].coordinates.latitude', line 1, position 35955."}.  
The coordinates hadn't been changed and neither had the business returns.  It seems to occur in a few places but not all.
- **Platform:** Desktop

## More information
When searching for solutions I came across issue #266 which had already been closed out and this is why I was adding a new issue.

### Endpoint
Fusion API

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=36.160000&longitude=-86.630000&radius=16093
```

**Comment by tomelm** [comment]
Hey @derk2689! As a general rule, while it doesn't happen often lat/longs can by null so it's good to handle that case.

We'll investigate if something's changed on our side again with regards to businesses returning null values.

**Comment by derk2689** [comment]
Thanks for the quick response.  We implemented that after seeing the other issue to mitigate failures on our end as well.
