### ISSUE TITLE
Is there a way to retrieve more than 50 results per call? 

### ISSUE THREAD

**Issue by stevenuba** [Yelp/yelp-fusion#301]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(business search endpoint)_
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** _(linux PHP)_

## Description
I am running business search endpoint and it gives only 50 results, fusion documentation says this endpoint returns up to 1000 results.

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
_(Fusion Search API)
### Parameters or Sample Request
https://api.yelp.com/v3/businesses/search?term=medical center&location=miami&Authorization=Bearer 

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by mittonk** [comment]
@stevenuba : You can get 50 results at a time, up to result #1000.  Use the `offset` parameter to page through results.  Try `offset=50`, then `offset=100`, etc.

**Comment by stevenuba** [comment]
Thanks for your quick response mittonk! do you have a sample when using offset?
Thanks in advanced!

**Comment by mittonk** [comment]
@stevenuba : This will get matches 51 -- 100 for `medical center` in `miami`:
* https://api.yelp.com/v3/businesses/search?offset=50&limit=50&term=medical%20center&location=miami

**Comment by stevenuba** [comment]
Now I understand!! Amazing! Thanks a lot!!
