### ISSUE TITLE
Is it possible to get API or Fusion for merchant's products, i.e., Product: name, description, price, photo?

### ISSUE THREAD

**Issue by Bafri** [Yelp/yelp-fusion#303]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(eg. feature request, bug, question, etc)_
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description
_(More detailed information explaining the problem, the expected results, the question, etc.)_

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
_(e.g. Fusion Search API)_

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information
Our app displays various restaurants and merchants. We need an API to get their menus and product lists, with specific data such as: item name, description, price & photo. See Here: https://youtu.be/w_Z45b1t_Qs

**Comment by tomelm** [comment]
Hey @Bafri! We currently don't have any plans to do so and I can't provide you any sort of timeline for this.

**Comment by watterso** [comment]
Closing because feature is not on our timeline.
