### ISSUE TITLE
How to add a business to Yelp via Fusion API?

### ISSUE THREAD

**Issue by aszalacinski** [Yelp/yelp-fusion#304]
I am looking into using the Yelp Fusion api to drive Search functionality on my app but one of my use cases needs to be able to add a business if it doesn't return in the search. This is in consideration for independent contractors and sole proprietor/sole employee type businesses.

This simply means I need to inject the new business into the Yelp Add a Business flow.

Is it possible to add an unlisted business to the Yelp domain using the Fusion API? Or is this a premium service that is not exposed? (Which makes sense as that WOULD be a spammers dream).

Thanks!

Aarron

**Comment by mittonk** [comment]
@aszalacinski : Sorry, adding a business isn't part of the Fusion API --- I'd suggest adding the business on www.yelp.com or biz.yelp.com.
