### ISSUE TITLE
Nearby UK postcode showing as france or Germany 

### ISSUE THREAD

**Issue by sinker007** [Yelp/yelp-fusion#305]
Bug
It appears as though UK postcodes are returning incorrect co-ordinates. I have attached a screenshot. The post code being used is PR7 7GT
![yelp](https://user-images.githubusercontent.com/32435201/31056110-91083b22-a6c4-11e7-9b1d-80c9134f0133.png)

Let me know if I am missing any information you may need

**Comment by mittonk** [comment]
@sinker007 : Postcodes are a bit tricky (they aren't very unique), but let's dig a little deeper.

Instead of a screenshot of your application, could you supply the full API URL you're calling (probably starts with `https://api.yelp.com/v3/businesses/search?location=PR7+7GT..`) and the JSON response you get?

**Comment by mittonk** [comment]
For example, I tried
`https://api.yelp.com/v3/businesses/search?term&location=PR7%207GT`
and received:
```
{
	"businesses": [
		{
			"id": "cowshed-buckshaw-village",
			"name": "Cowshed",
			"image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/wmmnH1KTmDQJTwU5lyp5FA/o.jpg",
			"is_closed": false,
			"url": "https://www.yelp.com/biz/cowshed-buckshaw-village?adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ssWONR4BhYiARowH3vsVEA",
			"review_count": 1,
			"categories": [
				{
					"alias": "desserts",
					"title": "Desserts"
				},
				{
					"alias": "coffee",
					"title": "Coffee & Tea"
				}
			],
			"rating": 4.0,
			"coordinates": {
				"latitude": 53.67608,
				"longitude": -2.65713
			},
			"transactions": [],
			"price": "££",
			"location": {
				"address1": "1 Barnes Wallis Way",
				"address2": "",
				"address3": null,
				"city": "Buckshaw Village",
				"zip_code": "PR7 7JA",
				"country": "GB",
				"state": "LAN",
				"display_address": [
					"1 Barnes Wallis Way",
					"Buckshaw Village PR7 7JA",
					"United Kingdom"
				]
			},
			"distance": 359.2048972142
...
		},
		{
			"id": "merlin-cycles-chorley",
			"name": "Merlin Cycles",
```
which looks as I expect.

**Comment by sinker007** [comment]
That looks correct. Unfortunately I didn't code this for my site its part of a wordpress theme installation. If I sent you the Oauth code minus my keys and the code that displays the results could you have a look for me ?

**Comment by mittonk** [comment]
I'd suggest you report this to the author of the Wordpress theme --- this sounds an awful lot like a bug in their code, and I don't think you and I can figure it out without them.
