### ISSUE TITLE
yelp_db.sql   has errors

### ISSUE THREAD

**Issue by yelp11976** [Yelp/yelp-fusion#306]
## Overview
mysql -u root -p  yelp_db < yelp_db.sql

aborting with error in the yelp file:

ERROR 1064 (42000) at line 881: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''PvjfVRC_OlmOlIu' at line 1

**Comment by tomelm** [comment]
@yelp11976 is this relating to the Yelp dataset?

**Comment by yelp11976** [comment]
yes

**Comment by yelp11976** [comment]
I download yelp_sql.tar  then untar the file tar -xvf on redhat EC2 instance.  I am getting this error when I try to import the data to MySQL yelp_db.  Any suggestions.

**Comment by tomelm** [comment]
@yelp11976 trying to run the import now, will let you know if I hit any problems. Could you recreate this issue in the dataset-examples repo (https://github.com/yelp/dataset-examples)?

I'm going to close the issue here as it's not API-related.
