### ISSUE TITLE
businesses/matches/lookup returns non-matching business

### ISSUE THREAD

**Issue by tlc** [Yelp/yelp-fusion#310]
Using a V3 python API with the following search terms
                                name='Taco',
                                address1='35 Broad St',
                                city='Red Bank',
                                state='NJ',
                                country='US'

businesses/matches/lookup returns the correct business and the one next door.
The one next door does not have 'Taco' in the name.  The documentation says that the name argument is matched against 'The name of the business.'.

````
{
  "businesses": [
    {
      "name": "Surf Taco",
      "coordinates": {
        "latitude": 40.3510599,
        "longitude": -74.06514
      },
      "phone": "+17329361800",
      "location": {
        "city": "Red Bank",
        "display_address": [
          "35 Broad St",
          "Red Bank, NJ 07701"
        ],
        "country": "US",
        "address2": "",
        "address3": "",
        "state": "NJ",
        "address1": "35 Broad St",
        "zip_code": "07701"
      },
      "display_phone": "(732) 936-1800",
      "id": "surf-taco-red-bank"
    },
    {
      "name": "Ashes Cigar Club Steakhouse & Seafood Raw Bar",
      "coordinates": {
        "latitude": 40.351158,
        "longitude": -74.065116
      },
      "phone": "+17322190710",
      "location": {
        "city": "Red Bank",
        "display_address": [
          "33 Broad St",
          "Red Bank, NJ 07701"
        ],
        "country": "US",
        "address2": "",
        "address3": "",
        "state": "NJ",
        "address1": "33 Broad St",
        "zip_code": "07701"
      },
      "display_phone": "(732) 219-0710",
      "id": "ashes-cigar-club-steakhouse-and-seafood-raw-bar-red-bank"
    }
  ]
}
````

**Comment by tlc** [comment]
Oddly, if I shorten address1 to 'Broad St', only the correct business is returned.
But the more specific '35 Broad St' returns the two.

**Comment by tomelm** [comment]
Hey @tlc! This might be a bug in our business matching system. Let me file a ticket internally and see if I can get someone to look at it.

**Comment by watterso** [comment]
As mentioned in the [docs for this endpoint](https://www.yelp.com/developers/documentation/v3/business_match):
>1. best match: This will only return 1 business that is the best match based on the information provided.
>2. lookup: This will return up to 10 businesses that is the best match based on the information provided.

There are many factors for matching businesses to input so that second result, despite not having taco in its name, scored highly because it was so close physically. If you want the best match we can give you and no extra  businesses, I'd suggest the best endpoint (`api.yelp.com/v3/businesses/matches/best`) over the lookup endpoint that you used.

**Comment by tlc** [comment]
Perhaps the docs should describe the "many factors".
