### ISSUE TITLE
[Yelp Fusion API] How can I get 'more business info'?

### ISSUE THREAD

**Issue by tokunami** [Yelp/yelp-fusion#311]
## Overview
- **Client ID:** 4NR2B_IEr9XvDnY3JSZgww
- **Issue type:** question
- **Summary:** how to get `more business info` using Yelp Fusion API?
- **Platform:** other

## Description
Hi, I want to get information `Good for Kids` or `Good for Groups` in "more business info" using API.
is it possible? if so, which API should I use? and how?

## More information
question

**Comment by tomelm** [comment]
Hey @tokunami! There's no way to do that at the moment so I can't provide any timeline for this.

**Comment by tokunami** [comment]
thanks for replying @tomelm!
