### ISSUE TITLE
Bicycles Category: 0 Results

### ISSUE THREAD

**Issue by tbryan** [Yelp/yelp-fusion#313]
## Overview
- **Client ID:** 07hdIK8bUNwl2mqfWN3KZg
- **Issue type:** bug
- **Summary:** No results for bicycles category
- **Platform:** web

## Description
I get results from every category I have tried except 'bicycles'. I have tried several lat/lng combinations. 'bicycles' is included in the categories list. https://www.yelp.com/developers/documentation/v2/all_category_list

### Endpoint
Fusion Search API

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/search?latitude=38.574131&longitude=-121.487568&categories=bicycles

### Response
{
    "businesses": [],
    "total": 0,
    "region": {
        "center": {
            "longitude": -121.487568,
            "latitude": 38.574131
        }
    }
}

**Comment by mittonk** [comment]
We've got several categories around bicycles, based on whether you're buying them, renting them, etc.  `bikes` is the one I usually check first.

That lat-lng looks like it's in the US --- and the country list for the `bicycles` from
* https://www.yelp.com/developers/documentation/v2/all_category_list
is `[PL, DK, PT, CZ]`.

US businesses dealing with bikes are usually in categories `bikes`, `bikerentals`, etc.

If your use case is around bicycles, check for the various aliases that mention "bike" or "bicycle"

If your use case is strictly US-based, you can also get a more focused category list at
* https://www.yelp.com/developers/documentation/v2/category_list?hl=en_US
but that's definitely less universal.

Does that give you enough to work with?

**Comment by tbryan** [comment]
Yes. using the category "bikes" works great. Thanks.

**Comment by mittonk** [comment]
Great!
