### ISSUE TITLE
Get a list of all supermarkets in a particular city

### ISSUE THREAD

**Issue by lmishra92** [Yelp/yelp-fusion#314]
I want to find the list of all grocery stores in a particular city. Is it possible using the yelp api or does it only return a limited number of results ?

**Comment by mittonk** [comment]
There is a limit, but it should be high enough for your use case.

You can get up to 1000 search results (in chunks) for a given search:
• https://www.yelp.com/developers/documentation/v3/business_search
• https://www.yelp.com/developers/documentation/v2/all_category_list , try category `grocery` for most supermarkets.

Does that give you enough to work with?
