### ISSUE TITLE
API Call: Get Average Rating? 

### ISSUE THREAD

**Issue by joshash** [Yelp/yelp-fusion#315]
I have the following information:

```

name = "AGEHA JAPANESE FUSION"
postal_code = "10019"
address1 = "767 NINTH AVENUE"
city = "New York"
state = "New York"
country = "US"
```

How do I go about making an API call to return the average rating of this business? I am new to APIs and am having trouble figuring out how to modify the given example to do this. Would somebody be able to provide an example?

**Comment by mittonk** [comment]
@joshash : There's several ways to do this, but I'd probably try either the Business or Search endpoints.

For either, you'll need to set up authentication, either in code or a tool like Postman or Insomnia:
• https://www.yelp.com/developers/documentation/v3/get_started
• https://www.yelp.com/developers/documentation/v3/authentication

1. If you know the business ID (https://www.yelp.com/biz/ageha-sushi-new-york => `ageha-sushi-new-york`), you can look that up directly in lots of detail:
`https://api.yelp.com/v3/businesses/ageha-sushi-new-york`
```
	"id": "ageha-sushi-new-york",
	"name": "Ageha Sushi",
	"rating": 4.0,
...
```

2. If you don't know the business ID, try a search:
`https://api.yelp.com/v3/businesses/search?location=767%20Ninth%20Avenue,%20New%20York,%20NY,%20US&term=Ageha%20Japanese%20Fusion`
Note this returns several businesses, only one of which is the one you want:
```
{
	"businesses": [
		{
			"id": "ageha-sushi-new-york",
			"name": "Ageha Sushi",
			"rating": 4.0,
...
		},
		{
			"id": "kodama-sushi-new-york-2",
			"rating": 3.5,
```

3. You could also use GraphQL or Business Match --- check the documentation for examples on how to use those.

Does that give you enough to get started?

**Comment by watterso** [comment]
Closed due to inactivity.
