### ISSUE TITLE
Circular image from Image URL

### ISSUE THREAD

**Issue by ChunAllen** [Yelp/yelp-fusion#316]
Currently I'm using v2 of yelp api. 
The available image sizes for the image_url are these: 
```
s.jpg: up to 40×40
ss.jpg: 40×40 square
m.jpg: up to 100×100
ms.jpg: 100×100 square
l.jpg: up to 600×400
ls.jpg: 250×250 square
o.jpg: up to 1000×1000
348s.jpg: 348×348 square
```
Is there a way to generate a circular image e.g. `348c.jpg`?
or if it's not possible to have a circular image, how can I set the dimension of an image to be `280x280`

**Comment by tomelm** [comment]
Hey @ChunAllen, there's no way to create or return circular images through the API nor can you really change the size. Any post-processing you want to do on the images will be up to you.

**Comment by ChunAllen** [comment]
I see, I'm currently developing a skill in Alexa that requests from Yelp API. 

I saw that there is a built-in skill in Alexa that also request in Yelp so I just wondered if it the API provides that.  
![img_6839](https://user-images.githubusercontent.com/2100728/31979965-0e280230-b97c-11e7-9cce-5fc3a2c056b4.JPG)

but hopefully the Yelp API will provide this functionality.

**Comment by mittonk** [comment]
@ChunAllen : I'd definitely suggest using an image library to do the circular masking; the Yelp API will give you a photo, but each integration gets to choose how to display it.
