### ISSUE TITLE
Event search endpoint returns 500 when I specify "location" parameter

### ISSUE THREAD

**Issue by Gear61** [Yelp/yelp-fusion#317]
## Overview
- **Client ID:** CCJqNVAXrhLSrbR2gxhIoA
- **Issue type:** Bug
- **Summary:** Events endpoint returns 500 when "location" parameter is passed in
- **Platform:** Mac OSX Postman

## Description
The events endpoint always returns 500 when I pass in the "location" parameter. I have signed up for the developer beta.

## More information
Tried it with a variety of locations from city to ZIP code to address.

### Endpoint
/events

### Parameters or Sample Request
GET https://api.yelp.com/v3/events?location=SF

### Response
```
{
    "error": {
        "code": "INTERNAL_ERROR",
        "description": "Something went wrong internally, please try again later."
    }
}
```
## Extra information
I'm testing the API with Postman.

**Comment by mittonk** [comment]
Definitely a bug, we'll get on that!

**Comment by mittonk** [comment]
@Gear61 : Fixed, please try again!

**Comment by Gear61** [comment]
It works! Thank you so much for the ultra-quick turnaround @mittonk! 👍
