### ISSUE TITLE
Update Event Search API documentation to reflect that cost and cost_max are doubles

### ISSUE THREAD

**Issue by Gear61** [Yelp/yelp-fusion#319]
Documentation: https://www.yelp.com/developers/documentation/v3/event_search

Sample request: https://api.yelp.com/v3/events?location=fremont

Event ID: newark-the-bay-area-night-market-4

These are the cost fields returned by the API (using Postman):
<img width="150" alt="screen shot 2017-10-29 at 12 38 12 pm" src="https://user-images.githubusercontent.com/1650117/32147530-299c3ed2-bca6-11e7-9d5e-be5e5de66866.png">

**Comment by mittonk** [comment]
Repro'd bug --- though looks like newark-the-bay-area-night-market-5 has the .65 prices, and newark-the-bay-area-night-market-4 is 5.0 and 7.0 (which are still formatted as doubles).

```
https://api.yelp.com/v3/events/newark-the-bay-area-night-market-5
```
reports
```
{
    "cost": 5.0,
    "cost_max": 7.0,
...
```

Thanks for the report, we'll get this sorted.

**Comment by watterso** [comment]
This has been updated :)
