### ISSUE TITLE
[Question from Yelp] Your thoughts on future functionality!

### ISSUE THREAD

**Issue by guangyang** [Yelp/yelp-fusion#32]
We're looking into what new functionality we might add to the v3 API and want to get the developer community's feedback!

If you had $100, how would you spend it among the options below?
1. Client SDKs
2. Adding more data to existing endpoints (ie. more photos, more properties like business website)
3. New endpoints to provide more public data (ie, deals, events)
4. New endpoints to provide more user data (ie, bookmarks, checkins, my reviews)
5. New endpoints to provide more transaction capability (ie, buy tickets, make appointments)
6. Other (please specify)

**Comment by wpohl** [comment]
1. $0 (can write my own); but need Java
2. $40 (All reviews, ordered by date descending, average, full text, user-id)
3. $60 (Merchant data)

**Comment by sp00m** [comment]
1. $0: calling a web API can be done easily whatever the programming language IMHO
2. $40: could be interesting
3. $40: especially the events
4. $0: not needed in my case
5. $10: to be considered
6. $10: having made-to-measure responses for data consumption minimization purposes  (e.g. `GET /businesses/search?...&excludes[]=location&excludes[]=categories`)

**Comment by brandonreid** [comment]
2. $100 (All reviews for a business, even if there are link back clauses or something)

**Comment by collinhundley** [comment]
1. $100: Show all reviews, and add a `time` property to each review.

**Comment by hostr** [comment]
2. $50
4. $40
5. $10

**Comment by vkman** [comment]
2.  $30 - Return deals/events with business search
2.  $30 - Return hours_open data within business search (vs separate call)
6.  $30 - Return multiple-category business search more proportionally across category (not letting the quantity of one category push out the results from other categories)
$10 tip.

Will send actual dollars if needed.

**Comment by bizmate** [comment]
2. $90 as added by @wpohl  v2 had the `time_created` for each review. Bring this back pls
2. $10 overall rating and reviews count to be returned in v3/businesses/{id}/reviews endpoint

**Comment by tomelm** [comment]
@bizmate `time_created` is in the response, our docs look out of date. Will update those

**Comment by bizmate** [comment]
@tomelm looks like the new time_created is not matching the previous format. 

At the moment i get back a formatted date that has not timezone information. `"time_created":"2010-08-25 15:21:26",` The time_created as per v2 doc was

```
reviews.time_created	number	Time created (Unix timestamp)
```
Is this likely to change back or is this going to stay?
Also any chance a timezone will be added or is this always UTC/GMT

**Comment by mittonk** [comment]
(Might be worth spinning `review.time_created` changes off as a separate issue.)

**Comment by bizmate** [comment]
@mittonk should i put these details in #19 or you would prefer a new issue?

**Comment by kddude** [comment]
2. $100 on more photos

**Comment by mittonk** [comment]
Thanks all for the survey responses!  We'll use these to direct future development.
