### ISSUE TITLE
Yelp Fusion API Returning nothing for Netherlands

### ISSUE THREAD

**Issue by lmishra92** [Yelp/yelp-fusion#320]
I used the following python command 

python sample.py --term="bars" --location="Amsterdam, The Netherlands"

It shows me no businesses in Amsterdam. 

Does Yelp API not work for Europe ?

**Comment by tomelm** [comment]
What query are you sending? That's working for me.

**Comment by mittonk** [comment]
@lmishra92 : Can you copy-paste the output of the script?  In particular, I want to make sure it's not hitting a network or login-credentials error.

**Comment by lmishra92** [comment]
from __future__ import print_function

import argparse
import json
import pprint
import requests
import sys
import urllib


# This client code can run on Python 2.x or 3.x.  Your imports can be
# simpler if you only need one of those.
try:
    # For Python 3.0 and later
    from urllib.error import HTTPError
    from urllib.parse import quote
    from urllib.parse import urlencode
except ImportError:
    # Fall back to Python 2's urllib2 and urllib
    from urllib2 import HTTPError
    from urllib import quote
    from urllib import urlencode


# OAuth credential placeholders that must be filled in by users.
# You can find them on
# https://www.yelp.com/developers/v3/manage_app
CLIENT_ID = "ukcyuHNeV3xQjVM5JKVJYA"
CLIENT_SECRET = "M6UdSr8cSRBVimdM5M5iyBB35mY0FQwSKNjujSPszlEJbIvIwItAtLrJRq4en9Sg"


# API constants, you shouldn't have to change these.
API_HOST = 'https://api.yelp.com'
SEARCH_PATH = '/v3/businesses/search'
BUSINESS_PATH = '/v3/businesses/'  # Business ID will come after slash.
TOKEN_PATH = '/oauth2/token'
GRANT_TYPE = 'client_credentials'


# Defaults for our simple example.
DEFAULT_TERM = 'restaurants'
DEFAULT_LOCATION = 'Rotterdam, Zuid-Holland, The Netherlands'
SEARCH_LIMIT = 1000


def obtain_bearer_token(host, path):
    """Given a bearer token, send a GET request to the API.

    Args:
        host (str): The domain host of the API.
        path (str): The path of the API after the domain.
        url_params (dict): An optional set of query parameters in the request.

    Returns:
        str: OAuth bearer token, obtained using client_id and client_secret.

    Raises:
        HTTPError: An error occurs from the HTTP request.
    """
    url = '{0}{1}'.format(host, quote(path.encode('utf8')))
    assert CLIENT_ID, "Please supply your client_id."
    assert CLIENT_SECRET, "Please supply your client_secret."
    data = urlencode({
        'client_id': CLIENT_ID,
        'client_secret': CLIENT_SECRET,
        'grant_type': GRANT_TYPE,
    })
    headers = {
        'content-type': 'application/x-www-form-urlencoded',
    }
    response = requests.request('POST', url, data=data, headers=headers)
    bearer_token = response.json()['access_token']
    return bearer_token


def request(host, path, bearer_token, url_params=None):
    """Given a bearer token, send a GET request to the API.

    Args:
        host (str): The domain host of the API.
        path (str): The path of the API after the domain.
        bearer_token (str): OAuth bearer token, obtained using client_id and client_secret.
        url_params (dict): An optional set of query parameters in the request.

    Returns:
        dict: The JSON response from the request.

    Raises:
        HTTPError: An error occurs from the HTTP request.
    """
    url_params = url_params or {}
    url = '{0}{1}'.format(host, quote(path.encode('utf8')))
    headers = {
        'Authorization': 'Bearer %s' % bearer_token,
    }

    print(u'Querying {0} ...'.format(url))

    response = requests.request('GET', url, headers=headers, params=url_params)

    return response.json()


def search(bearer_token, term, location):
    """Query the Search API by a search term and location.

    Args:
        term (str): The search term passed to the API.
        location (str): The search location passed to the API.

    Returns:
        dict: The JSON response from the request.
    """

    url_params = {
        'term': term.replace(' ', '+'),
        'location': location.replace(' ', '+'),
        'limit': SEARCH_LIMIT
    }
    return request(API_HOST, SEARCH_PATH, bearer_token, url_params=url_params)


def get_business(bearer_token, business_id):
    """Query the Business API by a business ID.

    Args:
        business_id (str): The ID of the business to query.

    Returns:
        dict: The JSON response from the request.
    """
    business_path = BUSINESS_PATH + business_id

    return request(API_HOST, business_path, bearer_token)


def query_api(term, location):
    """Queries the API by the input values from the user.

    Args:
        term (str): The search term to query.
        location (str): The location of the business to query.
    """
    bearer_token = obtain_bearer_token(API_HOST, TOKEN_PATH)

    response = search(bearer_token, term, location)

    businesses = response.get('businesses')

    if not businesses:
        print(u'No businesses for {0} in {1} found.'.format(term, location))
        return

    business_id = businesses[0]['id']

    print(u'{0} businesses found, querying business info ' \
        'for the top result "{1}" ...'.format(
            len(businesses), business_id))
    response = get_business(bearer_token, business_id)

    print(u'Result for business "{0}" found:'.format(business_id))
    pprint.pprint(response, indent=2)


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('-q', '--term', dest='term', default=DEFAULT_TERM,
                        type=str, help='Search term (default: %(default)s)')
    parser.add_argument('-l', '--location', dest='location',
                        default=DEFAULT_LOCATION, type=str,
                        help='Search location (default: %(default)s)')

    input_values = parser.parse_args()

    try:
        query_api(input_values.term, input_values.location)
    except HTTPError as error:
        sys.exit(
            'Encountered HTTP error {0} on {1}:\n {2}\nAbort program.'.format(
                error.code,
                error.url,
                error.read(),
            )
        )


if __name__ == '__main__':
    main()

**Comment by lmishra92** [comment]
![capture](https://user-images.githubusercontent.com/16020551/32327662-a5c97c70-bfd7-11e7-8438-1dcdb2fac0a5.PNG)

**Comment by mittonk** [comment]
@lmishra92 : 
Great, I can see what's wrong.  

1. You've set LIMIT=1000 (trying to get 1000 businesses at once), but the limit is 50 in a chunk, 1000 overall.  The actual API response you're getting back behind the scenes is:
```
{
	"error": {
		"code": "VALIDATION_ERROR",
		"description": "The supplied limit: 1000 is invalid, the maximum is 50."
	}
}
```
Start with 50 businesses instead of 1000, and you'll get `boguette-rotterdam`, `picknick-rotterdam`, etc.

2. sample.py is hiding that helpful error message and saying "No businesses" instead --- that's a bug in our example, sorry for the confusion!  I've filed #321 to fix that.

3. Once you've got the first 50 businesses, try adding `offset=50` to the search arguments, then `offset=100`, etc to get more chunks-of-50-businesses.  You can find more details on `offset` on 
* https://www.yelp.com/developers/documentation/v3/business_search

4. Don't reveal your CLIENT_SECRET!  Once you've got things working, I'd suggest going to
* https://www.yelp.com/developers/v3/manage_app
and deleting your old (revealed) app credentials and creating some new (secret) ones.

Does that give you enough to work with?

**Comment by mittonk** [comment]
Actually, I've disabled your revealed app credentials --- please go to https://www.yelp.com/developers/v3/manage_app to delete your old app and create a new one.

**Comment by watterso** [comment]
Closed due to inactivity.
