### ISSUE TITLE
Response headers missing some values.

### ISSUE THREAD

**Issue by Mukolajko** [Yelp/yelp-fusion#322]
From this article 

https://www.yelp.com/developers/documentation/v3/rate_limiting

We should get this 3 headers on every response

RateLimit-DailyLimit: 25000
RateLimit-Remaining: 25000
RateLimit-ResetTime: 2017-09-07T00:00:00+00:00

But somehow they are missing.

I tried using bussiness and search endpoints.

![default](https://user-images.githubusercontent.com/6652438/32441517-b5ac2cf6-c300-11e7-8a26-f51a4070e5b3.png)

Maybe you just forget to include it on some endpoints? Or im missing something?

Thank you.

**Comment by mittonk** [comment]
@Mukolajko : Access counts are currently a beta (trial) feature --- but the documentation doesn't say that, that's a bug.

If you'd like to see access counts, you can opt into beta features at
* https://www.yelp.com/developers/v3/manage_app

**Comment by Mukolajko** [comment]
@mittonk Thank you for info.

**Comment by robertjkeck2** [comment]
@mittonk I am in the Developer Beta and still am not seeing access counts in the response header.  Have they been removed or changed?

**Comment by mittonk** [comment]
@robertjkeck2 :  Interesting.  What URL are you accessing, and what is your Client ID?  (Don't reveal your Client Secret.)

**Comment by robertjkeck2** [comment]
@mittonk did you change something? I'm now seeing it in the headers for /v3/businesses/search and /v3/businesses/ when I didn't yesterday...

**Comment by mittonk** [comment]
No changes from me --- if you trip across missing headers again, please put the details here so we can dig further!

**Comment by tomelm** [comment]
Docs updated, closing this now. If you experience other issues let us know!
