### ISSUE TITLE
Issue with location results

### ISSUE THREAD

**Issue by GhostViz** [Yelp/yelp-fusion#323]
Using the API with Ruby some results return "" and other instances of the same result type return nil...

For example:
`{"id"=>"la-paloma-taqueria-dallas-8", "name"=>"La Paloma Taqueria", "image_url"=>"https://s3-media1.fl.yelpcdn.com/bphoto/0M7_7KbbAIvc-kHo6WFZjA/o.jpg", "is_closed"=>false, "url"=>"https://www.yelp.com/biz/la-paloma-taqueria-dallas-8?adjust_creative=N7o2nZ8Xc5c4kunEsd8sHg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=N7o2nZ8Xc5c4kunEsd8sHg", "review_count"=>12, "categories"=>[{"alias"=>"mexican", "title"=>"Mexican"}], "rating"=>3.0, "coordinates"=>{"latitude"=>32.93907, "longitude"=>-96.76934}, "transactions"=>[], "price"=>"$", "location"=>{"address1"=>"14035 Coit Rd", "address2"=>nil, "address3"=>nil, "city"=>"Dallas", "zip_code"=>"75240", "country"=>"US", "state"=>"TX", "display_address"=>["14035 Coit Rd", "Dallas, TX 75240"]}, "phone"=>"+19729341175", "display_phone"=>"(972) 934-1175", "distance"=>2555.896173628}`

`{"id"=>"gorditas-los-comales-dallas", "name"=>"Gorditas Los Comales", "image_url"=>"https://s3-media2.fl.yelpcdn.com/bphoto/YY-3WntBzYwiNll1t5QVqw/o.jpg", "is_closed"=>false, "url"=>"https://www.yelp.com/biz/gorditas-los-comales-dallas?adjust_creative=N7o2nZ8Xc5c4kunEsd8sHg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=N7o2nZ8Xc5c4kunEsd8sHg", "review_count"=>69, "categories"=>[{"alias"=>"mexican", "title"=>"Mexican"}], "rating"=>3.5, "coordinates"=>{"latitude"=>32.9283288, "longitude"=>-96.8113901}, "transactions"=>["pickup"], "price"=>"$", "location"=>{"address1"=>"13247 Montfort Dr", "address2"=>"Ste 100", "address3"=>"", "city"=>"Dallas", "zip_code"=>"75240", "country"=>"US", "state"=>"TX", "display_address"=>["13247 Montfort Dr", "Ste 100", "Dallas, TX 75240"]}, "phone"=>"+19723852455", "display_phone"=>"(972) 385-2455", "distance"=>1541.466729236}`

**Comment by watterso** [comment]
Yup this is a case of a restaurant not having a value for `address2` and `address3` (the nil/null case) and one that has a value that happens to be an empty string.
