### ISSUE TITLE
Can we get all reviews for a business on yelp with api call, even if its a paid service?

### ISSUE THREAD

**Issue by snehaanand20** [Yelp/yelp-fusion#324]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(eg. feature request, bug, question, etc)_
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description
_(More detailed information explaining the problem, the expected results, the question, etc.)_

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
_(e.g. Fusion Search API)_

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by mittonk** [comment]
@snehaanand20 : You might have a look at https://www.yelp.com/knowledge ; it's not self-signup like Fusion, but might be what you're looking for.
