### ISSUE TITLE
Yelp universal link support

### ISSUE THREAD

**Issue by kerenk1** [Yelp/yelp-fusion#326]
Hi,

As Yelp intend to support universal links, I am very surprised to see that it's not working as expected.

When I redirect the users to the following url: https://www.yelp.com/search?start=0&find_desc=Restaurants&find_loc=San+Francisco,+CA&attrs=PlatformDelivery,RestaurantsPriceRange2.1&cflt=american&ytp_st=delivery_default

In case Yelp is installed, url doesn’t filter the results - since from the last week Yelp app asks for location permissions and in addition seem to ignore the location passed via the find_loc (while same link works perfectly on web browser). It does not display any results although app is given location permissions indicating I'm in SF.
Isn’t that universal link supports both mobile and web?? I’m confused.
I will much appreciate if you could share with me how I can get it to work.

Thanks a lot.

**Comment by mittonk** [comment]
@matthewkyelp , @SSheldon : Either of you want to jump in here?

**Comment by SSheldon** [comment]
Hey @kerenk1, I'm not able to reproduce the issue you're describing. As far as I know, the Yelp iOS app should handle these parameters when opening a search universal link.

What version of the app are you using in your testing? Could you provide a screenshot of what you are seeing when opening this link?
