### ISSUE TITLE
Timezone of event time provided in yelp V3  event search API

### ISSUE THREAD

**Issue by flash5** [Yelp/yelp-fusion#327]
## Description
_Hi, I am trying to integrate events obtained from yelp API v3 but there is a slight confusion. The event time given at the time_start and time_end nodes are different from what they're being displayed on yelp website. Also the document of V3 API doesn't provide any information regarding the timezone which makes it nearly impossible to get the correct time of any event. Any solution?_

## More information
_How will I convert the time I received in event V3 API to the actual event time_

### Endpoint
_https://api.yelp.com/v3/events_

{
	"events": [{
		"event_site_url": "https://www.yelp.com/events/london-the-european-information-security-summit-2017",
		"id": "london-the-european-information-security-summit-2017",
		"latitude": 51.5009690970451,
		"longitude": -0.119283199310303,
		"name": "The European Information Security Summit 2017",
		"time_end": "2018-02-23 02:30",
		"time_start": "2018-02-21 17:00"
	}]
}

Visit the URL at node event_site_url and compare the start and end date time of event on website and API

**Comment by mittonk** [comment]
https://www.yelp.com/events/london-the-european-information-security-summit-2017
shows
```
From: Wednesday, Feb 21, 9:00 am
To: Thursday, Feb 22, 6:30 pm
```

So, that's not ideal.

**Comment by flash5** [comment]
Hi @mittonk any update on this issue? Thank you.

**Comment by mittonk** [comment]
@flash5 : No updates yet --- still in our to-do list, we'll look into it.

**Comment by flash5** [comment]
@mittonk Okay Cool.

**Comment by aanjaria** [comment]
Hi @mittonk any updates/eta on this issue?

**Comment by dan98765** [comment]
Hi @aanjaria, an update here: the time_start and time_end for events in the response have been updated to be ISO 8601 format with timezone offset: "YYYY-MM-DDTHH:MM:SS+HH:MM". The +HH:MM at the end should indicate the timezone offset from GMT. Could you please check it out and see if it works like you expect?

Changelog entry for this change: https://www.yelp.com/developers/v3/changelog#changelog-20181129

**Comment by dan98765** [comment]
@aanjaria thanks for spotting that, it does look like a bug. It's ticketed internally and we'll try to fix it soon.
