### ISSUE TITLE
yelp fusion fails to return these restaurants

### ISSUE THREAD

**Issue by sulphide0** [Yelp/yelp-fusion#329]
## Overview
when we query 'pastis' and 'podunk' in new york city, they aren't returned even though they are on the yelp website

https://www.yelp.com/biz/pastis-new-york
https://www.yelp.com/biz/podunk-new-york-2

e.g.
curl --request GET \
  --url 'https://api.yelp.com/v3/businesses/search?location=New%20York%20City&term=podunk' \
  --header 'authorization: Bearer some-token' \
  --header 'cache-control: no-cache' \

by the way, we are trying to find closed restaurants.

**Comment by mittonk** [comment]
1. These restaurants have been closed long enough that they don't show up in search, either on Fusion or www.yelp.com: https://www.yelp.com/search?find_desc=pastis&find_loc=9th+ave%2C+new+york

Using the ID, you can look them up with the Fusion API:
* https://api.yelp.com/v3/businesses/pastis-new-york
```
{
	"id": "pastis-new-york",
	"name": "Pastis",
	"image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/O-DYZG2kzjUDSQquM1DIXQ/o.jpg",
	"is_claimed": false,
	"is_closed": true,
```

2. Why are you trying to find closed businesses --- how does your use case compare to #249?

**Comment by sulphide0** [comment]
i'm not sure that we can know the id ahead of time (or am i missing something?).

i also posted on 249 which is the same use case.

**Comment by sulphide0** [comment]
how long after a business is assigned the closed status will it disappear from the api?

**Comment by sulphide0** [comment]
thanks for the response, by the way.

**Comment by mittonk** [comment]
The ID for https://www.yelp.com/biz/pastis-new-york is `pastis-new-york` --- how did you find that business page in the first place?  Google search results or some local data set?

For how long a closed business stays in search results (both for www and the Fusion API):
* https://www.yelp-support.com/article/Why-do-businesses-that-are-permanently-closed-sometimes-still-appear-in-Yelp-search-results?l=en_US
There are a few factors, but it's usually months-to-a-year.

Sounds like the core issue here is really the same as #249 , we can continue discussing there.

**Comment by sulphide0** [comment]
i found it by searching in google. but our programmatic stuff only uses yelp apis.

**Comment by anamariakantar** [comment]
Hey guys,

Do you know if there is a way to find out when the business was marked as closed?

**Comment by watterso** [comment]
@anamariakantar we don't and nor do have plans to surface this data in the api. In fact this data isn't even available on the Yelp website or mobile apps.
