### ISSUE TITLE
When will API v3 be ready for production use of developers apps?

### ISSUE THREAD

**Issue by sp00m** [Yelp/yelp-fusion#33]
Following https://github.com/Yelp/yelp-api-v3/blob/master/docs/others/faq.md#is-api-v3-ready-for-production-use-of-my-app, when are you roughly planning to make API v3 ready for production use of developers app? It would be great if I could have an estimation, so that I can try to make my app's development schedule suit yours ;) Of course, no pressure though!

**Comment by Wirwing** [comment]
Any ETA, guys? We are a little bit worried about the reviews endpoint data changing in a future.

**Comment by guangyang** [comment]
Totally understand the concern. We are in the middle of refining the API based on feedback and close a few loose ends. Hopefully we'll get to GA soon. Stay tuned!

**Comment by mittonk** [comment]
Yelp Fusion is now released and generally available.

There will be more changes in the future, as with any API --- but we'll now communicate breaking changes at a production level.
