### ISSUE TITLE
Business search returns "Invalid price filter provided" when price is added to the query string

### ISSUE THREAD

**Issue by aaduru** [Yelp/yelp-fusion#331]
## Overview
- **Client ID:** -qWaHcsd1FNhDOLm5IG1zw
- **Issue type:** "VALIDATION_ERROR", "Invalid price filter provided"
- **Summary:** when i pass value for the price in query string as '$' I am getting "Invalid price filter provided" error.
- **Platform:** Postman

## Description
_I was trying to make a get request using Postman. I have followed the documentation provided by Yelp. 'https://www.yelp.com/developers/documentation/v3/business_search'. I am able to view data when I pass location , term , distance as part of query string.

### Endpoint
_https://api.yelp.com/v3/businesses/search

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/search?term=restaurants&location=37.786882,-122.399972&distance=5000.000&price=$

### Response
{
    "error": {
        "code": "VALIDATION_ERROR",
        "description": "Invalid price filter provided"
    }
}

**Comment by mittonk** [comment]
The `price` argument takes a number --- for one-dollar-sign businesses, use `price=1`.
* https://www.yelp.com/developers/documentation/v3/business_search

Sounds like you figured it out!
