### ISSUE TITLE
More Business Info --> Where is that?

### ISSUE THREAD

**Issue by fxfitz** [Yelp/yelp-fusion#332]
## Overview
- **Client ID:** R_01b9zOnzijqVFHtYBPug
- **Issue type:** Question
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** REST/GraphQL API

## Description
When using yelp.com and viewing a business, there's "More Business Info" on the right which displays whether or not the location offers Wi-Fi.  Since the website does not allow me to filter by businesses that do or do not have Wi-Fi, I was hoping to use the API to pull that information, but I can't seem to find which endpoint houses this data.

Is this data just not available via the API? If not, is there any plans on adding an endpoint for it (either REST or GraphQL would be fine for me)?

Thanks! :-)

## More information
N/A

### Endpoint
N/A

### Parameters or Sample Request
N/A

### Response
N/A

## Extra information
N/A

**Comment by fxfitz** [comment]
Bump...

**Comment by mittonk** [comment]
@fxfitz : Wi-Fi data for individual businesses isn't part of the self-serve Fusion package --- though your use case might be a good match for Premium Access:
* https://www.yelp.com/fusion , click "Premium Access" and pitch your idea.

We don't yet have search-for-businesses-with-wifi as part of the Fusion API.

Does that give you something to work with?

**Comment by fxfitz** [comment]
@mittonk Well, I've submitted a request at the Premium Access link, but just waiting to hear back for now.

Sadly since it's not available now for the API, I'm guessing there's no real way for you (or me, I don't mind contributing!) to add an endpoint/resource? Or a graphQL query?

I'm don't want to revert to Selenium (and I doubt that's even allowed by Yelp's TOS) or something; I'd rather do it the right way. :-/

I'm surprised this information isn't returned as part of the Business API.

**Comment by nguyen-dinh-dh** [comment]
Hello, are there any news for this ticket? It'd be nice to have all the "Business Info" in Yelp Fusion API too, like "Delivery", "Take-out", "Takes Reservations"

**Comment by Hsanka6** [comment]
Did you hear back yet? @fxfitz

**Comment by fxfitz** [comment]
@Hsanka6 Negative; I put in the request and never heard back anything.

**Comment by watterso** [comment]
Hey everyone,
Access to the Wifi business attribute and being able to filter on the wifi attribute on the search endpoint remain unchanged, as in they remain not available to the general public. Despite the unchanged status of this specific attribute, we have recently added two more attributes for filtering on [the search endpoint](https://www.yelp.com/developers/documentation/v3/business_search) available to any Yelp Fusion developer!

The process to request access to more attributes or searching ability has changed in look, but not spirit. The page with details is now the [fusion VIP page](https://www.yelp.com/fusion/vip), which links to a new, more detailed [application page](https://www.yelp.com/fusion/vip/apply). Obviously spamming this page won't get you a higher chance of approval, but in your case @fxfitz, I would recommend resubmitting now that our form lets you describe your use case in more detail. For the rest of you, please feel free to also apply.
