### ISSUE TITLE
Category Names for all Locales

### ISSUE THREAD

**Issue by clarkpd** [Yelp/yelp-fusion#333]
## Description
Category Names in different languages. You have the categories listed at https://www.yelp.com/developers/documentation/v3/all_category_list/categories.json including their en_US name. Is there a way to get the names of each category in each locale (preferably in Json files)?

**Comment by mittonk** [comment]
@clarkpd : We don't have JSON-formatted versions of the other languages --- that's a good idea, marking this as an enhancement.

For now, we do have human-readable forms --- use "All" dropdown in the upper right of
* https://www.yelp.fr/developers/documentation/v3/all_category_list
to get to language-specific pages like
* https://www.yelp.fr/developers/documentation/v3/category_list  (note yelp.fr for France / French).

**Comment by dan98765** [comment]
@clarkpd we've just recently released new beta program endpoints for getting categories with localized (translated) names by locale. Please check out https://www.yelp.com/developers/documentation/v3/all_categories and play around with it to see if it fits your needs. As it is an early beta endpoint, expect that there may be some changes to it before it is taken out of beta. We appreciate any github issues for bugs/suggestions on it.
