### ISSUE TITLE
Replacing "client secret" with "api key"?

### ISSUE THREAD

**Issue by topspinj** [Yelp/yelp-fusion#335]
## Overview
- **Client ID:** _XPnwvakf-h8eQDoeu2zDHQ_
- **Issue type:** _API Key vs Client Secret?_
- **Summary:** Which key should we use with Yelp Fusion API? 

## Description
I've misplaced my client secret and tried retrieving it under **Manage App**. Couldn't find my client secret but did find my API key which according to Yelp Fusion's site, is the new standard key that we should be using in lieu of client secret: **"Looking for your client secret? The Fusion API now uses API Keys to authenticate requests."**

However, the API key didn't work with my code - said there was an error with "access token".

I miraculously was able to retrieve my client secret locally, and noticed that it was different from the API key. My client secret worked to authenticate requests, but my API key did not. If API keys are the new standard, how do we use them for authentication? For future reference, is there a way to retrieve our `client secret` on Yelp Fusion's site? 

### Endpoint
Fusion Search API

### Parameters or Sample Request

setting client_secret = API_key

### Response
```
Traceback (most recent call last):
  File "get_reviews.py", line 264, in <module>
    main()
  File "get_reviews.py", line 252, in main
    query_api(term, location, file_name)
  File "get_reviews.py", line 160, in query_api
    bearer_token = obtain_bearer_token(API_HOST, TOKEN_PATH)
  File "get_reviews.py", line 89, in obtain_bearer_token
    bearer_token = response.json()['access_token']
KeyError: 'access_token'
```

**Comment by tomelm** [comment]
Hey @topspinj! The API key is not a drop-in replacement for the client secret. With the API key, you no longer need to make a request into the token endpoint to get an access token. Before, the flow was:
1. make request to token endpoint with client id and client secret, get access token
2. put access token into header (`Authorization: Bearer <ACCESS TOKEN>`), make api requests

Now, the process is
1. put api key into header (`Authorization: Bearer <ACCESS TOKEN>`), make api requests

Your new api key never expires so you do not need to programmatically generate one. Let me know if you have any more questions

**Comment by topspinj** [comment]
Thanks for the update @tomelm - does this mean that client secrets are now deprecated? If so, perhaps we could update the docs & sample code in this repo to reflect the change.

**Comment by tomelm** [comment]
@topspinj yep, they're deprecated. They'll still work for a few more months. We've updated the docs on the site: https://www.yelp.com/developers/documentation/v3/authentication

We're working on updating the code samples here too!

**Comment by karishmavanjani** [comment]
Thank you so much for this! I'm new to the whole environment and all help docs on the internet asked me to put in my client_secret.
