### ISSUE TITLE
fetching more than 3 reviews, order by date, et al?

### ISSUE THREAD

**Issue by ryanckulp** [Yelp/yelp-fusion#338]
## Overview

we help businesses show of customer testimonials / merchant reviews on their website. currently integrated with many review providers, ie Google Places, Trustpilot, Yotpo, etc. 

## Description

requesting the ability to fetch more than 3 reviews from a Yelp business, or at least, fetch the **most recent 3** vs apparent "top recommended," so we can build a Yelp integration for mutual customers.

### Endpoint

https://www.yelp.com/developers/documentation/v3/business_reviews

### Parameters or Sample Request

```ruby
require 'httparty'
require 'json'

headers = {'Authorization' => 'Bearer XXXXXXXX'}
resp = HTTParty.get("https://api.yelp.com/v3/businesses/sole-foot-spa-austin/reviews", headers: headers)

reviews = JSON.parse(resp.body)['reviews']

reviews.each do |review|
  # need more than 3 arbitrary (not ordered) reviews here!
end
```

## Extra information

please let me know! we have several mutual customers asking for an integration... would be painless to build, just need the Endpoint to be... useful.

**Comment by romful** [comment]
Will be very nice to fix this and be able to show x reviews. Waiting for the enhancement.

**Comment by quytennis** [comment]
@ryanckulp We don't allow retrieval of more than 3 reviews in the Fusion API. If we offered an "order by date" option, developers could get more than 3 reviews over time which is less concerning than the current "order by Yelp Sort" which doesn't change very much.  If you would like to retrieve more than 3 reviews, please check out our [Yelp Knowledge program](https://www.yelp.com/knowledge)
