### ISSUE TITLE
Response data contains businesses with wrong zip code.

### ISSUE THREAD

**Issue by Goal1488** [Yelp/yelp-fusion#339]
## Overview
- **Issue type:** _Bug_
- **Summary:** _Response data contains businesses with wrong zip code_

## Description
_
Hi guys, hope you doing well!
I have an issue, trying to get a businesses list from api by zip code, got wrong response data, could you help me please!
_

## More information
_
Response data contains businesses with wrong zip code 
I'm trying to get restaurants with zip - 88417, but response contains restaurants with zip - 88435
_

### Endpoint
_(e.g. Fusion Search API)_

### Parameters or Sample Request
GraphQL query
```
{
  {
  search(location: "88417", term: "restaurant") {
    total
    business {
      name
      location {
        city
        zip_code
      }
    }
  }
}

```

### Response
```
{
  "data": {
    "search": {
      "total": 21,
      "business": [
        {
          "name": "Lake City Diner",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Annie's Restaurant",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Silver Moon Cafe",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Santa Fe Grille",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Comet II Drive In & Restaurant",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Route 66 Restaurant",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Sun & Sand Restaurant",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Diego's Pizza",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Joseph's Bar & Grill",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "SunSpot Cafe",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Joseph's Bar & Grill",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Subway",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Dairy Queen",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "McDonald's",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Carls Jr",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Popeyes Louisiana Kitchen",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Dairy Queen of Santa Rosa",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Carl's Jr.",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Country Pride Restaurant",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        },
        {
          "name": "Jenny's Denny's",
          "location": {
            "city": "Santa Rosa",
            "zip_code": "88435"
          }
        }
      ]
    }
  }
}

```

## Extra information
_Have a good day!_

**Comment by mittonk** [comment]
@Goal1488 : Looks like those are neighboring zip codes, and Santa Rosa (population 2800) has a lot more popular businesses than Newkirk (pop 7).

You could try setting smaller `radius`, but I suspect you'll end up with fewer and fewer businesses.  These search results basically mean "If you're in Newkirk and want a restaurant, we suggest driving over to Santa Rosa where there are good restaurants" --- and that seems pretty reasonable.

Have a look at the map view on
* https://www.yelp.com/search?find_desc=Restaurants&find_loc=88417

Zooming in (basically reducing `radius`) shows no restaurants around Newkirk and Cuervo:
* https://www.yelp.com/search?find_desc=Restaurants&find_loc=88417&start=0&l=g:-104.31189367465822,35.12652718677366,-104.52750036411135,34.986007249976026

Does that make sense?

**Comment by Goal1488** [comment]
Thanks for your reply!
Recently i've searched for:
parameters: **term=restaurants&latitude=36.13&longitude=-115.17&radius=3000**
And i've got result with:
Longitude: -115.2053274	
Latitude: 35.9987549	

![image](https://user-images.githubusercontent.com/9929577/34520622-17201cd6-f092-11e7-8595-9d56ff65bcc1.png)

as i see the distance between **89109** zip and the **Inca Vs Azteca** restaurant is ~ 13 km

**Comment by Goal1488** [comment]
Okay, another kind of issue,
lat long: **36.212935997511, -114.986646183705**
radius: **20 000**
![image](https://user-images.githubusercontent.com/9929577/34538567-8dc49770-f0d5-11e7-99e7-56243fcf8507.png)
why those items are not in response? they are in discoverable radius?!
