### ISSUE TITLE
Error happens when limit is too large

### ISSUE THREAD

**Issue by enwei-canonical** [Yelp/yelp-fusion#34]
curl --get --include 'https://api.yelp.com/v3/businesses/search?categories=casinos&latitude=37.7869&limit=100&locale=en_US&longitude=-122.4000&offset=0' -H 'Authorization:Bearer xxxxx'
HTTP/1.1 400 Bad Request
Date: Tue, 16 Aug 2016 01:42:03 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 93
Connection: keep-alive
Set-Cookie: __cfduid=dac5045b471419558a956fb6e52668b201471311722; expires=Wed, 16-Aug-17 01:42:02 GMT; path=/; domain=.yelp.com; HttpOnly
X-Proxied: 10-64-16-56-uswest1bprod
Server: cloudflare-nginx
CF-RAY: 2d312ff90c5e45e4-TPE

{"error": {"code": "VALIDATION_ERROR", "description": "The supplied limit: 100 is invalid."}}

In V2, there is no such error, just returns all the items. In addition, there is no API to get the count of the result.
If I set limit=10, 2 items will return, so the count of the result is 2. But why error happens when limit=100 or 300?
Thanks.

**Comment by guangyang** [comment]
Hi, the maximum value for limit is 50. I've updated the documentation at https://github.com/Yelp/yelp-api-v3/blob/master/docs/api-references/businesses-search.md. Granted that we should make the error message better to inform you that 50 is the maximum.

**Comment by enwei-canonical** [comment]
Got it and thanks so much.

**Comment by mittonk** [comment]
Added more verbose error message:
```
https://api.yelp.com/v3/businesses/search?term=pizza&location=manhattan&limit=52

{
  "error": {
    "description": "The supplied limit: 52 is invalid, the maximum is 50.",
    "code": "VALIDATION_ERROR"
  }
}
```
