### ISSUE TITLE
GraphQL fragments in queries suddenly stop being supported

### ISSUE THREAD

**Issue by Ystyr** [Yelp/yelp-fusion#342]
## Overview
- **Client ID:** DjO41dTl0TNigv7pQMFX0A
- **Issue type:** bug
- **Summary:** The day before yesterday, GraphQL queries in our app suddenly stop working.
- **Platform:** Desktop/web

## Description
The problem can be reproduced in https://www.yelp.com/developers/ GraphQL console.

## More information
Queries without a usage of fragments are working correctly. 

### Endpoint
_(e.g. Fusion Search API)_

### Parameters or Sample Request
_{
    b1: business(id: "yelp-san-francisco") {
        **...basicBizInfo**
    }
    b2: business(id: "garaje-san-francisco") {
        **...basicBizInfo**
    }
}_

_**fragment basicBizInfo on Business** {
    name
    id
    rating
    review_count
    photos
}_

### Response
{
  "errors": [
    {
      "message": "'FragmentSpread' object has no attribute 'selection_set'",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ]
    },
    {
      "message": "'FragmentSpread' object has no attribute 'selection_set'",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
    }
  ],
  "data": {
    "b1": null,
    "b2": null
  }
}

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by PhilippeRiegert** [comment]
I'm receiving the exact same error message: `'FragmentSpread' object has no attribute 'selection_set'` 😢 

Let me know if I can help or if you need more information.

#### My query : 

    query List($latitude: Float, $longitude: Float) {
        search(latitude: $latitude, longitude: $longitude, categories: "beer_and_wine") {
            total
            business {
                ...BusinessDetails
            }
        }
    }

    fragment BusinessDetails on Business {
        id
        name
        phone
        display_phone
        photos
        price
        rating
        coordinates {
            latitude
            longitude
        }
    	hours {
    		is_open_now
    		open {
    			end
    			start
    			day
    		}
    	}
        location {
            formatted_address
        }
    }

**Comment by Ystyr** [comment]
Thank you, Philippe!
For now, I've just got rid of fragments in queries, so it works, just wanted to report the issue.

**Comment by mittonk** [comment]
@Ystyr , @PhilippeRiegert : That's definitely a bug --- thanks for the report, we'll get on it!

**Comment by tomelm** [comment]
Apologies for the delay on this -- I pushed a fix out, this should be resolved now!

**Comment by PhilippeRiegert** [comment]
The fix is working for me, thanks @tomelm !
