### ISSUE TITLE
New Authentication: What are key and values for headers in new authentication where there is no need for Oauth. In the document, there seesm to be two explanation for the value, one is "Bearer <Your API KEY> and other is "Aothorization: Bearer <Your API KEY>". As a begginer of Python programming, I tried to access the data base using req.add_header("Autorization", header) 

### ISSUE THREAD

**Issue by kimai007** [Yelp/yelp-fusion#343]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(eg. feature request, bug, question, etc)_
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description
_(More detailed information explaining the problem, the expected results, the question, etc.)_

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
_(e.g. Fusion Search API)_

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by kimai007** [comment]
I could find Python sample program in GitHub corresponding to "New Authentication".

**Comment by tomelm** [comment]
@kimai007 could you update the description with your title? It's a little hard to read as-is.

Are you specifically asking what header values you need for the new auth? If so, we do describe that in the authentication page: https://www.yelp.com/developers/documentation/v3/authentication

The header needs to be "Authorization: Bearer <YOUR_API_KEY>"

**Comment by kimai007** [comment]
Thank you for your help. The issue is resolved by referencing sample Python codes.

Kiyotaka Imai

2018/01/09 3:00、Tomer Elmalem <notifications@github.com>のメール:
