### ISSUE TITLE
Question: new error code: 'TOO_MANY_REQUESTS_PER_SECOND' 

### ISSUE THREAD

**Issue by ZerocksX** [Yelp/yelp-fusion#348]
## Overview
- **Client ID:** ip9RhUfCdeIaiXjHjtIMyg
- **Issue type:** question
- **Summary:**  'TOO_MANY_REQUESTS_PER_SECOND' but speed is the same as before
- **Platform:** Web

## Description
I was collecting information about coffee shops around a chosen location to compare them and analyse neighbouring shops. For last couple of weeks I was collecting data without any issues. I rarely overstepped daily request limit, but because I needed to compare a lot of data really fast I had to use multiple parallel connections. I was making about 5 requests per second. Last week I started getting error message 'TOO_MANY_REQUESTS_PER_SECOND' and i can not get more than 1-2 requests per second. My code or internet speed has not changed. Could you tell me if this is an intended change?Also if it is is it a temporary change or a permanent one because I can not see any mention of it in Changelog or in Terms of Use?

## More information
full error is:
{'error': {'code': 'TOO_MANY_REQUESTS_PER_SECOND', 'description': 'You have exceeded the queries-per-second limit for this endpoint. Try reducing the rate at which you make queries.'}}

### Endpoint
/v3/businesses/search

### Response
```
{
'error': 
    {
        'code': 'TOO_MANY_REQUESTS_PER_SECOND',
        'description': 'You have exceeded the queries-per-second limit for this endpoint. Try reducing the 
        rate at which you make queries.'
    }
}
```

**Comment by xtremeactor** [comment]
Were you able to solve this? I'm having the same issue

**Comment by ZerocksX** [comment]
Sadly, no. I just slowed down to get any results.

On 23 Jan 2018 20:09, "xtremeactor" <notifications@github.com> wrote:

Were you able to solve this? I'm having the same issue

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Yelp/yelp-fusion/issues/348#issuecomment-359896859>,
or mute
the thread

**Comment by xtremeactor** [comment]
Any ideas for how to slow down? I can't seem to get the error to go away

**Comment by mjuraj** [comment]
I have the same problem. It's a pretty big problem, because I have to make more requests if we take into account that businesses count isn't correct in some cases.

**Comment by dlgallagher** [comment]
There are a number of ways to slow down the rate of your requests; the exact syntax will depend on what platform or programming language you're working in. 

A simple pseudocode example if you were making requests to the business endpoint:
```
for loop over each yelp business you are interested in
    make api request to get business data for business
    sleep for N milliseconds
```
You could then adjust how many N milliseconds is until you get no more TOO_MANY_REQUESTS_PER_SECOND errors. Another idea:
```
for loop over each yelp business you are interested in
    make api request to get business data for business
    if you get back a TOO_MANY_REQUESTS_PER_SECOND error:
        sleep for 1 second
        retry making api request to get business data for business
```
These are just some ideas. Someone could also make the if statement in the pseudocode above a while loop, etc etc.

**Comment by dan98765** [comment]
Examples of the errors when the quota is exceeded have been added to https://www.yelp.com/developers/documentation/v3/rate_limiting

Changelog entry: https://www.yelp.com/developers/v3/changelog#changelog-20180305
