### ISSUE TITLE
Possible to get the cropped version of users' image?

### ISSUE THREAD

**Issue by raajtram** [Yelp/yelp-fusion#350]
## Overview
- **Client ID:** WZHJHUiM2BkG18Vms9kE0w
- **Issue type:** question
- **Summary:** Is it possible to get the cropped version of users' image?
- **Platform:** Desktop

## Description
I'm using the Reviews API to fetch reviews for a particular business. I'm fetching the reviews[x].user.image_url, but it's returning the full size image that the users (must have) uploaded to their profile. This is clearly a performance issue.

Yelp displays cropped avatars next to each user's review. Is it possible to fetch that cropped image instead of the original image?

### Endpoint
Fusion Reviews API

**Comment by virgytam** [comment]
Hi Raaj, I'm assuming you want a smaller resolution image rather than the full sized. We currently have no plans to return a smaller resolution user image.

**Comment by waleedmazhar** [comment]
along with that you can use 60s.jpg and 300s.jpg
