### ISSUE TITLE
GraphQL: Too big `limit` fails requests

### ISSUE THREAD

**Issue by vhung92** [Yelp/yelp-fusion#352]
## Overview
- **Component:** GraphQL
- **Client ID:** _g_X3su0EbC39youW4PKJ_g_
- **Issue type:** _bug_
- **Summary:** _Using `limit: 1000` results in errors_
- **Platform:** _Mac OS X_

## Description
I'm trying to find out the name of the restaurants around Stockholm. The returned response results in lots of errors. (it works if I lower the limit to `~700`, haven't tried to find the exact limit it breaks at).

### Endpoint
https://api.yelp.com/v3/graphql

### Parameters or Sample Request
```
{
    search(categories: "restaurants",
            location: "stockholm",
            limit: 1000) {
        total
        business {
            name
        }
    }
}
```

### Response
```
{
    "errors": [
        {
            "message": "Data loader batch_load_fn function raised an Exception: HTTPURITooLong()",
            "locations": [
                {
                    "line": 6,
                    "column": 9
                }
            ]
        },
        ....
    ],
    "data": {
        "search": {
            "total": 5527,
            "business": [
                null,
                null,
                ...
            ]
        }
    }
}
```

## Extra information
Seems like setting the limit/offset to negative numbers returns `INTERNAL_ERROR` at least from the GraphQL API as well.

## Extra question
Also I'm wondering why there is a hard limit on `limit+offset <= 1000`. In my use case I would like to paginate through all the results in order to compile a complete list of results, not just the 1000 first search hits. Is there any way of doing this at the moment?

**Comment by teekwak** [comment]
Hi @vhung92, 

Currently the limit maximum you should be using on your GraphQL queries is 50 as described in https://www.yelp.com/developers/graphql/query/search .

For your extra question, there is currently no way of doing your complete list of results.
