### ISSUE TITLE
Yelp personal bookmark data

### ISSUE THREAD

**Issue by vish2398** [Yelp/yelp-fusion#354]
I was wondering if there is a way to access my personal bookmarks and notes via the API? When I use the Yelp mobile app or website, I use the bookmark feature quite extensively.  I would love to be able to access this data from the API.  From looking at the docs, I do not see a way to get this data.  Could this be added to the feature request list?

**Comment by virgytam** [comment]
Hi there! We currently don't have a way to retrieve your personal bookmarks, but it's definitely something worth considering in the future. Marking this as an enhancement.

**Comment by dgirvine8** [comment]
Virgytam, is there any timeframe for adding this enhancement at this point? It would be very useful!

**Comment by dsposito** [comment]
Agreed, would love to see this feature soon! Any rough ETA?

**Comment by watterso** [comment]
Hi everyone, unfortunately we cannot share engineering prioritization or timelines, but this idea is indeed tracked internally!

**Comment by logicxd** [comment]
Bump. Even if it's not for private bookmark (Collection), it'd be nice to grab public bookmarks.

**Comment by mary-vo** [comment]
Need this feature too. Thank you.

**Comment by aconstas** [comment]
Curious about this feature as well
