### ISSUE TITLE
API currently down?

### ISSUE THREAD

**Issue by zackyangzinc** [Yelp/yelp-fusion#356]
Please confirm your API is currently down?
{
"error": {
"code": "REQUEST_TIMED_OUT",
"description": "The request timed out, please try again later. If this continues, please create an issue on GitHub with the request you're making: https://github.com/Yelp/yelp-fusion/issues"
}
}

## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(eg. feature request, bug, question, etc)_
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description
_(More detailed information explaining the problem, the expected results, the question, etc.)_

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
_(e.g. Fusion Search API)_

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by dlgallagher** [comment]
Hi @zackyangzinc, thanks for the report. We are experiencing a partial outage of the API at this time; our team is working on resolving the issue. I'll update again when we're recovered.

**Comment by dlgallagher** [comment]
Service has been fully restored.
