### ISSUE TITLE
REQUEST_TIMED_OUT

### ISSUE THREAD

**Issue by JoMo1970** [Yelp/yelp-fusion#357]
## Overview
- **Client ID:** a5IIvWBoQzeJapqnFDyllw
- **Issue type:** Requests timing out
- **Summary:** Since yesterday, all requests are timing out. 
- **Platform:** Fusion API

## Description
Since yesterday, all of my requests to the Yelp api are timing out.

## More information
N/A

### Endpoint
https://api.yelp.com/v3/businesses/search

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/search?term=Mamma Mia Italian Grill & Pizza&location=Fort Worth TX

### Response
{
    "error": {
        "code": "REQUEST_TIMED_OUT",
        "description": "The request timed out, please try again later. If this continues, please create an issue on GitHub with the request you're making: https://github.com/Yelp/yelp-fusion/issues"
    }
}

**Comment by dlgallagher** [comment]
Hi @JoMo1970, thanks for the report. We are experiencing a partial outage of the API at this time; our team is working on resolving the issue. I'll update again when we're recovered.

**Comment by dlgallagher** [comment]
Service has been fully restored.

**Comment by JoMo1970** [comment]
Thanks for the help on this, Dan. Much appreciated.
