### ISSUE TITLE
Question: Return Business Responses in Reviews API Response

### ISSUE THREAD

**Issue by cgalaiya** [Yelp/yelp-fusion#358]
Is it possible for the Fusion API to return whether a business has responded to a review and what the business owner's response was to said review?

**Comment by quytennis** [comment]
Chiraag,

The Fusion API doesn't support for review responses but it is on our roadmap. This support will only be available to [Yelp Advertising partners](https://www.yelp.com/adpartners) so please sign up to become a partner for you haven't done so already.

Thanks,
Quy

**Comment by enyernave** [comment]
@quytennis has this changed at all in the last 4.5 years? Is review response still available to only Advertising Partners? Or is it open to all of the Fusion API developers now?
