### ISSUE TITLE
Question: calls per request 

### ISSUE THREAD

**Issue by simanthastew** [Yelp/yelp-fusion#359]
## Overview
- **Client ID:** uSFRYWtEn-iIVmjtbM_DWQ
- **Issue type:** question
- **Summary:** How many calls does one request count for?
- **Platform:** Desktop/web

## Description
We're experiencing a decrease in Yelp results in our search engine. We have seen an increase in searches completed, but nowhere near the 25,000 rate limit per 24 hours. On the high end, around 300 requests are being made to the API per day. Does each request only count as one call? Additionally, we have not yet upgraded to v3/updated our authentication process (currently using OAuth1). Is it possible for that to cause issues in our requests even though the token endpoint has not been fully deprecated yet?

### Endpoint
api.yelp.com/v2/search
api.yelp.com/v2/business
api.yelp.com/v2/phone_search

**Comment by virgytam** [comment]
Hi Samantha! By "decrease in Yelp results", do you mean decrease in successful responses from the Yelp API or a decrease in the number of businesses returned in a search request? 

the 25,000 per day limit is per request, so when you hit api.yelp.com/v2/search, that counts as just 1. 

I'm assuming that the token endpoint that you're referencing is the one announced here: https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going which is actually only for the v3 API, so v2 is not affected by this. That being said, we are deprecating the v2 API by this summer so we do recommend developers migrate to v3 ASAP.

**Comment by simanthastew** [comment]
Thank you!
