### ISSUE TITLE
is there anything that documents what errors may be returned by yelp apis?

### ISSUE THREAD

**Issue by sulphide0** [Yelp/yelp-fusion#362]
I can't find any documentation about that. I.e. what will the response look like for a request that has exceeded the daily quota?

**Comment by sulphide0** [comment]
anyone?

**Comment by dlgallagher** [comment]
Thanks for the good question, @sulphide0.

I think our documentation could be improved around errors. Specifically for exceeding the daily quota, it seems like https://www.yelp.com/developers/documentation/v3/rate_limiting should have an example of what that error would look like. I'll file a ticket internally and add that in.

**Comment by dan98765** [comment]
Examples of the errors when the quota is exceeded have been added to https://www.yelp.com/developers/documentation/v3/rate_limiting

Changelog entry: https://www.yelp.com/developers/v3/changelog#changelog-20180305
