### ISSUE TITLE
API returns only some closed businesses

### ISSUE THREAD

**Issue by anamariakantar** [Yelp/yelp-fusion#364]
Hi there,

Hopefully I am not double posting this issue - I had a read through existing ones and I think this is a bit different. I have successfully found some businesses that are marked as closed, however, I cannot find others. My logic is search by company and location in the first step, if no results then try by phone number. If businesses are found. pick up the top 1 query result.
So, when I search for this business: Chiefs Family Diner, 1200 Buchanan St Nashville, 615-953-2474 - I get different business names in both cases (and Chief Family Diner is not in any of the lists). I can see the place marked as closed on Yelp: https://www.yelp.com/search?find_desc=Chiefs+Family+Diner&find_loc=1200+Buchanan+St,+Nashville,+TN

But when I search for this closed business: DAIQS DAIQUIRI BAR AND GRILL, 2209 Murfreesboro Pike Nashville, 615-651-8064 - I can find the business, with the closed flag, when I search by phone
https://www.yelp.com/search?find_desc=Daiq%27s+Bar+and+Grill&find_loc=Nashville,+TN

Can someone help me out with this? Is there a better way to do it? Finding the business and the closed flag are the most important elements of my application.

Many thanks!!
Ana

**Comment by watterso** [comment]
Hey @anamariakantar,
As mentioned in #249 searching for closed businesses isn't a use case we actively support. @mittonk 
 describes in #329 that businesses can show up in search results 'months-to-a-year' after they close, this explains why you might be seeing different behavior between different businesses.

**Comment by anamariakantar** [comment]
@watterso many thanks for clarifying this. Seems like my issue is related to those 2, I read through them and thought it is something else - sorry about it.  I will ask my questions in #329 instead.
