### ISSUE TITLE
Different API results at points in time

### ISSUE THREAD

**Issue by anamariakantar** [Yelp/yelp-fusion#368]
I ran the query on several businesses a few days ago, and while at the point I got no results for some, checking them now, the API is returning results.
For example: https://api.yelp.com/v3/businesses/search?term=Booddumak&location=822 N Rolling Rd Catonsville
or
https://api.yelp.com/v3/businesses/search?term=New York Fried Chicken&location=4700 Liberty Heights Ave Gwynn Oak

Other results work fine, so I don't think there's an error in my code (as the same script now returns the results!). What would be the possible causes for the APIs returning different results at points in time?

Thanks!
Ana

**Comment by butterfield** [comment]
Not sure what happened with these two businesses in particular, but in general it should be expected that /search results will change a bit over time. For example, if a business has a name change, the business might no longer be returned for /search requests for the old name.
