### ISSUE TITLE
429 and 502 Errors

### ISSUE THREAD

**Issue by Pigpocket** [Yelp/yelp-fusion#373]
## Overview
- **Client ID:** _6QZYVuLI6ppWVIEICrx9vQ_
- **Issue type:** _Bug: 429 and 502 errors_
- **Summary:** _429 error when calling for opening hours after retrieving business ID. 502 error when re-doing the search in another location_
- **Platform:** _iOS_

## Description
_I call for search results for 'martini' within 16000 meters of user's coordinates. This is followed by a call for the business hours after getting the business IDs. At this point, I receive a number of 429 errors, though the results seem to show. When I move the map to a new location and "redo search results" my url string force unwrapping results in unexpectedly finding a nil value. I try this call in postman and get the following error:

<html>
    <body>
        <h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
    </body>
</html>

## Additional Information
_This behavior is inconsistent_

### Endpoint
_Fusion Business Search API, Fusion Business Lookup API_

### Parameters or Sample Request
_How my 429 errors appear:
https://api.yelp.com/v3/businesses/el-jefe-palm-springs-3_

### Response
_There was an error getting business hours: Optional("There was an error getting business info: Error Domain=taskForGetYelpSearchResults Code=1 \"Your request returned an invalid response! Status code: 429!\" UserInfo={NSLocalizedDescription=Your request returned an invalid response! Status code: 429!}")_

## Extra information
_This appears like issue #77 however my search request 'martini' shouldn't return enough records for it to result in an error of requesting too much since it is just myself using the app during development so I don't get the 'too many call requests' error either. Please advise._

**Comment by Pigpocket** [comment]
Thanks @dan98765 

This is the error response. My code is in Swift: 

`There was an error getting business hours: Optional("There was an error getting business info: Error Domain=taskForGetYelpSearchResults Code=1 \"Your request returned an invalid response! Status code: 429!\" UserInfo={NSLocalizedDescription=Your request returned an invalid response! Status code: 429!}")`

Which comes from this function, which uses the location ID to get the business hours:

`func getOpeningHoursFromID(id: String, completionHandlerForOpeningHours: @escaping (_ openNow: Bool, _ errorString: String?) -> Void) {
        
        let methods = Methods.Businesses + id
        
            self.taskForGetYelpSearchResults(method: methods, parameters: [:]) { (results, error) in
 
            if let error = error {
                completionHandlerForOpeningHours(false, "There was an error getting business info: \(error)")
            } else {
                if let results = results {
                    if let hours = results["hours"] as? [[String:AnyObject]] {
                        if let isOpenDict = hours[0] as? [String:AnyObject] {
                            if (isOpenDict["is_open_now"] as? Bool) != nil {
                                completionHandlerForOpeningHours(true, nil)
                            } else {
                                completionHandlerForOpeningHours(false, "Could not find opening hours: \(String(describing: error))")
                            }
                        }
                    }
                }
            }
        }
    }`

The original get request fails when I drag the map to a new location quickly. Not sure if this is related.  

![image](https://user-images.githubusercontent.com/23366254/37233496-495b8c50-23a8-11e8-8d89-6a8ac68e71f6.png)

Here is the project on Github if that is more helpful:

https://github.com/Pigpocket/MartiniFinder

Thanks and looking forward to your feedback!

**Comment by virgytam** [comment]
Hi @Pigpocket, HTTP 429 means you've exceeded your daily access limit. Do you routinely get this error with every request or does it happen after a certain number of requests? 

as per our documentation, developers are limited to 25,000 requests per 24 hours, resetting at midnight UTC time - https://www.yelp.com/developers/documentation/v3/rate_limiting

**Comment by virgytam** [comment]
Hi @Pigpocket, regarding using the GraphQL API to retrieve business hours in a single request rather than a second call after getting the business ID, you're correct; that's the essence of GraphQL -- that you can define what your response looks like. 

As for the 429, it's also possible that you're hitting a QPS rate limit. We limit developers to 5 QPS and if this is the case, your error message should look like this:

```
{
    "error": {
        "code": "TOO_MANY_REQUESTS_PER_SECOND",
        "description": "You have exceeded the queries-per-second limit for this endpoint.
                        Try reducing the rate at which you make queries."
    }
}
```
can you confirm this is the error message?

**Comment by Pigpocket** [comment]
@virgytam 

I'm not sure quite how to get that error message specifically. This is my getOpeningHoursFromId function that accepts the error object:

    func getOpeningHoursFromID(id: String, completionHandlerForOpeningHours: @escaping (_ openNow: Bool, _ errorString: String?) -> Void) {
        
        let methods = Methods.businesses + id
        
            self.taskForGetYelpSearchResults(method: methods, parameters: [:]) { (results, error) in
 
            if let error = error {
                completionHandlerForOpeningHours(false, "There was an error getting business info: \(error)")

And this is my GET request the passes it there:

        func taskForGetYelpSearchResults(method: String, parameters: [String:Any], completionHandlerForGET: @escaping (_ results: AnyObject?, _ error: NSError?) -> Void) {
        
        let session = URLSession.shared
        let urlString = YelpClient.Constants.yelpBaseURL + method + escapedParameters(parameters as [String : AnyObject])
        let url = URL(string: urlString)!
        let request = NSMutableURLRequest(url: url)
        request.httpMethod = "GET"
        request.addValue(YelpClient.Constants.apiKey, forHTTPHeaderField: YelpClient.Constants.authorization)
        let task = session.dataTask(with: request as URLRequest) { data, response, error in
            
            /* GUARD: There is no error */
            guard error == nil else {
                let userInfo = [NSLocalizedDescriptionKey: "There was an error with your request: \(String(describing: error))"]
                completionHandlerForGET(nil, NSError(domain: "taskForGetYelpSearchResults", code: 0, userInfo: userInfo))
                return
            }
            
            /* GUARD: Did we get a successful 2XX response? */
            guard let statusCode = (response as? HTTPURLResponse)?.statusCode, statusCode >= 200 && statusCode <= 299 else {
                if let response = response as? HTTPURLResponse {
                    let userInfo = [NSLocalizedDescriptionKey: "Your request returned an invalid response! Status code: \(response.statusCode)!"]
                    completionHandlerForGET(nil, NSError(domain: "taskForGetYelpSearchResults", code: 1, userInfo: userInfo))
                } else if let response = response {
                    let userInfo = [NSLocalizedDescriptionKey: "Your request returned an invalid response! Response: \(response)!"]
                    completionHandlerForGET(nil, NSError(domain: "taskForGetYelpSearchResults", code: 2, userInfo: userInfo))
                } else {
                    let userInfo = [NSLocalizedDescriptionKey: "Your request returned an invalid response!"]
                    completionHandlerForGET(nil, NSError(domain: "taskForGetYelpSearchResults", code: 3, userInfo: userInfo))
                }
                return
            }

My error response is this:

    There was an error getting business hours: Optional("There was an error getting business info: Your request returned an invalid response! Status code: 429!")

Sorry if this isn't helpful, I'm relatively new.

**Comment by Pigpocket** [comment]
Hey @virgytam 

I abandoned my former code temporarily as I found this Swift Wrapper: [https://github.com/chrisdhaan/CDYelpFusionKit](url)

I believe my former code was over-tapping your server as I made one call for business info and then used the business id in what I believed to be a second call, but based on the rate-limiting response seemed like it was one call _per business_. This CDYelpFusionKit appears to encompass business hours into the initial call, but when I try to access the isOpenNow property, I get a nil value. I've tried a number of different ways. I also noticed that I needed to be signed up as a developer for your beta program for the graphQL API to get opening hours? I did that, but I'm still getting a nil value. Am I missing something? This is my call:

     `        yelpAPIClient.searchBusinesses(byTerm: "Martinis",
                                     location: nil,
                                     latitude: MapCenter.shared.latitude,
                                    longitude: MapCenter.shared.longitude,
                                       radius: 16000,
                                   categories: nil,
                                       locale: nil,
                                        limit: 20,
                                       offset: 0,
                                       sortBy: nil,
                                   priceTiers: nil,
                                      openNow: false,
                                       openAt: nil,
                                   attributes: nil) { (response) in
                                    
                                    performUIUpdatesOnMain {
                                    
                                        if let response = response,
                                            let businesses = response.businesses,
                                            businesses.count > 0 {
                                            for business in businesses {
                                            Location.businesses.append(business)
                                                print(business.hours?[2].isOpenNow)`

I can access the other properties of the business, like id, name, etc with dot notation, but I can't get isOpenNow (I've tried indexing to 0, 1 and 2 in that array as CDYelpHours type is an array in that framework).

Sorry if this is confusing. I'm pretty new.

**Comment by Pigpocket** [comment]
I resolved my 429 errors by simply removing isOpenNow from my tableview cells, since it's unrealistic to expect fewer than 5 calls per second in all use cases and I don't want to slow my requests to render the result in the UI. Not too big a deal. I am curious though why the API was designed so that this property required an extra call?

I discovered my 502 error was related to having a URL with a special character in it that had not been converted properly. Is 502 the typical server response for this error? I'm fairly new at this, but this code seems to suggest its a server error, rather than my error in sending an improperly formatted URL.

Thanks for your help with all this, my app is nearly done.

**Comment by virgytam** [comment]
Hi @Pigpocket, I'm not sure if this Swift library alters the variable names, but in our documentation, the  attribute is `is_open_now` (lower-cased and with underscores). Does `business.hours[2].is_open_now` work?

**Comment by akshaykumar3** [comment]
> Hi @Pigpocket, regarding using the GraphQL API to retrieve business hours in a single request rather than a second call after getting the business ID, you're correct; that's the essence of GraphQL -- that you can define what your response looks like.
> 
> As for the 429, it's also possible that you're hitting a QPS rate limit. We limit developers to 5 QPS and if this is the case, your error message should look like this:
> 
> ```
> {
>     "error": {
>         "code": "TOO_MANY_REQUESTS_PER_SECOND",
>         "description": "You have exceeded the queries-per-second limit for this endpoint.
>                         Try reducing the rate at which you make queries."
>     }
> }
> ```
> can you confirm this is the error message?

Will 5 QPS be valid in the production system as well. I mean in the production system will we get error post 5 QPS?

**Comment by dan98765** [comment]
@akshaykumar3 the QPS rate limit for all non-Fusion-VIP developers is currently 5 QPS for each endpoint, including GraphQL. Any requests beyond that will result in an error message that indicates that.

**Comment by watterso** [comment]
>It does not, but I've verified with the owner of the other repo that it actually won't, so... I'm good to go at this point. Thanks for your help!

Issue appears resolved, closing.

**Comment by upa8** [comment]
@dan98765 

What is the QPS rate limit for Fusion-VIP developers?

**Comment by dan98765** [comment]
Hi @upa8 - could you please open a new issue to ask your question?
