### ISSUE TITLE
does the beta api return quota headers

### ISSUE THREAD

**Issue by sulphide0** [Yelp/yelp-fusion#375]
we aren't seeing these headers returned anymore:
https://www.yelp.com/developers/documentation/v3/rate_limiting

**Comment by dlgallagher** [comment]
Hi @sulphide0 thanks for the report. I just did a test query on the business endpoint with a beta-enabled client and had the 3 RateLimit-* headers returned. Could you double-check on the Manage App page that you're beta-enabled, and if so post your client ID (but please not your key or any other sensitive info) so I can investigate further?

**Comment by sulphide0** [comment]
thanks!

is the beta api url at a new address or path? we're currently still using
https://api.yelp.com/v3/ as the root url

**Comment by dlgallagher** [comment]
The uris for each endpoint are the same whether you are in the beta program or not. Being in the beta program or not is a True/False flag on your client, which you can configure via https://www.yelp.com/developers/v3/manage_app by opting in or out. 

If your client is in the beta program make a call to (for example) the business endpoint you will get back the rate limiting headers, and if you then go to the Manage App page and opt back out of beta and make the exact same business endpint call you will not see the headers.

**Comment by dan98765** [comment]
To close the loop here: on March 28th, 2018 we graduated these rate limiting headers out of the beta program so they'll be returned regardless of whether you are opted into beta or not. 
See the changelog entry: https://www.yelp.com/developers/v3/changelog#changelog-20180328 
Thanks to everyone who gave us feedback that they were useful.
