### ISSUE TITLE
Request for financial services returns empty list

### ISSUE THREAD

**Issue by Ystyr** [Yelp/yelp-fusion#377]
## Overview
- **Client ID:** DjO41dTl0TNigv7pQMFX0A
- **Issue type:** bug
- **Summary:** Request returning an empty list, but still showing a number of businesses found
- **Platform:** Desktop/web, Android

## Description
The problem can be reproduced in https://www.yelp.com/developers/ GraphQL console

### Parameters or Sample Request
query searchPois (
  $location: String = "usa,tx,dallas,downtown dallas" 
  $sort_by:String = "rating"
  $radius:Float = 850.0
  $limit:Int = 50
	) 
{
  financialservices: search(
    location: $location, sort_by: $sort_by, limit: $limit, radius: $radius, term: "financialservices"
    ) 
  {
    total
    business {
      name
      categories {alias}
    }
  }
}

### Response
{
  "data": {
    "financialservices": {
      "total": 9,
      "business": []
    }
  }
}

**Comment by dan98765** [comment]
Thanks for the report, @Ystyr! I was able to reproduce what you're describing here, and filed an internal ticket for this issue. We'll look into it.
