### ISSUE TITLE
Problem to Sign Up of a new account

### ISSUE THREAD

**Issue by Moh-BOB** [Yelp/yelp-fusion#378]
## Overview
- **Client ID:** (Not yet)
- **Issue type:** Bug
- **Summary:** Can't sign up a new account
- **Platform:** Desktop

## Description
Hi,
I'm having trouble when attempting to create an account on : https://www.yelp.com/login.
Even when attempting to connect with Facebook/Google+,  it doesn't work for me.
I get each time the following messages: 

` - "Are you a human? Please complete the bot challenge below." //(but the bot challenge is not visible)`
 Or, 
`
"Oops, Yelp is overworked right now //(when validating the new account form)".
`

This problem persists for me since a month.

Please can anyone help me ?

Thank you.

### Endpoint
Fusion Search Login

**Comment by dlgallagher** [comment]
Hi @Moh-BOB thanks for the report. I've filed a ticket internally to look into this.

**Comment by Moh-BOB** [comment]
Hi @dlgallagher  Thank you !

**Comment by dan98765** [comment]
@Moh-BOB which browser are you using? Also, do you have javascript enabled in your browser when you experience this issue?

**Comment by Moh-BOB** [comment]
@dan98765  i'm using Chrome sir, and javascript is enabled in my brower (by default).
Thank you

**Comment by dan98765** [comment]
@Moh-BOB could you please try signing up at https://www.yelp.com/developers/v3/manage_app with a different browser (i.e. firefox, IE...)?

**Comment by Moh-BOB** [comment]
Sorry, I just tested with Firefox. I got the same messages as with chrome.

**Comment by dan98765** [comment]
@Moh-BOB this is an issue with signing up for a yelp.com account rather than specifically a Yelp Fusion developer account (which you will be able to do at  https://www.yelp.com/developers/v3/manage_app once your Yelp.com user account is created and verified). 

From https://www.yelp-support.com/article/How-do-I-sign-up-for-Yelp?l=en_US
```
If you don't receive a confirmation message or run into other trouble with your account, please contact our Support team.
```
[Contacting our support team](https://www.yelp.com/support/contact/account_inquiry?src_article_id=000005405) about the issue you're experiencing with creating a Yelp.com account is your best bet here, they're equipped to respond to account creation questions.

**Comment by Moh-BOB** [comment]
Okay @dan98765 .
Thank you !

**Comment by sushmak02** [comment]
I am facing the same issue. Refer - http://tinyurl.com/y3bmusb8

**Comment by SergiuHKR** [comment]
I'm having the same exact issue. Chrome as well.

**Comment by ke4zzy** [comment]
Yes. Its the fact that YELP is watching the IP address and when more than one person logs in it throws up that Joke of a Bot Challenge page. 
They need to hire a Real I.T. guy and stop paying teeny boppers to write code for their website.

**Comment by EugeneEl** [comment]
Cannot sign up with gmail too(

**Comment by sateeshyegireddi** [comment]
I'm also having the same issue while trying to signing up with yelp.com

**Comment by raseldewy** [comment]
I am facing the same problem . Anyone can help me please

**Comment by fadjriaf** [comment]
I'm also facing the same issue while trying to sign up, help me please

**Comment by mayaliberman** [comment]
I have the same issue too.

**Comment by sridhargoshika** [comment]
I am also facing the same issue while trying to sign up of a new account. It always returning with a message `Oops, Yelp is overworked right now.`

It display message like `Are you a human? Please complete the bot challenge below.`  And there is no Captcha verification display when I try login with google.
on https://www.yelp.com/login?return_url=%2Fdevelopers%2Fv3%2Fmanage_app
Anyone can help me please

**Comment by akmallmr** [comment]
Me too. is there anyone can solve this problem ?

**Comment by jasony0206** [comment]
Thank you everyone for raising this issue. We are looking into it.

**Comment by KevinHock** [comment]
For those experiencing this: can you please share your IP address with us to help troubleshoot the issue?

**Comment by TobsDev** [comment]
Same problem over here. I tried using different IP-addresses, Safari, Chrome and Firefox but can't get it to work either.

**Comment by beevekmgr** [comment]
Same problem tried with from firefox... but sstill cant sign up....

**Comment by beevekmgr** [comment]
**I tried using VPN i.e. change my IP to _CANADA_ and now its all setup try changing the IP using VPN it may worked !!!**

**Comment by iamHSpace** [comment]
**Use a VPN. Change the location to America. Now it is working for me.**

**Comment by jasony0206** [comment]
Unfortunately, we currently do not allow users with [APNIC](https://en.wikipedia.org/wiki/Asia-Pacific_Network_Information_Centre#Economies) or [AFRINIC](https://en.wikipedia.org/wiki/AFRINIC#Economies) IP addresses to sign up for an account. We will update the Fusion documentation to reflect this restriction.

**Comment by usama-asfar** [comment]
I'm able to log in when I use VPN and set to USA

**Comment by mehmoodchohan** [comment]
use VPN then it's working

**Comment by fahad39** [comment]
For all of you experiencing this problem use VPN to signup

**Comment by dangtuanhuy** [comment]
I can't sign up Yelp with a new account, Facebook, Google.

**Comment by fahad39** [comment]
> I can't sign up Yelp with a new account, Facebook, Google.

Use VPN and then sign up set the location of United States

**Comment by salahac279** [comment]
> Hi @Moh-BOB thanks for the report. I've filed a ticket internally to look into this.

I also have the same problem is there any help you could offer?

**Comment by fahad39** [comment]
> > Hi @Moh-BOB thanks for the report. I've filed a ticket internally to look into this.
> 
> I also have the same problem is there any help you could offer?

use a VPN set its location to united states or somewhere else then login

**Comment by rayenmehrez77** [comment]
I have the same issue

**Comment by masibomabelethomas** [comment]
same problem here in Kenya Nairobi

**Comment by Moh-BOB** [comment]
I just tried again, it is working fine for me (on Chrome Version 83.0.4103.116).
Try to change browser, or to update Chrome.

**Comment by rohan2734** [comment]
I aslo have the issue, i tried to login with opera browser (builtin VPN) but doesnt work.

**Comment by sultanafghan** [comment]
in Chrome use Hola VPN and use USA Location it Will Work .

**Comment by 0xecho** [comment]
+1

**Comment by ShekarYenagandula** [comment]
Hi All,
I was facing the same issue.
Only solution I found is, In opera, Enable VPN and then you can able to SignIn/ Signup
[To enable VPN in Opera:

Go to your Settings (Alt+P).
Select Advanced in the left sidebar, and click Features.
Under VPN, toggle on Enable VPN.](https://www.opera.com/features/free-vpn)

**Comment by Salmankhan033** [comment]
> @dan98765 I am facing the same issue. Refer - http://tinyurl.com/y3bmusb8

use Vpn

**Comment by Salmankhan033** [comment]
In yelp have limited country. so you use VPN and select USA or UK then it will work

**Comment by minhtan4711** [comment]
still have this problem until now :<

**Comment by Tony0070** [comment]
The issue still persists 🙄

**Comment by eulerkochy** [comment]
Sign-up using Singapore VPN also works 😄

**Comment by Tony0070** [comment]
> Sign-up using Singapore VPN also works 😄

That's what I did 😉

**Comment by Salmankhan033** [comment]
It may not be available in your Country.
So you cab Use VPN then it will be Sign up

**Comment by gunjanmimo** [comment]
Use VPN and select Canda, it will work

**Comment by Kaustav1999paul** [comment]
Guys, just open any browser and connect to US VPN........ it will work

**Comment by manutdmohit** [comment]
> **Use a VPN. Change the location to America. Now it is working for me.**

Thanks bro

**Comment by manutdmohit** [comment]
> Use VPN and select Canda, it will work

Thanks Bro

**Comment by kartikeyjangir** [comment]
Why vpn , It is March 2022 and still the issue is not resolved !!

**Comment by Salmankhan033** [comment]
> Why vpn , It is March 2022 and still the issue is not resolved !!

Yelp is not available in your country for that you will use VPN

**Comment by DevArtifacTs** [comment]
I'm in Thailand and VPN not work for my case. I want to practice with Yelp API and develop Yelp App. Someone please help me, I cannot create my new account. Every time I verify my self isn't a robot It's tell me to verify again and again.
Thankyou in advance.

**Comment by kartikeyjangir** [comment]
There is not other way. You have to sign in using vpn. If vpn is not working in your system. Try using vpn master it is available in app store. Signin using Yelp, and create an account.
Than use that in your system or get copy the API key from mobile.

**Comment by AliShanpansota** [comment]
Are you a human? Please complete the bot challenge below.
yelp issuee

**Comment by devononymous** [comment]
> ## Overview
> * **Client ID:** (Not yet)
> * **Issue type:** Bug
> * **Summary:** Can't sign up a new account
> * **Platform:** Desktop
> 
> ## Description
> Hi, I'm having trouble when attempting to create an account on : https://www.yelp.com/login. Even when attempting to connect with Facebook/Google+, it doesn't work for me. I get each time the following messages:
> 
> ` - "Are you a human? Please complete the bot challenge below." //(but the bot challenge is not visible)` Or, `"Oops, Yelp is overworked right now //(when validating the new account form)".`
> 
> This problem persists for me since a month.
> 
> Please can anyone help me ?
> 
> Thank you.
> 


> Same problem over here trying to sign in, not signing up. I tried using different IP-addresses, Safari, Chrome and Firefox but can't get it to work either.

Use vpn

**Comment by mahmoudkandel980** [comment]
unfortunately using vpn does not working for me. 
1- made your country is USA.
2- put your Gmail account and any dummy password not your Gmail account origin password because you will receive a confirmation mail to make them sure that is your account.
3- make sure you write a valid zip code of any region in USA i put the zip code 08070. 
it worked in my case hope it work for yours

**Comment by princesssaba** [comment]
I face issue to it face captcha error in USA yelp captcha appear again and again I use many iPhone please any one guide me

**Comment by poolsafety** [comment]
trying to signup but facing same issue.
[](https://f005.backblazeb2.com/file/pool-certificate/index.html)

**Comment by princesssaba** [comment]
> trying to signup but facing same issue. [Pool Certificate](https://f005.backblazeb2.com/file/pool-certificate/index.html)

May it will update soon can you please report or contact where you from?

**Comment by ridhof** [comment]
using US VPN and put a valid US zip code works for me

**Comment by preciousnwaoha** [comment]
> Hi All, I was facing the same issue. Only solution I found is, In opera, Enable VPN and then you can able to SignIn/ Signup [To enable VPN in Opera:
> 
> Go to your Settings (Alt+P). Select Advanced in the left sidebar, and click Features. Under VPN, toggle on Enable VPN.](https://www.opera.com/features/free-vpn)

I tried all solutions here, the best way is to download Opera as stated. But, also make sure to tap the "vpn" icon near the url and switch to "Americas"

**Comment by AhmedHassan301** [comment]
Try singing with an email without using a Google account.

**Comment by FT-node** [comment]
I am running into this issue trying to sign in with a Google account... Very much a customer deterrent. Yelp needs to fix this ASAP

**Comment by lalwanikamaldev** [comment]
I was also facing same issue but then after that i tried on my VDI which is located in USA and it worked .

**Comment by alexbabez** [comment]
fuck yelp littrealy wtf is this man iam so frustrated like fuck you and fuck your fucking yelp put your antibots in your ass

**Comment by Excellencedev** [comment]
still facing this issue like yall should do something about this

**Comment by Gold240sx** [comment]
I'm getting this issue now, error: "[Error] The Content Security Policy directive 'frame-ancestors' is ignored when delivered in a report-only policy." from the console... It's just stuck on Captchas (Captcha test green checkmark, then asks if I'm human again and back to asking to complete a new test. Same behavior on Chrome and Safari.).

**Comment by amineArkanpro** [comment]
Worst signup on earth, excellent from yelp side !! -10000000 aura
