### ISSUE TITLE
sort_by Ignored

### ISSUE THREAD

**Issue by davecom** [Yelp/yelp-fusion#379]
## Overview
- **Client ID:** _XS2T5LEXDbAOyIGBb5X-Aw_
- **Issue type:** _bug_
- **Summary:** _Same results returned regardless of sort_by's value._
- **Platform:** _macOS/Swift/CDYelpFusionKit_

## Description
_Regardless of what value I set sort_by to be, I get the same results. This is true across many different searches that I have tried. Are other people having the same issue? Is there anything in a request that can cause sort_by to be ignored?_

### Endpoint
_Fusion Search API_

### Parameters or Sample Request

```
["sort_By": "rating", "location": "new york, ny", "limit": 50, "categories": "restaurants", "offset": 0, "radius": 16093, "term": "burger", "locale": "en_US"]
```
same as
```
["sort_By": "review_count", "location": "new york, ny", "limit": 50, "categories": "restaurants", "offset": 0, "radius": 16093, "term": "burger", "locale": "en_US"]
```
same as
```
["sort_By": "best_match", "location": "new york, ny", "limit": 50, "categories": "restaurants", "offset": 0, "radius": 16093, "term": "burger", "locale": "en_US"]
```
### Response
All responses the same... not just for these three but any queries that I try with sort_by for a given other set of criteria. The other criteria changes the response, but not sort_by.

**Comment by Valectar** [comment]
The field you're looking for is 'sort_by', rather than the 'sort_By' which you are using, since the parameter is case sensitive.

**Comment by davecom** [comment]
Thank you, this must be a bug in CDYelpFusionKit. I'll post a patch.
