### ISSUE TITLE
location not working correctly for AU

### ISSUE THREAD

**Issue by tcn33** [Yelp/yelp-fusion#38]
The result set returned for `location=63 York St, Sydney&radius=250` is far less precise than `latitude=-33.867572&longitude=151.205670&radius=250` - the first returns results that are several kilometres away, whereas the second returns the expected result.

I have tried phrasing the location string a number of different ways and nothing seems to change the results returned. Is `location` expecting an address format that's not supported in Australia, maybe?

**Comment by mittonk** [comment]
@tcn33 : It'd be helpful to see the responses you're getting, especially the "location" key.  Could you provide a gist or similar?

**Comment by tcn33** [comment]
Sure thing: https://gist.github.com/tcn33/fbcac5fa0f9fc07e2a27175a9ae5f2a8. There's an example of the result set using location and one using lat/long.

**Comment by mittonk** [comment]
I found `radius` is honored with `ll` but not `location`.

So, that explains this behavior --- still figuring out whether that's a confusing aspect that needs better documentation, or a straight-up bug.

**Comment by mittonk** [comment]
Marking this as a dup of #60 , please follow along over there for updates.
