### ISSUE TITLE
Oauth Token End Point Is Depricated How To solve this Problem?

### ISSUE THREAD

**Issue by AnkushSharma26** [Yelp/yelp-fusion#380]
Hiii,
 I'm also having a problem with authentication. I got the error during generating the oauth token. Can you tell me what I'm doing wrong?

Please check below code:- 

require_once ('lib/hhb_.inc.php');
$hc = new hhb_curl ( 'https://api.yelp.com/oauth2/token', true );
$hc->setopt_array ( array (
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => http_build_query ( array (
                'grant_type' => 'client_credentials', 
                'client_id' => 'XXXXXXX',
                'client_secret' => 'XXXXXXX' 
        ) ) 
) );
$hc->exec ();
$result = $hc->getStdOut ();

if($result)
{
        $data = json_decode($result);
        print_r($data);
}
====================================
====================================
[error] => stdClass Object
        (
            [code] => OAUTH_TOKEN_ENDPOINT_DEPRECATED
            [description] => The oauth2 token endpoint has been deprecated and removed; you must use your API key for authentication instead. Please see https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going for info & migration steps
        )

Please let me know if you have any solution for this type of error in case of accessing the token..

**Comment by teekwak** [comment]
Hi @AnkushSharma26,

We no longer use OAuth2 tokens for authentication. As noted in the link in your error message [(https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going)](https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going), starting March 1, 2018, we have moved over to using only API keys. 

Generating the API key can be found at [https://www.yelp.com/developers/v3/manage_app](https://www.yelp.com/developers/v3/manage_app).

**Comment by AnkushSharma26** [comment]
Hii teekwak,
Hope you are doing well!!

I have also read the below link artical for authentication
https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going but I think i miss somthing else.
You say "We no longer use OAuth2 tokens for authentication". Then please let me know how to get the access token with different Oauth.

Please let me know your feedback.

Thanks&Regards

**Comment by AnkushSharma26** [comment]
Hii teekwak,
Hope you are doing well!!

I have also read the artical for authentication. Please check the below link
https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going but I think i miss somthing else.
You say "We no longer use OAuth2 tokens for authentication". Then please let me know how to get the access token with different Oauth.

Please let me know your feedback.

**Comment by AnkushSharma26** [comment]
Hii teekwak,
Hope you are doing well!!

I have also read the artical for authentication. Please check the below link
https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going
but I think i miss somthing else.
You say "We no longer use OAuth2 tokens for authentication". Then please
let me know how to get the access token with different Oauth.

Please let me know your feedback.

**Comment by ejrivera6** [comment]
Hello, 
The links are not helpful. Would you please provide more detail on how to use the API Key to Authenticate
