### ISSUE TITLE
YELP API OAUTH ERROR HOW TO SOLVE THE PROBLEM?

### ISSUE THREAD

**Issue by AnkushSharma26** [Yelp/yelp-fusion#381]
Hiii,
 I'm also having a problem with authentication. I got the error during generating the oauth token. Can you tell me what I'm doing wrong?

Please check below code:- 

require_once ('lib/hhb_.inc.php');
$hc = new hhb_curl ( 'https://api.yelp.com/oauth2/token', true );
$hc->setopt_array ( array (
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => http_build_query ( array (
                'grant_type' => 'client_credentials', 
                'client_id' => 'XXXXXXX',
                'client_secret' => 'XXXXXXX' 
        ) ) 
) );
$hc->exec ();
$result = $hc->getStdOut ();

if($result)
{
        $data = json_decode($result);
        print_r($data);
}
====================================
====================================
[error] => stdClass Object
        (
            [code] => OAUTH_TOKEN_ENDPOINT_DEPRECATED
            [description] => The oauth2 token endpoint has been deprecated and removed; you must use your API key for authentication instead. Please see https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going for info & migration steps
        )

I have also read the artical for authentication. Please check the below link
https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going but I think i miss somthing else.
We no longer use OAuth2 tokens for authentication. Then please let me know how to get the access token with different Oauth in Yelp Fusion API

Please let me know your feedback.

Thanks&Regards

**Comment by virgytam** [comment]
Hi AnkushSharma26, you can retrieve your API key from the Manage App page: https://www.yelp.com/developers/v3/manage_app

**Comment by ejrivera6** [comment]
Hello Virgytam, 

I am using Postman, I have my API key in Headers with Bearer API_KEY as the value and the key as, well, the key. This is my error, what am I doing wrong? 

{
    "error": {
        "code": "OAUTH_TOKEN_ENDPOINT_DEPRECATED",
        "description": "The oauth2 token endpoint has been deprecated and removed; you must use your API key for authentication instead. Please see https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going for info & migration steps"
    }
}

**Comment by virgytam** [comment]
Hi @ejrivera6, which endpoint are you querying? This error message is returned from the /oauth2/token endpoint since it has been deprecated. You no longer need to use this endpoint to get your API  Key since it's in the Manage App page now

**Comment by AnkushSharma26** [comment]
Hii,

Thanks, The issue has been resolved...
