### ISSUE TITLE
Yelp Fusion - where to find Deals and Gift sertificates info?

### ISSUE THREAD

**Issue by macrognathus** [Yelp/yelp-fusion#384]
## Overview
- **Client ID:** float-matrix-san-francisco
- **Issue type:** question
- **Summary:** When I used 'https://api.yelp.com/v2/business/' endpoint, among other fields in response like 'rating' and 'review_count' I got 'reviews', 'deals' and 'gift_certificates'. For Yelp fusion API I see in documentation https://www.yelp.com/developers/documentation/v3/business that these fields are not returned any more. I see endpoint /businesses/{id}/reviews to get reviews, but is there any opportunity to get 'deals' and 'gift_certificates' from Fusion API?

### Endpoint
Fusion /businesses/search

Thanks so much in advance!

**Comment by virgytam** [comment]
hi @macisamuele, we don't have any current plans to include deals information in Fusion API but I'll label this as an enhancement request so we can track this

**Comment by macisamuele** [comment]
@macrognathus I think that the above ping was for you 😄

**Comment by macrognathus** [comment]
Thanks for information! I assume same answer is for 'gift certificates'.
