### ISSUE TITLE
Calling Yelp API v3 using Front End Javascript only

### ISSUE THREAD

**Issue by rita-aga** [Yelp/yelp-fusion#386]
- **Client ID:** gCa56D_lncDKDwocIs6iUg
- **Issue type:** Access denied
- **Platform:** MacOS
## Description
Getting error: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5500' is therefore not allowed access. The response had HTTP status code 403.

## More information
I'm new to this, so forgive me if this question is downright silly. I've looked through a number of related threads here and StackOverflow, but it's still not 100% clear to me. 
I understand that it's not ideal to call Yelp API from front end since the access key is exposed, however, my question is, is it even possible? And if it is, what is wrong with my code?
(I'm trying to figure out how to make it work using NodeJS/back-end API, but I don't know much about back end at this point, so I wanted to know if it is at all possible with front end only for now).
Thank you!

### Endpoint
Fusion Search API

### Parameters or Sample Request

JavaScript
```
var data = null;
var xhr = new XMLHttpRequest();
xhr.open("GET", "https://api.yelp.com/v3/businesses/search?text=coffee&latitude=37.786882&longitude=-122.399972");
xhr.setRequestHeader("Authorization", "Bearer <my key here>");
xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    data = JSON.parse(this.responseText);
    console.log(data);
  }
});
xhr.send(data);
```
jQuery
```
var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://api.yelp.com/v3/businesses/search?text=coffee&latitude=37.786882&longitude=-122.399972",
  "method": "GET",
  "headers": {
    "Authorization": "Bearer <my key here>",
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```
Both result in this:
### Response
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5500' is therefore not allowed access. The response had HTTP status code 403.

**Comment by virgytam** [comment]
Hi @rita-aga, you're right in that you shouldn't include your API Key in your frontend for security reasons and we currently do not support our API to be used in JavaScript. I'd definitely recommend making your requests from the backend where it's easier to control your API Key.

**Comment by rita-aga** [comment]
Thank you @virgytam for the promt response! 
Got it, will have to figure out how to request from the backend then. 
I got a bit confused since some threads/discussions made it sound like someone has figured out a magical way to use CORS or JSONP with Yelp which for me wasn’t working either (as it apparently clearly should not).
Thank you!
