### ISSUE TITLE
Inconsistency in data fetched from API

### ISSUE THREAD

**Issue by mjuraj** [Yelp/yelp-fusion#387]
## Overview
- **Client ID:** fy8m565WD7D0tv0tCZJ5sw
- **Issue type:** Bug
- **Summary:** When getting places in Seattle (radius 40km) I get 5k places, when split in smaller circles the sum is 1.5k.
- **Platform:** Desktop/web

## Description
So, this is the format of requests I made (headers not included):
```
https://api.yelp.com/v3/businesses/search?latitude=<lat>&longitude=<long>&radius=<radius>&categories=hotels,restaurants,food,bars,nightlife
```
This is what i get for Seattle (lat: 47.613169, long: -122.342064, rad: 40000): 5000 places

Now, I split that circle into 4 smaller circles (these circles together include the above circle and more):
(lat: 47.786375, long: -122.064711, rad: 28284): 662 places
(lat: 47.786375, long: -122.599500, rad: 28284): 265 places
(lat: 47.426018, long: -122.066547, rad: 28284): 440 places
(lat: 47.426018, long: -122.597664, rad: 28284): 364 places

You can see that I get 1731 places, which is significantly smaller than 5000. Also, when I search for "coffee" in "Seattle, WA" on Yelp I get 3000+ places.

### Endpoint
Fusion Search API

## Extra information
I've tried this using both Postman and Python shell.

Here is an image of circles that are made with the coordinates:
![screenshot from 2018-03-24 17-27-11](https://user-images.githubusercontent.com/2018839/37866281-f0e6921c-2f88-11e8-996d-79fde75f3bb5.png)

**Comment by JimmyRandom** [comment]
+1

**Comment by rohitshetty** [comment]
I confirm I get similar bug for london. 
![screenshot from 2018-06-19 12-26-39](https://user-images.githubusercontent.com/4188700/41780015-22872746-7651-11e8-81fb-dd68b0ddc7d6.png)
The right most bigger circle when queried yelp api says there is total of 627 photos.
![screenshot from 2018-06-19 12-31-17](https://user-images.githubusercontent.com/4188700/41780035-340abe6a-7651-11e8-9884-d9f043f5db59.png)
But when I use this circle, which lies inside the bigger circle I get around 1.4K restaurants listed. 
This inconsistency causes a lot of problem to us and we would like this to be solved, or at least some guidelines released on handling this.
