### ISSUE TITLE
Determine if API key is valid

### ISSUE THREAD

**Issue by dgsjm** [Yelp/yelp-fusion#389]
## Overview
- **Client ID:** kw7_TqL6zHaAN7owIeLF1Q
- **Issue type:** Question
- **Summary:** Is there a way to validate/verify an API key without querying a business/event endpoint?
- **Platform:** Desktop/web

## Description
I'm looking for a way to verify that an API key is valid without actually searching for businesses, transactions, events, etc.

Is there an endpoint or other method to simply validate an API key?

### Endpoint
https://api.yelp.com

**Comment by dan98765** [comment]
There isn't currently an endpoint that just validates an API key. What's the use case?

**Comment by dgsjm** [comment]
Thanks for the quick reply, Dan.

I’m developing a tool that will allow each of my website clients to enter their API key into their CMS and display their Yelp reviews on their website. The CMS tool will visually indicate whether they have successfully connected to the Yelp API.

I can just perform a default business lookup to test the API key, but I was wondering if there might be a more efficient method of simply verifying a key.

**Comment by dan98765** [comment]
A dedicated endpoint for validating an api key would get back a very quick response compared to doing a business lookup, but otherwise I can't think of many other advantages over doing a sample business lookup. I'd suggest going with your "sample business lookup to test the API key" idea.

**Comment by dgsjm** [comment]
Gotcha.
It just felt messy to fetch business data when it's not actually needed.
But a business lookup will work.
Thanks Dan.

**Comment by dan98765** [comment]
Thanks for opening an issue to check if there was a more efficient solution! Since it's just a single call  to test that they are valid it's seems like it would not be many requests.

**Comment by sushmak02** [comment]
@dan98765 I am trying to achieve the same. I will use the "sample business lookup to test the API key" idea for authentication.
Is there any specific response code for an incorrect API key? So, I can match the response code and display the authentication result to the user accordingly.
