### ISSUE TITLE
Business doesn't showing on search API

### ISSUE THREAD

**Issue by webappsllcInfo** [Yelp/yelp-fusion#390]
**Platform:**  iOS

### Endpoint
Fusion Search API

When searching 'Walmart' business with the following  API, it's not showing.
https://api.yelp.com/v3/businesses/search?term=walmart and other params.

But when searching with category wise,  like

https://api.yelp.com/v3/businesses/search?term=walmart&category=department and other params.

than Walmart is showing. So can you please guide us on that.

Here attach the screenshot for that.

![yelp search](https://user-images.githubusercontent.com/36496037/38124209-cc1f0d5a-33fd-11e8-9b3f-42d12cbb5c65.png)

**Comment by virgytam** [comment]
Hi @webappsllcInfo, the location param is required for search. Can you provide the entire search query including location (or lat/lng if you're using that instead)

**Comment by webappsllcInfo** [comment]
Hi @virgytam, Here is search query:

https://api.yelp.com/v3/businesses/search?term=Walmar&latitude=41.1177&longitude=-73.4082&limit=50&radius=20000&sort_by=distance&offset=0

And this is a search query with category-id:

https://api.yelp.com/v3/businesses/search?term=&latitude=41.1177&longitude=-73.4082&limit=50&radius=20000&categories=deptstores&sort_by=distance&offset=0

On searching of Walmart its not showing on the top.
