### ISSUE TITLE
different result in API and online (for moved business)

### ISSUE THREAD

**Issue by sheub** [Yelp/yelp-fusion#392]
## Overview
- **Client ID:** zNoubFwjaxxT_dCbSTiHaA
- **Issue type:** question
- **Summary:** The place 'La Chocolaterie, Leipzig' has recently moved. The online service (www.yelp.com/biz/la-chocolaterie-leipzig) is redirecting to www.yelp.com/biz/la-chocolaterie-leipzig-2 and gives a new page with the correct address. But a search with the API still gives the old business description only and gives the place as closed...

- **Platform:** API

## Question
How long will it take for the API *results* to be updated?
 I have noticed that the result on BingMaps which are probably also relying on the API gives also the place as closed...

### Endpoint
_Fusion Search API_

### Parameters or Sample Request
Search for ' La Chocolaterie, Leipzig'
```
https://api.yelp.com/v3/businesses/search?
```

### Response

```
{
 alias
:
"la-chocolaterie-leipzig"
categories
:
(2) [{…}, {…}]
coordinates
:
{latitude: 51.3429, longitude: 12.3589}
display_phone
:
"+49 341 5611268"
hours
:
[{…}]
id
:
"ZAh2Ko9wukntkKciJHQ-ow"
image_url
:
"https://s3-media1.fl.yelpcdn.com/bphoto/A4GEthm0FIxF0fpRUViujw/o.jpg"
is_claimed
:
false
is_closed
:
true
location
:
{address1: "Waldstr. 12", address2: "", address3: null, city: "Leipzig", zip_code: "04105", …}
name
:
"La Chocolaterie"
}
```

**Comment by dan98765** [comment]
@sheub interesting question. I'm able to reproduce this myself. It appears la-chocolaterie-leipzig moved locations, which creates a new Yelp business. Our www site automatically redirects the old business's url to the new business. We'll discuss what appropriate behavior of the Business Endpoint should be in this situation and get back to you.

**Comment by rubyonrails3** [comment]
@dan98765  I'm having same issues, I'm search for a place `Blue Moon Brewing Company` and I can find from yelp app but when I do this 
`https://api.yelp.com/v3/businesses/search?latitude&longitude&radius=40000&categories=restaurants&sort_by=best_match&location=Denver%2C+CO&limit=50&offset=0&term=blue+moon+brewing` then I get no results with that title.  I need to understand what I'm doing wrong. or how I change API request so I get that business.

**Comment by dan98765** [comment]
@rubyonrails3 https://www.yelp.com/biz/blue-moon-brewing-company-denver does not appear to be moved, nor have 0 reviews, so I don't think there's a clear connection to this issue. Could you please file a new one and we can discuss there?
