### ISSUE TITLE
Is it possible to get the take-out field? Is that the pickup?

### ISSUE THREAD

**Issue by anamariakantar** [Yelp/yelp-fusion#393]
I am after the take-out field, but I can't figure out if this is the equivalent to the pickup field. For example:

https://api.yelp.com/v3/businesses/search?term=Manitas Cafe&location=2078 Hayes St San Francisco

Gives no transactions but I can see that Take-out is Yes

Thanks!

**Comment by butterfield** [comment]
Hi @anamariakantar, the transactions list will only include transaction types that the business uses through Yelp's transactions platform (e.g. if a restaurant allows placing delivery orders via Yelp, then "delivery" will appear in the transactions list). The business you provided does not use Yelp's transactions platform, but they still offer Take-out in general.

The business attributes with Yes/No values (like Take-out, Accepts Credit Cards, etc.) that you see on the [business's Yelp page](https://www.yelp.com/biz/manitas-cafe-and-deli-san-francisco) are not publicly available via Fusion at this time.
