### ISSUE TITLE
Is there a way to include features in the API calls?

### ISSUE THREAD

**Issue by jonross10** [Yelp/yelp-fusion#394]
On the website you can filter results based off of a set of "features" ex. "Liked by 20-somethings", "Good for groups", "Has Coatcheck", etc. I know the API has the attributes parameter which seems similar to this, but it doesn't seem to support the features that the website uses. 

Is there any current way to filter off these values, or is this something that can be looked in to?

**Comment by dan98765** [comment]
Hi @jonross10, good question. Adding more searchable attributes is something we are discussing internally. We'll post an update here once we've decided on a plan.
