### ISSUE TITLE
How to Authorize Access Token

### ISSUE THREAD

**Issue by tapiad** [Yelp/yelp-fusion#399]
## Overview
- **Client ID:** _3U4iejBZ_VJJRSA64z_5VQ_
- **Issue type:** _Feature Request_
- **Summary:** _Every time I try making a request I'm getting an 'UNAUTHORIZED_ACCESS_TOKEN'_
- **Platform:** _Desktop/Web_

## Description
_(I just want it to return a result. I have looked at https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going but still not able to authorize my request._

### Endpoint
_https://api.yelp.com/v3/businesses/search_

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?term=food
```

### Response
```
{
    "error": {
        "code": "UNAUTHORIZED_ACCESS_TOKEN",
        "description": "The access token provided is not currently able to query this endpoint."
    }
}
```

## Extra information
_I have enter my API Key in the request header as followed:_
```
Authorization: Bearer <API Key>
```
What am I doing wrong?

**Comment by dan98765** [comment]
@tapiad I double checked that your client ID 3U4iejBZ_VJJRSA64z_5VQ is valid and active. Could you please go to your https://www.yelp.com/developers/v3/manage_app page and try re-copying over your API key into the header of your request?

If that still doesn't work, please comment here with exactly how your headers look (please redact your actual api key though!).

**Comment by tapiad** [comment]
How do I checkout if my client ID is valid and active?

I'm trying to make a GET Request through Postman and in the 'Headers' I
have this:


*Key:                            Value:*
Authorization               Bearer SKmdkflA...<*API Key*>...KSklfandn

**Comment by tapiad** [comment]
I have figure it out!

The API Key value on https://www.yelp.com/developers/v3/manage_app page is confusing. Since I couldn't copy and paste the API Key I couldn't tell the difference between a capitalize '**I**' and a lower case '**l**' when trying to type out the API Key character per character. They look similar! 
I finally was able to get the API Key by dragging and dropping it into a text editor.

@dan98765 Thanks for your help! :)

**Comment by tapiad** [comment]
@dan98765 The Text Field in which the API Key is located doesn't let you copy it or highlight it. You can try to click and hold and drag down starting for the **API Key** text and going over the text field and you will only be able to copy the **API Key** text. 
The way I was able to _copy_ the API Key was to click and hold on the API Key and drag it to an area where it will let you place like a text editor or a text field on the same page. You may need to double click and then hold the click for you to be able to drag the API Key.
Hope this help!

**Comment by dan98765** [comment]
@tapiad that is quite helpful. We'll change the field setup or add a JS button to copy to clipboard, or something along those lines.

**Comment by tapiad** [comment]
@dan98765 That will be very helpful for future users; thanks again.

**Comment by dan98765** [comment]
Update: we just pushed a minor change to the https://www.yelp.com/developers/v3/manage_app page such that the API Key is no longer in a disabled text field; now it is in a simple <p> tag so should be more easily copy-able.

**Comment by coolwoc** [comment]
@dan98765, I have a similar issue:

With my token I can have access to data from Postman,

but this time I am trying to do a search from my localhost application. 
I get a statusCode 403 + CORS block.

I am using a service in angular1.x
            searchAll: function(Term, Lat, Long) {
                var urlReq = 'https://api.yelp.com/v3/businesses/search?term=' + Term + '&latitude=' + Lat + '&longitude=' + Long;
                var token = 'myToken';
                return $http({
                    method: 'GET',
                    headers: {
                        'Authorization': 'Bearer ' + token
                    },
                    url: urlReq
                });
            }

Any light on this will be awesome!

**Comment by dan98765** [comment]
@coolwoc could you please file a new issue with as much info as possible?

**Comment by coolwoc** [comment]
@dan98765 sure!
