### ISSUE TITLE
403 error (Forbidden) when connecting from WordPress HTTP API

### ISSUE THREAD

**Issue by asitemade4u** [Yelp/yelp-fusion#400]
## Overview
- **Client ID**: p7dcieKpvMlyyc28UnAMcg
- **Issue type**: 403 error (Forbidden) when connecting from WordPress HTTP API
- **Summary**: I get a 403 error when trying to connect from WordPress HTTP API (see code below). I do not get any error when I connect another client (VisualStudio Code + REST Client extension).
I am able to connect to other APIs too (but not using the Bearer authentication method)
- **Platform**: Ubuntu/Linux 16.04 + Docker + WordPress 4.9x

## Description
Here is the code I am using from a WordPress PHP file. Some details:

- I am using a shortcode to pass the ID of the place I am looking for. I checked it and it is good = `starbucks-new-rochelle`.
- I saved the API Token (128 characters) in an Option field. I checked it and it is good
```php
function api_yelp_f($atts)
{
    extract(
        shortcode_atts(
            array(
                'slug' => '',
            ),
            $atts
        )
    );
    $api_data = get_transient('api_yelp_' . $slug);
    if (false === $api_data) {
        // $api_user = get_field('api_user_yelp', 'option');
        $api_key = get_field('api_key_yelp', 'option');
        $url = "https://api.yelp.com/v3/businesses/" . $slug;
        $args = array(
            'headers' => array(
                "Authorization" => "Bearer " . $api_key,
            )
        );
        $response = wp_remote_get($url, $args);
        $http_code = wp_remote_retrieve_response_code($response);
        if ($http_code <> '200') {
            if (is_wp_error($response)) {
                echo 'API error: ' . $response->get_error_message();
            }
            if ($response["code"] = '403') {
                echo 'API error: Forbidden';
            }
            return false;
        }
        $body = wp_remote_retrieve_body($response);
        $body = utf8_encode($body);
        $data = json_decode($body, true);
        if (json_last_error() === JSON_ERROR_NONE) {
            if (!empty($data)) {
                set_transient('api_yelp_' . $slug, $data, 60 * 60);
            } else {
                echo 'JSON error: ' . json_last_error();
            }
        }
    } else {
        $data = $api_data;
    }
    $context = Timber::get_context();
    $context['body'] = $data;
    Timber::render('api-yelp-one.twig', $context);
}
add_shortcode('api_yelp', 'api_yelp_f');
```

## More information
When I execute this request from VisualStudio Code + REST Client, it works perfectly ({{token}} is saved as a variable):
```html
get https://api.yelp.com/v3/businesses/starbucks-new-rochelle
Authorization: Bearer {{token}}
```

### Endpoint
Fusion **Businesses** API

### Parameters or Sample Request
```html
get https://api.yelp.com/v3/businesses/starbucks-new-rochelle
Authorization: Bearer {{token}}
```

### Response
I attach a screen copy:

![selection_001](https://user-images.githubusercontent.com/11460106/38627901-0bfacaac-3d7e-11e8-9182-29a4ec6b446b.png)

**Comment by watterso** [comment]
Hi @asitemade4u ,

As discussed in #218 we do block all requests coming from wordpress integrations, so that is what is causing this HTTP 403. There are no plans to change this policy.

**Comment by meech-ward** [comment]
@watterso I'm sure there's a good reason to block all requests coming from WordPress integrations, but I'm not sure what this reason is. Would you be able to explain it to me, please?

**Comment by raphaelparent** [comment]
I haven't stumbled on the reason why this is the case and the silence from Yelp is concerning me a little bit. 

Wordpress is one of the most used platforms for content management on the web and I believe a lot of people would benefit from at least knowing why you decided to go that route, for I am sure there is a decent explanation.
