### ISSUE TITLE
Weird behaviour of Yelp API

### ISSUE THREAD

**Issue by AmitMirgal** [Yelp/yelp-fusion#401]
## Overview

Used Fusion Business Search API to get the businesses. Following are the parameters latitude, longitude, and radius... Tried with different radius value too... Still not able to resolve. 

### Parameters or Sample Request

https://api.yelp.com/v3/businesses/search?latitude=43.72397639999999&longitude=-79.2896841&radius=100

## Extra information
Expected to get **Marshalls 808 Warden Ave, Toronto, ON M1L 4T7** result too.

**Comment by watterso** [comment]
Hi @AmitMirgal,

If you are looking for that specific Marshalls, try using the `term` parameter (more info in [the search docs](https://www.yelp.com/developers/documentation/v3/business_search)) setting it equal to `Marshalls`.

Let me know how that turns out

**Comment by AmitMirgal** [comment]
@watterso It works after adding term parameter...Thanks... but I would love to know why the API works in this way...

**Comment by watterso** [comment]
@AmitMirgal , I'm glad it worked! You could've probably eventually found the Marshall's using the `offset` and `limit` parameters, but when using the search api, the more specific your query the better.
