### ISSUE TITLE
Issue with hours array in businesses response

### ISSUE THREAD

**Issue by jonross10** [Yelp/yelp-fusion#402]
## Overview
- **Issue type:** bug I think? not sure if I'm just missing something or not.
- **Summary:** Querying the business api, but returned hours array doesn't appear to offset indices for each day.
- **Platform:** Node

## Description
I'm querying the business endpoint to try to get the hours for various businesses on yelp. This business (id: QOJG4Uomx527hTjQwMkgzA) is only open for 4 days of the week and is closed Sunday, Monday and Tuesday. [Link](https://www.yelp.com/biz/stem-minneapolis?adjust_creative=DmYz04lhxTJerbt3SmUeig&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=DmYz04lhxTJerbt3SmUeig). When it returns the hours, I would expect the response to include maybe a null or an empty object in the array for indices 0,1 and 6 and then the correct hours object for indices 2-5. 

What I get instead is an array with just 4 objects indicating the hours for Wednesday through Saturday. There doesn't seem to be a correct way to determine (from this response object) which object refers to which day. I know how it lines up, since I looked at it on the webpage, but just from the response you can't really determine the hours.

Is there a way to include null or an empty object in the array for the missing days?

### Endpoint
 Fusion Business API

### Response
_The full JSONbody response
```
{ id: 'QOJG4Uomx527hTjQwMkgzA',
   alias: 'stem-minneapolis',
   name: 'Stem',
   image_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/IUPdjIaTGpDL64MxzO1T_w/o.jpg',
   is_claimed: true,
   is_closed: false,
   url: 'https://www.yelp.com/biz/stem-minneapolis?adjust_creative=DmYz04lhxTJerbt3SmUeig&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=DmYz04lhxTJerbt3SmUeig',
   phone: '+16129000021',
   display_phone: '(612) 900-0021',
   review_count: 73,
   categories: 
      [ { alias: 'wine_bars', title: 'Wine Bars' },
      { alias: 'tapasmallplates', title: 'Tapas/Small Plates' },
      { alias: 'cocktailbars', title: 'Cocktail Bars' } ],
   rating: 4,
   location: 
      { address1: '24 University Ave NE',
         address2: 'Ste 125',
         address3: '',
         city: 'Minneapolis',
         zip_code: '55413',
         country: 'US',
         state: 'MN',
         display_address: [ '24 University Ave NE', 'Ste 125', 'Minneapolis, MN 55413' ],
         cross_streets: '' },
   coordinates: { latitude: 44.98865, longitude: -93.25735 },
   photos: 
      [ 'https://s3-media1.fl.yelpcdn.com/bphoto/IUPdjIaTGpDL64MxzO1T_w/o.jpg',
         'https://s3-media4.fl.yelpcdn.com/bphoto/E4FAdaT1d3qP9lcBv46Xxg/o.jpg',
         'https://s3-media1.fl.yelpcdn.com/bphoto/B2V2-RcEX9Y40E7Pb9hYSA/o.jpg' ],
   price: '$$',
   hours: [ { open: [Object], hours_type: 'REGULAR', is_open_now: false } ],
   transactions: [ 'restaurant_reservation' ] 
}
```
_The hours object_
```
[ { open: [ [Object], [Object], [Object], [Object] ],
     hours_type: 'REGULAR',
     is_open_now: false 
} ]

```

**Comment by watterso** [comment]
Hi @jonross10 ,
I'd like to draw your attention to the `hours[x].open[x].day` field in the [business lookup docs](https://www.yelp.com/developers/documentation/v3/business). This is the field that is used to identify to which day the hours in the `open` list apply. Let me know if you other questions about hours.

**Comment by jonross10** [comment]
So if I wanted to get the start time of a business for a specific day, I would have to iterate over the entire open array and find the open[x].day field that matches the day I'm looking for? That doesn't seem exactly efficient. Do you know if there is a reason why the hour objects aren't mapped to an index indicative of the day it applies to?

**Comment by watterso** [comment]
Thats correct you would iterate over the array :)

The benefit of having the open hours be in a list really comes from the fact that businesses can have multiple hours per day for businesses. For example a restaurant might open for lunch, close, then open again for dinner, or a small professional services firm might close for lunch during the day.

In the end the inefficiency isn't that large as these lists will never be 'big data' (I can't imagine a business having hundreds of thousands of hours data). So a look up from iterating over an array won't be that much more inefficient than a map lookup (_maybe_ milliseconds slower). If you find the timings important for your integration you could build an index on your end.

P.S. you might find `open_now` and the `open_at` parameters to [business_search](https://www.yelp.com/developers/documentation/v3/business_search) helpful
