### ISSUE TITLE
Error 400 no generic error

### ISSUE THREAD

**Issue by coolboiime** [Yelp/yelp-fusion#403]
## Overview
- **Client ID:**jyHeS_MVualewtI_Ab4wHg
- **Issue type:** question, bug
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** react native/apollo client

## Description
Trying to do a business search, but get's error 400 instead with no reason why.

### Endpoint
Fusion Search API

### Parameters or Sample Request
```
this.client = new ApolloClient({
	uri: 'https://api.yelp.com/v3/graphql',
	request: (operation) => {
		operation.setContext({
			headers: {
				Authorization: `Bearer ${API_KEY}`,
				"Content-Type": 'application/graphql',
			}
		})
	},
	cache: new InMemoryCache(),
});
```

### Response
```
[Network error]: Error: Response not successful: Received status code 400
```

## Extra information
Error information from remote js debugger (react native)

**Comment by coolboiime** [comment]
This is the query we're making. We also tried it in a test, and that worked.
```
const query = gql`
{
  search(location: "san francisco") {
    total
    business {
      name
    }
  }
}
```

**Comment by teekwak** [comment]
Query looks good to me. Just tested myself as well via command-line.

I see that you are using React-Native. Correct me if I am wrong, but your code snippet seems to be creating the ApolloClient in a React component. If so, this will cause a CORS error when the ApolloClient makes the fetch request, which we do not currently support (see https://github.com/Yelp/yelp-fusion/issues/64 for workarounds to this issue).

**Comment by coolboiime** [comment]
I found that the request isn’t being created inside a React component.

The component calls the function which the function loads the class via an instance.
