### ISSUE TITLE
[Feature request] Return Yelp deals in business search or business details

### ISSUE THREAD

**Issue by Gear61** [Yelp/yelp-fusion#405]
## Overview
- **Issue type:** Feature request
- **Summary:** It would be awesome if the API returned deal information; I remember it being in v2 of the API. It would also provide my app without another reason to link into Yelp, since the deal needs to be redeemed there.

### Endpoint
https://api.yelp.com/v3/businesses/search or https://api.yelp.com/v3/businesses/{id}

**Comment by dan98765** [comment]
As per #14 and #360 we still have no current plans to add deals information in the v3 (Fusion) API.
