### ISSUE TITLE
Double values in category API

### ISSUE THREAD

**Issue by angelaki** [Yelp/yelp-fusion#408]
For the following request [https://api.yelp.com/v3/categories](url) multiple categories get listed twice (e.g. "recreation", index 7, 1317)

Furthermore it's distinct count does not match the current Json [https://www.yelp.com/developers/documentation/v3/all_category_list/categories.json](url): Json contains 1539 entries, while API provides 1269.

**Comment by dan98765** [comment]
Thanks for opening this issue, @angelaki! I've filed an internal ticket about this and we'll take a look at this behavior.

**Comment by dan98765** [comment]
A fix to remove the duplicates is live now; the response sizes are more in-line with what we'd expect now.
