### ISSUE TITLE
Transactions returned via API not the same as Web Results

### ISSUE THREAD

**Issue by joealfaro** [Yelp/yelp-fusion#409]
## Overview
- **Client ID:** EmlCardOVRoYkW4B95aT3A
- **Issue type:** Bug/Question
- **Summary:** I am calling the Business Details API to get information about a known business. In particular, I am interested in the "Transactions" field for this call. The API call succeeds and returns 1 Transaction. If I search for the business on the web I see 22 "Transactions". How do I get access to all the transactions?
- **Platform:** Web / Curl

## Description
I call the Business Details API to get information about "Gary Danko". As you can see from the response below, I get 1 "Transaction" = restaurant_reservation.

If I find Gary Danko on the web, I see the following "Transactions". How can I get access to this data?

Takes Reservations **Yes**
Delivery **No**
Take-out **No**
Accepts Credit Cards **Yes**
Accepts Apple Pay **No**
Accepts Android Pay **No**
Good For **Dinner**
Parking **Valet**
Bike Parking **No**
Wheelchair Accessible **Yes**
Good for Kids **No**
Good for Groups **Yes**
Attire **Dressy**
Ambience **Classy, Upscale**
Noise Level **Average**
Alcohol **Full Bar**
Outdoor Seating **No**
Wi-Fi **No**
Has TV **No**
Waiter Service **Yes**
Caters **No**
Gender Neutral Restrooms **Yes**

### Endpoint
Fusion Business Details API

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/WavvLdfdP6g8aZTtbBQHTw

### Response
{
  "id": "WavvLdfdP6g8aZTtbBQHTw", 
  "alias": "gary-danko-san-francisco", 
  "name": "Gary Danko", 
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/NCX50ST3Hjg7y8wTcwQXog/o.jpg", 
  "is_claimed": true, 
  "is_closed": false, 
  "url": "https://www.yelp.com/biz/gary-danko-san-francisco?adjust_creative=EmlCardOVRoYkW4B95aT3A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=EmlCardOVRoYkW4B95aT3A", 
  "phone": "+14157492060", 
  "display_phone": "(415) 749-2060", 
  "review_count": 4730, 
  "categories": [
    {
      "alias": "newamerican", 
      "title": "American (New)"
    },
   {
      "alias": "french", 
      "title": "French"
    }, 
   {
      "alias": "wine_bars", 
      "title": "Wine Bars"
   }
  ], 
  "rating": 4.5,
  "location": {
      "address1": "800 N Point St", 
      "address2": "", 
      "address3": "", 
      "city": "San Francisco", 
      "zip_code": "94109", 
      "country": "US", 
      "state": "CA", 
      "display_address": [
          "800 N Point St", 
          "San Francisco, CA 94109"
       ], 
  "cross_streets": ""
  }, 
  "coordinates": {
      "latitude": 37.80587, 
      "longitude": -122.42058
  }, 
  "photos": [
      "https://s3-media2.fl.yelpcdn.com/bphoto/NCX50ST3Hjg7y8wTcwQXog/o.jpg", "https://s3-media1.fl.yelpcdn.com/bphoto/FPKISqnxIvdOI20JGyRSwQ/o.jpg", 
      "https://s3-media3.fl.yelpcdn.com/bphoto/n_0M2diQx5D707rXqu8mRw/o.jpg"
  ], 
  "price": "$$$$", 
  "hours": [
    {
      "open": [
      {
           "is_overnight": false, 
          "start": "1730", 
          "end": "2200", 
          "day": 0
      }, 
     {
          "is_overnight": false, 
           "start": "1730", 
           "end": "2200", 
           "day": 1
      }, 
      {
           "is_overnight": false, 
           "start": "1730", 
           "end": "2200", 
           "day": 2
      }, 
      {
           "is_overnight": false, 
           "start": "1730", 
           "end": "2200", 
           "day": 3
      }, 
      {
           "is_overnight": false, 
           "start": "1730", 
           "end": "2200", 
           "day": 4
      }, 
      {
           "is_overnight": false, 
           "start": "1730", 
           "end": "2200", 
           "day": 5
      }, 
      {
           "is_overnight": false, 
           "start": "1730", 
           "end": "2200", 
           "day": 6
      }
    ], 
    "hours_type": "REGULAR", 
    "is_open_now": false
   }
  ], 
"transactions": ["restaurant_reservation"]
}

**Comment by umair-tp** [comment]
As per this https://www.yelp.com/developers/documentation/v3/transaction_search the transaction field of Business details returns  

> A list of Yelp transactions that the business is registered for. Current supported values are "pickup", "delivery", and "restaurant_reservation"

And not the actual transactions. Maybe to get transactions you need this https://www.yelp.com/developers/documentation/v3/transaction_search

**Comment by joealfarotule** [comment]
Thanks umber-tp. I did read the documentation and know that it says the values are limited. I was just wondering if there is any way to get at the other values. They're clearly there as we see them on the Yelp web page. Why do we not have access to them via API?
I also saw the 'transaction_search' endpoint but this does not give me what I want either :(

**Comment by butterfield** [comment]
Hi @joealfaro, @umair-tp and the documentation are correct in saying that the only values you can expect to see in the list under the "transactions" key are "pickup", "delivery", and "restaurant_reservation". These values describe which offerings of the Yelp transactions platform are available for this biz.

The list you provided ("Takes Reservations" through "Gender Neutral Bathrooms") are more general business attributes that are not publicly available via Fusion at this time.

**Comment by athersharif** [comment]
@butterfield @joealfaro I understand that this issue is closed now but it's possible to filter out such attributes by using the `attributes` request parameter as mentioned in the [docs](https://www.yelp.com/developers/documentation/v3/business_search). However, the attributes list doesn't cover all the attributes that we see on a yelp business page. Guessing the Yelp devs are working on it?
