### ISSUE TITLE
location vs coordinate return diffrante results

### ISSUE THREAD

**Issue by galskari** [Yelp/yelp-fusion#41]
When quering the API with https://api.yelp.com/v3/businesses/search?term=florists&location=222+N+Columbus+Dr+Chicago

we get a diffrent result from the list that the web interface of yelp.com returns. This discrepancy is a little odd. Is this an expected behaviour?

Thanks in advance

**Comment by mittonk** [comment]
@galskari : Could you include what you see from the API, and what differences you're concerned about?

**Comment by mittonk** [comment]
No response, closing.
