### ISSUE TITLE
Can't lookup business by alias in v3

### ISSUE THREAD

**Issue by dwhalenenr** [Yelp/yelp-fusion#410]
## Overview
- **Client ID:** Zl1UQFRW8_AtyLURvddkUQ
- **Issue type:** bug / question
- **Summary:**  I can't access a business' profile using /v3/businesses/{alias}/
- **Platform:** Web / API

## Description
I have Yelp pages in a database using their ALIAS, rather than their ID.  I could query them in v2 by calling /v2/business/{alias}.   When I make calls to /v3/businesses/{alias}/ I get an error

### Endpoint
/v3/businesses/{alias}

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/steven-hara-koeingrubloff-realty-northbrook

returns an error, even though the yelp page exists and has a review.

### Response
{"error": {"code": "BUSINESS_NOT_FOUND", "description": "The requested business could not be found."}}

## Extra information
This is essential for people like myself that never had the Yelp ID to begin with.  In fact, I can't even translate an alias to an id without this call working.  So, please help me!

**Comment by dan98765** [comment]
Hi @dwhalenenr thanks for the details, and for confirming the yelp page exists and has a review and so should be accessible via the Fusion API. 

I'm having difficulty reproducing this issue. The `v3/businesses/{business_id}` endpoint accepts a business_id of either a business alias or the unique 22 character business ID, so it should work fine for this use case. When I make the request:
```
https://api.yelp.com/v3/businesses/steven-hara-koeingrubloff-realty-northbrook
```
I get back the expected business results for it:
```
{
	"id": "uvlNBYGtoMG_2I02kEzS_Q",
	"alias": "steven-hara-koeingrubloff-realty-northbrook",
	"name": "Steven Hara - KoeingRubloff Realty",
        ... <other fields> ....
}
```
For reference this is the www page for this business: https://www.yelp.com/biz/steven-hara-koeingrubloff-realty-northbrook

Business aliases may have unicode characters in them, which can sometimes be challenging to encode in a URL. However there are no unicode characters in this business alias. I'll dig a bit more and see if I can figure out what happened with your request to make it return a 404.

**Comment by dan98765** [comment]
@dwhalenenr could you please check that your request is:
```
https://api.yelp.com/v3/businesses/steven-hara-koeingrubloff-realty-northbrook
```
and not
```
https://api.yelp.com/v3/businesses/steven-hara-koeingrubloff-realty-northbrook.json
```
? 

Our system will think the .json at the end is part of the alias, and return a 404 since there is no business with that alias.

**Comment by dwhalenenr** [comment]
Hi Dan.

I think you found it!  Wow I never noticed that was in there. I “borrowed” a curl function from another api wrapper we had.

Thanks for digging deeper for me. Saved me a big headache.

I notice that I still can’t load a profile if a page has no reviews. Any hope of opening that up so I can at least translate my ids and maybe verify the business name?

Thanks again!

David Whalen

Sent from my iPhone

On Apr 28, 2018, at 12:03 AM, Dan <notifications@github.com<mailto:notifications@github.com>> wrote:


@dwhalenenr<https://github.com/dwhalenenr> could you please check that your request is:

https://api.yelp.com/v3/businesses/steven-hara-koeingrubloff-realty-northbrook


and not

https://api.yelp.com/v3/businesses/steven-hara-koeingrubloff-realty-northbrook.json


?

Our system will think the .json at the end is part of the alias, and return a 404 since there is no business with that alias.

**Comment by dan98765** [comment]
Glad to hear that it's working now! 

> I notice that I still can’t load a profile if a page has no reviews. Any hope of opening that up so I can at least translate my ids and maybe verify the business name?
Unfortunately we can not return business information for businesses with 0 reviews at this time. However, if you have time I'd appreciate if you could explain why you need those results so we can think about your use case while planning for the future. 

What is the minimum amount of business info you'd need to translate your ids/verify biz name? Are you just hoping to know if some input business alias maps to an active, but unreviewed, business (i.e. just need a boolean true/false)? What's the data used for in the application/service/project you're building?
