### ISSUE TITLE
Trying to access the photos in the GraphQL API result in an error

### ISSUE THREAD

**Issue by PhilippeRiegert** [Yelp/yelp-fusion#415]
## Overview
- **Issue type:** Bug
- **Summary:** Trying to get the `photos` in the GraphQL API result in an error
- **Platform:** Desktop/web, iOS

## Description
When you try to access `photos` in the graphQL api it return an error: 
`GraphQLScalarType' object has no attribute 'graphene_type`

### Endpoint
Fusion GraphQL API

### Sample Request
```
{
  business(id: "garaje-san-francisco") {
    photos
  }
}
```
You can try this request in the Yelp Graphiql console:
https://www.yelp.com/developers/graphiql?query=%7B%0A%20%20business(id%3A%20%22garaje-san-francisco%22)%20%7B%0A%20%20%20%20photos%0A%20%20%7D%0A%7D

### Response
```
{
  "errors": [
    {
      "message": "'GraphQLScalarType' object has no attribute 'graphene_type'",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ],
  "data": {
    "business": {
      "photos": null
    }
  }
}
```

**Comment by dan98765** [comment]
Hi @PhilippeRiegert thanks for filing this issue. Sounds like a pretty clear bug to me; we really appreciate these kinds of reports especially while the GraphQL API is in beta. I'll file a ticket internally and we'll look into it.

**Comment by pbadeer** [comment]
We're getting this error as well, happy to contribute details if it helps.

**Comment by pbadeer** [comment]
This appears to be fixed for me.

**Comment by dan98765** [comment]
@pbadeer I've pushed out a fix for the immediate issue with `photos` just now, but found a related issue with `reviews` that I'm also fixing now/improving test coverage.

**Comment by dan98765** [comment]
Tests and test queries are looking good now. Thanks again @PhilippeRiegert for opening this issue and @pbadeer for confirming.
