### ISSUE TITLE
Would be great to have wheelchair_accessible as an attribute

### ISSUE THREAD

**Issue by athersharif** [Yelp/yelp-fusion#417]
## Overview
- **Client ID:** 3M-50htEnUgR9ZbbPkkAJQ
- **Issue type:** feature request
- **Summary:** Would be great to have `wheelchair_accessible` attribute available for `attributes` [here](https://www.yelp.com/developers/documentation/v3/business_search)
- **Platform:** Desktop/web

## Description
The list of `attributes` does not include all the attributes that we're able to see on a business' Yelp page. Would be great to add more to the list, specifically `wheelchair_accessible`.

### Endpoint
/businesses/search

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?attributes="wheelchair_accessible"
```

**Comment by watterso** [comment]
Hey @athersharif, thanks for the suggestion! I've gone ahead and started a discussion about this idea internally.

**Comment by athersharif** [comment]
@watterso thanks! let me know if I can help in any way. 

couple of other suggestions as well (can create separate issues, if you like):

- allow for the attribute search to have the `or` property. as of now, it's the `and` behavior.
- allow for the attributes to be returned as part of the response. this can potentially even address the above-mentioned suggestion and this issue as well, giving users the ability to filter out as necessary. :)

and while i have your attention, any plans of open sourcing the api? would love to contribute! happy to write a React HOC also.

**Comment by watterso** [comment]
I would encourage you to open separate issues for separate issues keeps the noise down when people want to discuss particular points :)

What do you mean by open sourcing? Alot of what we use to run the api is open source (more on [Yelp Open Source](https://yelp.github.io/)), but the code that makes the connection from our databases / services to the outside world is unlikely too ever be open source (and wouldn't actually be that useful).

**Comment by athersharif** [comment]
@watterso any update on this?

**Comment by dan98765** [comment]
Hi @athersharif, sorry for the delay! Internal discussion on this is still ongoing and we'll update again here soon.

**Comment by watterso** [comment]
Heads up @athersharif you can now filter search results for Wheelchair Accessible businesses :)
See more on the [changelog](https://www.yelp.com/developers/v3/changelog#changelog-20181130) or hit this url:
```
https://api.yelp.com/v3/businesses/search?location=sf&attributes=wheelchair_accessible
```

**Comment by athersharif** [comment]
just saw this - great news! thanks @watterso!
