### ISSUE TITLE
access the number of check-ins a business has

### ISSUE THREAD

**Issue by je-lopez** [Yelp/yelp-fusion#419]
## Overview
- **Issue type:** question, request
- **Summary:** business check-ins count

## Description
Is there a way to access the number of check-ins a business has?

### Endpoint
Fusion Search API

## Extra information
Including a date, and how many of those check-ins were shared on Twitter and Facebook would be useful as well.

**Comment by teekwak** [comment]
Hi @je-lopez,

We currently do not have a way of accessing the number of check-ins that a business has. I've filed a ticket for this internally, so we will continue to track it from there!

**Comment by je-lopez** [comment]
@teekwak Thanks! I can't imagine this would have high priority. Is this something I could do?

**Comment by watterso** [comment]
Appreciate the enthusiasm @je-lopez , but no sadly there is nothing to be done on your end :(
