### ISSUE TITLE
Validation Erro

### ISSUE THREAD

**Issue by MalcolmTJames** [Yelp/yelp-fusion#420]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(eg. feature request, bug, question, etc)_
- **Summary:** _I'm trying to create a more narrow search to find Vegetarian or Vegan restaurants _
- **Platform:** _(Desktop/web)_

## Description
_I'm trying to get a list of business that has Vegetarian options _

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
https://api.yelp.com/v3/businesses/search?term=lunch&categories=Vegetarian,Vegan,&latitude=42.6861&longitude=-73.8239&sort_by=best_match

### Response
{
    "error": {
        "code": "VALIDATION_ERROR",
        "description": "'' is too short",
        "field": null,
        "instance": ""
    }
}

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by teekwak** [comment]
Hi @MalcolmTJames,

Looks like you have an extra comma after "Vegan" in your categories query parameter. Removing that should fix things.
