### ISSUE TITLE
API returns ACCESS_LIMIT_REACHED

### ISSUE THREAD

**Issue by ilanfrai** [Yelp/yelp-fusion#423]
## Overview
- **Client ID:** 2bHSZhM0huV8LRh3YHaOSQ
- **Issue type:** bug
- **Summary:** API returns ACCESS_LIMIT_REACHED although quota has not been reached
- **Platform:** any platform

## Description
We have a daily limit of 40K calls. Every time we reach around 23K remaining calls we start getting ACCESS_LIMIT_REACHED from your API. Two days ago when we started to see it in the logs I did a cUrl from my Mac which reproduced this (see cUrl below). In the fusion web interface I saw 22K remaining calls and the cUrl returned ACCESS_LIMIT_REACHED.
In case you want o check your logs, our IP (from which I performed the cUrl call) is : 141.226.237.84

### Parameters or Sample Request
```
curl -X POST -H "Authorization: Bearer OUR_API_KEY" -H "Content-Type: application/graphql" https://api.yelp.com/v3/graphql --data '
 {
     test: search(term: "burrito",
             location: "san francisco",
             limit: 5) {
         total
         business {
             name
             url
         }
     }
 }'
```

**Comment by Valectar** [comment]
This should be fixed, now you should be able to your fully daily limit in graphql requests.
