### ISSUE TITLE
please tell  me  what version of ssl/tls is supported?

### ISSUE THREAD

**Issue by PengXiaolong123** [Yelp/yelp-fusion#427]
please tell  me  what version of ssl/tls is supported?
Thanks a lot!

**Comment by dan98765** [comment]
Hi @PengXiaolong123:
```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
```
You can find this and a lot more information on [ssllabs.com SSL Report for api.yelp.com](https://www.ssllabs.com/ssltest/analyze.html?d=api.yelp.com).

One additional note: although we currently still support TLS <1.2, we plan to drop support at some point, hopefully soon. So for anyone reading this message from the future, please use TLS >=1.2.
