### ISSUE TITLE
Reviews are not coming along with business/search api

### ISSUE THREAD

**Issue by dineshgautam22** [Yelp/yelp-fusion#431]
Hi Yelp

According to you "we don't return data for businesses without reviews. This is mentioned at the top of the documentation page: https://www.yelp.com/developers/documentation/v3/business_search, "Note: at this time, the API does not return businesses without any reviews."

But I just run the yelp api, I am not getting review list for the business in V3 api version, but in the V2 I was getting the review list.

Please let me know if there is special parameter need to add in request to get review in the response?

**Comment by watterso** [comment]
Hi @dineshgautam22 I'm gonna need more information to dig into this. Could you provide me:
* your `client_id`
* the api call you are making (be sure to redact your API Key if necessary)
* the response from the api call

**Comment by dineshgautam22** [comment]
I am not using `client_id` anywhere in the code, I am just calling the below api "https://api.yelp.com/v3/businesses/search" with api key authentication.

And I am getting below response:
`{
    businesses =     (
                {
            alias = "yayoi-cupertino";
            categories =             (
                                {
                    alias = japanese;
                    title = Japanese;
                },
                                {
                    alias = comfortfood;
                    title = "Comfort Food";
                }
            );
            coordinates =             {
                latitude = "37.337110507689";
                longitude = "-122.036201704747";
            };
            "display_phone" = "(408) 564-8852";
            distance = "1773.042455490575";
            id = SMVEtOV6PG467oZqyNRhAw;
            "image_url" = "https://s3-media4.fl.yelpcdn.com/bphoto/GVivqEV5C1vGaVsYze5Tlw/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "20682 Homestead Rd";
                address2 = "<null>";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "20682 Homestead Rd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = YAYOI;
            phone = "+14085648852";
            price = "$$";
            rating = 4;
            "review_count" = 403;
            transactions =             (
                "restaurant_reservation"
            );
            url = "https://www.yelp.com/biz/yayoi-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "the-city-fish-cupertino";
            categories =             (
                                {
                    alias = sandwiches;
                    title = Sandwiches;
                },
                                {
                    alias = seafood;
                    title = Seafood;
                },
                                {
                    alias = fishnchips;
                    title = "Fish & Chips";
                }
            );
            coordinates =             {
                latitude = "37.3227601469653";
                longitude = "-122.053648956402";
            };
            "display_phone" = "(408) 320-1434";
            distance = "944.488340204203";
            id = 71smT9Rw7HVv9fXLLiUdhw;
            "image_url" = "https://s3-media1.fl.yelpcdn.com/bphoto/1o4t-4G6FWoYG7o23Mw8JQ/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "21678 Stevens Creek Blvd";
                address2 = "";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "21678 Stevens Creek Blvd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "The City Fish";
            phone = "+14083201434";
            price = "$$";
            rating = "4.5";
            "review_count" = 471;
            transactions =             (
                pickup
            );
            url = "https://www.yelp.com/biz/the-city-fish-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "lazy-dog-restaurant-and-bar-cupertino";
            categories =             (
                                {
                    alias = newamerican;
                    title = "American (New)";
                },
                                {
                    alias = burgers;
                    title = Burgers;
                },
                                {
                    alias = comfortfood;
                    title = "Comfort Food";
                }
            );
            coordinates =             {
                latitude = "37.3234666014751";
                longitude = "-122.00862669582";
            };
            "display_phone" = "(408) 359-4690";
            distance = "3043.164453690785";
            id = "h_pdXO0TiXjVPJ-tXPvYLg";
            "image_url" = "https://s3-media2.fl.yelpcdn.com/bphoto/Z8fXHXIyU6maxQv0sCbt8g/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "19359 Stevens Creek Blvd";
                address2 = "";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "19359 Stevens Creek Blvd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Lazy Dog Restaurant & Bar";
            phone = "+14083594690";
            price = "$$";
            rating = 4;
            "review_count" = 1564;
            transactions =             (
                delivery
            );
            url = "https://www.yelp.com/biz/lazy-dog-restaurant-and-bar-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "red-hot-wok-cupertino";
            categories =             (
                                {
                    alias = chinese;
                    title = Chinese;
                },
                                {
                    alias = taiwanese;
                    title = Taiwanese;
                }
            );
            coordinates =             {
                latitude = "37.3220766185619";
                longitude = "-122.014959059792";
            };
            "display_phone" = "(408) 996-2999";
            distance = "2479.500864669359";
            id = "NZPHTkXarsLEbZlnyieD-Q";
            "image_url" = "https://s3-media4.fl.yelpcdn.com/bphoto/J4n66daJwN9tjw_7E64t7g/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "10074 E Estates Dr";
                address2 = "";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "10074 E Estates Dr",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Red Hot Wok";
            phone = "+14089962999";
            price = "$$";
            rating = 4;
            "review_count" = 991;
            transactions =             (
                pickup
            );
            url = "https://www.yelp.com/biz/red-hot-wok-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "gochi-japanese-fusion-tapas-cupertino";
            categories =             (
                                {
                    alias = japanese;
                    title = Japanese;
                },
                                {
                    alias = tapas;
                    title = "Tapas Bars";
                }
            );
            coordinates =             {
                latitude = "37.3368621985872";
                longitude = "-122.022732496261";
            };
            "display_phone" = "(408) 725-0542";
            distance = "2429.436382684846";
            id = d21yLIv0j4Cc2WVNsQAmZw;
            "image_url" = "https://s3-media2.fl.yelpcdn.com/bphoto/uN3aEULD68EXS5PIWcV7FQ/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "19980 E Homestead Rd";
                address2 = "";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "19980 E Homestead Rd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Gochi Japanese Fusion Tapas";
            phone = "+14087250542";
            price = "$$$";
            rating = 4;
            "review_count" = 1781;
            transactions =             (
            );
            url = "https://www.yelp.com/biz/gochi-japanese-fusion-tapas-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "galp\U00e3o-gaucho-brazilian-steakhouse-cupertino-3";
            categories =             (
                                {
                    alias = brazilian;
                    title = Brazilian;
                },
                                {
                    alias = bars;
                    title = Bars;
                }
            );
            coordinates =             {
                latitude = "37.3227351";
                longitude = "-122.0191573";
            };
            "display_phone" = "(408) 366-2370";
            distance = "2090.007455290754";
            id = 228MtApQZsrGTHy8psMmiw;
            "image_url" = "https://s3-media2.fl.yelpcdn.com/bphoto/8Co7lv8jW01z-rA4Cwlncg/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "19780 Stevens Creek Blvd";
                address2 = "";
                address3 = "<null>";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "19780 Stevens Creek Blvd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Galp\U00e3o Gaucho Brazilian Steakhouse";
            phone = "+14083662370";
            price = "$$$";
            rating = "4.5";
            "review_count" = 204;
            transactions =             (
                "restaurant_reservation"
            );
            url = "https://www.yelp.com/biz/galp%C3%A3o-gaucho-brazilian-steakhouse-cupertino-3?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "eureka-cupertino";
            categories =             (
                                {
                    alias = newamerican;
                    title = "American (New)";
                },
                                {
                    alias = burgers;
                    title = Burgers;
                },
                                {
                    alias = bars;
                    title = Bars;
                }
            );
            coordinates =             {
                latitude = "37.3233788180085";
                longitude = "-122.009085416794";
            };
            "display_phone" = "(669) 266-6752";
            distance = "3002.179236189365";
            id = hrtNDDOfwMy6z2WUJlJEeg;
            "image_url" = "https://s3-media2.fl.yelpcdn.com/bphoto/YZk7TadIMMhT6v22n0-wBg/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "19369 Stevens Creek Blvd";
                address2 = "Ste 130";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "19369 Stevens Creek Blvd",
                    "Ste 130",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Eureka!";
            phone = "+16692666752";
            price = "$$";
            rating = 4;
            "review_count" = 571;
            transactions =             (
            );
            url = "https://www.yelp.com/biz/eureka-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "alexanders-steakhouse-cupertino-cupertino";
            categories =             (
                                {
                    alias = steak;
                    title = Steakhouses;
                },
                                {
                    alias = "wine_bars";
                    title = "Wine Bars";
                }
            );
            coordinates =             {
                latitude = "37.3233674576911";
                longitude = "-122.009842804904";
            };
            "display_phone" = "(408) 446-2222";
            distance = "2935.222131548392";
            id = fTeiio1L2ZBIRdlzjdjAeg;
            "image_url" = "https://s3-media1.fl.yelpcdn.com/bphoto/jtKdQ9qwui8zEhgRt_V4MA/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "19379 Stevens Creek Blvd";
                address2 = "<null>";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "19379 Stevens Creek Blvd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Alexander's Steakhouse - Cupertino";
            phone = "+14084462222";
            price = "$$$$";
            rating = 4;
            "review_count" = 3362;
            transactions =             (
            );
            url = "https://www.yelp.com/biz/alexanders-steakhouse-cupertino-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "coconuts-fish-caf\U00e9-cupertino";
            categories =             (
                                {
                    alias = hawaiian;
                    title = Hawaiian;
                },
                                {
                    alias = fishnchips;
                    title = "Fish & Chips";
                }
            );
            coordinates =             {
                latitude = "37.3225549566322";
                longitude = "-122.023540847003";
            };
            "display_phone" = "(408) 216-9553";
            distance = "1721.348862091601";
            id = TqNUz6wbAEJ5Dex1VOkgOg;
            "image_url" = "https://s3-media2.fl.yelpcdn.com/bphoto/5zKWG4yHUnMrbEmBGvKwaA/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "20010 Stevens Creek Blvd";
                address2 = "";
                address3 = "<null>";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "20010 Stevens Creek Blvd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Coconut's Fish Caf\U00e9";
            phone = "+14082169553";
            price = "$$";
            rating = 4;
            "review_count" = 344;
            transactions =             (
                delivery,
                pickup
            );
            url = "https://www.yelp.com/biz/coconuts-fish-caf%C3%A9-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        },
                {
            alias = "tofu-plus-cupertino";
            categories =             (
                                {
                    alias = korean;
                    title = Korean;
                },
                                {
                    alias = bbq;
                    title = Barbeque;
                }
            );
            coordinates =             {
                latitude = "37.3361560447221";
                longitude = "-122.015085853636";
            };
            "display_phone" = "(408) 777-0900";
            distance = "2920.777275142649";
            id = "l5xYUGbX6EOzLGz_bgVr5w";
            "image_url" = "https://s3-media3.fl.yelpcdn.com/bphoto/o7pEeNCQ8FP2kmbtTEL6og/o.jpg";
            "is_closed" = 0;
            location =             {
                address1 = "10971 N Wolfe Rd";
                address2 = "";
                address3 = "";
                city = Cupertino;
                country = US;
                "display_address" =                 (
                    "10971 N Wolfe Rd",
                    "Cupertino, CA 95014"
                );
                state = CA;
                "zip_code" = 95014;
            };
            name = "Tofu Plus";
            phone = "+14087770900";
            price = "$$";
            rating = 4;
            "review_count" = 471;
            transactions =             (
            );
            url = "https://www.yelp.com/biz/tofu-plus-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA";
        }
    );
    "json_string" = "{\"businesses\": [{\"id\": \"SMVEtOV6PG467oZqyNRhAw\", \"alias\": \"yayoi-cupertino\", \"name\": \"YAYOI\", \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/GVivqEV5C1vGaVsYze5Tlw/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/yayoi-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 403, \"categories\": [{\"alias\": \"japanese\", \"title\": \"Japanese\"}, {\"alias\": \"comfortfood\", \"title\": \"Comfort Food\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.337110507689, \"longitude\": -122.036201704747}, \"transactions\": [\"restaurant_reservation\"], \"price\": \"$$\", \"location\": {\"address1\": \"20682 Homestead Rd\", \"address2\": null, \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"20682 Homestead Rd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14085648852\", \"display_phone\": \"(408) 564-8852\", \"distance\": 1773.042455490575}, {\"id\": \"71smT9Rw7HVv9fXLLiUdhw\", \"alias\": \"the-city-fish-cupertino\", \"name\": \"The City Fish\", \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/1o4t-4G6FWoYG7o23Mw8JQ/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/the-city-fish-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 471, \"categories\": [{\"alias\": \"sandwiches\", \"title\": \"Sandwiches\"}, {\"alias\": \"seafood\", \"title\": \"Seafood\"}, {\"alias\": \"fishnchips\", \"title\": \"Fish & Chips\"}], \"rating\": 4.5, \"coordinates\": {\"latitude\": 37.3227601469653, \"longitude\": -122.053648956402}, \"transactions\": [\"pickup\"], \"price\": \"$$\", \"location\": {\"address1\": \"21678 Stevens Creek Blvd\", \"address2\": \"\", \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"21678 Stevens Creek Blvd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14083201434\", \"display_phone\": \"(408) 320-1434\", \"distance\": 944.488340204203}, {\"id\": \"h_pdXO0TiXjVPJ-tXPvYLg\", \"alias\": \"lazy-dog-restaurant-and-bar-cupertino\", \"name\": \"Lazy Dog Restaurant & Bar\", \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/Z8fXHXIyU6maxQv0sCbt8g/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/lazy-dog-restaurant-and-bar-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 1564, \"categories\": [{\"alias\": \"newamerican\", \"title\": \"American (New)\"}, {\"alias\": \"burgers\", \"title\": \"Burgers\"}, {\"alias\": \"comfortfood\", \"title\": \"Comfort Food\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.3234666014751, \"longitude\": -122.00862669582}, \"transactions\": [\"delivery\"], \"price\": \"$$\", \"location\": {\"address1\": \"19359 Stevens Creek Blvd\", \"address2\": \"\", \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"19359 Stevens Creek Blvd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14083594690\", \"display_phone\": \"(408) 359-4690\", \"distance\": 3043.164453690785}, {\"id\": \"NZPHTkXarsLEbZlnyieD-Q\", \"alias\": \"red-hot-wok-cupertino\", \"name\": \"Red Hot Wok\", \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/J4n66daJwN9tjw_7E64t7g/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/red-hot-wok-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 991, \"categories\": [{\"alias\": \"chinese\", \"title\": \"Chinese\"}, {\"alias\": \"taiwanese\", \"title\": \"Taiwanese\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.3220766185619, \"longitude\": -122.014959059792}, \"transactions\": [\"pickup\"], \"price\": \"$$\", \"location\": {\"address1\": \"10074 E Estates Dr\", \"address2\": \"\", \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"10074 E Estates Dr\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14089962999\", \"display_phone\": \"(408) 996-2999\", \"distance\": 2479.5008646693586}, {\"id\": \"d21yLIv0j4Cc2WVNsQAmZw\", \"alias\": \"gochi-japanese-fusion-tapas-cupertino\", \"name\": \"Gochi Japanese Fusion Tapas\", \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/uN3aEULD68EXS5PIWcV7FQ/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/gochi-japanese-fusion-tapas-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 1781, \"categories\": [{\"alias\": \"japanese\", \"title\": \"Japanese\"}, {\"alias\": \"tapas\", \"title\": \"Tapas Bars\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.3368621985872, \"longitude\": -122.022732496261}, \"transactions\": [], \"price\": \"$$$\", \"location\": {\"address1\": \"19980 E Homestead Rd\", \"address2\": \"\", \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"19980 E Homestead Rd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14087250542\", \"display_phone\": \"(408) 725-0542\", \"distance\": 2429.4363826848457}, {\"id\": \"228MtApQZsrGTHy8psMmiw\", \"alias\": \"galp\\u00e3o-gaucho-brazilian-steakhouse-cupertino-3\", \"name\": \"Galp\\u00e3o Gaucho Brazilian Steakhouse\", \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/8Co7lv8jW01z-rA4Cwlncg/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/galp%C3%A3o-gaucho-brazilian-steakhouse-cupertino-3?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 204, \"categories\": [{\"alias\": \"brazilian\", \"title\": \"Brazilian\"}, {\"alias\": \"bars\", \"title\": \"Bars\"}], \"rating\": 4.5, \"coordinates\": {\"latitude\": 37.3227351, \"longitude\": -122.0191573}, \"transactions\": [\"restaurant_reservation\"], \"price\": \"$$$\", \"location\": {\"address1\": \"19780 Stevens Creek Blvd\", \"address2\": \"\", \"address3\": null, \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"19780 Stevens Creek Blvd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14083662370\", \"display_phone\": \"(408) 366-2370\", \"distance\": 2090.0074552907536}, {\"id\": \"hrtNDDOfwMy6z2WUJlJEeg\", \"alias\": \"eureka-cupertino\", \"name\": \"Eureka!\", \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/YZk7TadIMMhT6v22n0-wBg/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/eureka-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 571, \"categories\": [{\"alias\": \"newamerican\", \"title\": \"American (New)\"}, {\"alias\": \"burgers\", \"title\": \"Burgers\"}, {\"alias\": \"bars\", \"title\": \"Bars\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.3233788180085, \"longitude\": -122.009085416794}, \"transactions\": [], \"price\": \"$$\", \"location\": {\"address1\": \"19369 Stevens Creek Blvd\", \"address2\": \"Ste 130\", \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"19369 Stevens Creek Blvd\", \"Ste 130\", \"Cupertino, CA 95014\"]}, \"phone\": \"+16692666752\", \"display_phone\": \"(669) 266-6752\", \"distance\": 3002.1792361893654}, {\"id\": \"fTeiio1L2ZBIRdlzjdjAeg\", \"alias\": \"alexanders-steakhouse-cupertino-cupertino\", \"name\": \"Alexander's Steakhouse - Cupertino\", \"image_url\": \"https://s3-media1.fl.yelpcdn.com/bphoto/jtKdQ9qwui8zEhgRt_V4MA/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/alexanders-steakhouse-cupertino-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 3362, \"categories\": [{\"alias\": \"steak\", \"title\": \"Steakhouses\"}, {\"alias\": \"wine_bars\", \"title\": \"Wine Bars\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.3233674576911, \"longitude\": -122.009842804904}, \"transactions\": [], \"price\": \"$$$$\", \"location\": {\"address1\": \"19379 Stevens Creek Blvd\", \"address2\": null, \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"19379 Stevens Creek Blvd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14084462222\", \"display_phone\": \"(408) 446-2222\", \"distance\": 2935.2221315483916}, {\"id\": \"TqNUz6wbAEJ5Dex1VOkgOg\", \"alias\": \"coconuts-fish-caf\\u00e9-cupertino\", \"name\": \"Coconut's Fish Caf\\u00e9\", \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/5zKWG4yHUnMrbEmBGvKwaA/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/coconuts-fish-caf%C3%A9-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 344, \"categories\": [{\"alias\": \"hawaiian\", \"title\": \"Hawaiian\"}, {\"alias\": \"fishnchips\", \"title\": \"Fish & Chips\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.3225549566322, \"longitude\": -122.023540847003}, \"transactions\": [\"delivery\", \"pickup\"], \"price\": \"$$\", \"location\": {\"address1\": \"20010 Stevens Creek Blvd\", \"address2\": \"\", \"address3\": null, \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"20010 Stevens Creek Blvd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14082169553\", \"display_phone\": \"(408) 216-9553\", \"distance\": 1721.3488620916014}, {\"id\": \"l5xYUGbX6EOzLGz_bgVr5w\", \"alias\": \"tofu-plus-cupertino\", \"name\": \"Tofu Plus\", \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/o7pEeNCQ8FP2kmbtTEL6og/o.jpg\", \"is_closed\": false, \"url\": \"https://www.yelp.com/biz/tofu-plus-cupertino?adjust_creative=anVzFbucA9SOPjbFLFLnsA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=anVzFbucA9SOPjbFLFLnsA\", \"review_count\": 471, \"categories\": [{\"alias\": \"korean\", \"title\": \"Korean\"}, {\"alias\": \"bbq\", \"title\": \"Barbeque\"}], \"rating\": 4.0, \"coordinates\": {\"latitude\": 37.3361560447221, \"longitude\": -122.015085853636}, \"transactions\": [], \"price\": \"$$\", \"location\": {\"address1\": \"10971 N Wolfe Rd\", \"address2\": \"\", \"address3\": \"\", \"city\": \"Cupertino\", \"zip_code\": \"95014\", \"country\": \"US\", \"state\": \"CA\", \"display_address\": [\"10971 N Wolfe Rd\", \"Cupertino, CA 95014\"]}, \"phone\": \"+14087770900\", \"display_phone\": \"(408) 777-0900\", \"distance\": 2920.777275142649}], \"total\": 1500, \"region\": {\"center\": {\"longitude\": -122.04299926757812, \"latitude\": 37.32210920065857}}}";
    region =     {
        center =         {
            latitude = "37.32210920065857";
            longitude = "-122.0429992675781";
        };
    };
    total = 1500;
}`

**Comment by watterso** [comment]
FYI you will find your client_id on our website when you navigate to `https://www.yelp.com/developers/v3/manage_app`.

As per the documentation on [business search](https://www.yelp.com/developers/documentation/v3/business_search) review information is not something that is returned by that endpoint. You'll want to use the [reviews endpoint](https://www.yelp.com/developers/documentation/v3/business_reviews) to retrieve that information.

**Comment by watterso** [comment]
I'll close this out, if you have new issues feel free to open another issue!
