### ISSUE TITLE
Feature Request - Need to confirm the api corressponding to the link: https://www.yelp.com/search?find_desc=Things+To+Do&find_loc=Sayreville%2C+NJ.

### ISSUE THREAD

**Issue by PragatisGitHub** [Yelp/yelp-fusion#433]
https://api.yelp.com/v3/search?find_desc=""&find_loc=""

?

Please confirm.

Thanks

**Comment by dan98765** [comment]
Hi @PragatisGitHub - could you add more detail to your issue so we can assist you better? For example, what API calls have you tried running, what were the results, and why they do not match what you were expecting?
