### ISSUE TITLE
How to ensure I am informed of API changes?

### ISSUE THREAD

**Issue by anroy** [Yelp/yelp-fusion#439]
## Overview
- **Client ID:** 2-KE4heDc9eBezL_aO7fyw
- **Issue type:** Question
- **Summary:** How to ensure I am informed of API changes?
- **Platform:** Web, Android

## Description
I don't recall being informed that API v2 will be deprecated, and to use Fusion.
Looking through my mailbox the only remotely relevant mails I see are:
- On 2016-07-19 (almost 2 years ago) I received a mail telling me of a preview to API v3.
- On 2018-05-25 I received a mail telling me of changes to the Privacy Policy. (All sites have been sending such mails, because of the EU's GDPR).

The consequence is that our service simply stopped working one day!
Why was I not informed and, more importantly, what should I do to avoid this in the future?
Thanks.

### Endpoint
Fusion Business Search

**Comment by virgytam** [comment]
Hi @anroy, we sent notifications to the email address supplied to us when you registered for your V2 key. The client_id you supplied just now is not a valid V2 key (it maps to a Fusion API client) 

In the future, we suggest you keep your contact information up to date in the manage app page: https://www.yelp.com/developers/v3/manage_app
