### ISSUE TITLE
WKWebView CORS error

### ISSUE THREAD

**Issue by peterpeterparker** [Yelp/yelp-fusion#44]
Hi,

I'm using Ionic2. To improve the performance of my app on iOS9, I want to take advantage of WKWebView to improve the overall performances.

Unfortunately, using WKWebView, I wasn't able to query the Yelp API v3.

Only ajax requests with header containing 'Access-Control-Allow-Origin: *' are allowed (or could be performed) using WKWebView.

Could you plz then enhance your API v3 and allow Cors?

Side notes:

I tried both cordova-plugin-wkwebview-engine and telerik wkwebview plugins.

In both plugin you find references to that problem:

https://github.com/Telerik-Verified-Plugins/WKWebView/issues/87

https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/3

Also note that I already opened a Cors ticket problem with the Yelp API, which could be solved with the help of a local proxy. Unfortunately this solution only work for local development purpose and can't be embedded and shipped in a Ionic / Cordova mobile solution

https://github.com/Yelp/yelp-api-v3/issues/21

Thx in advance for your feedback

**Comment by tomelm** [comment]
Hey @peterpeterparker! We don't have any plans to allow CORS on the API. The auth flow we've built for the v3 API isn't suited towards being integrated directly from a client, it risks exposing sensitive information from inside the app.

**Comment by peterpeterparker** [comment]
Hi @tomelm, thx for your answer. I understand that point of view, but in the current state, doesn't then that mean that every single Angular client requests performed on WKWebView, Safari running on >iOS 8, not gonna be accepted aka not gonna work?  

I guess these clients exists too? Or maybee I just miss something and there is a simple solution to such a problem, in that case, would be realy thanksful to hear about it.

**Comment by tomelm** [comment]
@peterpeterparker I think the best option right now is probably going to be building a small backend for your app to handle requests to the API and forward those on.

**Comment by peterpeterparker** [comment]
@tomelm well that's one of the thing I'm trying to avoid because this would means more load on my servers, which I have to avoid. It's also one of the reason why I implemented the Yelp services instead of services of other providers (like the one beginning with Four...).

But again, maybe I'm dumb and other people using the Yelp V3 Api thru Angular2 or Ionic2 within WKWebView doesn't face CORS problems, would be glad to hear how they solve it. And if I'm not that dumb, means other peoples face or gonna face the same problem using the Yelp V3 Api.

**Comment by peterpeterparker** [comment]
For the record, the referenced cordova plugin issue (https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/3) is now close since the release of the version 3 of the plugin. 

I tried it, I wasn't more lucky.
