### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by jackdoe786** [Yelp/yelp-fusion#440]
The top-3 image sometimes returned from Yelp API is not the best. Would it be fine if we switch over those images with the one on the websites.

https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg (In the API sampe response)
https://s3-media3.fl.yelpcdn.com/bphoto/bkK3i1htmYvWU8lXTMuUjQ/o.jpg (one I would like to use)

Or maybe a way to call image is which classified as "outside" on the website.

**Comment by Valectar** [comment]
We do not yet have a way to query by photo classification, although that is internally ticketed.
To maintain consistency in the display of yelp data and avoid a bad user experience in the event of individual photos being removed, you should stick to displaying only photos you receive from the API.
