### ISSUE TITLE
Creating API application results in error page

### ISSUE THREAD

**Issue by Yopi** [Yelp/yelp-fusion#442]
Not sure if this is the correct place to report this!

## Overview
- **Issue type:** _bug_
- **Summary:** _Trying to create an application to get API key_
- **Platform:** _Web: Firefox with uMatrix_

## Description
Creating an application will result in `Dog ate our servers` error page. Seemingly as a direct result of having blocked Google iFrames (with them, recaptcha). Would be more helpful to get an error relating to failure of validation or something similar. I assumed that unblocking all Yelp resources would allow it to function properly, but that was not the case.

**Comment by dan98765** [comment]
@Yopi this is definitely the correct place to report this, thanks! As you found, we use recaptcha as part of the process for a user to sign up for the API. I'll create an internal ticket for us to handle failures there more gracefully.
