### ISSUE TITLE
Incorrect event start and end times from GraphQL

### ISSUE THREAD

**Issue by hhz1001** [Yelp/yelp-fusion#443]
## Overview
- **Issue type:** bug
- **Summary:** Event start and end times returned by GraphQL queries are consistently 7 or 8 hours too far ahead
- **Platform:** Desktop/web

## Description
The time_end and time_start fields returned by a call to GraphQL for event-specific information are offset from the actual end and start times as shown on Yelp's website. As far as I can tell, the offset is +7 hours for all events occurring during daylight savings time and +8 hours for all events occurring outside of daylight savings time, regardless of location. If time_end and time_start are intended to be returned in GMT, this means that the times are always correct for events in the Pacific time zone, but always offset for events in other time zones by the difference between local time and Pacific time.

## More information
Below are two example requests and responses for events in New York, one occurring just before the end of daylight savings and one occurring just after. The first has an actual start time of Nov 2, 8:30 pm, while GraphQL returns 2018-11-03 03:30, an offset of 7 hours. The second has an actual start time of Nov 4, 5:00 pm, while GraphQL returns 2018-11-05 01:00, an offset of 8 hours.

### Endpoint
GraphQL event details

### Parameters or Sample Request
GraphQL query 1: 
```
{
    event(id: "new-york-rock-the-yacht-friday-night-party-cruise-6") {
        id
        name
        time_start
        time_end
    }
}
```
GraphQL query 2: 
```
{
    event(id: "new-york-alive-after-five-sunday-happy-hour-cruise-9") {
        id
        name
        time_start
        time_end
    }
}
```

### Response
GraphQL query 1: 
```
{
  "data": {
    "event": {
      "id": "new-york-rock-the-yacht-friday-night-party-cruise-6",
      "name": "Rock the Yacht: Friday Night Party Cruise",
      "time_start": "2018-11-03 03:30",
      "time_end": "2018-12-01 08:00"
    }
  }
}
```
GraphQL query 2: 
```
{
  "data": {
    "event": {
      "id": "new-york-alive-after-five-sunday-happy-hour-cruise-9",
      "name": "Alive After Five Sunday Happy Hour Cruise",
      "time_start": "2018-11-05 01:00",
      "time_end": "2018-11-26 04:00"
    }
  }
}
```

**Comment by Valectar** [comment]
We are aware of this issue and it is being tracked in [this ticket](https://github.com/Yelp/yelp-fusion/issues/327).
