### ISSUE TITLE
After 1600 queries, keep getting "ACCESS_LIMIT_REACHED" error

### ISSUE THREAD

**Issue by mapyang** [Yelp/yelp-fusion#444]
## Overview
- **Client ID:** _riDqnkcwgN0J5Yt9gyjR4Q_
- **Issue type:** _bug_
- **Summary:** _After 1600 queries, keep getting "ACCESS_LIMIT_REACHED" error_
- **Platform:** _Desktop/web_

## Description
_With 25000 daily limit, we have been using the Yelp Fusion API every now and then with no problem. But from the morning of 07/26/2018, after 900 successful queries, we constantly got ACCESS_LIMIT_REACHED error. 
Resetting API_KEY does not help either._

### Endpoint
_https://api.yelp.com/v3/businesses/search_

### Parameters or Sample Request
```
url_params: {'term': 'Peter+Luger', 'limit': 50, 'location': 'New+York+City,+NY'}
```

### Response
```
{u'error': {u'code': u'ACCESS_LIMIT_REACHED', u'description': u"You've reached the access limit for this client. See instructions for requesting a higher access limit at https://www.yelp.com/developers/documentation/v3/rate_limiting"}}
```

## Extra information
__

**Comment by dan98765** [comment]
Hi @mapyang - you can check your daily request usage on the Manage App page https://www.yelp.com/developers/v3/manage_app "API Usage" section. I took a quick look in our logs and confirmed client ID `riDqnkcwgN0J5Yt9gyjR4Q` has made 25k requests in the most recent 24 hour limiting window (approx 1/3 business endpoint hits, 2/3 search endpoint hits). 

Refreshing your API key does not reset your daily usage count.

**Comment by mapyang** [comment]
@dan98765  thanks for the prompt response. 
We just realized the issue should be our other components making unexpected calls and we are working to have it fixed.
Really appreciate Yelp's effort of making this data available to the public.

**Comment by dan98765** [comment]
@mapyang glad to hear it! 👍
