### ISSUE TITLE
GraphQL recent change caused user review name and photo to return null

### ISSUE THREAD

**Issue by coolboiime** [Yelp/yelp-fusion#448]
## Overview
- **Client ID:** jyHeS_MVualewtI_Ab4wHg
- **Issue type:** bug
- **Summary:** Getting reviews using GraphQL returns nothing for user picture and name.
- **Platform:** JavaScript fetch

## Description
Using GraphQL caused the user photos and names to return null. Tested this using the GraphiQL panel, in addition to the project I'm working on.

### Endpoint
GraphQL Search API

### Response
<img width="987" alt="screen shot 2018-08-02 at 6 19 37 pm" src="https://user-images.githubusercontent.com/9779803/43623876-a9d055da-96b1-11e8-9d4b-1ea43077f91c.png">

## Extra information
Not sure about the recent GraphQL update, but this was unexpected. Good thing I had a fallback set in place.

**Comment by teekwak** [comment]
Hi @coolboiime,

I was able to reproduce the issue. Going to track this issue internally. Thanks!

**Comment by coolboiime** [comment]
Let me know when you get to fix this!

**Comment by teekwak** [comment]
Hi @coolboiime,

This should be fixed now. Closing this issue out, but feel free to reopen/file a new issue if something comes up.

**Comment by coolboiime** [comment]
Thanks, it works now.
