### ISSUE TITLE
Search not returning entire list of businesses when using offset parameter

### ISSUE THREAD

**Issue by Jfairfield1** [Yelp/yelp-fusion#449]
### Overview
**Issue type**: 
Bug

**Summary**: 
We can't seem to get the correct number of results when searching using term and location

**Description**:
Our app requests data using a search term and a location.

When making this sample request:

> https://api.yelp.com/v3/businesses/search?limit=20&term=childcare&location=NY

The output works as expected.  It returns 20 businesses and a total property of 485.

When using the offset parameter to try to get more results, it stops working after ~350

For example, 

> https://api.yelp.com/v3/businesses/search?limit=20&term=childcare&location=NY&offset=450

Should include 20 items (450-470), but it doesn't seem to return any businesses.

**Endpoint**
Fusion Search API

**Parameters or Sample Request**

> https://api.yelp.com/v3/businesses/search?limit=20&term=childcare&location=NY&offset=450

Response
```
{
  "businesses": [],
  "total": 485,
  "region": {
    "center": {
        "longitude": -73.99429321289062,
        "latitude": 40.70544486444615
    }
  }
}
```

**Comment by hcancelik** [comment]
+1 I'm having the exact same issue. 

The total results returns as 744 for search term "cannabis" and location="los angeles, ca" however the total results are only 695 after looping through all results with offset.

**Comment by watterso** [comment]
Hi all,
Paginating search does have weird behavior as you reach the upper end of your results, one way to combat this is by using a hard filter like `categories`, luckily both of your use cases seem to lend themselves to this. You'll need to fill out the `categories` parameter [as described in the search docs](https://www.yelp.com/developers/documentation/v3/business_search) and find the appropriate category off of the [all category list page](https://www.yelp.com/developers/documentation/v3/all_category_list) (or programmatically via the [category endpoints](https://www.yelp.com/developers/documentation/v3/category)):
* @Jfairfield1 you'll want the value `childcare`
* @hcancelik you'll want any one or combination (or all) of: `cannabisdispensaries`, `cannabis_clinics`, `cannabistours`, `cannabiscollective`, `cannabisreferrals`

**Comment by Jfairfield1** [comment]
My use case allows users to search using a custom term.  So unfortunately, I don't think the categories will work.  Is there any estimate on a timeline to fix the paginating search results issue?

**Comment by watterso** [comment]
@Jfairfield1 the issue is tracked internally, but I can't share engineering timelines. In general though I would highlight that the impact of this bug is probably low, search engine users are notorious for not going past page one, not sure very many users will make it to page 17 (350 / 20).

**Comment by Jfairfield1** [comment]
Fair enough.  Thanks for the response.
