### ISSUE TITLE
REQUEST_TIMED_OUT 

### ISSUE THREAD

**Issue by rashichauhan7** [Yelp/yelp-fusion#451]
## Overview
 Endpoint
Fusion Search API
https://api.yelp.com/v3/businesses/:id

-Client ID:  "579BEGwnrM59wcpM0YqOJEzhD3S_WzX3xVByv_G2zHC5JJUSH8PE01wojvBQSDh8Lyco0wXUJAlvYOPOazNYGoza8n1XwtbW82dTFUqdv7lrn30h6dNwSr40PvpQW3Yx"

Response 
Status code 504
Request Timed out

Working perfectly fine till today morning. Does not give error on buisinesses/search.

**Comment by coolboiime** [comment]
Same error here!

**Comment by watterso** [comment]
Hey all,
This was caused by an outage that affected the whole Yelp site. It happened 2018-08-19 in the morning PDT (afternoon UTC). Things should be back to normal now :)

**Comment by coolboiime** [comment]
@watterso Is there a status page we can be notified of in case things like this happen again? Thanks.
