### ISSUE TITLE
Add "Open to All" attribute parameter option?

### ISSUE THREAD

**Issue by campkels** [Yelp/yelp-fusion#452]
## Overview
- **Client ID:** X5MmjZFVqzFseGv2UnsxKw
- **Issue type:** feature request
- **Summary:** Would be great to have an ```opentoall``` parameter option available when [searching for businesses](https://www.yelp.com/developers/documentation/v3/business_search) by attribute
- **Platform:** Desktop/web

## Description
The ["Open to All" attribute](https://www.yelpblog.com/2018/07/opentoall) was a fantastic addition of much importance to the LGBTQ+ and other minority communities - making it easier for them to identify safe and welcoming places to patronize. It is not currently included through the API, but I believe it would be extremely useful for developers and data scientists aiming to make this capability better known and more accessible to those that would benefit.

### Endpoint
/businesses/search

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?attributes="opentoall"
```

**Comment by watterso** [comment]
Hey @campkels, thanks for the input! I've filed a ticket internally to track this idea, someone will post back here if / when theres an update regarding this :)

**Comment by watterso** [comment]
Hey @campkels good news! You can now use the [search endpoint](url) to get businesses which are [Open To All](https://www.yelpblog.com/2018/07/opentoall)!  This is done by passing the value `open_to_all` to the `attributes` parameter of the search endpoint, for example if you access the api using [curl](https://en.wikipedia.org/wiki/CURL):
```
curl --header "Authorization: Bearer <api-key>" "https://api.yelp.com/v3/businesses/search?location=baltimore&attributes=open_to_all"
```
More info at:
* [Search Docs](https://www.yelp.com/developers/documentation/v3/business_search)
* [GraphQL Search Docs](https://www.yelp.com/developers/graphql/query/search)

**Comment by campkels** [comment]
AWESOME!! Thank you!
