### ISSUE TITLE
reach out and flay someone

### ISSUE THREAD

**Issue by brighterness** [Yelp/yelp-fusion#453]
Can this be used to bridge contact to yelp users' email?

**Comment by dan98765** [comment]
@brighterness the Yelp API can not return yelp users' emails or any other personal information.

**Comment by brighterness** [comment]
Bridge.  I don't want to harvest.  If I could snap my fingers and end the life of everyone who facilitates spam I would.

**Comment by brighterness** [comment]
(I would genocide remove all prius drivers)
