### ISSUE TITLE
Jabber Texting notifications

### ISSUE THREAD

**Issue by brighterness** [Yelp/yelp-fusion#454]
Is there an existing fusion app that will allow me to receive my own yelp notifications via Jabber Texting (xmpp)?

**Comment by watterso** [comment]
User-specific information like specifically _your_ notifications is not available via [Yelp Fusion](http://yelp.com/fusion). Furthermore, [Yelp Fusion](http://yelp.com/fusion) data can only be requested via HTTPS requests, there is no support for other protocols (like xmpp) or outbound (Yelp pushes data to you) integrations.
