### ISSUE TITLE
Searches with the "reservation" attribute enabled return no results

### ISSUE THREAD

**Issue by shishovic** [Yelp/yelp-fusion#456]
## Overview
Business search API endpoints returns no results with the "reservation" attribute enabled

## Description
I wasn't able to search business (restaurants in this case) with the "reservation" attribute query parameter. It returned no results for cities like "Berlin" and "Paris" even though the website provided the results of the search and even though the results returned from querying without the "reservation" returned some website with reservations enabled.

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
Fusion Search API

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?term=restaurant&radius=17000&attributes=reservation
```

**Comment by watterso** [comment]
Hey @shishovic, the `reservation` attribute is a little more specific than its name indicates. As described [in the search docs](https://www.yelp.com/developers/documentation/v3/business_search):
> `reservation` - businesses with [Yelp Reservations](https://www.yelp.com/search?find_desc=Reservations) bookings enabled on their profile page

So what you are seeing is that for the cities you searched there are no businesses that have Yelp Reservations, there might be those that accept phone or reservations via other online platforms, but this specific search attribute is for filtering on Yelp Reservations.
