### ISSUE TITLE
ability to return full `description` field on events endpoints

### ISSUE THREAD

**Issue by adamyala** [Yelp/yelp-fusion#457]
## Overview
- **Client ID:** `hxI7p8UuW6qUKAVYC9q3WA`
- **Issue type:** feature enhancement
- **Summary:** Descriptions returned by the events endpoint are truncated. Could the full descriptions be returned?
- **Platform:** web API

## Description
The event sample in the docs [here](https://www.yelp.com/developers/documentation/v3/event) is a great example. The `description` field in the example is ~150 characters long. 
```
Saucy is throwing up a pop-up restaurant party over at Anfilo Coffee! Give the menu a little peruse and then register to reserve your spot! Prices are shown...
```
But on the event page [here](https://www.yelp.com/events/oakland-saucy-oakland-restaurant-pop-up), the description is much longer.
```
Saucy is throwing up a pop-up restaurant party over at Anfilo Coffee! Give the menu a little peruse and then register to reserve your spot! Prices are shown next to the dishes and donations to Saucy will be appreciated! 

Menu
Apps and Entrees 
Edamame truffle butter, sesame garlic GF $5
Hamachi Shooters yellowtail, taberu rayu, crispy onions, ponzu GF $13
Saucy Sticky Wings soy, ginger, honey, garlic GF $8
Steamed Pork Buns pork belly, black bean garlic sauce, pickled daikon, cilantro $10
Braised Short Ribs soy braised, truffle parmesan cauliflower puree, mint cilantro slaw $18
Mussels red curry, coconut milk, cilantro GF $10
Saucy Nachos beef, cheese, kimchi, onions, jalapenos, crema $11
Hierloom Tomatoes shaved asparagus, avocado, red onions, yuzu ginger vinaigrette GF $9

Dessert
Mini Cheese Tart (3) 5-cheese tart, shortbread crust, white chocolate $8
Flourless Chocolate Cake chocolate mousse, berry coulis GF $8

Drinks
Beer $5
Cold Junmai Sake $7
Sake Spritzer // Small Carafe $13
Sake Spritzer // Large Carafe $24
Spritzer $3
```
Could the `/events/` endpoints be altered to return the full description? Or a flag I can pass in saying that I'd like the full text?

### Endpoint
Event Endpoints:
```
v3/events/{id}
v3/events/
v3/events/featured
```

**Comment by dan98765** [comment]
Hi @adamyala I've filed a ticket for this internally to discuss. We'll get back to you here with an answer on this as soon as possible.

**Comment by adamyala** [comment]
🙌 Ty for the crazy fast reply.

**Comment by dan98765** [comment]
@adamyala sorry, we will not be returning the full event description at this time from our public API. Our product team envisions user-facing apps created using the Public API could show the excerpt of the event description and then have a link to the full event on Yelp if users want to read more. 

If you've got a great use case that does not fit this, please pitch it in an [application for Yelp Fusion VIP](https://www.yelp.com/fusion/vip) and/or email api@yelp.com.
