### ISSUE TITLE
Booking a reservation

### ISSUE THREAD

**Issue by asontha** [Yelp/yelp-fusion#458]
Is it possible to book a reservation through the Yelp fusion API? I see it's possible to see that a restaurant takes reservations, but I don't see an easy way of actually booking the reservation.

**Comment by dan98765** [comment]
Hi @asontha we do not currently have a public API for booking reservations through Yelp. If you'd like to pitch your proposed use-case to our Business Development team please [apply for Fusion VIP](https://www.yelp.com/fusion/vip) and/or email api@yelp.com. 

Maybe related: for https://github.com/Yelp/yelp-fusion/issues/137 we may add in a direct "action link" in the search and/or business endpoint response that would drop a user directly to the reservations flow for a business. If that would fit your use case, please add a comment there.

**Comment by dan98765** [comment]
**Update**: there is now a Reservation API (documentation at https://docs.developer.yelp.com/v1.0/docs/reservation) which can be used to create & interact with Yelp Reservations procedurally via API calls. It is only available to partners who have signed contracts with Yelp, so my advice in the previous comment to reach out to the Business Development team if you have a compelling use case still applies. 

For the foreseeable future the Reservation API will remain private, so I will close out this issue.
