### ISSUE TITLE
Are multiple featured events supported?

### ISSUE THREAD

**Issue by richierocks** [Yelp/yelp-fusion#460]
## Overview
- **Client ID:** _ktgThAe5KssZ0XT2NRyhuw_
- **Issue type:** _question_
- **Summary:** _It is unclear if multiple featured events are possible_
- **Platform:** _Any_

## Description

The documentation for the `events/featured` endpoint shows an example that returns a single event. From playing around, I've only ever managed to get it to return zero or one events.

I'd like to know

1. Is more than one event ever returned from this endpoint?
1. If so, what is the data structure? Is it the same as for the `events` endpoint?

## More information

> This endpoint returns the featured event for a given location.

The docs suggest that there will only be one event, but I have code paranoia and would like it spelled out!

### Endpoint
_events/featured_

**Comment by watterso** [comment]
@richierocks you are correct the featured event enpoint will either return 0 or 1 events :)
