### ISSUE TITLE
business_search endpoint - Specifying location using zip codes

### ISSUE THREAD

**Issue by lelseed** [Yelp/yelp-fusion#461]
## Overview
I have a question about specifying location using the business_search endpoint. If I want to get restaurant data that operate in a specific zip code, can I just specify it using this parameter: location=20009 ? I ask because when I run the following code, I get restaurants in other zip codes and I'm not sure why that's the case so if you can shed some light, that'll be great. 

### Endpoint
business_search endpoint

### Parameters or Sample Request
This is the URL I'm using:

LIMIT=50
offset=0
url = "https://api.yelp.com/v3/businesses/search?limit={}&offset{}&location=20009"

### Response
I get restaurants from the desired zip code and other zip codes.

**Comment by watterso** [comment]
Hey @lelseed, two things here:

- `location=20009` is indeed a valid input, on the backend we do some best effort [geocode](https://en.wikipedia.org/wiki/Geocoding) to turn your input into a location
- It is not a hard filter to only include results from that place, the search area might smartly resize on the backend to try to return the best results for your area. If you have this hard requirement, i recommend doing multiple searches and filtering your results after the fact on the `location.zip_code` field.
