### ISSUE TITLE
Using API in JavaScript & load key into HTML

### ISSUE THREAD

**Issue by tslewis1** [Yelp/yelp-fusion#463]
## Overview
- **Client ID:** _(TWMNEkBZq9VALm1TOkL46w)_
- **Issue type:** _(question)_
- **Summary:** _(I cannot figure out how to load my API key into a script tag in my HTML file. I am using Google Maps API as well and am using JavaScript for map functionality.)_
- **Platform:** _(Desktop/web)_

## Description
_(So I would like to use the Yelp Fusion API to load information about each location that I have coded into my map using Google Maps API. I need to figure out how to load the API key into my HTML file for use, however I have not been able to find out how to do that via the documentation or Google searches.)_

## More information
_()_

### Endpoint
_(Fusion API key)_

## Extra information
_(I want to use the Yelp Fusion API alongside the Google Maps API, and within JavaScript)_

**Comment by teekwak** [comment]
Hi @tslewis1,

I'm guessing that you have a few locations on your Google map that you want to display information when a user clicks/hovers/interacts with that location. In the same script that you able to create a map object from the Google Maps API, you can set your API key as a variable and use it to make an AJAX request to grab information about each location from the Yelp Fusion API. 

However, correct me if I'm wrong, but it sounds like you are using client-side JavaScript. I would be extremely careful about putting your API key here. Anyone can access/steal your API key through the browser's console or through GitHub if you check in this file.
