### ISSUE TITLE
Can't find a business using the api, but can see using normal yelp search in website

### ISSUE THREAD

**Issue by deepakbharanikana** [Yelp/yelp-fusion#464]
## Overview
- **Client ID:** _XU327YkaCD0n1d_
- **Issue type:** _bug_
- **Summary:** _I can't few locations in the website but can't find them using fusion api/_
- **Platform:** _web_

## Description
_https://www.yelp.com/biz/bath-and-body-works-richmond  

_This is the business i am trying to find using the api, this is only an example but there're several other businesses that are available in yelp website but not in API

### Endpoint
_Fusion Search API_

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?term="Bath Body Works"&location="3801 National Rd E Rm 723 Richmond, IN 47374"&radius=8000
```

### Response
```
{
    "businesses": [],
    "total": 0,
    "region": {
        "center": {
            "longitude": -84.84500885009766,
            "latitude": 39.829883992379024
        }
    }
}
```

**Comment by dan98765** [comment]
Hi @deepakbharanikana, the [Bath & Body Works](https://www.yelp.com/biz/bath-and-body-works-richmond) biz you linked to has 0 reviews. As per [Business Search Endpoint](https://www.yelp.com/developers/documentation/v3/business_search) documentation page, the API does not return businesses with 0 reviews.
