### ISSUE TITLE
Parent alias category not returning any child categories

### ISSUE THREAD

**Issue by Alberto-Funk** [Yelp/yelp-fusion#467]
## Overview
- **Client ID:** HHfVh4GhQdZ_-dNKSAaTjw
- **Issue type:** Help Wanted
- **Summary:** I am trying to return all of the child categories of a parent alias(eg. restaurants => Afghan , African, American, Andalusian, Barbeque, etc etc)
- **Platform:** Any

## Description
My goal is to receive all of the child categories of a parent alias.
I have tried /categories/restaurants, /categories .. along with most other endpoints and parameters
All it returns is one object instead of all of the child categories

## More information
I have no way of accessing all of the child categories of any parent alias like restaurants, nightlife, etc

### Endpoint
https://api.yelp.com/v3/categories/restaurants

### Parameters or Sample Request
https://api.yelp.com/v3/categories/restaurants

### Response
{
    "category": {
        "alias": "restaurants",
        "title": "Restaurants",
        "parent_aliases": [],
        "country_whitelist": [],
        "country_blacklist": []
    }
}
![restaurant_categories](https://user-images.githubusercontent.com/35757684/46328563-efa6a700-c5bc-11e8-9815-de0bcca05203.PNG)

## Extra information
Is there a way to retrieve multiple categories based on a parent alias?

**Comment by teekwak** [comment]
Hi @Alberto-Funk,

Right now, we don't have a direct way of getting all children categories given a parent alias. The next best way I can think of it is to use the /categories/restaurants endpoint to get the alias of the restaurants category (which is probably just "restaurants") and then make another request to the /categories endpoint to retrieve all categories. Then you can filter for categories where the parent alias of the category matches that of the parent alias you are interested in.

**Comment by Alberto-Funk** [comment]
Got it, thank you for the reply.
