### ISSUE TITLE
"Approve all" for compliments feature

### ISSUE THREAD

**Issue by LifeisaJourney** [Yelp/yelp-fusion#470]
## Overview
- **Client ID:** _(Daw52o_JmV0tzWFsZ92ctw)_
- **Issue type:** _(feature request & question)_
- **Summary:** _(approve all compliments)_
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description
_(Approving each compliment on the user side is quite annoying. Is there an "approve all button" or a checklist feature coming soon?)_

##Suggestion 
_(If the API for friend ID is allowed, I think it is fairly do-able to implement the feature)_

**Comment by watterso** [comment]
Hi @LifeisaJourney,
This seems like feedback for one of our consumer products, unfortunately this is meant for issues related to our [Yelp Fusion API](https://www.yelp.com/fusion)
