### ISSUE TITLE
More than one search term for query in GraphQL console?

### ISSUE THREAD

**Issue by Thom84** [Yelp/yelp-fusion#471]
Hello,

I tried several times to add an additional search term to a query without any success. Would you be able to provide an example of running a GraphQL query with more than one search term? I know this issue was addressed for using the Yelp Api directly but I am not sure how to access the Yelp API other than using the GraphQL console. And I could not access the links that provide the query examples. Any and all help would be appreciated!

**Comment by watterso** [comment]
Hey @Thom84,
In the GraphQL world you can have multiple Queries in one request by using [Aliases](https://graphql.org/learn/queries/#aliases). Heres an example query on our api:
```graphql
{
  burrito_search: search(term: "burrito", location: "san francisco") {
    total
    business {
      name
    }
  }
  plumber_search: search(term: "plumber", location: "san francisco") {
    total
    business {
      name
    }
  }
}
```

If you want to play around with this query heres a link to it on our console - [🔗link🔗](https://www.yelp.com/developers/graphiql?query=%7B%0A%20%20burrito_search%3A%20search(term%3A%20%22burrito%22%2C%20location%3A%20%22san%20francisco%22)%20%7B%0A%20%20%20%20total%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20plumber_search%3A%20search(term%3A%20%22plumber%22%2C%20location%3A%20%22san%20francisco%22)%20%7B%0A%20%20%20%20total%0A%20%20%20%20business%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

Good Luck!
