### ISSUE TITLE
Can't get the authentication call right

### ISSUE THREAD

**Issue by kcovert** [Yelp/yelp-fusion#473]
## Overview
- **Client ID:**  -Va-4pQJi1pg4dAyUjaeaA
- **Issue type:** Can't get the authentication call right using Postman or in code
- **Summary:** The authentication guide page gives no clear example of a properly formed authentication Fusion call. We can only guess and none of my guessees are working.
- **Platform:** Desktop Windows 10

## Description
This is what I have in Postman for my last attempt...

longitude -122.399972

access_token < my api key >

Authorization bearer < my client id >  Why is this two words? It will be parsed as Authontication : bearer. Have tried just bearer etc.

latitude 28.0781

text del

## What Postman forms up for the call, (notice the parsing on Authorization bearer)....

https://api.yelp.com/v3/businesses/search?access_token= < my api key > &Authorization : bearer=-< my client ID > I have to insert spaces in this because of the HTML parsing on this site.

### Response
{
    "error": {
        "code": "TOKEN_MISSING",
        "description": "An access token must be supplied in order to use this endpoint."
    }
}

## Extra information
What am I doing wrong? Please forgive my frustration at a simple thing made hard by no documentation, or just a simple example of what the authentication call string would look like. I assume I won't be getting a client secret response like oauth.

**Comment by blipdropper** [comment]
In Postman you are clicking the "Authorization" button and then putting Bearer <your app id> right?

**Comment by teekwak** [comment]
Hi @kcovert,

In Postman, there should be a tab right under where you insert the URL named "Authorization". Set the type to "Bearer Token" and put your API key in the "Token" field on the right. You should not be sending your API key as a query parameter in the URL you are trying to hit.

**Comment by watterso** [comment]
In the interest of sharing even more info, postman looks like this for me:
![image](https://user-images.githubusercontent.com/1614083/47876906-bb025700-ddd7-11e8-8f50-042d567a7400.png)
Fill in `<you-api-key>` and it should work. For other readers, you'll want the [authentication page](https://www.yelp.com/developers/documentation/v3/authentication) in our docs.
