### ISSUE TITLE
Match endpoint returning unexpected results

### ISSUE THREAD

**Issue by chronesthesiac** [Yelp/yelp-fusion#476]
## Overview
- **Client ID:** W5atZnNsv_iPEVbA7yJ_yA
- **Issue type:** Fusion API Business Match Endpoint inaccurate
- **Summary:** Expecting Fusion API to return an empty businesses array if name not found at location. Unexpected matches being returned.
- **Platform:** Desktop/web

## Description
This is just one example that I've hit in the first 10 calls I've attempted to make, so I'm concerned that this issue will show itself with other businesses as well. The exact call I'm making is noted below, and the response is for a completely different business.

Clearly, the location is an exact match, so this business is in the same shopping center, but the name "Star Nails" is very different from "Santander Bank".

## More information
I've tried querying just "Santander", which results in an empty array response. I've also made sure to try encoding the blank spaces as + and %20, neither makes a difference.

If I just do a manual search via the UI, there are actually no entries on Yelp for this business at this exact location. So the thing is, I am _**expecting**_ an empty array, but frustratingly, keep getting returned another business entirely.

### Endpoint
Fusion Business Match

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/matches?name=santander bank&address1=235 queen street&city=SOUTHINGTON&state=CT&country=US

https://api.yelp.com/v3/businesses/matches?name=Santander+Bank&address1=235+queen+street&city=SOUTHINGTON&state=CT&country=US

https://api.yelp.com/v3/businesses/matches?name=Santander%20Bank&address1=235%20queen%20street&city=SOUTHINGTON&state=CT&country=US

### Response
{
    "businesses": [
        {
            "id": "J6sRhC7r-k57-sIURzzEhA",
            "alias": "star-nails-southington",
            "name": "Star Nails",
            "coordinates": {
                "latitude": 41.6231194,
                "longitude": -72.8706284
            },
            "location": {
                "address1": "235 Queen St",
                "address2": "",
                "address3": "",
                "city": "Southington",
                "zip_code": "06489",
                "country": "US",
                "state": "CT",
                "display_address": [
                    "235 Queen St",
                    "Southington, CT 06489"
                ]
            },
            "phone": "+18606210826",
            "display_phone": "(860) 621-0826"
        }
    ]
}

## Extra information
I also happened to query the API for the Star Nails business as well, although I'm not sure how that might be related.

**Comment by dan98765** [comment]
Hi @chronesthesiac - the Business Match endpoint returns business results that fully or partially match the input arguments. In this case, the business returned matches your input address exactly (same street address) but has a different name. Internally we calculate a 'match score' for each business and then apply a 'match threshold' to only return those businesses that are matching within some close range. 

The endpoint has a query argument `match_threshold` which currently can be `none` (no match threshold applied) or `default` (a moderate threshold applied). Would your use case be satisfied if we added a new `strict` value for this that applies an exceptionally high threshold such that only an exact or nearly exact set of input arguments would match?

**Comment by chronesthesiac** [comment]
Yes @dan98765, I think that would be great actually. I noticed and also actually tried using the <code>match_threshold</code> parameter, but as you mention, there's only two options, and clearly <code>default</code> is still quite forgiving. I don't know how your current match score works for a business, but say if <code>none</code> is obviously 0%, <code>default</code> is say something like a 50% threshold match, then a <code>strict</code> option that is something like 75% would be incredibly helpful to round out that <code>match_threshold</code> spectrum.

Thanks!

**Comment by dan98765** [comment]
We've added a new strict value that `match_threshold` can accept which should filter out all business matches except those that are nearly perfectly matched by the input. 
Changelog for v3 REST: https://www.yelp.com/developers/v3/changelog#changelog-20181112
Changelog for GraphQL: https://www.yelp.com/developers/graphql/changelog#changelog-20181112

Please try it out. 👍
