### ISSUE TITLE
Multiple Term Search

### ISSUE THREAD

**Issue by krrishdholakia** [Yelp/yelp-fusion#477]
How could i use an OR for the search terms?
for example:
when i do:

https://api.yelp.com/v3/businesses/search?term=art&latitude=40.8009124&longitude=-73.9677041&radius=20000

and

https://api.yelp.com/v3/businesses/search?term=nature&latitude=40.8009124&longitude=-73.9677041&radius=20000

i get different results than when i do:

https://api.yelp.com/v3/businesses/search?term=art+nature&latitude=40.8009124&longitude=-73.9677041&radius=20000

where the results seem heavily skewed towards that of "art".. even reordering (nature+art) has no effect.

**Comment by dan98765** [comment]
Hi @krrishdholakia - we do not currently support using the boolean operator 'OR' in search queries. Your best bet here where you have two independent `term` strings you want separate results for is to make two queries.  

When you use the term `art+nature` our systems do not see that as two separate terms, but rather one. The search endpoint tries to 'understand' the search term and return the best results, which may include some parts of your query over others based on the quality of results or which businesses other Yelp users have chosen to interact with after making a similar query. 

So to reiterate: if you want to get separate result sets for each of your query strings, I suggest making multiple queries.
