### ISSUE TITLE
Wrong query for Migrated Business

### ISSUE THREAD

**Issue by rchzh** [Yelp/yelp-fusion#481]
## Overview
- **Client ID:** 5Ers-96nMItrZRCqtC7mDA
- **Issue type:** question/bug
- **Summary:** Api request is redirected multiple times
- **Platform:** Desktop/web

## Description
While making [Business request](https://www.yelp.com/developers/documentation/v3/business) I am using seems like old business Id. So I am redirected to new one. It is fine for user, cause it can see only latest result. For developer I see that I'm redirected to new business id. 
While redirecting I receive response with Header where there are Location value present multiple times. I think it is problem, cause lately request url has wrong format and returns 404 response.

### Endpoint
https://api.yelp.com/v3/businesses/5Ers-96nMItrZRCqtC7mDA

### Response
```
1st Redirect Response Header: 
HTTP/1.1 301 Moved Permanently
Server: nginx
Content-Type: application/json
Location: http://api.yelp.com/v3/businesses/En7T6MgLCLyZWr65EYBAWg
Location: http://api.yelp.com/v3/businesses/En7T6MgLCLyZWr65EYBAWg
X-Proxied: 10-65-130-116-useast1bprod
Content-Length: 192
Accept-Ranges: bytes
Date: Fri, 30 Nov 2018 15:05:03 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-fra19134-FRA
X-Cache: MISS
X-Cache-Hits: 0

```
Next request are built like "https://api.yelp.com/v3/businesses/En7T6MgLCLyZWr65EYBAWg,http://api.yelp.com/v3/businesses/En7T6MgLCLyZWr65EYBAWg"
Response of this :
{"error": {"code": "NOT_FOUND", "description": "Resource could not be found."}}

## Extra information
My simple program:

```
           string page = "https://api.yelp.com/v3/businesses/5Ers-96nMItrZRCqtC7mDA";
            
            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
                    "Bearer",
                    "SOME_TOKEN");
                using (HttpResponseMessage response = await client.GetAsync(page))
                using (HttpContent content = response.Content)
                {
                    string result = await content.ReadAsStringAsync();
                    if (result != null)
                    {
                        Console.WriteLine(result);
                    }
                }
            }
```

**Comment by dan98765** [comment]
Hi @rchzh thanks for the bug report. We're repro'd this issue and @watterso has ticketed it internally.
