### ISSUE TITLE
[Question]: Is it possible to have multiple parameters for sort_by?

### ISSUE THREAD

**Issue by SeongwoonHong** [Yelp/yelp-fusion#484]
I'm using this endpoint. https://api.yelp.com/v3/businesses/search

would it be possible to sort by multiple parameters?

For instance, https://api.yelp.com/v3/businesses/search?term=something&sort_by=distance,price

If that's possible, would it also be possible to sort price ascending or descending specifically?

Thank you so much.

**Comment by dan98765** [comment]
Hi @SeongwoonHong it is currently not possible to sort by multiple parameters. 

From https://www.yelp.com/developers/documentation/v3/business_search the description of `sort_by`:

> Optional. Suggestion to the search algorithm that the results be sorted by one of the these modes: best_match, rating, review_count or distance. The default is best_match...<truncated>

**Comment by SeongwoonHong** [comment]
thanks..
