### ISSUE TITLE
Authorize Token Yelp Search with Angular1.x respond 403

### ISSUE THREAD

**Issue by coolwoc** [Yelp/yelp-fusion#486]
## Overview
Client ID: l3lL--dDPUGHVjzUdGxJ_g
IssueType: Question
Summary: my authorization token does not work using Service with Angular1.6. I have a respond 403.
Platform: Web/Desktop

## Description
I have authorization token of Yelp Account for Testing purposes. I can retrieve data from Postman without not issue when I do a search by category using Latitude and Longitude. However, When I do a $http request from a service using Angular 1.6 -- I have no data and a msg saying I have a  respond 403.

### Endpoint
https://api.yelp.com/v3/businesses/search?term=All&latitude=41.048649&longitude=28.979530

### Parameters or Sample Request
Service Used in Angular1.x
    function NeighbourhoodService($http) {
        return {
            searchAll: function(Term, Lat, Long) {
                var urlReq = 'https://api.yelp.com/v3/businesses/search?term=' + Term + '&latitude=' + Lat + '&longitude=' + Long;
                var token = 'myToken';
                return $http({
                    method: 'GET',
                    headers: {
                        'Authorization': 'Bearer ' + token
                    },
                    url: urlReq
                });
            }
        }
    }

### Response
Response 403 -- authorization is not working 
& 
CORS btwn my localhost and https://api.yelp.com.

<img width="1252" alt="screen shot 2018-12-21 at 21 35 56" src="https://user-images.githubusercontent.com/371733/50357951-bdc43180-0568-11e9-9939-c3458863cb37.png">

**Comment by watterso** [comment]
Hey @coolwoc 
Your original title captured the cause here more accurately, this error is because our API does not support [CORS|https://en.wikipedia.org/wiki/Cross-origin_resource_sharing] as described in #21 and #64 Your best bet is to not make requests directly to the yelp api from your frontend, instead hit your own API endpoint that makes the request server side. You get the added bonus of not leaking your API key in your frontend code :)

**Comment by coolwoc** [comment]
hi @watterso! 
Yes I saw a couple of post about it after posted my question - we did a call on the BE to yelp in order to get the data following an Python example found it here. Perhaps documentation should be more clear about or do I miss the point on the documentation about it.
Thanks for your reply :) by the way the API works like a charm!!
