### ISSUE TITLE
Implementing GraphQL

### ISSUE THREAD

**Issue by JakeEllis** [Yelp/yelp-fusion#487]
## Overview
- **Client ID: 573AQcMjerFQe1oUveqzjw
- **Issue type: Help Wanted - Implementing GraphQL 
- **Summary: I am attempting to use GraphQL to search for multiple yelp businessIDs at a time in hopes that it will be faster than the yelp fusion api that I am currently using. When setting up the Apollo Client I am getting HTTP errors.
- **Platform:  Android

## Description
I have successfully created my query and schema (and tested on the web console), although I am getting an http error when creating the okHttpClient and Apollo client. I think I am using the wrong BASE_URL but I cannot find documentation to explain which URL I am supposed to use and why. 

### Parameters or Sample Request

GraphQL script:

        query BusinessDetails($businessID: String!){
          businessEntries: business(id: $businessID) {
            id
            name
            is_claimed
            is_closed
            url
            phone
            display_phone
            review_count
            rating
            price
            categories {
              title
            }
            location {
              formatted_address
            }
            coordinates {
              latitude
              longitude
            }
            photos
            hours {
              hours_type
              is_open_now
              open {
                end
                start
                day
              }
            }
            reviews {
              text
              rating
              time_created
              user {
                name
                image_url
              }
            }
          }
        }

Activity.java script

                   final String BASE_URL = "https://api.yelp.com/v3/graphql/";
                    
                   OkHttpClient okHttpClient = new OkHttpClient.Builder().build();

                    ApolloClient apolloClient = ApolloClient.builder()
                            .serverUrl(BASE_URL)
                            .okHttpClient(okHttpClient)
                            //.normalizedCache(normalizedCacheFactory, cacheKeyResolver)
                            .build();

                    final BusinessDetailsQuery searchYelp = BusinessDetailsQuery.builder()
                            .businessID("p4AcvxZ9mosYYwPqTpjteg")
                            .build();

                    ApolloCall<BusinessDetailsQuery.Data> yelpFeedCall = apolloClient
                            .query(searchYelp);

                    yelpFeedCall.enqueue(new ApolloCall.Callback<BusinessDetailsQuery.Data>() {
                        @Override
                        public void onResponse(@Nonnull Response<BusinessDetailsQuery.Data> response) {
                            BusinessDetailsQuery.Data data = response.data();
                        }

                        @Override
                        public void onFailure(@Nonnull ApolloException e
                        ) {
                            String exep = e.toString();
                        }
                    });

### Response

    com.apollographql.apollo.exception.ApolloHttpException: HTTP 404

**Comment by watterso** [comment]
Hey @JakeEllis,
Glad your query works on the web console! I'm not at all an expert at Apollo, but the 404 does seem to match up with your instinct that your `BASE_URL` is wrong. I think it might be the trailing `/` on your `BASE_URL`, when I tried a a manual curl to `https://api.yelp.com/v3/graphql/` (vs `https://api.yelp.com/v3/graphql`) I do indeed get a 404. Could you try removing that?

**Comment by JakeEllis** [comment]
Thanks for the response @watterso. With the BASE_URL = "https://api.yelp.com/v3/graphql" I am getting a HTTP 401 error.

**Comment by watterso** [comment]
This is the relevant section in their React docs - https://www.apollographql.com/docs/react/recipes/authentication.html#Header can't find their Java docs

**Comment by watterso** [comment]
I don't have experience either, are you building a client by first doing `apollo-codegen` ? Like it does [here](https://github.com/apollographql/apollo-android/blob/master/docs/source/essentials/get-started.md#downloading-a-schema)? If so it looks like you'll need to include your api key at that step:
>If needed, you can use the `header` option to add additional HTTP headers to the request. For example, to include an authentication token, use `--header "Authorization: Bearer <token>"`:
> `
apollo-codegen download-schema https://api.github.com/graphql --output schema.json --header "Authorization: Bearer <token>`

**Comment by JakeEllis** [comment]
I really was hoping that was the fix. I couldnt remember if I used the authorization header but I reran that command and generated the schema file and I am still getting the HTTP 401 error.

This is the command I ran:

    apollo-codegen download-schema https://api.yelp.com/v3/graphql --output schema.json --header "Authorization: Bearer My-API-Key-here"

**Comment by pranayairan** [comment]
This is how you can get the API key and put it in your apollo request 
https://github.com/pranayairan/YelpQL/blob/master/app/src/main/java/binarybricks/com/yelpql/network/GraphQLClient.java#L70 

To get auth token you need to call a different service look at this file https://github.com/pranayairan/YelpQL/blob/master/app/src/main/java/binarybricks/com/yelpql/network/YelpService.java 

Let me know if this helps.

**Comment by JakeEllis** [comment]
Thank you for your response @pranayairan! I will have to try this out tonight!

**Comment by watterso** [comment]
Nice. Thanks @pranayairan ! Just want to point out that the second link there references getting an auth token via `client_id` and `client_secret`, this is the old way of doing  authentication (deprecated end of 2017) the new way is with a simple api key, more deets [here](https://www.yelp.com/developers/documentation/v3/authentication)

@JakeEllis It does look like @pranayairan solution of using a request interceptor to add auth header and adding it to the `OkHttpClient` seems like the way to go, keep us posted!

**Comment by watterso** [comment]
@JakeEllis whats the goal of your GraphQL query? The example you gave above is a query to look up a specific business for which you already have an id, but if your goal is to search for businesses at a location and grab some info about them I would suggest using a query like this:
```graphql
{
  search(term:"plumber", location: "san francisco", attributes: "request_a_quote", limit: 20) {
    total
    business {
      name
      id
      rating
      review_count
      messaging {
        url
      }
    }
  }
}
```
This will give you a result like this:
```json
{
  "data": {
    "search": {
      "total": 248,
      "business": [
        {
          "name": "Fast Response Plumbing & Rooter",
          "id": "FVqrsDMdIrlh00d-86bflA",
          "rating": 4.5,
          "review_count": 400,
          "messaging": {
            "url": "https://www.yelp.com/raq/fast-response-plumbing-and-rooter-san-francisco-3?adjust_creative=<client_id>&utm_campaign=yelp_api_v3&utm_medium=api_v3_graphql&utm_source=<client_id>#popup%3Araq"
          }
        },
        ...
      ]
    }
  }
}
```

**Comment by JakeEllis** [comment]
Thanks @watterso . My goal is to look up specific business ids.

I think I have it all figured it out now! I am going through some testing a revisions now.
