### ISSUE TITLE
Popular Dishes Request?

### ISSUE THREAD

**Issue by kantcliff** [Yelp/yelp-fusion#488]
## Overview
- **Client ID:** G88KRyzAOuRJ7Gh7VvGBFg
- **Issue type:**  feature request
- **Summary:** Are there any plans to include "Popular Dishes" in the API?
- **Platform:** Desktop/web

**Comment by watterso** [comment]
Hi @kantcliff , I've noted this as a possible enhancement to the information available in our API, if you have an integration already in mind, this would be something you can request as a part of our [Fusion VIP program](https://www.yelp.com/fusion/vip)

**Comment by kantcliff** [comment]
@watterso, I've applied for the Fusion VIP program. However, I haven't heard back. Any recommendations? Should I be worried about protecting my IP when submitting this sort of request? Thank you for your help!

**Comment by watterso** [comment]
@kantcliff unfortunately I don't have any insight into how Fusion VIP requests are triaged, prioritized, or when / if they respond to requests so I can't help you there, sorry.

Could you clarify what you mean by IP? Is that **I**ntellectual **P**roperty or **I**nternet **P**rotocol (as in your IP address?)?
