### ISSUE TITLE
[Question] Allow additional data to be passed in on businesses-search

### ISSUE THREAD

**Issue by parisbutterfield** [Yelp/yelp-fusion#49]
I just created a new v3 client for Node (https://github.com/parisbutterfield/node-yelp). It's a fork of a v2 client.

I'm often making two API calls and the data returned is pretty much the same. I'm displaying a list of results from /businesses/search and want the hours included on each row in the list.

Example/Problem:
I make a call to https://api.yelp.com/v3/businesses/search
Then I need the hours. There's another call to https://api.yelp.com/v3/businesses/{id}
The data returned from the businesses with the id, is nearly the same as what's in the search.

Potential Solution:
Because everyone doesn't need hours or photos in the /businesses/search/. Allow for an additional query parameter that when set, can include the requested data in the response.

**Comment by tomelm** [comment]
Hey @parisbutterfield! We're trying to find ways to add more data without compromising performance. Having parameters for what you want in a response works well to start but could get hard to manage and cause the query to become huge if too many parameters do that.

#9 covers adding hours permanently to the search endpoint
