### ISSUE TITLE
INTERNAL_ERROR

### ISSUE THREAD

**Issue by sulphide3** [Yelp/yelp-fusion#490]
{u'error': {u'code': u'INTERNAL_ERROR', u'description': u'Something went wrong internally, please try again later.'}}

We get this error a lot but have no idea what it means... Anyone know?

**Comment by watterso** [comment]
@sulphide3 in the future please fill out the issue template rather than submitting a free-form issue like this.

In order to look into this, we'll need your `client_id` (**not** your api key), you can find it on the [manage app page](https://www.yelp.com/developers/v3/manage_app).

**Comment by dan98765** [comment]
Closing this out for lack of information.
