### ISSUE TITLE
query: What does total may be limited to 40 for non-default sorts such as "distance" and "review_count" mean in docs

### ISSUE THREAD

**Issue by rohitshetty** [Yelp/yelp-fusion#491]
## Overview
- **Client ID:**  NA
- **Issue type:** _(question)_
- **Summary:** _(What does " total may be limited to 40 for non-default sorts such as "distance" and "review_count"." mean in the business search endpoint docs? What are the rules triggering this?)_
- **Platform:** NA

## Description
In Business Search Endpoint here https://www.yelp.com/developers/documentation/v3/business_search The description for response `total` reads as "total may be limited to 40 for non-default sorts such as "distance" and "review_count"." What does this mean? What are the condition triggering this total to be 40 ?

## More information
NA
### Endpoint
_(GET https://api.yelp.com/v3/businesses/search)_

### Parameters or Sample Request
NA
### Response
NA
## Extra information
NA

**Comment by dan98765** [comment]
@rohitshetty that description for the "total" parameter is confusing and not really accurate anymore. I've updated the page https://www.yelp.com/developers/documentation/v3/business_search to remove the mention of being limited to 40. Do please open an issue if you encounter any new bugs while working with various values of the `sort_by` parameter.
