### ISSUE TITLE
Add Deals attribute to business details endpoint response

### ISSUE THREAD

**Issue by Gabe-SpotMe** [Yelp/yelp-fusion#492]
## Overview
- **Issue type:** Feature Request
- **Summary:** The search endpoint returns whether or not a business has a deal via the 'attribute' field but the business details endpoint does not return that as a part of the 'attributes' that are returned.

## Description
Other issues have already been closed requesting deals data.  To clarify, I'm not asking to provide the details of what the deal is, just an attribute that says whether or not there is a deal so we know if we should link them to your site.  This is just to add parity between the search endpoint and the business endpoint.

## More information
Currently if we want to get details on a business, we use the search endpoint AND the business details endpoint because only the search endpoint shows the 'deals' attribute.  This results in extra load on both our systems and eats through our rate limit twice as fast.

### Endpoint
https://api.yelp.com/v3/businesses/search or https://api.yelp.com/v3/businesses/{id}

**Comment by dan98765** [comment]
Hi @Gabe-SpotMe thanks for the feature request! I've bumped our internal ticket for this feature.
