### ISSUE TITLE
Can't fetch any records that post 1000 by count

### ISSUE THREAD

**Issue by leonidz83** [Yelp/yelp-fusion#494]
## Overview
- **Client ID:** qgjcHsI-weygz6W836-94Q
- **Issue type:** bug/question
- **Summary:** In case that there are more then 1000 search results from api, how do I pull the 1000+ records if I am limited to `limit + offset <=1000`
- **Platform:** Desktop

## Description
In my search result i am getting more then 1000 records, lets say for this example that I am getting 1200.
How can I pull the last 200 records? at the moment I am not able to do so as I am limited to `limit + offset <=1000`

### Endpoint
Fusion Search API

### Parameters or Sample Request

`search_results = yelp_api.search_query(term='Skin Care', location='Mississauga, On', limit=1, offset=offset)`

### Response
_(SAMPLE PLEASE REMOVE)_
`
{
	'region': {
		'center': {
			'longitude': -79.65774536132812,
			'latitude': 43.59313723570342
		}
	},
	'total': 1200,
	'businesses': [{
		'review_count': 11,
		'categories': [{
			'alias': 'spas',
			'title': 'DaySpas'
		},
		{
			'alias': 'skincare',
			'title': 'SkinCare'
		},
		{
			'alias': 'laser_hair_removal',
			'title': 'LaserHairRemoval'
		}],
		'display_phone': '+1905-271-2980',
		'alias': 'the-body-clinic-day-spa-mississauga',
		'image_url': 'https: //s3-media3.fl.yelpcdn.com/bphoto/J8rqd4Zelwi-Mn66dIC1Ag/o.jpg',
		'rating': 5.0,
		'distance': 6198.395208081101,
		'phone': '+19052712980',
		'name': 'TheBodyClinicDaySpa',
		'location': {
			'city': 'Mississauga',
			'country': 'CA',
			'address2': 'Unit2',
			'display_address': ['1200VanierDrive',
			'Unit2',
			'Mississauga,
			ONL5H4C7',
			'Canada'],
			'state': 'ON',
			'address1': '1200VanierDrive',
			'zip_code': 'L5H4C7',
			'address3': ''
		},
		'id': 'Qx5dhODc6vKib_99IzxmCw',
		'price': '$$',
		'is_closed': False,
		'url': 'https: //www.yelp.com/biz/the-body-clinic-day-spa-mississauga?adjust_creative=qgjcHsI-weygz6W836-94Q&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=qgjcHsI-weygz6W836-94Q',
		'transactions': [],
		'coordinates': {
			'longitude': -79.6263379631581,
			'latitude': 43.542250258203
		}
	}]
}
`

**Comment by dan98765** [comment]
Hi @leonidz83, the restriction that limit+offset must be <=1000 is built into the Fusion API; making Business Search endpoint requests where limit+offset>1000 currently will return an error message with that explanation. 

My general suggestion to people encountering this is: 
A) lower the radius of your search request
B) add a more specific search term/location or filters (i.e. category filters) 
...until you no longer get so many results returned. 

In your case, you might look up several latitude+longitude coordinates of areas within `Mississauga, On` that you are most interested in, and then do low-radius search requests at each of those coordinates. The Business Search endpoint requires you to pass in either a text location OR latitude+longitude to give more flexibility when specifying the search location ([documentation](https://www.yelp.com/developers/documentation/v3/business_search)).
