### ISSUE TITLE
[Question] Are there any post-calls for updating the business entry?

### ISSUE THREAD

**Issue by lucascheurer** [Yelp/yelp-fusion#498]
## Question
I'm currently developing a web tool, which includes automatic synchronisation of external Accounts with the companies data. Is there any API, which I could use to post this data to a yelp entry?

**Comment by dan98765** [comment]
Hi @lucascheurer we do have APIs that can be used to update to business data on Yelp, but they are currently only available to partner companies involved in our Yelp Advertising Partners program (https://www.yelp.com/adpartners - see "Listing Management") or Yelp Platform Partners program (https://www.yelp.com/developers/platform). 

There is no update API available via Yelp Fusion (which is what this github repo is for) at this time.
