### ISSUE TITLE
How do I get an api for a second app?

### ISSUE THREAD

**Issue by frankmancininb** [Yelp/yelp-fusion#499]
Just a quick question, how do I submit information for a second app?  I have one and and want to make another..  It seems that I can only have one key for multiple apps?

## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _(eg. feature request, bug, question, etc)_
- **Summary:** _(A few sentences describing the issue and what you're trying to do)_
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description
_(More detailed information explaining the problem, the expected results, the question, etc.)_

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
_(e.g. Fusion Search API)_

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by dan98765** [comment]
Hi @frankmancininb this is an excellent question. We have on our internal roadmap to build out "Multi-App" support for users, but unfortunately it currently has no timeline for when that will be built. Let's leave this issue open marked as 'enhancement'.

**Comment by joshgilson** [comment]
+1

**Comment by Jzhang0107** [comment]
+1
