### ISSUE TITLE
business_match query is not working under GraphQL

### ISSUE THREAD

**Issue by aratcliffe** [Yelp/yelp-fusion#500]
## Overview
- **Client ID:** ZbvtB6EHglX3MCskelyqhA
- **Issue type:** Bug
- **Summary:** I cannot run any business_match query using GraphQL including the example on the [doc page](https://www.yelp.com/developers/graphql/query/business_match).
- **Platform:** Web

## Description
Attempting to run the business_match example returns the error:
`"Oh no, something went wrong with the GraphQL query! We returned the following error: {'errors': [{'message': 'Cannot query field \"name\" on type \"Businesses\".', 'locations': [{'line': 3, 'column': 5}]}, {'message': 'Cannot query field \"rating\" on type \"Businesses\".', 'locations': [{'line': 4, 'column': 5}]}, {'message': 'Cannot query field \"id\" on type \"Businesses\".', 'locations': [{'line': 5, 'column': 5}]}, {'message': 'Field \"business_match\" argument \"address1\" of type \"String!\" is required but not provided.', 'locations': [{'line': 2, 'column': 3}]}]}"`

I understand `address1` is now a required parameter (but not included in the example) which resolves the last error reported but not the "Cannot query field..." errors.

### Endpoint
GraphQL (https://api.yelp.com/v3/graphql).

### Parameters or Sample Request
```
{
  business_match(name: "Garaje", city: "San Francisco", state: "CA", country: "US", address1: "", match_threshold: NONE) {
    name
    rating
    id
  }
}
```

**Comment by dan98765** [comment]
Hi @aratcliffe thanks for the report. The example on the docs page is out of date. A better working example might be:
```
{
    business_match(
        name: "Walgreens",
      	address1: "Geary",
        city: "San Francisco",
        state: "CA",
        country: "US"
    ) {
        business {
          name
          location {
            formatted_address
          }
        }
    }
}
```
(also since it uses a real biz name that will actually return a result which makes it a nicer example)

I'll update the page with this example.

**Comment by aratcliffe** [comment]
Thanks Dan, that's working for me now.
