### ISSUE TITLE
Request with Accept-Language header containing en-NZ locale is rejected

### ISSUE THREAD

**Issue by aratcliffe** [Yelp/yelp-fusion#501]
## Overview
- **Client ID:** ZbvtB6EHglX3MCskelyqhA
- **Issue type:** Bug
- **Summary:** Request with Accept-Language header containing en-NZ locale is rejected
- **Platform:** Web

## Description
An INVALID_LOCALE error is returned when making a request to the GraphQL endpoint with an Accept-Language header containing the en-NZ locale. Overriding the Accept-Language in the proxy I'm using to use en-US resolves the problem but should not be necessary.

### Endpoint
GraphQL endpoint

### Parameters or Sample Request

```
Accept-Language: en-NZ,en-US;q=0.9,en;q=0.8,la;q=0.7
```

### Response
```
{"error": {"code": "INVALID_LOCALE", "description": "The locale you specified is not valid."}
```

**Comment by dan98765** [comment]
`en-NZ` is not a yelp-supported locale. Check out the list of supported locales at https://www.yelp.com/developers/documentation/v3/supported_locales

I think we could make the error message better; we have the same INVALID_LOCALE code if the locale is a totally bogus locale and if it's a valid locale but not supported by Yelp.

**Comment by aratcliffe** [comment]
@dan98765 en-NZ is listed on the page you linked to. In my case the request is initiated by the client and whatever headers set by the browser were passed through to the endpoint by the proxy which would not be an uncommon scenario. As the locale wasn't being set by me explicitly it took some hours to get to the root of the problem. If the error message had said that an invalid locale had been passed in the Accept-Language I would have been able to resolve the problem a lot quicker.

**Comment by dan98765** [comment]
*facepalm* yes you're right it is there, my bad. I'll ticket internally to improve the error message.

**Comment by aratcliffe** [comment]
Thanks. So there are 2 issues: if the docs are correct the request should have succeeded as en-NZ is a supported locale and secondly the error message could explicitly identify the header as the source when an invalid locale is passed that way.
