### ISSUE TITLE
API key is N/A

### ISSUE THREAD

**Issue by SeongwoonHong** [Yelp/yelp-fusion#503]
## Overview
- **Client ID:** 7KX1N6fXhVTvdtFcT25K5w
- **Issue type:**  bug
- **Summary:** API key is N/A. cannot even refresh it
- **Platform:** Mac OS 10.13.6

## Description

Yelp api has been returning same search results so i was wondering why and have realized that my api key is N/A in https://www.yelp.com/developers/v3/manage_app

<img width="300" alt="Screen Shot 2019-03-11 at 10 05 21 PM" src="https://user-images.githubusercontent.com/19713918/54169657-085b9880-444a-11e9-9204-7ffa1759606b.png">

So, I've tried to refresh the key by clicking 'Refresh my API key' button and I got this message

<img width="593" alt="Screen Shot 2019-03-11 at 10 05 46 PM" src="https://user-images.githubusercontent.com/19713918/54169659-0abdf280-444a-11e9-9c5c-26dd7feafe62.png">

### Endpoint
_(e.g. Fusion Search API)_
https://api.yelp.com/v3/businesses/search

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
https://api.yelp.com/v3/businesses/search?categories=Afghan Restaurant&location=new york

**Comment by abhinav118** [comment]
Facing the same issue right now! Any update on this?
