### ISSUE TITLE
Refresh API key returns server error

### ISSUE THREAD

**Issue by stepantubanov** [Yelp/yelp-fusion#506]
## Overview
- **Client ID:** KKIuJe82NFkUXLc-kplx_Q
- **Issue type:** bug
- **Summary:** Click on a "Refresh API key" deleted the old key without generating a new one.
- **Platform:** _(Desktop/web, Android, iOS, etc)_

## Description

We had a working API key, it was time to update it as part of regular credential rotation. Click on "Refresh API key" button returned a server error but managed to make our old key invalid. The old API key does not work and the new one was not generated.

Button that was used:
<img width="536" alt="Screenshot 2019-03-29 at 21 17 09" src="https://user-images.githubusercontent.com/1050523/55260437-b9469d80-5268-11e9-869d-48deb1d3f595.png">

Result of clicking the button:
<img width="727" alt="Screenshot 2019-03-29 at 21 17 26" src="https://user-images.githubusercontent.com/1050523/55260447-be0b5180-5268-11e9-89f6-8da5753f5402.png">

Expected behavior: A new API key.

### Endpoint
https://api.yelp.com/v3/businesses/search

### Parameters or Sample Request

```
https://api.yelp.com/v3/businesses/search?locale=en_US&location=401%20Laconia%20Lane,%20Schaumburg,%20IL,%2060193&term=HomeTeam%20Inspection%20Service
```

### Response

Using the old key this now yield authorization error.

```
{"error": {"code": "UNAUTHORIZED_ACCESS_TOKEN", "description": "The access token provided is not currently able to query this endpoint."}}'
```

## Extra information

Has been like this for a while. Initially tried to update on March 6. Have tried a few times since then last time today - server error still.

**Comment by stepantubanov** [comment]
Looks like this might be the same as https://github.com/Yelp/yelp-fusion/issues/503 but that one is closed for some reason.

**Comment by abhinav118** [comment]
Facing the same issue right now! Any update on this? @virgytam

**Comment by dan98765** [comment]
Hi @stepantubanov thanks for your bug report. We believe we have now fixed the "Refresh My API Key" button on the Manage App page. Please try clicking it, and your key should be regenerated and displayed correctly. Please let us know if you encounter any other issues - thanks!
