### ISSUE TITLE
postman error

### ISSUE THREAD

**Issue by korymath** [Yelp/yelp-fusion#51]
Error getting access token from client_credentials flow: SyntaxError: Unexpected token < in JSON at position 0

**Comment by tomelm** [comment]
Could you try this without postman? Seems like postman might be doing something weird

**Comment by BusbyActual** [comment]
I tried the web version of postman and it worked for me

**Comment by mittonk** [comment]
@korymath : Are you still having trouble in Postman?  What is the response body you receive?  Are you getting an HTTP 200 or other status code?

(I have a hunch the < is from an HTML error page, possibly from an intermediate CDN or load-balancer rather than the actual API.)

**Comment by korymath** [comment]
The error that I see is this: 
Error getting access token from client_credentials flow: SyntaxError: Unexpected token < in JSON at position 0

But that is just on trying to Request the Access Token in Postman. This is on the mac version, I will try the online version.

**Comment by mittonk** [comment]
@korymath : I think you might be trying to use Postman's OAuth helpers?  I'd suggest using the Postman collection here:
* https://www.yelp.com/developers/documentation/v3/get_started

and manually POSTing to /oauth2/token , and copying the resulting access_token.

There are many configuration options in Postman's OAuth helpers, I've found them more confusing than helpful.

**Comment by watterso** [comment]
Closed because of inactivity / Issue is resolved.
