### ISSUE TITLE
Help with API key - displays as N/A

### ISSUE THREAD

**Issue by vlloyd-ilm** [Yelp/yelp-fusion#515]
## Overview
- **Client ID:** _y-J0p4-5Ibk8Qj9pUMMcmg_
- **Issue type:** _API key says N/A_
- **Summary:** _Our API key appears to not be functioning. It currently says N/A_
- **Platform:** _Desktop_

## Description
Our reviews are integrated on a website so while the API key isn't functioning properly the site shows we have no Yelp reviews, and a 0 star rating. I've tried refreshing the key but am getting "The dog ate our website" error.
![Capture](https://user-images.githubusercontent.com/50589385/57635065-79b3e680-7574-11e9-847b-a9b6fd2fde10.JPG)
![Capture2](https://user-images.githubusercontent.com/50589385/57635093-88020280-7574-11e9-9072-2d1cff2e7bba.JPG)

 _

## More information
_(What is the issue here? I know a similar ticket was opened last month but it hasn't been solved.)_

### Endpoint
_(Fusion Search API)_

```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response

```

**Comment by dan98765** [comment]
Hi @vlloyd-ilm thanks for your bug report. We believe we have now fixed the "Refresh My API Key" button on the Manage App page. Please try clicking it, and your key should be regenerated and displayed correctly. Please let us know if you encounter any other issues - thanks!
