### ISSUE TITLE
"The dog ate our website" every time I try to refresh my API key. 

### ISSUE THREAD

**Issue by vietbub** [Yelp/yelp-fusion#516]
Today, 5/13/2019, I've been trying to refresh my API key. After clicking the confirmation, I get the website error page of "The dog ate our website". I've attempted this in multiple browsers and same error pops up. I've been attempting sporadically all day which huge time gaps in between.

**Comment by dan98765** [comment]
Hi @vietbub thanks for your bug report. We believe we have now fixed the "Refresh My API Key" button on the Manage App page. Please try clicking it, and your key should be regenerated and displayed correctly. Please let us know if you encounter any other issues - thanks!
