### ISSUE TITLE
No API key provided (N/a)

### ISSUE THREAD

**Issue by AMCL9** [Yelp/yelp-fusion#517]
## Overview
- **Client ID:** _(47mPXr_ZdDLRW9zUyYmTAw)_
- **Issue type:** _(no API key)_
- **Summary:** _(tried to create an App, No API key provided, cannot refresh API key either)_
- **Platform:** _(Desktop)_

## Description
_(tried to create an App, No API key provided, cannot refresh API key either)_

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

**Comment by dan98765** [comment]
Hi @AMCL9 thanks for your bug report. We believe we have now fixed the "Refresh My API Key" button on the Manage App page. Please try clicking it, and your key should be regenerated and displayed correctly. Please let us know if you encounter any other issues - thanks!
