### ISSUE TITLE
Getting limited access of 1000 records of only full services restaurants but not getting any limited service restaurants

### ISSUE THREAD

**Issue by IngridCooper** [Yelp/yelp-fusion#520]
## Overview
- **Client ID:** Z7cHy8w1HG2Rl7W5-dhQ
- **Issue type:** Question
- **Summary:** We need the limited service restaurants also alongwith the full services restaurants in Peachtree Corners and Norcross, GA, US
- **Platform:** Android, iOS

## Description
We have integrated Yelp SDK to get the restaurants in Peachtree Corners and Norcross, GA, US but we are getting only a maximum of 1000 restaurants and which are all full service restaurants. We would like to get the limited service restaurants as well. We have attached screenshots of the Yelp integration and attribution in our app.

Can you please let us know how we can get the limited service restaurants as well in our app?

### Endpoint
```
const client = yelp.client(<<API Key>>);
client.search(searchRequest(offset))
```

### Parameters or Sample Request
```
const client = yelp.client(<<API Key>>);
client.search(searchRequest(offset))

const searchRequest = (offset) => {
    return {
      term: 'Restaurent',
      location: 'peachtree corners, ga',
      offset: offset,
      limit: YELP_LIMIT
    }
  };
```

### Response
![Yelp Branding and Rating in Dining   Entertaiment](https://user-images.githubusercontent.com/1281787/58233237-1b97b800-7d59-11e9-8e39-f7d36a7be848.png)

```
{
	"id": "5cdd4e2539229c6ec30fc047",
	"list": {
		"id": "iBaxEk9uL2JRrr0eI25AxQ",
		"alias": "ba-bellies-peachtree-corners",
		"name": "Ba Bellies",
		"image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/iIqYrse9HjXUmmNPNmsqVw/o.jpg",
		"is_closed": false,
		"url": "https://www.yelp.com/biz/ba-bellies-peachtree-corners?adjust_creative=_Z7cHy8w1HG2Rl7W5_-dhQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=_Z7cHy8w1HG2Rl7W5_-dhQ",
		"review_count": 343,
		"categories": [{
			"alias": "asianfusion",
			"title": "Asian Fusion"
		}, {
			"alias": "gastropubs",
			"title": "Gastropubs"
		}],
		"rating": 4.5,
		"coordinates": {
			"latitude": 33.956238,
			"longitude": -84.233545
		},
		"transactions": ["pickup", "delivery"],
		"price": "$$",
		"location": {
			"address1": "6025 Peachtree Pkwy",
			"address2": "Ste 9",
			"address3": "",
			"city": "Peachtree Corners",
			"zip_code": "30092",
			"country": "US",
			"state": "GA",
			"display_address": ["6025 Peachtree Pkwy", "Ste 9", "Peachtree Corners, GA 30092"]
		},
		"phone": "+17707100565",
		"display_phone": "(770) 710-0565",
		"distance": 1288.8417495778974
	}
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by pakcybershagufta** [comment]
I m facing issue in business search api
Limit 50
Offset 1
Category bars
Location Houston TX
I m getting same records?

**Comment by dan98765** [comment]
Hi @IngridCooper  thanks for the report. We do not distinguish between full and limited service restaurants in the business search response. Could you give an example of a business that you expect to see in the response (a limited service restaurant) that you are unable to get back?

You also mentioned you can only get 1000 results. As per https://www.yelp.com/developers/documentation/v3/business_search we only allow up to 1000 results to be returned with combinations of limit+offset for non-Fusion-VIP API keys.

**Comment by IngridCooper** [comment]
Hi @dan98765 thank you for your reply. Sure, examples of limited service restaurants that we expect to see in our API response are Dunkin Donuts, Panda Express etc. However, we are able to see these restaurants in the Yelp website. The below are their respective Yelp website links:

Dunkin Donuts: https://www.yelp.com/biz/dunkin-donuts-norcross-7?osq=Dunkin+Donuts
Panda Express: https://www.yelp.com/biz/panda-express-norcross

Regarding getting only upto 1000 results, could you please let us know the steps to move forward on how we can get Fusion VIP API keys so that we can get more than 1000 results in our app?
