### ISSUE TITLE
How can we get all SF restaurants business data? 

### ISSUE THREAD

**Issue by junnychen** [Yelp/yelp-fusion#525]
## Overview
- **Client ID:** _oS0tLlCfmLFzmEX0BdPgSQ_
- **Issue type:** _(eg. result request)_
- **Summary:** _(Request to get more than 1,000 restaurants result in SF.)_

## Description
Hi, 

We are trying to get 4000+ restuarants business reults for a school project by calling Yelp Fusion API, but only getting 986.  
Is it possible to get them all by calling it multiple times? Please let us know. Thank you so much
## More information

Python code in Jupyter notebook

url = 'https://api.yelp.com/v3/businesses/search?location=San Francisco&limit=50'
API_KEY = 'Bearer APIKEY..'
r = requests.get(url, headers={'Authorization': API_KEY}).json()
df=pd.io.json.json_normalize(r['businesses'])

for i in range(1,20):
        r = requests.get(url+'&offset='+str(i*50), headers={'Authorization': API_KEY}).json()
        df=df.append(pd.io.json.json_normalize(r['businesses']))

```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

**Comment by jasony0206** [comment]
Hi @junnychen, thank you for opening this issue. As per https://www.yelp.com/developers/documentation/v3/business_search, we only allow up to 1000 results to be returned for non-Fusion-VIP API keys. If you're interested in **Fusion VIP**, please check out https://www.yelp.com/fusion/vip.
