### ISSUE TITLE
Yelp Authorization problem

### ISSUE THREAD

**Issue by tanyagmaslach** [Yelp/yelp-fusion#528]
Hi,
I have tried several ways to get an access token (Yelp Fusion API) and been unsuccessful.

Issue type: can get authorization token for using Yelp API.

Summary:  In postman, I  put the GET request URL for the endpoint I want (https://api.yelp.com/businesses/matches) and in Headers, I put Key: Authorization  Value: Bearer <API Key> but I get error 
COULD NOT GET ANY RESPONSE.
Platform: desktop, mac

## Description and Sample request
I am trying to score quality of restaurants by only their proximity to search origin...so I need lat/long and zip.  But I can't even get an access code and am frustrated. 

### Endpoint
Yelp Fusion API  https://api.yelp.com/businesses/matches)

Thank you!

**Comment by kumar88kanishk** [comment]
Hi peeps, this doesnt work me either, can anyone help
