### ISSUE TITLE
Not giving proper result

### ISSUE THREAD

**Issue by akatrodiya** [Yelp/yelp-fusion#53]
My Search queries:
1. https://api.yelp.com/v3/businesses/search?term=Holonis&latitude=32.7180088&longitude=-117.1578045&limit=10
result: { "businesses": [],  "total": 0}

2.  https://api.yelp.com/v3/businesses/search/phone?phone=+18885524037
result: { "error": { "code": "CLIENT_ERROR", "description": "Bad Request" }}

Company already exist in Yelp: https://www.yelp.com/biz/holonis-san-diego

I'm working with Yelp API from like a month.. I see some strange things in it.. It is working for some businesses.. it is not for few. I already see it is working for few companies.. like.. these are working:

1. https://api.yelp.com/v3/businesses/search?term=We Olive & Wine Bar&latitude=32.8488417&longitude=-117.2753434&limit=10

2. https://api.yelp.com/v3/businesses/search/phone?phone=+18585518250

I could not understand it.. is there any privacy in data? I also saw phone search is not working for many companies. Please guide me.

**Comment by watterso** [comment]
Hi @akatrodiya, I'm looking into this, I'll update this with information I find.

**Comment by mittonk** [comment]
Hm, this looks like a business with 0 reviews.  @watterso , did you notice that aspect?

**Comment by akatrodiya** [comment]
@mittonk hmm.. I noticed it now.. but If there is no reviews in the business. we should at least get the basic details.

**Comment by mittonk** [comment]
Sorry, the Yelp Fusion API does not return businesses with 0 reviews.
