### ISSUE TITLE
Fatal Error: Curl failed with error #500: {"error": {"code": "INTERNAL_ERROR", "description": "Something went wrong internally, please try again later."}

### ISSUE THREAD

**Issue by ImChase** [Yelp/yelp-fusion#540]
## Overview
- **Client ID:** _(e.g. 54iswz5SmV1DXmyou4JsZw)_
- **Issue type:** _(eg. Started getting this error message)_
- **Summary:** _(We are simply pulling Yelp reviews, mostly for testing purposes at this point, and things were working well for over a month and nothing on our end changed yet this error started occuring. The reviews still pull at least half the other time, and the other half we get this error.)_
- **Platform:** _(Desktop and Mobile)_

### Endpoint
_(e.g. Fusion Search API v3)_

### Parameters or Sample Request
Relevant code here:
https://pastebin.com/nhgY0PTh
```

### Extra information
_(Everything was working flawlessly, only in the last week maybe did this error start happening. I really am quite unsure what is happening, as it doesn't always fail either.)_

**Comment by ihalter** [comment]
I've got the same thing here - intermittently just stopping from working. I hit the API repeatedly many times, do you think adding a pause between requests would resolve this issue? I'm using the open-sourced Yelp API code, so likely not a syntax issue: https://github.com/Yelp/yelp-fusion/blob/master/fusion/python/sample.py

ClientID: lsG8ZNMv8UjoidMAHAzIVw
IssueType: _see above_
Summary: _see above_
Platform: Windows 10 Desktop


```
headers = {
        'Authorization': 'Bearer %s' % api_key,
    }
    response = requests.request('GET', url, headers=headers, params=url_params)
```
url_params: {'term': 'restaurants', 'longitude': -76.27, 'latitude': 36.86586, 'radius': 7400, 'limit': '50', 'offset': 350}
returned: {'error': {'code': 'INTERNAL_ERROR', 'description': 'Something went wrong internally, please try again later.'}}
