### ISSUE TITLE
400 Status Error when trying to send "raw graphql" request in Swift

### ISSUE THREAD

**Issue by fad0** [Yelp/yelp-fusion#555]
## Overview
- **Client ID:**   FnEUiXIJOvYs9MR-SgYyzQ
- **Issue type:** Can't get "raw graphql" request to work in swift
- **Summary:** I create the full url request, with correct headers, and "raw graphql" data, but keep getting a 400 status error
- **Platform:** Swift 5 on a MacAir in Xcode.

## Description
The main issue is I can't find an example of how to do a "raw graphql" request in Swift.  The curl example here: https://www.yelp.com/developers/graphql/guides/intro works fine on the command line.  I'm trying to built the same request in Swift and can't get it to work.  Here's the relevant part of my code:

```
        let url = URL(string: "https://api.yelp.com/v3/graphql")
        let session = URLSession.shared
        var request = URLRequest(url: url!)
        request.httpMethod = "POST"
        request.setValue("application/graphql", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer <my actual key>", forHTTPHeaderField: "Authorization")

        let paramToSend = "{ business(id: \"Hgc27X2PX2jZQMcVtbJ9vQ\") { name } }"
        request.httpBody = paramToSend.data(using: String.Encoding.utf8)
        let task = session.dataTask(with: request, completionHandler: {
            (data, response, error) in
```

### Response

```
request: https://api.yelp.com/v3/graphql
response : Optional(<NSHTTPURLResponse: 0x600002b7aee0> { URL: https://api.yelp.com/v3/graphql } { Status Code: 400, Headers {
    "Accept-Ranges" =     (
        bytes
    );
    "Content-Length" =     (
        94
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Wed, 29 Jan 2020 17:40:31 GMT"
    );
    Server =     (
        nginx
    );
    Via =     (
        "1.1 varnish"
    );
    "x-b3-sampled" =     (
        0
    );
    "x-cache" =     (
        MISS
    );
    "x-cache-hits" =     (
        0
    );
    "x-proxied" =     (
        "10-65-214-75-useast1cprod"
    );
    "x-routing-service" =     (
        "10-65-150-72-useast1bprod; site=public_api_v3"
    );
    "x-served-by" =     (
        "cache-ams21021-AMS"
    );
    "x-zipkin-id" =     (
        2f273dab4533a468
    );
} })

```

## Extra information
I don't think I can use apollo because the graphql requests are pre-generated into a API.swift and my graphql requests will change depended on how many businesses I am trying to get information for.  Sending the "raw graphql" request looks easy, but I can't get it to work.

**Comment by Daniel-Reiling** [comment]
Did you ever get the "raw graphql" query to work? 

I am facing the same issue trying to make a query with a dynamic list of business ids, meaning I can not use Apollo.

**Comment by Daniel-Reiling** [comment]
Actually I got a raw query to work by expanding your code. Your code was all right except the server expects the "Accept-Language" header to be set. I set mine to "en-US". The code is provided below.

        let url = URL(string: "https://api.yelp.com/v3/graphql")!
        let session = URLSession.shared

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/graphql", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.setValue("en-US", forHTTPHeaderField: "Accept-Language")

        let paramToSend = """
        {
            business(id: \"\(testBusinessID)\") {
                name
            }
        }
        """

        request.httpBody = paramToSend.data(using: .utf8)

**Comment by fad0** [comment]
@Daniel-Reiling 
No.  I never figured it out.  I just tried it with the added setValue and it worked.  Thank you, thank you, thank you!!!  How the hell did you figure it out?  Was it trial and error or some reference/manual?

**Comment by Daniel-Reiling** [comment]
@fad0 
I actually tried using Apollo first before I realized the API limitation. But during that process, I printed the `error.localizedDescription` and that lead me to the answer here: 

https://www.yelp.com/developers/graphql/guides/localization

Glad I can help! From the commits on this repo and the issues, I can not tell if the Yelp API is still supported or being worked on...
