### ISSUE TITLE
How to get more then three reviews from yelp fusion api?

### ISSUE THREAD

**Issue by Sukhwinder92** [Yelp/yelp-fusion#557]
## Overview
- **Issue type:** get all reviews from yelp fusion API
- **Platform:** _(web)_

## Description
want to get all reviews post on yelp business page using yelp api in web.

                var FeedRequestUrl = "https://api.yelp.com/v3/businesses/TR0-w6VoZDAdvFQiq7P2Ug/reviews";
                HttpWebRequest feedRequest = (HttpWebRequest)WebRequest.Create(FeedRequestUrl);
                feedRequest.Method = "GET";
                feedRequest.Accept = "application/json";
                feedRequest.ContentType = "application/json; charset=utf-8";
                feedRequest.Headers.Add("Authorization", "Bearer p4*************************************************************************************************************nXg2tLJoii_UteoJCXnYx");
                WebResponse feedResponse = (HttpWebResponse)feedRequest.GetResponse();
                using (feedResponse)
                {
                    using (var reader = new StreamReader(feedResponse.GetResponseStream()))
                    {
                        var result = reader.ReadToEnd();
                        return result; 
                    }
                }

### Endpoint
but return only three reviews

**Comment by ihl396** [comment]
Can someone from the team respond with an update or a proper label?
