### ISSUE TITLE
500 Error using curl and yelp-fusion package.

### ISSUE THREAD

**Issue by yahorkhatskoleverx** [Yelp/yelp-fusion#566]
## Overview
- **Client ID:** _L-l4plBkZ9o1ve34CCNolA_
- **Issue type:** _bug_
- **Summary:** _I request data from my application and get 500 error. Same thing with requesting from Postman_
- **Platform:** _Node.js_

## Description
_I request data from my Node.js application using yelp-fusion and sometimes got 500 error. I thought that it could be connected with yelp-fusion package so I decided to try this request in the Postman. So this 500 error also appears when I request API from Postman. This error does not always appear. I can send some requests to the API and it return 200 status but sometimes it return 500 status error._

### Endpoint
_Fusion Search API v3_

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?longitude= -122.43644714355469&latitude=37.778917407781236&radius=1200&limit=50&offset=100
```

### Response
```
{
    "error": {
        "code": "INTERNAL_ERROR",
        "description": "Something went wrong internally, please try again later."
    }
}
```

**Comment by bizmate** [comment]
Is the space between the = and the - in the url longitude parameter in your test requests?

**Comment by yahorkhatskoleverx** [comment]
@bizmate it's just a typo, sorry. 500 error keeps appearing with the correct URL.
