### ISSUE TITLE
more than 5 categories in search API????

### ISSUE THREAD

**Issue by mwilliams-sh** [Yelp/yelp-fusion#57]
Can anyone tell me if there is a way to use/select more than 5 "categories" when doing a search request through the Yelp Search API?  We would like to be able to use/select up to 15-20 categories...is that possible?  Right now it limits us to 5.

Thanks!
Mark

**Comment by mittonk** [comment]
@mwilliams-sh : What's your use case for that many categories?  Have you considered using a higher-level category (like "restaurants" instead of "chinese,mexican"?)

**Comment by mwilliams-sh** [comment]
I have thought about using a higher category like restaurants, but I am trying to do a broad enough search request to get as many restaurant types in the results without having everything show up like fast food restaurants.

Mark Williams
CEO
QuickTable
(330) 575-7339

**Comment by mittonk** [comment]
That makes some sense, sounds like a @guangyang question at this point.

**Comment by mwilliams-sh** [comment]
so do you know if this is possible, or am I absolutely limited to 5 categories in a single search?

**Comment by mittonk** [comment]
@mwilliams-sh : Hm, ~10 categories are working for me.  

Are you getting an HTTP error code?  If so, could you supply a gist of the query & error output?

Or are you just not seeing matches from categories 6, 7, 8..?  If so, could you provide an example query & output?

**Comment by mittonk** [comment]
10 categories works for me.
