### ISSUE TITLE
Trying to use Yelp business search api, errors

### ISSUE THREAD

**Issue by DanaNobile** [Yelp/yelp-fusion#571]
I am getting so many mixed answers- what data do i need to get the api to work? I see authorization bearer, I see secret codes, api keys, I don't know what the current format is.

    var queryURL = "https://api.yelp.com/v3/businesses/search?term=restaurants";
WHERE DOES MY API GO?

        $.ajax({
            url: queryURL,
            headers: {
                Authorization: 'Bearer WHAT GOES HERE? ',
            },
            method: 'GET',
            dataType: 'json'
        })   
                console.log(queryURL);
                console.log(response);

**Comment by JOyo246** [comment]
https://www.yelp.com/developers/documentation/v3/authentication

> To authenticate API calls with the API Key, set the Authorization HTTP header value as Bearer API_KEY.
