### ISSUE TITLE
How to get only restaurants, Not fast food, coffee, sandwiches, etc?

### ISSUE THREAD

**Issue by prakashnnpatel** [Yelp/yelp-fusion#572]
## Overview
- **Client ID:** 
- **Issue type:** Get mix categories data
- **Platform:** Web

## Description
We are using Yelp API to display nearby restaurants, but it pull a lot of mix data like fast food, food trucks, delivery, coffee & tea, sandwiches, motorcycle repair, etc
is there any way to pull only restaurants? we already set categories & term attributes in request.

### Endpoint
https://api.yelp.com/v3/businesses/search?categories=restaurants&term=restaurants&latitude=40.0239724&longitude=-105.25313466&location=Boulder%2C+CO&limit=10&sort_by=distance

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/search?categories=restaurants&term=restaurants&latitude=40.0239724&longitude=-105.25313466&location=Boulder%2C+CO&limit=10&sort_by=distance

**Comment by JOyo246** [comment]
This is just a flaw of yelp.... check out their app and search for restaurants, you'll likely get similar results as the api call.
