### ISSUE TITLE
Business search Yelp API

### ISSUE THREAD

**Issue by Dija-pingme** [Yelp/yelp-fusion#573]
![image](https://user-images.githubusercontent.com/66441184/83803018-ce436b80-a679-11ea-949e-445270b5e41c.png)

 I am trying to access the business search API and above is the encountered error.
In the documentation of business search (https://www.yelp.com/developers/documentation/v3/business_search), there isn't any authorization field. 
Any input on this, will be of great help.

**Comment by JOyo246** [comment]
https://www.yelp.com/developers/documentation/v3/authentication

> To authenticate API calls with the API Key, set the Authorization HTTP header value as Bearer API_KEY.
Just because there's no URL parameter does not mean that there's no authorization.
If you slide over two tabs to the left on that top panel, you'll be golden..
