### ISSUE TITLE
Documentation incorrect for pricing_filter

### ISSUE THREAD

**Issue by thedanotto** [Yelp/yelp-fusion#58]
[Business Search Documentation](https://www.yelp.com/developers/documentation/v3/business_search) states to use `pricing_filter`:

![screen shot 2016-09-22 at 11 03 38 am](https://cloud.githubusercontent.com/assets/5581358/18756152/708e5020-80b4-11e6-8b63-206209e8d917.png)

**DOESN'T WORK:** https://api.yelp.com/v3/businesses/search?term=food&latitude=36.143309&longitude=-86.767002&pricing_filter=1,2

**DOESN'T WORK:** https://api.yelp.com/v3/businesses/search?term=food&latitude=36.143309&longitude=-86.767002&price_filter=1,2

**WORKS:** https://api.yelp.com/v3/businesses/search?term=food&latitude=36.143309&longitude=-86.767002&price=1,2

Possible Solution: Update your Business Search Documentation to be correct?

**Comment by mittonk** [comment]
Good catch, that looks wrong to me as well.

**Comment by mittonk** [comment]
Looks like fallout from a filter-name change in #42.

**Comment by mittonk** [comment]
Looks like commit https://github.com/Yelp/yelp-fusion/commit/dfb51ea09cdfde902a76fbb9fdfeb078869b99b5 got dropped when we moved the documentation from Github to yelp.com/developers .  Merging those changes back in.

**Comment by mittonk** [comment]
Updated docs to use the new names `price` and `open_now`.  Thanks for the catch!
