### ISSUE TITLE
authentication in api 3.0

### ISSUE THREAD

**Issue by saurabhima** [Yelp/yelp-fusion#59]
I am having problem in authentication with fusion api v3.0 in python. Can you give me a sample code for this authentication in python

**Comment by thedanotto** [comment]
Sorry not a python dev, but using the requests library along with this should help. Going to https://www.yelp.com/developers/documentation/v3/get_started and clicking on the Postman button helped me successfully authenticate.

Make a POST Request to
https://api.yelp.com/oauth2/token

And send your client_id, client_secret in the body. Also send `grant_type`: `client_credentials`

![screen shot 2016-09-22 at 1 03 23 pm](https://cloud.githubusercontent.com/assets/5581358/18760072/0b3c626e-80c5-11e6-86fc-4a81a16b2e8f.png)

Once you have your access Token -- You need to pass it in the header. This wasn't at all clear in the API documentation, but you need to pass it like `Authorization: Bearer [access_token]
![screen shot 2016-09-22 at 1 05 23 pm](https://cloud.githubusercontent.com/assets/5581358/18760113/3f6f8e58-80c5-11e6-8bd2-01a7b1745cfb.png)

**Comment by mittonk** [comment]
We're looking into Python examples!  We don't have them ready yet, sorry.

For now, I'd suggest imitating the Postman requests on https://www.yelp.com/developers/documentation/v3/get_started , as @thedanotto suggested.

**Comment by GaillePug** [comment]
Thanks for the suggestions. Just bumping this up! 

I'm using the Requests library and setting the Authorization HTTP header to Bearer: headers = {'Authorization': 'Bearer %s' % authorization_token}

I get status code 500: "The server has either erred or is incapable of performing the requested operation".

What am i missing?

**Comment by jj99999** [comment]
I'm also having a problem with authentication.  I got an access token using Postman.  I send an ajax call using the token but the response I get back is a TOKEN_MISSING error.   Can you tell me what I'm doing wrong?

  var token = "....my access token goes here.....";
  var queryURL = "https://crossorigin.me/https://api.yelp.com/v3/businesses/search?term=pizza&latitude=40.4941043&longitude=-74.440837&pricing_filter=1&limit=10";

      $.ajax({
        url: queryURL,
	method: 'GET',
	beforeSend: function(xhr, settings){xhr.setRequestHeader('Authorization', 'Bearer ' + token);},
        complete: function(response){ console.log(response) }
       });

**Comment by mittonk** [comment]
@jj99999 : You're using crossorigin.me , I suspect that's not passing on the `Authorization` header.  Please try sending a request directly to yelp.com for comparison (probably from a non-XHR environment because of CORS).

**Comment by harishperfect** [comment]
@mittonk 
Python Example here for oauth 2.0 (Yelp Fusion API v3)

```
import re
import requests
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

#Fill app key details from Yelp
client_id = '<client id here>'
client_secret = '<client secret here>'

#Authenticate and get access token
client = BackendApplicationClient(client_id=client_id)
yelp = OAuth2Session(client=client)
token = yelp.fetch_token(token_url='https://api.yelp.com/oauth2/token', client_id=client_id, client_secret=client_secret)

#Construct custom Authentication header
#Can use a better way to access the token string from returned unicode JSON. This is quick and dirty
tokenstring = str(token)
accesstok = re.findall(r"'access_token': u'(.*?)', ",tokenstring)
authhead = "Bearer " + accesstok[0]
head = {'Authorization': authhead}

#Call needed yelp endpoint with custom header using requests module
r = requests.get("https://api.yelp.com/v3/businesses/north-india-restaurant-san-francisco/reviews", headers= head)
print r.text

```

Outputs the last 3 review of location.

Thanks to @thedanotto for showing Authorization header construction on postman

**Comment by harishperfect** [comment]
@mittonk 

Python oauth 2.0 for Fusion V3

```
import requests
 
app_id = 'client_id'
app_secret = 'client_secret'
data = {'grant_type': 'client_credentials',
        'client_id': app_id,
        'client_secret': app_secret}
token = requests.post('https://api.yelp.com/oauth2/token', data=data)
access_token = token.json()['access_token']
url = 'https://api.yelp.com/v3/businesses/search'
headers = {'Authorization': 'bearer %s' % access_token}
params = {'location': 'San Bruno',
          'term': 'Japanese Restaurant',
          'pricing_filter': '1, 2',
          'sort_by': 'rating'
         }
 
resp = requests.get(url=url, params=params, headers=headers)
 
import pprint
pprint.pprint(resp.json()['businesses'])
```

Code by @dawran6

**Comment by mittonk** [comment]
@saurabhima , @harishperfect (and maybe even @thedanotto) : I've added a basic Python example at 
* https://github.com/Yelp/yelp-fusion/tree/master/fusion/python

Please take it for a spin, and file new issues with any bugs or enhancements!

**Comment by JackEdwardLyons** [comment]
In POSTMAN I had to add the Authorization and search term details in as key / value parameters. See screenshot.

![yelp-screenshot](https://cloud.githubusercontent.com/assets/16175039/26259870/314ffec8-3c88-11e7-89bc-5aaef208a8d9.png)

**Comment by ngokul3** [comment]
![error](https://user-images.githubusercontent.com/3115544/30231943-5c12b55c-94bb-11e7-81d3-2be23b72045a.png)

Attached is the error that I'm getting while trying to fetch token from Yelp. Am I missing something?

**Comment by mittonk** [comment]
@ngokul3 : Looks like you've got too many "a"s in the URL; should be `https://api.yelp.com/oauth2/token` .

**Comment by ngokul3** [comment]
You are right! The URL was not correct. Thanks

**Comment by Pigpocket** [comment]
Yelp Fusion's API documentation states that tokens are no longer necessary, and that I can use an API Key on its own. However, when I try doing a call in Postman, similar to @JackEdwardLyons above, I get the following response:

{
    "error": {
        "code": "TOKEN_MISSING",
        "description": "An access token must be supplied in order to use this endpoint."
    }
}

My call looks like so: 

https://api.yelp.com/v3/businesses/search?term=restaurant&location=boulder&Authorization=Bearer MyApiKey

...where "MyApiKey" is my API Key. Am I missing something?

**Comment by Pigpocket** [comment]
Hey just curious if anyone knew the answer to my question above. Thank you.

**Comment by mittonk** [comment]
@Pigpocket : That Authorization is a header, not a query string keyword.  Think of it as:
URL: https://api.yelp.com/v3/businesses/search?term=restaurant&location=boulder
Headers: "Authorization" => "Bearer MyApiKey"

See the steps in https://www.yelp.com/developers/documentation/v3/authentication , especially "set the Authorization HTTP header value as Bearer API_KEY."

Does that help?

(Also: Next time I'd suggest opening a fresh issue, rather than commenting on a closed one; that'll help us notice more quickly.)

**Comment by Pigpocket** [comment]
Yes, that helps! I've got it working now. Sorry, I know that was a bit of a newbie question, so I appreciate your response. It is also the first time I've posted a question on Github... I'll make sure to do it in a new issue next time. 

Thanks again.

**Comment by mittonk** [comment]
Wonderful!
