### ISSUE TITLE
Please add last_time_updated to businessess returned

### ISSUE THREAD

**Issue by GregSaintJean** [Yelp/yelp-fusion#593]
## Overview
- **Client ID:** M9hoWvKGosX0XqzK4QOxMQ
- **Issue type:** Feature Request
- **Summary:** I would like a timestamp for when the last time information about a business was updated. For business closure information
- **Platform:** Desktop/Web

## Description
I was looking at the endpoints for businesses and the business search and noticed that all the responses don't have any information about when was the last time it was updated.

## More information
So if I wanted to find out which businesses were closed before the pandemic, I could take a look at the businesses that were closed before the month of February 2020. I don't see this information in the business search results or the detailed business information and was wondering if it could be added.

### Endpoint
(https://api.yelp.com/v3/businesses/search)
(https://api.yelp.com/v3/businesses/{id})

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?latitude=25.6882185&longitude=-80.3187254&radius=40000&limit=50
```

### Response
```
{
	"id": "opz-z4k-WK0KsyyR1Vwg5A",
	"alias":"whisk-gourmet-food-and-catering-miami-2",
	"name":"WHISK Gourmet Food & Catering",
	"image_url":"https://s3-media2.fl.yelpcdn.com/bphoto/F8qi-Pc6eze0_do6FY4Snw/o.jpg",
	"is_closed":false,
	"url":"https://www.yelp.com/biz/whisk-gourmet-food-and-catering-miami-2?adjust_creative=M9hoWvKGosX0XqzK4QOxMQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=M9hoWvKGosX0XqzK4QOxMQ",
	"review_count":1179,
	"categories": [
		{
			"alias":"newamerican",
			"title":"American (New)"
		}
	],
	"rating":4.5,
	"coordinates": {
		"latitude": 25.70289,
		"longitude": -80.28466
	},
	"transactions": [
		"delivery"
	],
	"price": "$$",
	"location":{
	    "address1":"7382 SW 56th Ave",
            "address2":"",
            "address3":"",
            "city":"Miami",
            "zip_code":"33143",
            "country":"US",
            "state":"FL",
            "display_address":[
               "7382 SW 56th Ave",
               "Miami, FL 33143"
            ]
	},
	"phone":"+17862688350",
    "display_phone":"(786) 268-8350",
    "distance":3768.7326218333387,
    "last_updated": "2020-8-22T3:55:30" (or "2020-8-22")
}
```

**Comment by GregSaintJean** [comment]
Hello?

**Comment by zxy919781142** [comment]
Hello. Could I ask whether you have solved the issue?

**Comment by GregSaintJean** [comment]
You are asking me @zxy919781142?

**Comment by zxy919781142** [comment]
Sorry. I just want to inquire whether the issue has been solved or whether you have any other ideas to deal with it @GregSaintJean 
.

**Comment by GregSaintJean** [comment]
O no. I haven't seen or heard back from anyone. It's a feature request.

**Comment by zxy919781142** [comment]
That's true. I also need such information.
