### ISSUE TITLE
Multiple GraphQL queries in single request timeout

### ISSUE THREAD

**Issue by jchristo12** [Yelp/yelp-fusion#597]
## Overview
- **Client ID:** gJMdCeKFAetORhOAN3u_jQ
- **Issue type:** question
- **Summary:** Multiple GraphQL queries in single request timeout
- **Platform:** Desktop/web

## Description
I have hundreds of coordinate pairs and for each one I would like to return the total number of businesses that match the query parameters. When attempting to submit the queries in a single request using the GraphQL endpoint, the request times out when there are > ~25 queries in the request.

## More information
Knowing that the GraphQL API is still in beta, is this timeout limit something that is planned? Or is it a side effect of using a beta product? If it is the former, that would be helpful to know so I can change course now.

This issue is similar to #414 

### Endpoint
https://api.yelp.com/v3/graphql

### Parameters or Sample Request
_Example using 3 queries:_
```
{
  id_2481175: search(categories: "bars", price: "1,2,3,4", radius: 16094, latitude: 38.609171999999994, longitude: -76.919776) {
    total
  }
  id_1239925: search(categories: "bars", price: "1,2,3,4", radius: 16094, latitude: 26.6126953, longitude: -81.63884509999998) {
    total
  }
  id_1271569: search(categories: "bars", price: "1,2,3,4", radius: 16094, latitude: 25.670375600000003, longitude: -80.4488718) {
    total
  }
}
```
The response that fails is essentially the same but with 10x queries.

### Response
_Successful response:_
```
{
'id_2481175': {'total': 25},
 'id_1239925': {'total': 12},
 'id_1271569': {'total': 54}
}
```
_Failed response:_
```
HTTPError: 504 Server Error: Gateway Time-out for url: https://api.yelp.com/v3/graphql
```

**Comment by gserapio** [comment]
I'm having this issue, too. Have you found a resolution? Is the problem related to caching?

**Comment by jchristo12** [comment]
> I'm having this issue, too. Have you found a resolution? Is the problem related to caching?

I just queried in batches of ~10 and looped thru. 🤷🏻‍♂️ I'm not sure about the caching.
