### ISSUE TITLE
Plans for native Swift client?

### ISSUE THREAD

**Issue by davecom** [Yelp/yelp-fusion#6]
In the past Yelp has provided official native client libraries for select platforms/languages. A roadmap about this would be helpful (before we go and roll our own unofficial libraries). Are there plans to offer an official Swift library for v3?

**Comment by guangyang** [comment]
Client library is an important area we are looking into next. We'll share our thoughts when we get a little bit deeper into it. Meanwhile, help us understand which languages do you like to see.

Thanks.

**Comment by mittonk** [comment]
We had V2 client libraries for Python, Ruby, Objective-C (usable in Swift), and Android-style Java.  All of those certainly sound like fine plans to me.

**Comment by tomelm** [comment]
@mittonk asking for all languages is easy, we need to prioritize which we focus on first :p

**Comment by davecom** [comment]
It might be helpful to evaluate the popularity of the existing official libraries that you have produced. Perhaps by using GitHub traffic graphs since you appear to have all of the V2 libraries in one repository? I would also evaluate the popularity of third-party Yelp libraries by platform.

**Comment by mittonk** [comment]
https://github.com/Yelp/yelp-ios (usable in Swift) has been updated for Fusion!

Now, I think we just need an example of calling it from Swift ...

**Comment by lefeverela** [comment]
How about Android ? I used to use the following git: https://github.com/Yelp/yelp-android
But this is only using v2.0.
Is the fusion API available the same way somewhere?

Thanks

**Comment by ranga543** [comment]
Please see here for accessing yelp fusion API using [yelp-fusion-android](https://github.com/ranga543/yelp-fusion-android)
