### ISSUE TITLE
location= does not appear to work in conjuction with radius

### ISSUE THREAD

**Issue by thedanotto** [Yelp/yelp-fusion#60]
This api call returns a total count of 3 businesses (correct)...
https://api.yelp.com/v3/businesses/search?term=food&latitude=36.151272&longitude=-86.794099&radius=50&limit=50&price=1,2,3,4&open_at=1474581601

This api call returns a total count of 682 businesses (incorrect)...
https://api.yelp.com/v3/businesses/search?term=food&location=1711+Division+St+Nashville+TN+37203&radius=50&limit=50&price=1,2,3,4&open_at=1474581601

The only difference is using location vs. lat lng

**Comment by mittonk** [comment]
Hm, this sounds as-expected to me.

"total" is documented as:
> The total number of business Yelp finds based on the search criteria. Sometimes, the value may exceed 1000. In such case, you still can only get up to 1000 businesses.

That's the number Yelp found in the database, not the number it returned.  Does that explain the answer?

If not: Please provide the response bodies you get (perhaps as a gist), so I can verify you're seeing the same things I am.

**Comment by thedanotto** [comment]
I wasn't 100% clear, I was referring to the body as well. When I search by lat lng, other filters appear to be applied correctly, in my case, a radius of 50 meters. However, with a location based search, it doesn't appear that the results are filtered by the radius parameter.

Lat Lng Search Results
https://gist.github.com/thedanotto/a383eb75d5d12a3e82cc4082e5a084dd

Location Search Results
https://gist.github.com/thedanotto/7430b52e34d27546339ea64a482a1f1e

**Comment by mittonk** [comment]
Wonderful, that much clearer.

Well, that's certainly somewhere between confusing & wrong.  I'll dig in a little.

**Comment by mittonk** [comment]
Yup, doesn't look like we use `radius` when parsing `location`.

Seeing whether we should document that oddness, or change it.

**Comment by mittonk** [comment]
Same issue as #38 .

**Comment by mittonk** [comment]
OK, I think we should honor the combination of `location` and `radius`.  Heading that direction.

For oddly-shaped locations this might cause some confusing results --- like getting only water when using a small radius at the center of a C-shaped city.

**Comment by mittonk** [comment]
@thedanotto , @tcn33 : I've re-jiggered the location parsing to handle combining free-text `location` and a `radius`.

Mind having a look, see if that better covers your use cases?

**Comment by tcn33** [comment]
@mittonk spot on, thank you :)

**Comment by udayankoliya** [comment]
@mittonk : i have passed  `latitude` ,`longitude` and  `radius` in my yelp api call but it returns more than that radius result how to solve that
i attached my api call screenshot  link
https://nimb.ws/VDXHxn
