### ISSUE TITLE
How do I find any restaurant sub branch in canada.

### ISSUE THREAD

**Issue by swamy9082** [Yelp/yelp-fusion#613]
How do I find any restaurant sub branch in Canada.

For example: Dominos. 
I wanted to know all dominos branches that are available in Canada. 

Any help is appreciated.

**Comment by lbchanjr** [comment]
Based on your example, you may use this endpoint:
https://api.yelp.com/v3/businesses/search?term=dominos&location=canada

This will provide you with 20 (default limit) Dominos restaurants within Canada.

Additionally, you may add the "limit" and "sort_by" parameters to the endpoint to increase the number of returned results (max. limit of 50) and sort your result by the following criteria: distance, best_match, rating, review_count.

Hope this helps.
