### ISSUE TITLE
Getting Businesses from "Collections"

### ISSUE THREAD

**Issue by TriceB** [Yelp/yelp-fusion#617]
Is it possible to use the Yelp Fusion API to get business information from a Yelp Collection? I currently have collections with specific types of businesses and am trying to use Python to pull those rather than searching through all businesses.

**Comment by ziggymacarthur** [comment]
Has anyone looked into this?? Im wanting to clean up my yelp bookmarks and dont want to delete one by one each restaurant thats either not near me or closed. Being able to query from a specific collection or my bookmarks would be helpful.

**Comment by axsuul** [comment]
Also looking to access Yelp collections via API!
