### ISSUE TITLE
Extend query-able filters in attributes parameter

### ISSUE THREAD

**Issue by wardnath** [Yelp/yelp-fusion#62]
From the docs, the only queryable attributes are `hot_and_new` and `pokeshop`

<img width="720" alt="screen shot 2016-09-24 at 10 48 26 am" src="https://cloud.githubusercontent.com/assets/4514195/18809568/9939f0e2-8244-11e6-9bca-efd3b9587ecc.png">

Is there a way to filter by more information accessible by yelp web search? For example: "liked-by-vegetarians" or "dogs-allowed", such as in the image below?

<img width="483" alt="screen shot 2016-09-24 at 10 56 33 am" src="https://cloud.githubusercontent.com/assets/4514195/18809597/9bd0427e-8245-11e6-9f98-cc9becd7f7c4.png">

Some of these values can be queried for, such as "open at" already because they have their own parameter, but not all of the terms can be searched for to my knowledge.

**Comment by mittonk** [comment]
@wardnath : You're correct, we've only got a few attribute filters set up for Yelp Fusion so far.

@guangyang , @tomelm : More questions around specific search filters... and a stale, typo'd "pokeshop" doc.

**Comment by kf6kjg** [comment]
Any status update on attribute filters?

**Comment by tomelm** [comment]
@kf6kjg still no updates for this.

**Comment by clairefro** [comment]
Could "Black Owned" also become a searchable attribute?
