### ISSUE TITLE
I wanted to create/update yelp business listing using API

### ISSUE THREAD

**Issue by Shary81** [Yelp/yelp-fusion#626]
## Overview
- **Client ID:** IwiC7JegbpAqqxFfzwaRDA
- **Issue type:** feature request, question
- **Summary:** I wanted to create/update yelp business listing using API
- **Platform:** Desktop/web

## Description
i wanted to use "https://partner-api.yelp.com/v1/ingest/create"  this api, and your sample CURL call is not using any API key inside, i wanted to know about the username and password i need to pass inside the CURL request

below is your CURL sample code from your documentation link https://docs.developer.yelp.com/reference#business-update

curl \ -X POST \ -H "Content-type: application/json" \ --user 'username:password' \ -d '{"businesses": [{"matching_criteria": { "yelp_business_id": "pzni3DBjMPxrBsbKbf2gbQ", "address1": "800 N Point St","city": "San Francisco","country": "US","name": "Gary Danko","phone": "+14157492060","postal_code": "94109","state": "CA"},"options": {"use_matching_criteria_for_update": "false","create_if_missing": "false"},"update": {"wifi": "no","hours": [{"day": "thursday", "open": "08:00", "close": "15:00"}]}}]}' \ https://partner-api.yelp.com/v1/ingest/create

## More information
Can you tell me which specific username and password need to be passed in the above curl call ? 

### Endpoint
Yelp Data Ingestion API to programmatically perform updates.

### Parameters or Sample Request

curl \
  -X POST \
  -H "Content-type: application/json" \
  --user 'username:password' \
  -d '{"businesses": [{"matching_criteria": { "yelp_business_id": "pzni3DBjMPxrBsbKbf2gbQ", "address1": "800 N Point St","city": "San Francisco","country": "US","name": "Gary Danko","phone": "+14157492060","postal_code": "94109","state": "CA"},"options": {"use_matching_criteria_for_update": "false","create_if_missing": "false"},"update": {"wifi": "no","hours": [{"day": "thursday", "open": "08:00", "close": "15:00"}]}}]}' \
  https://partner-api.yelp.com/v1/ingest/create
### Response
{
    "error": {
        "code": "401_UNAUTHORIZED",
        "description": "This server could not verify that you are authorized to access the document requested.  Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required."
    }
}

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by rockdog** [comment]
Hi @Shary81,

thanks for opening this issue.

The request you are trying to perform is part of our Partner API not Fusion hence you won't be able to perform such requests with your Fusion credentials.

Since this issue tracker is for issues regarding our Public API will close it.
