### ISSUE TITLE
Internal Server Errors Occur Seemingly WIthout Pattern on Fusion API

### ISSUE THREAD

**Issue by aidanreid98** [Yelp/yelp-fusion#628]
## Overview
- **Client ID:** tO6o-wNNr-Sjsx7lax8DKA
- **Issue type:** Bug/Question
- **Summary:** I am trying to find mexican restaurants across the 100 most populous U.S. cities. I start making requests to the API, but every so often I will get a 500 error. These errors don't come at consistent times or requests.
- **Platform:**  Sending requests to the API from a python script run on a Mac

## Description
Not much to say. I was having no problems at all with this code, but two days ago these random internal server errors started popping up. There doesn't appear to be any pattern to them that I can see? I have tried putting 5 second gaps between cities to see if it was a rate limiting issue.

### Endpoint
_(e.g. Fusion Search API)_
 'https://api.yelp.com/v3/businesses/search'

### Parameters or Sample Request
Here is my request code
API_HOST = 'https://api.yelp.com'
SEARCH_PATH = '/v3/businesses/search'
SEARCH_TERM = 'mexican'
offset is a number from 50 to 950, limit is 50
    response = requests.get(
        API_HOST+SEARCH_PATH,
        params={'categories': SEARCH_TERM, 'location': city, 'limit': LIMIT, 'offset': offset},
        headers={'Authorization': 'Bearer %s' % api_key},
    )
### Response

```
<Response [500]>
{'Connection': 'keep-alive', 'Content-Length': '112', 'content-type': 'application/json', 'server': 'envoy', 'x-routing-service': 'routing-main--useast1-b579557df-z48bc; site=public_api_v3', 'x-cloudmap': 'routing_useast1', 'x-proxied': '10-65-86-244-useast1aprod', 'x-extlb': '10-65-86-244-useast1aprod', 'Accept-Ranges': 'bytes', 'Date': 'Sun, 06 Jun 2021 21:49:32 GMT', 'Via': '1.1 varnish', 'X-Served-By': 'cache-pwk4971-PWK', 'X-Cache': 'MISS', 'X-Cache-Hits': '0'}
{"error": {"code": "INTERNAL_ERROR", "description": "Something went wrong internally, please try again later."}}
```

**Comment by gserapio** [comment]
I am experiencing the same problem on GraphQL! The internal server error pops up randomly, never at the same place in my code. I also tried putting in 1-second gaps, this didn't help.
