### ISSUE TITLE
Autocomplete validation error... "platform_insertion"?

### ISSUE THREAD

**Issue by benjuhn** [Yelp/yelp-fusion#629]
## Overview
- **Client ID:** E18o67Qr008EtEhXfVBQZQ
- **Issue type:** troubleshooting question
- **Summary:** Autocomplete returning 400 bad request... validation error... "platform_insertion"
- **Platform:** web & iOS

## Description
The autocomplete endpoint of the Yelp Fusion API returned expected results until a few days ago.

I know that my API key is valid because the business and search endpoints are still returning expected results.

According to the documentation, the required parameters for the autocomplete endpoint are: text, latitude, and longitude.

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
Fusion Autocomplete API

### Parameters or Sample Request
```
https://api.yelp.com/v3/autocomplete?longitude=-118.1624984548154&latitude=34.09355202325028&text=Pi
```

### Response
```
{
    "error": {
        "code": "VALIDATION_ERROR",
        "description": "'platform_insertion' is not one of ['empty', 'completion', 'fuzzy', 'completion_query_lm', 'fuzzy_query_lm', 'category', 'recent_location', 'business_category']",
        "field": "suggestions"
    }
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by bizmate** [comment]
Are you url encoding the request correctly?
Show your code

**Comment by benjuhn** [comment]
> Are you url encoding the request correctly?
> Show your code

I have included the code for a sample request in the original post. It looks like I didn't previously detail that it is a GET request. The only header I include in my request is my bearer token API key.

As I said in the original post, the GET requests to the search and business endpoints are returning results properly. I have formatted everything according to Yelp Fusion documentation. As this repository is specific to Yelp Fusion, I didn't previously include links to the documentation.

https://www.yelp.com/developers/documentation/v3/business_search
https://www.yelp.com/developers/documentation/v3/business
https://www.yelp.com/developers/documentation/v3/autocomplete

Again, the only endpoint returning any error is the autocomplete endpoint.

Also, again, the autocomplete endpoint returned results properly until a few days ago.

It would be really helpful if someone could explain the error response.

**Comment by benjuhn** [comment]
For comparison purposes:

Tested again earlier today, and again just now... the first request returns expected results, while the second returns the error mentioned in the original post.

https://api.yelp.com/v3/autocomplete?longitude=-118.1624984548154&latitude=34.09355202325028&text=de
https://api.yelp.com/v3/autocomplete?longitude=-118.1624984548154&latitude=34.09355202325028&text=pi

**Comment by rockdog** [comment]
Hi @benjuhn, thanks for opening this issue. 

There was indeed a problem with that endpoint such that under some circumstances it would return a validation error even though the request was perfectly valid. This issue should now be fixed. 

I am going to close this issue but feel free to re-open if you keep seeing this error.
