### ISSUE TITLE
More than 3 business reviews in yelp

### ISSUE THREAD

**Issue by prasannapalle** [Yelp/yelp-fusion#636]
## Overview
- **Client ID:** _APXemOvPS5vyVkXH4EBpuQ
- **Issue type:** _ Fetching reviews from API request.
- **Summary:** _ I am hitting the API request with a business ID but everytime it is fetching only 3 reviews
- **Platform:** _ Web

## Description
How to get more than 3 reviews

## More information
I am getting only 3 business reviews per one yelp request. How can I get more number of reviews using yelp business reviews API. Could you please help me

### Endpoint
https://api.yelp.com/v3/businesses/OyfQqsutE3VNEHHlsRNRaQ/reviews

**Comment by oporter1** [comment]
per their documentation they only allow 3 reviews to be returned --> https://www.yelp.com/developers/documentation/v3
