### ISSUE TITLE
Vaccination Status of Restaurants

### ISSUE THREAD

**Issue by victorli112** [Yelp/yelp-fusion#638]
Is it possible to query restaurants using the new "Feature" Yelp added that filters restaurants on if they require vaccinations or if all the staff is vaccinated? I tried putting it in the "Term" attribute 
`'term': 'vaccination required` and `'term': 'proof of vaccination required` 
both return restaurants that don't require vaccinations. Is this supported in the API yet?

**Comment by AugustineLabs** [comment]
Tried this as well. This comes from the `attributes` param, which oddly is the only data on `business` that Yelp requires the developer apply for their enterprise program.

To search by or access this data they first have to be:
1) Approved by Yelp to access on a case-by-case basis
2) A business (as opposed to an individual)

Strange move by Yelp in the interest of public health in my opinion.
