### ISSUE TITLE
API request gives status 400

### ISSUE THREAD

**Issue by imckain** [Yelp/yelp-fusion#643]
## Overview
- **Client ID:** xuGcNUZc74zQxuoETNlq4g
- **Issue type:** API request 400
- **Summary:** API request started failing with a 400 out of nowhere. It's being used in a React Native app.
- **Platform:** iOS

## Description
I uploaded a build of the app to Apple Connect through Transporter and everything was working fine. My app got kicked back for an `info.Plist` issue. I added the necessary params in `app.json`, created a new build, and sent it to AC with Transporter. My app in Test Flight was working as expected, but after I uploaded the new version with the Plist update my API refused to send results.

I tested it with the old build version on Test Flight, with my local dev file with expo, by returning app.json to its original build state, and even recloned from my repo. -- So basically, there was literally nothing changed and it stopped working.

I added console.logs to my API call hook and I am receiving the following error:
```
Request failed with status code 400
at node_modules/axios/lib/core/createError.js:16:14 in createError
at node_modules/axios/lib/core/settle.js:17:22 in settle
at node_modules/axios/lib/adapters/xhr.js:54:12 in onloadend
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:605:6 in setReadyState
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:395:6 in __didCompleteResponse
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
```

### Endpoint
Fusion Search API

## Extra information
I did a binary build and it was working fine so I have no idea what's going on. It's almost like the API shut me out because I have no problem accessing it with Postman.

And because someone will ask, here's my API call:

API Call
```
import axios from 'axios';
import { REACT_APP_YELP_API_KEY } from '@env';

export default axios.create({
  baseURL: 'https://api.yelp.com/v3/businesses',
  headers: {
    Authorization: `Bearer ${REACT_APP_YELP_API_KEY}`
  }
}); 
```
The hook in question:
```
import React, { useCallback, useEffect, useState } from 'react';
import yelp from '../api/yelp';
import * as Location from 'expo-location';

export default () => {
  const [location, setLocation] = useState(null);
  const [locationErrorMessage, setLocationErrorMessage] = useState(null);
  const [results, setResults] = useState([]);
  const [apiErrorMessage, setApiErrorMessage] = useState('');

  const getLocation = async () => {
    const { status } = await Location.requestForegroundPermissionsAsync();
    console.log(status);
    if (status !== 'granted') {
      setLocationErrorMessage('Permission to access location was denied');
      return;
    }
    const location = await Location.getCurrentPositionAsync({});
    console.log('Location Checked');
    setLocation(location.coords);
  };
  
  const searchAPI = useCallback(async (defaultTerm) => {
    try {
      console.log('searchAPI() ran');
      console.log('====================================');
      console.log(location);
      console.log('====================================');
      const response = await yelp.get('/search', {
        params: {
          limit: 50,
          term: defaultTerm,
          latitude: location.latitude,
          longitude: location.longitude,
          radius: 4000,
        }
      });
      console.log('response: ' + response.data.businesses);
      setResults(response.data.businesses);
    } catch (error) {
      console.log('====================================');
      console.log(error);
      console.log('====================================');
      setApiErrorMessage('Something went wrong 😢 \n Check back later')
    }
  }, [location]);

  useEffect(() => {
    getLocation();
  }, []);

  useEffect(() => {
    if (location) {
      searchAPI('');
    }
  }, [location])

  console.log(results);

  return [searchAPI, results, apiErrorMessage, location, locationErrorMessage];
};
```

**Comment by imckain** [comment]
I can't explain how or why, but after a break for a couple hours, I started up my app and my API call worked again. It's like the API was blocking me somehow? I'm not sure, but glad it's back. 

I did not change a single line of code from taking a break to now- The API was sending a 400 for reasons that are beyond me.

**Comment by rockdog** [comment]
Hi @imckain,

thanks for opening this issue.

It could have been that we had some issues during that time impacting our API's. Glad it started working again.
