### ISSUE TITLE
I am getting error while trying to perform OAuth for Respond to review API

### ISSUE THREAD

**Issue by akash-cis** [Yelp/yelp-fusion#648]
## Overview
I want to authorize the business by performing OAuth for using the Respond to review API as shown in these docs. [https://docs.developer.yelp.com/docs/respond-to-reviews-api](https://docs.developer.yelp.com/docs/respond-to-reviews-api).
while following the first step I am redirecting to the **https://biz.yelp.com/login/authorize?client_id=client_id&redirect_uri=redirect.uri&response_type=code&scope=r2r&state=some_unique_string**  getting an error that **"An error has occurred. Please contact the administrator."**

![image](https://user-images.githubusercontent.com/93192708/150920577-f9442b8e-740a-42ce-9fea-2da891b84111.png)

am I missing something or do I need to fill out some form or premium access to be able to access this feature?

**Comment by LianshanWang-hub** [comment]
I meet same issue. Want to understand that is there is any following up for this?
