### ISSUE TITLE
How to make contract with partner to enable Private Review API access

### ISSUE THREAD

**Issue by LianshanWang-hub** [Yelp/yelp-fusion#649]
## Overview
- **Client ID:** _faNf9fphzxBioC06JB1lXw_
- **Issue type:** _question_
- **Summary:** _Usage of [Private Reviews API](https://docs.developer.yelp.com/docs/private-reviews-api)_
- **Platform:** _Desktop/web_

## Description
_This developer document ([Private Reviews API](https://docs.developer.yelp.com/docs/private-reviews-api)) mentioned that the "Access to this API is reserved for contracted Yelp partners".
Could you share us more details about how to make contract with partner to get this access?
Is that the same thing with OAuth that mentioned in Respond to Review API?_

### Endpoint
_Private Reviews API_

```
GET https://api.yelp.com/v3/private/businesses/{business_id}/reviews
```

**Comment by rockdog** [comment]
Hi @LianshanWang-hub,

thanks for opening this issue. 

The Private Reviews API is not part of the standard feature set of Yelp's Public API. You can find more details on https://knowledge.yelp.com/ as well as how to get in contact.
