### ISSUE TITLE
Got no answer

### ISSUE THREAD

**Issue by snipymc** [Yelp/yelp-fusion#65]
Hello,

by using Yelp API v3 I have a problem getting some information by request.

The first step, get an access_token is no problem. After that, searching by phone, I get no response...do you have some ideas, what is wrong?

> <?php
> $API_HOST = 'api.yelp.com';
> $PHONE_PATH = '/v3/businesses/search/phone';
> $BUSINESS_PATH = '/v3/businesses';
> $ACCESS_KEY = NULL;
> $result = NULL;
> function init() {
>     global $result; 
>     $url    = "https://api.yelp.com/oauth2/token";
>     $post = array(
>         "grant_type" => "client_credentials", 
>         "client_id" => "client-id", 
>         "client_secret" => "client-secret"
>     );
>     $postText = http_build_query($post);
>     $ch = curl_init();
>     curl_setopt($ch, CURLOPT_URL, $url);
>     curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
>     curl_setopt($ch, CURLOPT_POST, true);
>     curl_setopt($ch, CURLOPT_POSTFIELDS, $postText); 
>     curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
>     curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
>     $result = curl_exec($ch);
>     $secret = json_decode($result);
>     $_GLOBALS['access_key'] = $secret->access_token;
>     echo $_GLOBALS['access_key'];
>     phone('+495610815',$_GLOBALS['access_key']);
> }
> function phone($number,$key) {  
>     $br = curl_init('https://api.yelp.com/v3/businesses/search/phone?phone='.$number);
>     curl_setopt($br, CURLOPT_HTTPHEADER, array('Authorization: Bearer '.$key));
>     curl_setopt($br, CURLOPT_RETURNTRANSFER, true);
>     $data = curl_exec($br);
>     curl_close($br);
> $fetch = json_decode($data);
> echo $fetch->total;
> }
> init();
> ?>

**Comment by mittonk** [comment]
@snipymc : Let's check some of the intermediate steps.

1. What are the first ~5 letters of `$secret`?  This won't be enough to comprise security, but I want to make sure you're not getting "" or "ERROR..." or similar.
2. What HTTP status code do you get from your OAuth2 POST?
3. What HTTP status code do you get from your main phonesearch GET?
4. What response body do you get from your main phonesearch GET?

**Comment by mittonk** [comment]
No response, closing.
