### ISSUE TITLE
price property contains other currencies besides "$"

### ISSUE THREAD

**Issue by apibugsreporting** [Yelp/yelp-fusion#651]
## Overview
- **Client ID:** ULHW7ynqdXE8Z9Fnr4irFw
- **Issue type:** bug
- **Summary:** The [Businesses Search endpoint](https://www.yelp.com/developers/documentation/v3/business_search) returns different currencies in the `businesses[x].price` property depending on the location. For example, it may return euros (`"€"`) or pounds (`"£££"`)
- **Platform:** web API

## Description
According to the [documentation of this endpoint](https://www.yelp.com/developers/documentation/v3/business_search), the "Value is one of $, $$, $$$ and $$$$.". This specification is violated. If this is intended behavior, it should at least be documented in the API documentation.

### Endpoint
GET /businesses/search

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?price=2%2C1&latitude=40.529156&term=food&location=Milan%2C%20Italy
https://api.yelp.com/v3/businesses/search?offset=116&limit=10&location=Tokyo&sort_by=distance&locale=tr_TR&longitude=-108.85355
```

### Response
```json
[...]
        "rating": 4.5,
            "coordinates": {
                "latitude": 35.6827868949174,
                "longitude": 139.76417304854
            },
            "transactions": [],
            "price": "￥",
            "location": {
                "address1": "丸の内1-5-1",
                "address2": "新丸の内ビルディング B1F",
                "address3": "",
                "city": "千代田区",
[...]
```

## Extra information
Several test reports revealing these issues are available at the following URLs:
- http://apitesting.ddns.net/fse2022/restest/target/allure-reports/yelp_Businesses__r_rt_custom/#behaviors/b1a8273437954620fa374b796ffaacdd/f07646839b13da8c/
- http://apitesting.ddns.net/fse2022/restest/target/allure-reports/yelp_Businesses__r_rt_custom/#behaviors/b1a8273437954620fa374b796ffaacdd/d051652eeaf65965/

**Comment by rockdog** [comment]
Thanks for submitting this. The documentation for the `price` attribute has been updated.

https://docs.developer.yelp.com/reference/v3_business_search
