### ISSUE TITLE
how can i get email id of user to send auto response on his/her reviews using yelp API

### ISSUE THREAD

**Issue by Muneebmalik72** [Yelp/yelp-fusion#659]
Hello,
we are developing auto responder tools to send auto reply on reviews/comments if some user posted on some business. 
to send this auto reply we need email id of user so that we can send auto response on base of pre-defined keywords in admin panel by client. 

looking forward kind response

**Comment by rockdog** [comment]
Hi @Muneebmalik72, this sort of information is not available via our API.
