### ISSUE TITLE
Respond to Review

### ISSUE THREAD

**Issue by Muneebmalik72** [Yelp/yelp-fusion#661]
Hello,
Is it possible for the Fusion API to return response to my business  after getting review using Fusion Api.
here is the APi but i could not use this can anyone help 
https://partner-api.yelp.com/reviews/v1/review_id

**Comment by rockdog** [comment]
Hi @Muneebmalik72, our Partner API's are not part of our Public API offerings (see https://docs.developer.yelp.com/docs/yelp-partner-apis) and as such you won't have access to these endpoints by default.

However if you are interested in using them please reach out to our Partner Support team.
