### ISSUE TITLE
API for getting questions asked about a business

### ISSUE THREAD

**Issue by HolySahar** [Yelp/yelp-fusion#665]
## Overview
- **Client ID:** N/A
- **Issue type:** feature request/question
- **Summary:** an API to get business questions
- **Platform:** N/A

## Description
I have looked at the existing Yelp Fusion APIs. They are great but I didn't see any of them can be used to get a list of questions that people ask about a business. Do you already have such information provided through an API? If not, is there another API that I can use?

## More information
Sample data I'm interested in: https://www.yelp.com/questions/Xd_l7jtUAZZAAvK8-mI2Jw

### Endpoint
N/A

### Parameters or Sample Request
N/A

### Response
N/A

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by rockdog** [comment]
Hi @HolySahar, retrieving business questions is currently not supported.

However we are tracking this and similar feature requests internally. I recommend checking https://docs.developer.yelp.com/changelog every once in a while for announcements of new feature releases.
