### ISSUE TITLE
Yelp API - Get all the reviews by user

### ISSUE THREAD

**Issue by lugrace** [Yelp/yelp-fusion#666]
## Description
Was wondering if there is an api/endpoint to get all the reviews by user? I don't want to search by businese or anything, just the user. I want to make something that maps all of the places I've reviewd

**Comment by rockdog** [comment]
Hi @lugrace, retrieving reviews by user is not currently supported. 

However we are tracking this and similar feature requests internally. I recommend checking https://docs.developer.yelp.com/changelog every once in a while for announcements of new feature releases.
