### ISSUE TITLE
Worldwide search

### ISSUE THREAD

**Issue by elenajp** [Yelp/yelp-fusion#667]
## Overview
- **Issue type:**  feature request, question
- **Summary:** Is it possible to search for a term e.g scuba worldwide?

## Description
I would love to search for things worldwide instead of having to enter each city separately.
## More information
 Is this possible? I could not find it, so I am guessing not. Unless I missed it. 
 If it is not possible, would it be implemented in the future? It would be nice!

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?term=scuba&location=worldwide
```

Thanks!

**Comment by rockdog** [comment]
Hi @elenajp,

thanks for this feature request. At this point searching `worldwide` isn't something we support.
