### ISSUE TITLE
Is there a way to get a description of a business from Fusion API?

### ISSUE THREAD

**Issue by NickBrinsmade** [Yelp/yelp-fusion#668]
I didn't see anything in the documentation, but I was curious. I'm trying to choose between the TripAdvisor API and this. TripAdvisor contains a field in the business responses that gives a brief (or somewhat extended) description of a given location. Does the Fusion API have something similar? Is it maybe done through a different endpoint?

As an aside, I THINK I've seen sites powered by the Fusion API that have business descriptions, but again I'm not seeing it in the documentation.

Any help is much appreciated! Thanks :)

**Comment by rockdog** [comment]
Hi @NickBrinsmade,
the Fusion API is capable of returning that information. Please check out https://fusion.yelp.com/enterprise/ for more details.
