### ISSUE TITLE
API business categories list

### ISSUE THREAD

**Issue by BusbyActual** [Yelp/yelp-fusion#67]
There doesn't seem to be a comprehensive list of these categories for the v3.0 API. I found documentation and JSON for Yelp's v2.0 API for a comprehensive [list](https://www.yelp.com/developers/documentation/v2/all_category_list).  Is there some documentation or json you can provide me with? 

Warmly,

Busby

**Comment by tomelm** [comment]
The list for v2 and v3 are the same. We'll work on restructuring those docs so it's clearer

**Comment by BusbyActual** [comment]
Thank you tomelm.

**Comment by mittonk** [comment]
@BusbyActual : Fixed, you can now find the category list in the V3 docs as well:
* https://www.yelp.com/developers/documentation/v3/all_category_list
* https://www.yelp.com/developers/documentation/v3/all_category_list/categories.json
