### ISSUE TITLE
REQUEST_TIMED_OUT in Yelp api

### ISSUE THREAD

**Issue by RohanMondal0505** [Yelp/yelp-fusion#671]
## Overview
- **Client ID:** 7e_wJt5K0SCzekwpEnM9gw
- **Issue type:** Tying to fetch this data
- **Platform:** Desktop/web, Android,

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/search?term=restaurant/search?term=restaurants&location=SanDiego

### Response

{
    "error": {
        "code": "REQUEST_TIMED_OUT",
        "description": "The request timed out, please try again later. If this continues, please create an issue on GitHub with the request you're making: https://github.com/Yelp/yelp-fusion/issues"
    }
}

**Comment by bizmate** [comment]
you have two query strings in your URL, this is definitely a problem on the YELP side as it might cause denial of service but if you want it to work fix the request

**Comment by RohanMondal0505** [comment]
Thanks

**Comment by RohanMondal0505** [comment]
Thanks
