### ISSUE TITLE
Business location postal_code returning null

### ISSUE THREAD

**Issue by dylan-hstk** [Yelp/yelp-fusion#673]
## Overview
- **Client ID:** 8ztMHXm0LaSj1TTxES6yIg
- **Issue type:** bug
- **Summary:** Business location postal_code returning null
- **Platform:** All

## Description
Hello, I started refactoring a yelp integration today from using the regular API to using the GraphQL API because we wanted to get images and hours directly from the search instead of having to query every business to retrieve that information. Everything was going great until I tried to get the postal_code field and every business seems to be returning null.

## More information
You can reproduce this from the GraphiQL in the docs page:

https://www.yelp.com/developers/graphql/objects/location

![image](https://user-images.githubusercontent.com/110476179/189974053-0a63b1e7-9153-47f2-8a60-65dd216a5390.png)

I've tried other locations and they seem to all be returning null for postal_code. Is this something related to my API KEY?

**Comment by rockdog** [comment]
Hi @dylan-hstk, thanks for reporting this issue. 

On the Rest-API this field is returned as `zip_code`. However in the GraphQL API this field is named `postal_code`. 

I was able to verify its always returning `null`. I'll be checking the code later but this looks like a bug.

**Comment by rockdog** [comment]
@dylan-hstk This issue has been resolved. It did also affect `formatted_address`. 

Thanks again for reporting this.
