### ISSUE TITLE
Getting Menu / dish details from API

### ISSUE THREAD

**Issue by ahmednrana** [Yelp/yelp-fusion#675]
## Overview
- **Client ID:** _hWKvIkdz7XazsJ_UozsvFg_
- **Issue type:** _question_
- **Summary:** _Is it possible to get Menu Items and dish details from Yelp API (fusion or ingestion or any other)_
- **Platform:** _API_

## Description
I am trying to fetch Menu Items and dish details from Yelp API (fusion or ingestion or any other) for a business. Is it supported? If yes, can anyone guide me to its documentation

**Comment by rockdog** [comment]
Hi @ahmednrana, retrieving menus/menu items is currently not supported.

However we are tracking this and similar feature requests internally. I recommend checking https://docs.developer.yelp.com/changelog every once in a while for announcements of new feature releases.
