### ISSUE TITLE
Should we cache the access-token or should we keep fetching for the access-token?

### ISSUE THREAD

**Issue by Sticksword** [Yelp/yelp-fusion#68]
So I'm curious about the workflow of the oauth endpoint for getting the Yelp API access_token. Does it automatically generate a new token and return it once the old one expires? Does it return the same generated token? I don't want to make unnecessary calls to it and generate a bunch of tokens that I won't use.

**Comment by bizmate** [comment]
Cache it until it expires, dont need to call the auth resource several times. The token returns a ttl . See expires_in at https://www.yelp.com/developers/documentation/v3/get_started

**Comment by Sticksword** [comment]
What is `ttl`? So if I call the oauth endpoint multiple times, it will still return the same token unless it has expired, upon which it will return a new token. Is this right though?

**Comment by bizmate** [comment]
https://en.wikipedia.org/wiki/Time_to_live. It does return the same one indeed. Have you tried?

**Comment by Sticksword** [comment]
I have not because I did not want to create new ones unnecessarily. It's why I opened an issue. Thank you for the help and info!
