### ISSUE TITLE
Bussiness search with ConnectionError

### ISSUE THREAD

**Issue by yuanmr420** [Yelp/yelp-fusion#680]
## Overview
- **Client ID:** vi6PJLyGSHk2wnIx5ZWtLw
- **Issue type:** ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
- **Summary:** I tried to get some info from business search endpoint but sometimes it will return a ConnectionError.
- **Platform:** Desktop/Python

## Description
_(More detailed information explaining the problem, the expected results, the question, etc.)_
I tried to retrieve 10 restaurants info from business search url. Sometimes I could get a json str while others I just got a connectionerror. Besides, I didn't hit daily API limit. Also, at the same time, I used my own api key to run the yelp sample code provided on github

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
API_KEY= 'xxx'
API_HOST = 'https://api.yelp.com'
SEARCH_PATH = '/v3/businesses/search'

### Parameters or Sample Request
_(SAMPLE PLEASE REMOVE)_
```
url_params={'location':'NYC','limit':10,'term':'dinner'}
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
![Snipaste_2022-12-01_17-10-41](https://user-images.githubusercontent.com/102813028/205012637-e6dda518-629e-41a0-abaa-2e73a53c13ae.jpg)

```

**Comment by yuanmr420** [comment]
[](url)
![Snipaste_2022-12-01_17-10-41](https://user-images.githubusercontent.com/102813028/205012805-e2e22a10-05c1-41d5-9f52-5a603a3a4dee.jpg)

**Comment by rockdog** [comment]
Hi @yuanmr420,

quick heads up that we refreshed your API Key. Please do not post your credentials publicly. You can find more infos here: https://docs.developer.yelp.com/docs/fusion-authentication.

Maybe our updated documentation at https://docs.developer.yelp.com/reference/v3_business_search is helpful. It also offers an interactive console to try out different endpoints.

**Comment by yuanmr420** [comment]
> Hi @yuanmr420,
> 
> quick heads up that we refreshed your API Key. Please do not post your credentials publicly. You can find more infos here: https://docs.developer.yelp.com/docs/fusion-authentication.
> 
> Maybe our updated documentation at https://docs.developer.yelp.com/reference/v3_business_search is helpful. It also offers an interactive console to try out different endpoints.

Thanks for your reminder. I will check that. Thanks again!
