### ISSUE TITLE
Error trying to create app

### ISSUE THREAD

**Issue by beehilly** [Yelp/yelp-fusion#683]
## Description
I keep getting this error: "We’re sorry. This page isn’t working right now. Please wait a few minutes and try again." when trying to create an app to get the API key

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
https://www.yelp.com/developers/v3/manage_app

`

**Comment by ian-sieg** [comment]
I have also had this issue the entire day
![image](https://user-images.githubusercontent.com/98928887/211071357-9036eab4-6ebf-4fc4-b6c3-b0904d325a12.png)

**Comment by oimartin** [comment]
Had the same issue yesterday and today. I was trying on a university wifi on Chrome, Firefox, Safari and Edge with nothing working. I even tried on my phone with my wireless data, but had the same result: We're sorry. This page isn't working right now. Please wait a few minutes and try again. :/

**Comment by beehilly** [comment]
Thanks for confirmingOn Jan 6, 2023, at 5:05 PM, Olivia ***@***.***> wrote:﻿
Had the same issue yesterday and today. I was trying on a university wifi on Chrome, Firefox, Safari and Edge with nothing working. I even tried on my phone with my wireless data, but had the same result: We're sorry. This page isn't working right now. Please wait a few minutes and try again. :/

**Comment by beehilly** [comment]
Thanks for confirmingOn Jan 6, 2023, at 1:01 PM, Ian Sieg ***@***.***> wrote:﻿
I have also had this issue the entire day

**Comment by beehilly** [comment]
Seems like this issue persists today as well. :-(

**Comment by rockdog** [comment]
@beehilly Thanks for reporting this and sorry for the inconvenience. We are currently looking into this issue. We will post an update once this issue is resolved.

**Comment by rockdog** [comment]
@beehilly We've identified the problem and rolled out a fix. Feel free to re-open this issue.

**Comment by beehilly** [comment]
Thank you!

**Comment by ian-sieg** [comment]
Thanks!

**Comment by oimartin** [comment]
Thank you!
