### ISSUE TITLE
Is it possible retrieve the 'Inside' Photos category for business? 

### ISSUE THREAD

**Issue by mansidak** [Yelp/yelp-fusion#684]
So when we retrieve businesses in a search and get their ID we can get their pictures. I want to know if it's possible to retrieve just the 'Inside' section of the photos via the API? I'm talking about the following:

https://www.yelp.com/biz_photos/provision-coffee-bar-phoenix-6?tab=interior

**Comment by smimar** [comment]
Any update?

**Comment by mansidak** [comment]
@smimar I stopped looking a while ago. Just picked the project back up and still haven't found an answer. Hbu?

**Comment by smimar** [comment]
@mansidak unfortunately I couldn't find any solution to this.

**Comment by rockdog** [comment]
Hi @mansidak, 

we currently don't offer retrieving business photos on a dedicated endpoint. However as part of our Fusion Enterprise program (https://fusion.yelp.com/enterprise/) we allow getting more photo related information.
