### ISSUE TITLE
How can I get list of all parent categories?

### ISSUE THREAD

**Issue by smimar** [Yelp/yelp-fusion#685]
I am trying to find the api that I should use to retrieve list of all parent categories . 

I have looked into this 
https://docs.developer.yelp.com/reference/v3_all_categories

but the results of this api does not match with the list of categories on this page
https://docs.developer.yelp.com/docs/resources-categories  

So I am a bit confused.
I appreciate if someone can help me figure out how to pull the list of parent categories.

Thanks,
Emin

**Comment by rockdog** [comment]
Hi @smimar,

the reference at https://docs.developer.yelp.com/docs/resources-categories might not be 100% accurate when it comes to 2nd or 3rd level categories. However it does include all the top level categories such as `active`, `arts`, `auto`, `beautysvc`, and so on.

The source of truth is the actual endpoint as documented at https://docs.developer.yelp.com/reference/v3_all_categories.
