### ISSUE TITLE
How do you get more images for restaurents from https://api.yelp.com/v3/businesses/[id]. Curretnly it gets only 3 images

### ISSUE THREAD

**Issue by Yamirb** [Yelp/yelp-fusion#687]
## Overview
- **Client ID:** _y8rs4PED5sNo8qUqMBagQA_
- **Issue type:** _question_
- **Summary:** _I am looking to get more than 3 images from a restaurant's yelp page_
- **Platform:** _web/app_

## Description
_(More detailed information explaining the problem, the expected results, the question, etc.)_

## More information
_(Fill this section out if applicable (for things like bugs or questions))_

### Endpoint
_https://api.yelp.com/v3/businesses/[id]_

### Parameters or Sample Request
_(photos(list))_
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
_(SAMPLE PLEASE REMOVE)_
```
{
  "id": "garaje-san-francisco",
  "name": "Garaje",
  "categories": [
    {
      "alias": "gastropubs",
      "title": "Gastropubs"
    },
    ...
  ],
  "price": "$$",
  ...
}
```

## Extra information
_(Anything else you that you think might help us better resolve this)_

**Comment by rockdog** [comment]
Hi @Yamirb, retrieving more than 3 business photos is supported as part of our Fusion Enterprise program. For more details I recommend checking out https://fusion.yelp.com/enterprise/.
