### ISSUE TITLE
Searching for a business with a term and location set to "the junction" returns a server error

### ISSUE THREAD

**Issue by attaboy** [Yelp/yelp-fusion#69]
I'm making an API call to `https://api.yelp.com/v3/businesses/search`. If I pass `location` as `the junction`, along with any value for `term`, I get back a 500 response with an HTML error page, instead of a JSON response as expected.

Example: `https://api.yelp.com/v3/businesses/search?location=the%20junction&term=burritos`

**Comment by mittonk** [comment]
Trying this on the WWW search view:
* https://www.yelp.com/search?find_desc=burritos&find_loc=the+junction&ns=1

```
Sorry, but we didn't understand the location you entered.
Did you mean one of these previous locations: ...
```

1. For you: Try being more specific about the location.
2. For Yelp: We should be returning something that means ERROR_LOCATION_NOT_FOUND instead of a 500.

**Comment by mittonk** [comment]
@attaboy : Now being more helpful:
```
{
  "error": {
    "code": "VALIDATION_ERROR",
    "description": {
      "error": {
        "code": "LOCATION_NOT_FOUND",
        "description": "Could not execute search, try specifying a more exact location."
      }
    }
  }
}
```
