### ISSUE TITLE
Why doesn't it show me the confirmation dialog box that names the app and the permissions that I request = r2r? with yelp services

### ISSUE THREAD

**Issue by Global-Manu-Man** [Yelp/yelp-fusion#690]
I'm looking at the instructions that come in the yelp documentation of the Authorization Code Workflow process:

Base URL: GET https://biz.yelp.com/oauth2/authorize

Parameters:
- client_id,

- redirect_uri,

- response_type,

- scope,

- state.

r2r - enables respond to review permission.

`https://biz.yelp.com/oauth2/authorize?client_id=DCMI3aF1m74HiebWnlXJPg&redirect_uri=https://www.locallity.com.mx/registration&response_type=code&scope=r2r&state=2N2xXjANcjYRWMJ`

The question is the following: why doesn't the application authorize me, why doesn't it show me the confirmation dialog box that names the app and the permissions that I request = r2r?

The error is as follows:

error= oauth_client_info_not_found&error_description=Specified client has not been set up with OAuth client info

![image](https://github.com/Yelp/yelp-fusion/assets/84020431/175549ea-28b4-4f92-84ef-cfeef699f4e4)

I hope it shows me the permission confirmation window for the app.

![image](https://github.com/Yelp/yelp-fusion/assets/84020431/f17d60c9-71ae-4ea7-935b-ee663c1dd7d9)

**Comment by bizmate** [comment]
``error= oauth_client_info_not_found

**Comment by rockdog** [comment]
Hi @Global-Manu-Man,

the Respond To Reviews API is part of Partner APIs and hence you probably don't have access. You can read more on https://docs.developer.yelp.com/docs/respond-to-reviews-api-v2 and https://docs.developer.yelp.com/docs/yelp-partner-apis.
