### ISSUE TITLE
API Request for Self-User Info

### ISSUE THREAD

**Issue by kylekam** [Yelp/yelp-fusion#692]
Is it possible to access my own user information through the API, such as locations that I've reviewed? I found this older issue with a similar request but there wasn't any follow-up. https://github.com/Yelp/yelp-fusion/issues/666.

**Comment by rockdog** [comment]
Hi @kylekam, retrieving your own user information, such as reviews or bookmarks is currently not supported. We are tracking these feature requests internally but have no immediate plans to implement those.
