### ISSUE TITLE
Business Search Results are responding with unspecified results, validated with docs site

### ISSUE THREAD

**Issue by drbarq** [Yelp/yelp-fusion#695]
## Overview
- **Client ID:** arDiBdZpkyG0HRMeGqINBw
- **Issue type:** Search Results on api and within documentation
- **Summary:** a call to https://api.yelp.com/v3/businesses/search responds with all results except for the provided category
- **Platform:** Desktop/web, Docs

## Description
Hello Team,

Looking for some help with how to interact with the https://api.yelp.com/v3/businesses/search API.  

A request to 'https://api.yelp.com/v3/businesses/search?location=denver&term=restaurants&categories=Indian&locale=en_US&price=2&sort_by=best_match&limit=20'

Yields results all over the place.  This can be validated within the provided documentation site with the first result and through my own testing on my application

## More information
This was working earlier in the weekend and earlier today.  Am I interacting with the api incorrectly or did something change?

### Endpoint
Business Search : https://api.yelp.com/v3/businesses/search

### Parameters or Sample Request

Location: "Denver",
term: "restaurants".
categories: "indian"
price: 2

'https://api.yelp.com/v3/businesses/search?location=denver&term=restaurants&categories=Indian&locale=en_US&price=2&sort_by=best_match&limit=20'

### Response

This is just the first result from the yelp docs page : https://docs.developer.yelp.com/reference/v3_business_search

```
{
  "businesses": [
    {
      "id": "svJWwW0ilssyqk_UML0mUg",
      "alias": "work-and-class-denver",
      "name": "Work & Class",
      "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/UVm-9_NVYmstYrMvnfjuEw/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/work-and-class-denver?adjust_creative=arDiBdZpkyG0HRMeGqINBw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=arDiBdZpkyG0HRMeGqINBw",
      "review_count": 1777,
      "categories": [
        {
          "alias": "newamerican",
          "title": "New American"
        },
        {
          "alias": "latin",
          "title": "Latin American"
        },
        {
          "alias": "cocktailbars",
          "title": "Cocktail Bars"
        }
      ],
      "rating": 4.5,
      "coordinates": {
        "latitude": 39.75761,
        "longitude": -104.98604
      },
      "transactions": [
        "delivery"
      ],
      "price": "$$",
      "location": {
        "address1": "2500 Larimer St",
        "address2": "Ste 101",
        "address3": "",
        "city": "Denver",
        "zip_code": "80205",
        "country": "US",
        "state": "CO",
        "display_address": [
          "2500 Larimer St",
          "Ste 101",
          "Denver, CO 80205"
        ]
      },
      "phone": "+13032920700",
      "display_phone": "(303) 292-0700",
      "distance": 2801.724901630797
    },
    {
      "id": "GmniFxffmpFcbmb5KWIwbA",
      "alias": "culinary-dropout-denver-denver-4",
      "name": "Culinary Dropout",
      "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/qMsIbd4zbcsW5yI9jWg3OA/o.jpg",
      "is_closed": false,
      "url": "https://www.yelp.com/biz/culinary-dropout-denver-denver-4?adjust_creative=arDiBdZpkyG0HRMeGqINBw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=arDiBdZpkyG0HRMeGqINBw",
      "review_count": 702,
      "categories": [
        {
          "alias": "newamerican",
          "title": "New American"
        }
      ],
      "rating": 4,
      "coordinates": {
        "latitude": 39.73128133284685,
        "longitude": -104.93915937581268
      },
      "transactions": [],
      "price": "$$",
      "location": {
        "address1": "4141 E 9th Ave",
        "address2": "",
        "address3": null,
        "city": "Denver",
        "zip_code": "80220",
        "country": "US",
        "state": "CO",
        "display_address": [
          "4141 E 9th Ave",
          "Denver, CO 80220"
        ]
      },
      "phone": "+17207790190",
      "display_phone": "(720) 779-0190",
      "distance": 2699.046113689636
    },
   }
   
```
![Screenshot 2024-01-28 at 10 31 20 PM](https://github.com/Yelp/yelp-fusion/assets/8879523/0b42f186-89f2-4dfb-9864-fde71e1f3452)

## Extra information

Any help would be greatly appreciated.  Please let me know if there is anything else I can provide. 

Thank you

**Comment by rockdog** [comment]
Hi @drbarq, 

when executing search with the same parameters as mentioned above all search results seem to be in Denver. So I am not quite sure I fully understand what you mean by "all over the place". What exactly do you think is wrong with the results?
