### ISSUE TITLE
Unable to get oauth2.0 autherization API access end points for Yelp developer account.

### ISSUE THREAD

**Issue by snaplogicteam** [Yelp/yelp-fusion#696]
Hi Team,

I am new to this API access tokens. I tried to make a connection for API access end points but i was getting error. (Validation error and bearer token does not match). Even I did not receive any client secret code also. Can you please help me on this issue.

Regards,
Swathi

**Comment by snaplogicteam** [comment]
Hi Team,

Anyone could help me on this issue. And please considerate on this priority.

Thanks,
Swathi

**Comment by bizmate** [comment]
hi @snaplogicteam , this is not stackoverflow and it is not a training platform. Follow the documentation to the best of your knowledge. If you cannot understand the documentation check stackoverflow or post a question there.

You need to at least try to do something first, document it very well and then show what you are doing and why you think it is not working

**Comment by rockdog** [comment]
Hey @snaplogicteam, 

after signup you can access your API key at https://www.yelp.com/developers/v3/manage_app. 

In order to getting started let me point you to https://docs.developer.yelp.com/docs/fusion-authentication which also shows a simple Curl command.

Another example to test whether your access is working:

```
curl --request GET --url https://api.yelp.com/v3/categories --header 'Authorization: Bearer YOUR_API_KEY' --header 'accept: application/json'
```

**Comment by rockdog** [comment]
Hi @snaplogicteam, feel free to re-open if you are still running into issues.
