### ISSUE TITLE
Error upon submission of Create App form, unable to get Yelp Fusion API key

### ISSUE THREAD

**Issue by brookeseiter** [Yelp/yelp-fusion#697]
## Overview
- **Client ID:** none provided yet
- **Issue type:** creating an app/getting a Yelp Fusion API key
- **Summary:** receive error when attempting to submit create an app form on https://www.yelp.com/developers/v3/manage_app
- **Platform:** Desktop, iOS (both on safari and google chrome)

## Description
Create an App form was completely filled out with all necessary information. Upon submission, I received this error message: 'Something went wrong. Please refresh the page.' I am unable to submit the create app form and therefore have not been given an API key and am unable to create an app. I tried on several browsers (safari and google chrome) and came across this same issue. I already have a yelp account and used the same email in the form as the one connected to my yelp account. I am using my own laptop via my home's private wifi.

## More information
Bug: upon refreshing the page, my information is cleared out of the form and I noticed that the 'Create App' section of the toolbar on the left hand side of the page turns to 'Manage App' momentarily, then switches back to 'Create App.'

## Endpoint
https://www.yelp.com/developers/v3/manage_app

**Comment by rockdog** [comment]
Hi @brookeseiter, thanks for raising this. We are currently looking into this.

**Comment by ankur93** [comment]
Hi @brookeseiter,
Thanks for reaching out.

This is now resolved. You should be able to create an app now.
