### ISSUE TITLE
Unauthorized access token

### ISSUE THREAD

**Issue by raisk** [Yelp/yelp-fusion#698]
## Overview
- **Client ID:** _(e.g. lrVVpyP-aBRmP1I1KUqXkw)_
- **Issue type:** _unauthorized access token message_
- **Summary:** _calling the yelp api gives the unauthorized token message which used to work fine earlier_
- **Platform:** _Desktop/web_

## Description
_we use yelp api to fetch nearby data and display on the website, using the given keys and api it used to work just fine but recently its giving an unauthorized access token message instead of providing the data_

### Endpoint
_ufPLTrJmBMXsP3DRGzZ6fuSHhIoR0tLYwtiSUR7pBxxZhuaWGxtEuVLcmbDj7nK73ARUvxlR58WQMWmimRwZmFlH-AhoU1VquUQ1q1J-YWEt-dpBdEFNxQoKwy-WnYx_

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?categories=arts&term=arts&latitude=38.512806&longitude=-121.461752&location=Sacramento%2C+CA&limit=10&sort_by=distance
```

### Response
```
{"error": {"code": "UNAUTHORIZED_ACCESS_TOKEN", "description": "The access token provided is not currently able to query this endpoint."}}```

**Comment by rockdog** [comment]
Hi @raisk,

what's your Client ID? 

You can find it on this page: https://www.yelp.com/developers/v3/manage_app.

**Comment by rockdog** [comment]
@raisk I'm going to close this issue. If you still need help feel free to re-open.
