### ISSUE TITLE
how to call user controls to the main page from another page?

### ISSUE THREAD

**Issue by NikitaTurakhia** [Yelp/yelp-fusion#70]
hello,

I want to create an application where when I click on the button from main page, it will call user control page and will display text box with button to my main page and again when I click on the button displayed with the text box, it will again display another text box with the button in my main page. I want to do this multiple time.
Please help me with an example.

Thank you!

**Comment by mittonk** [comment]
@NikitaTurakhia : Sounds like your main question is around your programming language and app framework.  
1. What language and framework are you using --- C# and .NET?  Python and Flask?  Ruby and Rails?  etc.
2. For the general app flow you're describing, I'd suggest asking in a language- or framework-specific forum --- once you've got basic pages and forms and are trying to get data from the Yelp API, we can probably help more.
