### ISSUE TITLE
Yelp Events 

### ISSUE THREAD

**Issue by SeanOThomas** [Yelp/yelp-fusion#72]
Yelp Events returned by the Search API as business objects do not contain time fields. How is the "Upcoming Events" section of the Yelp app implemented?

**Comment by virgytam** [comment]
Hi @SeanOThomas, we don't return events as part of our Search API. Can you send an example response?

**Comment by SeanOThomas** [comment]
Is there another API that returns Yelp Events? I set a "yelpevents" category filter on the search. An example is below:  

Business{  
   id=yee-yelps-guys-night-out-hong-kong-tailors-atlanta,
   name=YEE:Yelp's Guys' Night Out @ Hong Kong Tailors,
   categories=   [  
      Category      {  
         alias=yelpevents,
         name=Yelp Events
      }
   ],
   displayPhone=null,
   distance=22386.165432367827,
   eat24Url=null,
   imageUrl=https://s3-media1.fl.yelpcdn.com/bphoto/iQxEOSkhS-aeEg6WwDsZ6w/ms.jpg,
   isClaimed=false,
   isClosed=false,
   menuProvider=null,
   menuDateUpdated=null,
   mobileUrl=https://m.yelp.com/biz/yee-yelps-guys-night-out-hong-kong-tailors-atlanta?adjust_creative=HQq91KkeLChrPUSbwziOQw&utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=HQq91KkeLChrPUSbwziOQw,
   phone=null,
   reservationUrl=null,
   reviewCount=7,
   snippetImageUrl=https://s3-media4.fl.yelpcdn.com/photo/EbQ9E5-Ibq_6GYbSgC6nLw/ms.jpg,
   snippetText=Well,
   I never...! Yes,
   this was truly a first all guys' night out Yelp Event. Girls get everything; more clothing options,
   more closet space,
   and exclusive...,
   url=https://www.yelp.com/biz/yee-yelps-guys-night-out-hong-kong-tailors-atlanta?adjust_creative=HQq91KkeLChrPUSbwziOQw&utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=HQq91KkeLChrPUSbwziOQw,
   deals=null,
   giftCertificates=null,
   location=Location   {  
      address=      [  
         5378         Buford Hwy NE
      ],
      city=Atlanta,
      coordinate=Coordinate      {  
         latitude=33.89927,
         longitude=-84.27929
      },
      countryCode=US,
      crossStreets=null,
      displayAddress=      [  
         5378         Buford Hwy NE,
         Atlanta,
         GA 30340
      ],
      geoAccuracy=8.0,
      neighborhoods=null,
      postalCode=30340,
      stateCode=GA
   },
   rating=5.0,
   ratingImgUrl=https://s3-media1.fl.yelpcdn.com/assets/2/www/img/f1def11e4e79/ico/stars/v1/stars_5.png,
   ratingImgUrlLarge=https://s3-media3.fl.yelpcdn.com/assets/2/www/img/22affc4e6c38/ico/stars/v1/stars_large_5.png,
   ratingImgUrlSmall=https://s3-media1.fl.yelpcdn.com/assets/2/www/img/c7623205d5cd/ico/stars/v1/stars_small_5.png,
   reviews=null
}

**Comment by mittonk** [comment]
Ah, I get it.

This is a purpose-built business entity that goes with an Event entity; it's much less useful without the Event entity which has times, waitlist parameters, etc.

That Event entity isn't available through the public API, classifying this as an enhancement request.

**Comment by tomelm** [comment]
Events API is now a thing! https://www.yelp.com/developers/documentation/v3/event_search

**Comment by flash5** [comment]
Hi, I am trying to integrate events obtained from yelp API v3 but there is a slight confusion. The event time given at the time_start and time_end nodes are different from what they're being displayed on yelp website. Also the document of V3 API doesn't provide any information regarding the timezone which makes it nearly impossible to get the correct time of any event. Any solution?
