### ISSUE TITLE
Document default locale en_US

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-fusion#73]
`locale` defaults to en_US for all the endpoints it applies to.

We should document this across the various endpoints like 
- https://www.yelp.com/developers/documentation/v3/business_search
  or possibly on 
- https://www.yelp.com/developers/documentation/v3/supported_locales 

When writing this, we should make the situation clearer around #66  (which asks for `locale=*`).

**Comment by dan98765** [comment]
Today we've added "Defaults to en_US" to the description of the `locale` parameter on the doc pages for endpoints that accept a `locale` param.
