### ISSUE TITLE
how to enable real distance filter for fusion api?

### ISSUE THREAD

**Issue by swizardlv** [Yelp/yelp-fusion#74]
Hi yelp expert,

By default , the radius filter is talking about service area. If i search by radius_filter=500 , usually get result out of 500 meters circle.

I find in yelp web page, there is a distance filter : Driving , Biking, walk, within 4 blocks. How can we use this in REST api?

Thanks in advance!

**Comment by mittonk** [comment]
@swizardlv : This is the same issue we've discussed in the older V3 API in https://github.com/Yelp/yelp-api/issues/155 .

Yelp Fusion treats "service areas" (mostly plumbers and other businesses that are mobile within a certain area) as being available right-here if the will come here to do their job.

If that meaning of "available here" isn't what you want, I'd suggest post-filtering results based on distance.

The "driving", "biking" etc filters are basically just certain settings for radius_filter.
