### ISSUE TITLE
Invalid Bearer Token should return a useful error message, not HTTP500

### ISSUE THREAD

**Issue by askedrelic** [Yelp/yelp-fusion#78]
Hi Ken!

```
$ curl -v -X GET -H "Authorization: Bearer iamnotabear" -H "Cache-Control: no-cache" "https://api.yelp.com/v3/businesses/search?term=delis&latitude=37.786882&longitude=-122.399972"
*   Trying 104.16.56.23...
* Connected to api.yelp.com (104.16.56.23) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: yelp.com
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> GET /v3/businesses/search?term=delis&latitude=37.786882&longitude=-122.399972 HTTP/1.1
> Host: api.yelp.com
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Bearer invalidbear
> Cache-Control: no-cache
> Postman-Token: bf7b8484-c155-4fa5-84b9-5c4e04b3bf85
>
< HTTP/1.1 500 Internal Server Error
< Date: Sat, 15 Oct 2016 10:52:17 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 226
< Connection: keep-alive
< Set-Cookie: __cfduid=ddf7b87f763ee5290a3315b53eb4384dd1476528736; expires=Sun, 15-Oct-17 10:52:16 GMT; path=/; domain=.yelp.com; HttpOnly
< X-Proxied: extlb4-r9-iad1
< Server: cloudflare-nginx
< CF-RAY: 2f22b87c0b711a93-DUS
<
<html>
 <head>
  <title>500 Internal Server Error</title>
 </head>
 <body>
  <h1>500 Internal Server Error</h1>
  The server has either erred or is incapable of performing the requested operation.<br/><br/>
 </body>
* Connection #0 to host api.yelp.com left intact
```

I see you commented about this recently, but just wanted to create a separate ticket for tracking. https://github.com/Yelp/yelp-fusion/issues/45#issuecomment-252120758

**Comment by askedrelic** [comment]
Interesting anecdote about this situation: I was at a hackathon this weekend trying to get some folks using the Yelp API. They were using the Paw OSX application and copy/pasting the Bearer token from the auth endpoint response. But their Paw window was small, the display of the JSON token was being cropped, so they were copying the cropped token (I noticed their token was only like 12~ chars long). When they switched to a raw text display of the response, they were able to copy the full token.

**Comment by mittonk** [comment]
Excellent, thanks for the extra ticket --- we've got several different 500 errors running around, and this helps us tackle each in turn.

I agree, an invalid bearer token should give a clear error message like 401, INVALID_TOKEN.

**Comment by mittonk** [comment]
@askedrelic : `"Authorization": "Bearer foobar"` now gives:
```
{
  "error": {
    "code": "TOKEN_INVALID",
    "description": "Invalid access token or authorization header."
  }
}
```
which should be much, much easier to debug.

**Comment by VisonChen** [comment]
lueluelue
