### ISSUE TITLE
Plans for exposing more business photos than 3?

### ISSUE THREAD

**Issue by kddude** [Yelp/yelp-fusion#8]
Do you have any plans for exposing the business photos via some API that are available for each business on their actual Yelp page? I've been hoping for this for a while and was super excited to see you've upped the number to 3 (if I'm understanding correctly), but the ability to query just the photos or get more by default would be awesome!

**Comment by guangyang** [comment]
Yeah, your understanding it correctly. And they are all original size/resolution so you'll get the best quality as well.

We are definitely looking for ways to help. Could you please help us understand your use case where you need more than 3 photos?

**Comment by kddude** [comment]
My specific use case is based off of my primary reason for using Yelp: I use the pictures a lot more to help influence where to eat rather than the reviews or a lot of the data on that side of the business' page.

I'd like to be able to just see a collage/slideshow of random pictures from nearby restaurants so that I can pick one that looks tasty and THEN drill down into the information on the business, rather than the opposite (finding a business, then looking at its pictures). I was hoping to develop an app or website that did this sort of thing, and easy access to the pictures would be great for this purpose and I'm sure a bunch of other uses I hadn't thought of yet.

Bumping up the default to 3 is greatly appreciated though already!

**Comment by apastel** [comment]
I would like to be able to fetch any of the photos for a business, especially by using the caption as a reference point. For example, at a Mexican restaurant I'd like to be able to fetch photos of their California burrito by combing through the photo captions for "california burrito". High level -- I want to be able to find pictures of any particular menu item that users may have uploaded.

**Comment by willyhoang** [comment]
:+1:

**Comment by kddude** [comment]
Still interested in the features apastel and I have asked for at some point -- would be awesome!

**Comment by CaptainCrunchTaco** [comment]
Any update on making this feature real?

**Comment by quytennis** [comment]
We do not have plans to provide more than 3 photos at this time; your apps should direct people who want to see more photos to the photos page for a given business at yelp.com - For example, direct people to this page to see more photos of Gary Danko: https://www.yelp.com/biz_photos/gary-danko-san-francisco

**Comment by lucaslupo** [comment]
I would strongly advise on reconsidering this, or at least to improve your algorithm to define what the best photos are because I keep encountering cases where of the three photos for a restaurant, I get the photo of the bathroom, and I don't see how that can be defined as the best photo
