### ISSUE TITLE
Authorization Header

### ISSUE THREAD

**Issue by IanRobbRB** [Yelp/yelp-fusion#81]
I am getting {"error": {"description": "An access token must be supplied in order to use this endpoint.", "code": "TOKEN_MISSING"}} when trying to call the API.

The cURL PHP I am using is as follows:

```
$curl = curl_init('https://api.yelp.com/v3/businesses/search?term='.$_GET['location'].'&latitude='.$_GET['latitude'].'&longitude='.$_GET['longitude'].'&radius=500');

curl_setopt($curl, CURLOPT_HTTPHEADER, 'Authorization: Bearer '.$_GET['token']);

curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$response = curl_exec($curl);

curl_close($curl);

echo $response;

```

I cannot work out where I am going wrong?

**Comment by mittonk** [comment]
My PHP's a little rusty, but let's compare your code against what Postman generates for "Code => PHP => cURL":
```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.yelp.com/v3/businesses/search?location=sf&term=coffee",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "authorization: Bearer REDACTED_MITTONK_TOKEN",
    "cache-control: no-cache",
    "postman-token: 847b5b90-6967-a4c7-24f9-a59341c3c2a3"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

There's a few differences, but the one that grabs my eye is you set CURLOPT_HTTPHEADER to a string, and Postman sets it to an array of strings.  That sounds pretty likely.

Checking the docs: http://php.net/manual/en/function.curl-setopt.php

I see:
> CURLOPT_HTTPHEADER	An array of HTTP header fields to set, in the format array('Content-type: text/plain', 'Content-length: 100')

So, try using an array for CURLOPT_HTTPHEADER.  Does that give you enough to run with?

**Comment by mittonk** [comment]
Hopefully that worked out, please comment or open a new issue if you have more problems.
