### ISSUE TITLE
Getting "description" and/or "restaurant website" from Yelp business API

### ISSUE THREAD

**Issue by tomelm** [Yelp/yelp-fusion#83]
From @kimmiies in yelp/yelp-ruby#52:

> Hi there,
> 
> We're trying to get some information from your website that we're not sure is available from the API. The two in particular are:
> 
> the restaurant website vs the yelp url for the restaurant
> a description of the restaurant or "from the business" description vs the snippet_text (which gives us random views).
> Any help or guidance would be greatly appreciated

**Comment by mittonk** [comment]
The business' own website isn't available through the API.

The "About This Business" text written by the business owner also isn't available.  (The `snippet_text` is drawn from user's reviews of the business.)

**Comment by Janpot** [comment]
I'm also interested in restaurant website. Is this on any kind of roadmap?
