### ISSUE TITLE
Possible to search more than one search term?

### ISSUE THREAD

**Issue by Vk12** [Yelp/yelp-fusion#85]
I was wondering if its possible to pass in multiple search terms into the parameters when doing a single business/search query. For example: I'd want 50 of the most relevant Mexican, Japanese, Chinese restaurants. 

Thanks in advance!

**Comment by mittonk** [comment]
Certainly.  If you're searching for terms, start with spaces between the words; when URL-encoded, this will end up looking like:
* https://api.yelp.com/v3/businesses/search?location=boston&term=burrito+sushi+noodles

If using category filters, draw your category aliases from 
* https://www.yelp.com/developers/documentation/v3/all_category_list
and separate them with commas:
* https://api.yelp.com/v3/businesses/search?location=boston&term=tasty&categories=mexican,japanese,chinese
