### ISSUE TITLE
Error token missing

### ISSUE THREAD

**Issue by futurikidis21** [Yelp/yelp-fusion#86]
I managed to get a token but when i do a get request i get the below message.
On header authentication where should put "Bearer" and the token.
It has a key and a value field.

Thank you

{
  "error": {
    "description": "An access token must be supplied in order to use this endpoint.",
    "code": "TOKEN_MISSING"
  }
}

**Comment by futurikidis21** [comment]
I think i did correctly now but any request i send i get the below message
`<html>
    <head>
        <title>400 Bad Request</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>400 Bad Request</h1>
        </center>
        <hr>
        <center>cloudflare-nginx</center>
    </body>
</html>`

**Comment by mittonk** [comment]
@futurikidis21 : What's one URL you're sending requests to, including the "https://api.yelp.com" part?

**Comment by futurikidis21** [comment]
I am testing  the following url but it returns the above error. 
https://api.yelp.com/v3/autocomplete?text=del&latitude=37.786882&longitude=-122.399972

**Comment by mittonk** [comment]
@futurikidis21 : Great, found some of your requests.

Looks like you've tried a few patterns for

Header Name ("Key" in Postman)   |  Header Value ("Value" in Postman)
--------|-------
MY_TOKEN  | Bearer
Bearer | MY_TOKEN
Token | MY_TOKEN

The correct setup is:

Header Name ("Key" in Postman)   |  Header Value ("Value" in Postman)
--------|-------
Authorization | Bearer MY_TOKEN

Want to give that a try?

**Comment by futurikidis21** [comment]
Thanks yes got it now. It works!!! Thank you very much...

**Comment by mittonk** [comment]
Excellent.
