### ISSUE TITLE
Getting fewer than 20 results in search

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-fusion#87]
@NikitaTurakhia writes:

>Hello,
>
>I am using yelp API v3.
>When I run business API with term restaurant, I am getting only 14 businesses instead of 20 and >when I run API with term pizza I am getting only 3 businesses.
>Please help me with this issue.
>
>Thank you,
>Nikita

@NikitaTurakhia : What are your full request URLs?  (In particular, I'm wondering if you're searching in an area that just doesn't have much pizza, or using a very small search `radius`, or similar.)

**Comment by NikitaTurakhia** [comment]
Hello,

my request url is: string yelpurl = "https://api.yelp.com/v3/autocomplete?text=" + pizza; and the area in which I am searching is 52 Mt Summer Dr, Bolton, CT 06043

When I enter this area and pizza for search in yelp I am getting more results.

**Comment by mittonk** [comment]
@NikitaTurakhia : 
1. Are you sure on that URL?  What you describe sounds more like
* https://api.yelp.com/v3/businesses/search?term=pizza&location=52+Mt+Summer+Dr,+Bolton,+CT+06043

which returns 3 businesses.

(In particular, Autocomplete is going to return a few categories and maybe some businesses, rather than lots of businesses; in addition, it requires a lat-long position and it sounds like you've got a location string.)

2. I do see 3 businesses on the Search API, and >10 on www.yelp.com:
* https://www.yelp.com/search?find_desc=Pizza&find_loc=52+Mt+Summer+Dr%2C+Bolton%2C+CT+06043&ns=1

So, I can reproduce the problem.  Poking it a little.

**Comment by NikitaTurakhia** [comment]
@mittonk 
Yes. I am giving the same URL and yesterday i was getting 3 results and today I am getting 4 results.

**Comment by mittonk** [comment]
@NikitaTurakhia : Are you using "search" or "autocomplete"?  I'm still a little unsure.

What actual results are you getting --- what's the response?  You can use a https://gist.github.com/ link or just paste the response in here.

**Comment by NikitaTurakhia** [comment]
@mittonk  sorry I am using search API: string yelpurl = "https://api.yelp.com/v3/businesses/search?term=" + izza + "&location=" + 52 Mt Summer Dr, Bolton, CT 06043+ "&offset=" + "&sort=0";

And I am getting this response:
"{\"total\": 3, \"businesses\": [{\"categories\": [{\"alias\": \"pizza\", \"title\": \"Pizza\"}, {\"alias\": \"italian\", \"title\": \"Italian\"}], \"price\": \"$$\", \"rating\": 3.0, \"phone\": \"+18606470345\", \"id\": \"georginas-pizza-restaurant-bolton\", \"url\": \"https://www.yelp.com/biz/georginas-pizza-restaurant-bolton?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ\", \"name\": \"Georgina's Pizza Restaurant\", \"review_count\": 29, \"image_url\": \"https://s3-media3.fl.yelpcdn.com/bphoto/1QI-Mwjqd-XJkrEv4yVc2Q/o.jpg\", \"location\": {\"city\": \"Bolton\", \"country\": \"US\", \"zip_code\": \"06043\", \"address2\": \"\", \"address3\": \"\", \"address1\": \"275 Boston Tpke\", \"state\": \"CT\"}, \"distance\": 598.2630683223999, \"coordinates\": {\"longitude\": -72.45847, \"latitude\": 41.78506}, \"is_closed\": false}, {\"categories\": [{\"alias\": \"movers\", \"title\": \"Movers\"}], \"rating\": 4.5, \"phone\": \"+16173195700\", \"id\": \"antons-movers-boston-5\", \"url\": \"https://www.yelp.com/biz/antons-movers-boston-5?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ\", \"name\": \"Anton's Movers\", \"review_count\": 322, \"image_url\": \"https://s3-media4.fl.yelpcdn.com/bphoto/kIsjjErEMLzo_6GjxFxllw/o.jpg\", \"location\": {\"city\": \"Boston\", \"country\": \"US\", \"zip_code\": \"02115\", \"address2\": \"Ste 301\", \"address3\": \"\", \"address1\": \"1005 Boylston St\", \"state\": \"MA\"}, \"distance\": 129203.06164839999, \"coordinates\": {\"longitude\": -71.0862448811531, \"latitude\": 42.3477143794298}, \"is_closed\": false}, {\"categories\": [{\"alias\": \"burgers\", \"title\": \"Burgers\"}, {\"alias\": \"chicken_wings\", \"title\": \"Chicken Wings\"}, {\"alias\": \"bars\", \"title\": \"Bars\"}], \"rating\": 3.5, \"phone\": \"+18606494684\", \"id\": \"three-js-cafe-bolton\", \"url\": \"https://www.yelp.com/biz/three-js-cafe-bolton?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ\", \"name\": \"Three J's Cafe\", \"review_count\": 4, \"image_url\": \"https://s3-media2.fl.yelpcdn.com/bphoto/FJM06uQWYmKSuA0FS3rhGg/o.jpg\", \"location\": {\"city\": \"Bolton\", \"country\": \"US\", \"zip_code\": \"06043\", \"address2\": \"\", \"address3\": \"\", \"address1\": \"124 Boston Tpke\", \"state\": \"CT\"}, \"distance\": 1041.515924064, \"coordinates\": {\"longitude\": -72.4656399339437, \"latitude\": 41.7839515954256}, \"is_closed\": false}]}"

**Comment by NikitaTurakhia** [comment]
Hello @mittonk:

Please message me when this problem get solved.

**Comment by mittonk** [comment]
@NikitaTurakhia : Certainly!

**Comment by mittonk** [comment]
* https://api.yelp.com/v3/businesses/search?term=pizza&location=52+Mt+Summer+Dr,+Bolton,+CT+06043

now shows 10 results, and 
```
"total": 308
```

@NikitaTurakhia : Things now look good to me, please give it a try.

**Comment by NikitaTurakhia** [comment]
Thank you @mittonk 

It's working perfectly.
