### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by ShermanTank4** [Yelp/yelp-fusion#88]
I'm using postman and continue to get "500 internal server error" when trying to use my access token as the header value.  I'm using the value Bearer access_token and I'm sure my token is typed in correctly.  I'm new to the whole coding thing so I'm sure it's possible I'm messing up on a really easy step.  Thanks for the help!

**Comment by ShermanTank4** [comment]
Figured it out, nevermind

**Comment by tomelm** [comment]
What was it?

**Comment by mittonk** [comment]
(I'd expect the header to look like:

Header Name ("Key" in Postman)   |  Header Value ("Value" in Postman)
--------|-------
Authorization | Bearer MY_TOKEN
)
