### ISSUE TITLE
Apostrophe Issue

### ISSUE THREAD

**Issue by IanRobbRB** [Yelp/yelp-fusion#89]
I am having a problem when searching for locations that contain an apostrophe in the name. 

`$curl = curl_init('https://api.yelp.com/v3/businesses/search?term='.rawurlencode($_POST['location']).'&latitude='.$_POST['latitude'].'&longitude='.$_POST['longitude'].'&radius=500');`

I am getting the response {"businesses": [], "total": 0} even though the business does have a profile.

**Comment by tomelm** [comment]
Hey @IanRobbRB what business are you searching for?

**Comment by IanRobbRB** [comment]
Tyler's Kiln, Latitude 51.308251643957 Longitude 1.069603024223

**Comment by tomelm** [comment]
Looking at their business page, they don't have any reviews at the moment: https://www.yelp.co.uk/biz/the-tylers-kiln-canterbury

The API doesn't return businesses that don't have reviews so I'm guessing it's that instead of the apostrophe (unless you have other examples).

**Comment by mittonk** [comment]
* https://api.yelp.com/v3/businesses/search?term=peet%27s+coffee&location=berkeley

works as expected (finds "Peet's Coffee") via Postman, curl, etc.

* https://api.yelp.com/v3/businesses/search?term=peet's coffee&location=berkeley
works as expected in Postman (which is fairly lenient about encoding).

I concur, the core issue here is 0 reviews on Tyler's Kiln.

Filed more targeted #90 to clearly document that policy, closing this one.
