### ISSUE TITLE
Returned distance unit in meter?

### ISSUE THREAD

**Issue by peterpeterparker** [Yelp/yelp-fusion#91]
Hi,

Its the unit of the returned distance of the /businesses/search API always in meter? If no, how could I now which unit is returned?

I tried to define the locale while querying the API but I guess I always get back a number, therefore I wanted to clear that question. Thx in advance for your answer.

https://www.yelp.co.uk/developers/documentation/v3/business_search

**Comment by tomelm** [comment]
Hey @peterpeterparker! It's always in meters regardless of locale.

**Comment by tomelm** [comment]
I'll clarify this in the docs

**Comment by mittonk** [comment]
Better now: https://www.yelp.co.uk/developers/documentation/v3/business_search
> This returns meters regardless of the locale.
