### ISSUE TITLE
search api result and yelp.com results are not same

### ISSUE THREAD

**Issue by NikitaTurakhia** [Yelp/yelp-fusion#92]
Hey @mittonk ,

I know I am bothering you so much but please help me in this.
I am working on yelp api v3. When I enter starbucks as aterm in search_api it gives me 70 results, where in when I enter starbucks in yelp.com, it is giving me only 14 results.
How is it possible?

Thanks,
Nikita

**Comment by mittonk** [comment]
@NikitaTurakhia : What specific queries are you using?

This sounds different from #75 , so I'd like to get some details.

**Comment by NikitaTurakhia** [comment]
Hello,


When I use below query to get the result, I got 72 results. But, when I enter the same location and term in the yelp.com, i got only 18 results.



string yelpurl = "https://api.yelp.com/v3/businesses/search?term=" + STARBUCKS + "&location=" + 52 Mt Summer Dr, Bolton, CT 06043 + "&offset=" + 20 + "&sort=0";


Result:


{"businesses": [{"is_closed": false, "phone": "+18605596984", "coordinates": {"longitude": -72.4950957966791, "latitude": 41.830976954653}, "rating": 4.0, "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/GTAeHC39JVoxKw2OY4-c1w/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-vernon-5?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 6578.56992896, "name": "Starbucks", "id": "starbucks-vernon-5", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 9, "location": {"state": "CT", "address1": "135 Talcottville Rd", "country": "US", "address3": null, "zip_code": "06066", "address2": "", "city": "Vernon"}}, {"is_closed": false, "phone": "+18606471523", "coordinates": {"longitude": -72.5687149662815, "latitude": 41.7673800033298}, "rating": 4.0, "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/3q7D__oARdNJhHayq47xQA/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/starbucks-manchester-38?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 9656.52602068, "name": "Starbucks", "id": "starbucks-manchester-38", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 19, "location": {"state": "CT", "address1": "185 Spencer St", "country": "US", "address3": "", "zip_code": "06040", "address2": "", "city": "Manchester"}}, {"is_closed": false, "phone": "+18606441919", "coordinates": {"longitude": -72.5264882738965, "latitude": 41.8132882522022}, "rating": 2.5, "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/3Cp7xVGneErIzLTb-mNptg/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-manchester-22?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 7056.1029498, "name": "Starbucks", "id": "starbucks-manchester-22", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 38, "location": {"state": "CT", "address1": "172 Deming St", "country": "US", "address3": null, "zip_code": "06042", "address2": null, "city": "Manchester"}}, {"is_closed": false, "phone": "+18606443736", "coordinates": {"longitude": -72.5589328785953, "latitude": 41.8056133709588}, "rating": 3.0, "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/80B9EB_txyI2Ms6qqyNt5g/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-manchester-34?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 9167.45725072, "name": "Starbucks", "id": "starbucks-manchester-34", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 26, "location": {"state": "CT", "address1": "1428 Pleasant Valley Rd", "country": "US", "address3": "", "zip_code": "06040", "address2": "", "city": "Manchester"}}, {"is_closed": false, "phone": "+18606484088", "coordinates": {"longitude": -72.5458908, "latitude": 41.8068619}, "rating": 2.5, "image_url": "", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-manchester-31?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 8193.830047083999, "name": "Starbucks", "id": "starbucks-manchester-31", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 3, "location": {"state": "CT", "address1": "194 Buckland Hills Dr", "country": "US", "address3": "", "zip_code": "06042", "address2": "Ste 2500", "city": "Manchester"}}, {"is_closed": false, "phone": "+18606528945", "coordinates": {"longitude": -72.6202634658202, "latitude": 41.7202429027464}, "rating": 4.0, "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/yglHEL52bOqRyB7kMFHbdA/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-glastonbury-2?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 15361.83185549, "name": "Starbucks", "id": "starbucks-glastonbury-2", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 22, "location": {"state": "CT", "address1": "140 Glastonbury Blvd", "country": "US", "address3": "", "zip_code": "06033", "address2": "", "city": "Glastonbury"}}, {"is_closed": false, "phone": "+18603682434", "coordinates": {"longitude": -72.6068842, "latitude": 41.7125283}, "rating": 3.0, "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/mjc_kcJuOU-GyUW1fxCgDg/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-glastonbury?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 14793.91186289, "name": "Starbucks", "id": "starbucks-glastonbury", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 22, "location": {"state": "CT", "address1": "70 Hebron Ave", "country": "US", "address3": null, "zip_code": "06033", "address2": null, "city": "Glastonbury"}}, {"is_closed": false, "phone": "+18606528925", "coordinates": {"longitude": -72.5946900621057, "latitude": 41.7068701583261}, "rating": 3.0, "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/JJCcsGxdVFgxYmC2AyH5ow/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-glastonbury-3?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 14281.289597359999, "name": "Starbucks", "id": "starbucks-glastonbury-3", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 1, "location": {"state": "CT", "address1": "Stop Shop", "country": "US", "address3": "", "zip_code": "06033", "address2": "55 Oak St", "city": "Glastonbury"}}, {"is_closed": false, "phone": "+18605295228", "coordinates": {"longitude": -72.6558202, "latitude": 41.6911136}, "rating": 3.5, "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/_R1X9ZeIelfjdFq3sht35A/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-wethersfield?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 19369.07638544, "name": "Starbucks", "id": "starbucks-wethersfield", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 29, "location": {"state": "CT", "address1": "1090 Silas Deane Hwy", "country": "US", "address3": null, "zip_code": "06109", "address2": "", "city": "Wethersfield"}}, {"is_closed": false, "coordinates": {"longitude": -72.6516330242157, "latitude": 41.8901941212029}, "rating": 2.5, "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/IY26NxL2yLJp5hRfvdZ-qA/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/starbucks-windsor-2?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 20442.75722248, "name": "Starbucks", "id": "starbucks-windsor-2", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 5, "location": {"state": "CT", "address1": "201-865 High Path Rd", "country": "US", "address3": "", "zip_code": "06095", "address2": "", "city": "Windsor"}}, {"is_closed": false, "phone": "+18608717797", "coordinates": {"longitude": -72.4746796488762, "latitude": 41.8648403137922}, "rating": 4.0, "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/Q_UYTYJJfn_E7XjeZ3tz9Q/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/kevins-coffee-roasters-vernon-rockville?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 9529.994077189998, "name": "Kevin's Coffee Roasters", "id": "kevins-coffee-roasters-vernon-rockville", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 33, "location": {"state": "CT", "address1": "78 Windsor Ave", "country": "US", "address3": "", "zip_code": "06066", "address2": "", "city": "Vernon Rockville"}}, {"is_closed": false, "phone": "+18604544202", "coordinates": {"longitude": -72.486412, "latitude": 41.8459206}, "rating": 4.5, "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/h2zAtX5pQTNxz3OOsEZz_g/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/great-harvest-bread-company-vernon?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 7741.912891024, "name": "Great Harvest Bread Company", "id": "great-harvest-bread-company-vernon", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}, {"alias": "bakeries", "title": "Bakeries"}, {"alias": "sandwiches", "title": "Sandwiches"}], "review_count": 22, "location": {"state": "CT", "address1": "425 Talcottville Rd", "country": "US", "address3": "", "zip_code": "06066", "address2": null, "city": "Vernon"}}, {"is_closed": false, "phone": "+18604321805", "coordinates": {"longitude": -72.5206146240234, "latitude": 41.7717437744141}, "rating": 5.0, "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/pKJB4dYEbfw3JmD2Pu5JuA/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/silk-city-coffee-manchester?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 5640.910347786, "name": "Silk City Coffee", "id": "silk-city-coffee-manchester", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}, {"alias": "bakeries", "title": "Bakeries"}, {"alias": "pretzels", "title": "Pretzels"}], "review_count": 22, "location": {"state": "CT", "address1": "763 Main St", "country": "US", "address3": "", "zip_code": "06040", "address2": null, "city": "Manchester"}}, {"is_closed": false, "phone": "+18606435763", "coordinates": {"longitude": -72.5421146, "latitude": 41.7645311}, "rating": 4.5, "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/RY0qZWWIJ4utmWRk5Rd7Bg/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/king-donuts-manchester?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 7551.032292303999, "name": "King Donuts", "id": "king-donuts-manchester", "categories": [{"alias": "donuts", "title": "Donuts"}, {"alias": "coffee", "title": "Coffee & Tea"}, {"alias": "bagels", "title": "Bagels"}], "review_count": 19, "location": {"state": "CT", "address1": "467 Hartford Rd", "country": "US", "address3": "", "zip_code": "06040", "address2": "", "city": "Manchester"}}, {"is_closed": false, "phone": "+18606574466", "coordinates": {"longitude": -72.6092224121094, "latitude": 41.7123260498047}, "rating": 4.0, "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/LByeL2Ju9T7jMA7dKdySQA/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/daybreak-coffee-roasters-glastonbury-2?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 14964.59122126, "name": "Daybreak Coffee Roasters", "id": "daybreak-coffee-roasters-glastonbury-2", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 105, "location": {"state": "CT", "address1": "2377 Main St", "country": "US", "address3": "", "zip_code": "06033", "address2": null, "city": "Glastonbury"}}, {"is_closed": false, "phone": "+18607425114", "coordinates": {"longitude": -72.3697478, "latitude": 41.7972601}, "rating": 3.5, "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/ONUw3OWbhAhZNV00DZpf8w/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/dunkin-donuts-coventry-5?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 7230.423922722, "name": "Dunkin' Donuts", "id": "dunkin-donuts-coventry-5", "categories": [{"alias": "donuts", "title": "Donuts"}, {"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 9, "location": {"state": "CT", "address1": "3516 Main St", "country": "US", "address3": null, "zip_code": "06238", "address2": null, "city": "Coventry"}}, {"is_closed": false, "phone": "+18604305866", "coordinates": {"longitude": -72.574732080102, "latitude": 41.717570731228}, "rating": 5.0, "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/JlUncKkxmQZCP2STt-4sDQ/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/berkins-blend-cafe-glastonbury?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 12241.745656579998, "name": "Berkins Blend Cafe", "id": "berkins-blend-cafe-glastonbury", "categories": [{"alias": "desserts", "title": "Desserts"}, {"alias": "coffee", "title": "Coffee & Tea"}, {"alias": "internetcafe", "title": "Internet Cafes"}], "review_count": 26, "location": {"state": "CT", "address1": "1003 Hebron Ave", "country": "US", "address3": "", "zip_code": "06033", "address2": "", "city": "Glastonbury"}}, {"is_closed": false, "phone": "+18606481443", "coordinates": {"longitude": -72.52828, "latitude": 41.81388}, "rating": 2.0, "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/pMLueHav-vH-qcRoHS2vSA/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/dunkin-donuts-manchester-29?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 7212.037213221999, "name": "Dunkin' Donuts", "id": "dunkin-donuts-manchester-29", "categories": [{"alias": "donuts", "title": "Donuts"}, {"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 9, "location": {"state": "CT", "address1": "210 Deming St", "country": "US", "address3": null, "zip_code": "06042", "address2": null, "city": "Manchester"}}, {"is_closed": false, "phone": "+18606331499", "coordinates": {"longitude": -72.6144122, "latitude": 41.7205619}, "rating": 4.0, "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/Ltf40PRp_rcYt6bq_EChxw/o.jpg", "price": "$$", "url": "https://www.yelp.com/biz/down-to-earth-tea-and-coffee-house-glastonbury?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 14910.40474346, "name": "Down to Earth Tea & Coffee House", "id": "down-to-earth-tea-and-coffee-house-glastonbury", "categories": [{"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 62, "location": {"state": "CT", "address1": "2860 Main St", "country": "US", "address3": "", "zip_code": "06033", "address2": null, "city": "Glastonbury"}}, {"is_closed": false, "phone": "+18606449195", "coordinates": {"longitude": -72.5529327392578, "latitude": 41.8064155578613}, "rating": 4.0, "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/MQxbza5aWaBLaNcEcLWq0w/o.jpg", "price": "$", "url": "https://www.yelp.com/biz/dunkin-donuts-manchester-6?adjust_creative=LP7cNZ4wcTZL3aW5iBgomQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=LP7cNZ4wcTZL3aW5iBgomQ", "distance": 8724.16535239, "name": "Dunkin' Donuts", "id": "dunkin-donuts-manchester-6", "categories": [{"alias": "donuts", "title": "Donuts"}, {"alias": "coffee", "title": "Coffee & Tea"}], "review_count": 2, "location": {"state": "CT", "address1": "80 Buckland Hills Dr", "country": "US", "address3": "", "zip_code": "06040", "address2": "", "city": "Manchester"}}], "total": 72}

________________________________

**Comment by NikitaTurakhia** [comment]
Hello @mittonk ,

Did you get any solution for this issue?

**Comment by mittonk** [comment]
1. Definitely different from #75 , you're getting plenty of name matches.
2. Looks related to your earlier issue #87 about radius
3. When I search https://www.yelp.com/search?find_desc=Starbucks&find_loc=52+Mt+Summer+Dr%2C+Bolton%2C+CT+06043&ns=1 I see 50 results, more in line with the API response.

I suspect you've got a distance filter or custom map view on your WWW search, could you check that?

**Comment by NikitaTurakhia** [comment]
I checked but I did not use any distance filter in it...

**Comment by mittonk** [comment]
1. "ns=1" isn't relevant to this discussion, removed.
2. After you do a search on Yelp, and see your 14 results, what's the full URL in your browser?  Please copy-paste it in here.  It'll likely have lots of extra stuff (maybe "ns=1", maybe "choq=0", etc) --- I'd like to see exactly what.

**Comment by NikitaTurakhia** [comment]
Hello,
I am getting below picture after 2nd page in yep.com.
![error](https://cloud.githubusercontent.com/assets/21182650/20798723/eb65a034-b7ad-11e6-9852-9294b0413166.png)

**Comment by mittonk** [comment]
Wonderful, having the exact link and screenshot helps a lot.

I can reproduce the behavior you're seeing on www.yelp.com :
* https://www.yelp.com/search?find_desc=starbucks&find_loc=52+mt+sumner+dr,bolton,ct+06043&start=10 says "Showing 11-20 of 50" but shows 8 actual matches.
* https://www.yelp.com/search?find_desc=starbucks&find_loc=52+mt+sumner+dr,bolton,ct+06043&start=20 says "Showing 21-30 of 50" but shows 0 actual matches.

So, I'm very suspicious of that "maximum number of matches" on WWW, and somewhat suspicious on the API as well.  

Next step: Actually page through the API search results, and compare them to the WWW search results by name or ID, rather than just comparing "total number".

**Comment by NikitaTurakhia** [comment]
I am getting only 10 matching results in my api where in www.yelp.com, it is showing only 5 matching results till page 2 and after that its showing the error page which i have sent you in previous message.

**Comment by mittonk** [comment]
@NikitaTurakhia : I'm confused, you say 
> I am getting only 10 matching results in my api 

but your output above shows 20 results.

**Comment by NikitaTurakhia** [comment]
I meant when I am running my API I got only 10 results matching with my term rest are others

**Comment by mittonk** [comment]
Ah, I see.
```
"starbucks-vernon-5"
"starbucks-manchester-38"
"starbucks-manchester-22"
"starbucks-manchester-34"
"starbucks-manchester-31"
"starbucks-glastonbury-2"
"starbucks-glastonbury"
"starbucks-glastonbury-3"
"starbucks-wethersfield"
"starbucks-windsor-2"
"kevins-coffee-roasters-vernon-rockville"
"great-harvest-bread-company-vernon"
"silk-city-coffee-manchester"
"king-donuts-manchester"
"daybreak-coffee-roasters-glastonbury-2"
"dunkin-donuts-coventry-5"
"berkins-blend-cafe-glastonbury"
"dunkin-donuts-manchester-29"
"down-to-earth-tea-and-coffee-house-glastonbury"
"dunkin-donuts-manchester-6"
```
Yelp search is _not_ just a business name search --- for example, "dunkin-donuts-coventry-5" has a review that says "far better than Starbucks".

Those non-Starbucks matches are expected.

**Comment by NikitaTurakhia** [comment]
Okay thanks.
