### ISSUE TITLE
how to get Price range i.e $11-30 in yelp Search API

### ISSUE THREAD

**Issue by mubakhan99** [Yelp/yelp-fusion#93]
I am having some issues with Yelp Search API i.e. I can't find Restaurant's Price range in JSON response which with $ icons in Yelp Web Application and Mobile App shown in attachment
So i need support regarding this
Thanks

**Comment by mittonk** [comment]
* https://www.yelp.com/developers/documentation/v3/business_search 

suggests the `price` key:
* https://api.yelp.com/v3/businesses/search?term=bar&location=boston
```
{
  "businesses": [
    {
      "price": "$$$",
      "id": "yvonnes-boston",
      "name": "Yvonne's",
...
```

So, that's got the "$$$" part.  Are you asking about the "11-30" part?

**Comment by mubakhan99** [comment]
Hi mittonk thanks, thats  what i was looking for, yes i would be interested in price range too
Currently i noticed i am using api version 2, how can i upgrade to version 3 api because i don't see any procedure in my developer console.
e.g. using version 2 Api
Link: https://api.yelp.com/**v2**/search/?location=San%20Francisco,%20CA
i get response which lacks price details
but i can't use version 3 Api which has price details like you showed me
i.e.
Link: https://api.yelp.com/**v3**/search/?location=San%20Francisco,%20CA
it says : 
{"error": {"description": "Resource could not be found", "code": "NOT_FOUND"}}

thanks for your time
thanks

**Comment by mittonk** [comment]
For V3, you'll need a separate set of keys, and different OAuth authorization steps.  See the upgrade guide here:
* https://www.yelp.com/developers/documentation/v3/get_started

The API Console doesn't yet support V3 --- for that sort of clicking-around-exploring, most people use a tool called Postman instead (there's instructions in the Get Started page).

**Comment by mubakhan99** [comment]
Hi mittonk thanks, thats what i was looking for, yes i would be interested
in price range too
Currently i noticed i am using api version 2, how can i upgrade to version
3 api because i don't see any procedure in my developer console.
e.g. using version 2 Api
Link: https://api.yelp.com/**v2**/search/?location=San%20Francisco,%20CA
i get response which lacks price details
but i can't use version 3 Api which has price details like you showed me
i.e.
Link: https://api.yelp.com/**v3**/search/?location=San%20Francisco,%20CA
it says :
{"error": {"description": "Resource could not be found", "code":
"NOT_FOUND"}}

thanks for your time
thanks

**Comment by mittonk** [comment]
@mubakhan99 : Fusion (aka V3) uses different URLs:
* https://api.yelp.com/v3/businesses/search?term=bar&location=boston

not  https://api.yelp.com/v3/search/?location=San%20Francisco,%20CA
