### ISSUE TITLE
oauth2 token expire_in 6773249 instead of 15552000

### ISSUE THREAD

**Issue by peterpeterparker** [Yelp/yelp-fusion#94]
Hi,

According the following documentation page, the oauth2 token should expire after 15552000 seconds but I just noticed, that at least in my case, the token I get will expire in 6773249 seconds.

https://www.yelp.co.uk/developers/documentation/v3/get_started

Is something wrong with my app?

**Comment by peterpeterparker** [comment]
now seems I get 6772790....understood even when I ask for a new token if I had a previous one I will get it till it expirate. Sorry for dumb question.

**Comment by tonybadguy** [comment]
I noticed the same thing. Maybe reopen the issue? I think the documentation is misleading for this and should be updated.

**Comment by peterpeterparker** [comment]
as @tonybadguy noticed, maybe would be cool to improve the documentation about it?

**Comment by tonybadguy** [comment]
Sorry I already opened an issue for this and something else I found on https://github.com/Yelp/yelp-fusion/issues/98 so ok to close

**Comment by peterpeterparker** [comment]
sure
