### ISSUE TITLE
What are the possible error codes/descriptions for the Reviews API

### ISSUE THREAD

**Issue by Sticksword** [Yelp/yelp-fusion#95]
I am trying to build a service on top of the Reviews API and I would like to know how to handle all of the error cases. For example, what happens when I go over the rate limit of 25,000? I also noticed that for an invalid token, I get a 500 response. Is this right? What about an expired token? Also 500? I have not checked yet for this case. Ideally, I think this should be added as a chart of some sort to the documentation page. Thank you!

**Comment by mittonk** [comment]
Most 500 responses are bugs on our side --- we're working through those and changing them to either give good results (a 200) or a helpful error message (usually a 400).

Sounds like you might be talking about #78  in particular.

**Comment by mittonk** [comment]
We don't yet have a comprehensive list of errors --- that's definitely a future plan.

**Comment by Sticksword** [comment]
Oh okay thanks! Would you happen to know what happens when I go over the rate limit? Would there be a 500 or a 400?

**Comment by Sticksword** [comment]
Also, is the rate limit simply based on account/app_id or based on IP address? I ask on behalf of a company that wishes to integrate with the Yelp Reviews API.

**Comment by mittonk** [comment]
@Sticksword :
1. We definitely still need error documentation.   Leaving this issue open to cover that angle.
2. #78 fixed, that 500 is now a 401 with a helpful error message.
3. Over Limit will be HTTP 429, again with a helpful error message.
4. Limit is by `app_id`, and each app should have only one `app_id`.

**Comment by gfairchild** [comment]
Any ETA on getting that full list of possible errors? I'm the developer of [yelpapi](https://github.com/gfairchild/yelpapi), and I'm transitioning the project to the new Fusion API. I want to make sure I'm properly capturing errors.

**Comment by iqnivek** [comment]
This might be a separate issue, but I've been seeing intermittent but regular 500s and 504s with yelp fusion business/reviews requests.. is that API instability? The errors seem to happen every day or two.
