### ISSUE TITLE
How is possible to search?

### ISSUE THREAD

**Issue by cendelinova** [Yelp/yelp-fusion#97]
Hello,
I would like to ask what kind of local bussiness I can search it could be also pet shops? I need to get a list of pet shops, vets. I am not sure if I can do it with Yelp API.

Thanks for answers

Petra

**Comment by mittonk** [comment]
@cendelinova : I'd probably start with a "Search" for `categories=petstore` in your area:
* https://www.yelp.com/developers/documentation/v3/business_search
* https://www.yelp.com/developers/documentation/v3/all_category_list

Something like 
* https://api.yelp.com/v3/businesses/search?categories=petstore&location=boston
```
{
  "businesses": [
    {
      "name": "Fish & Bone",
      "categories": [
        {
          "alias": "petstore",
          "title": "Pet Stores"
        }
      ],
      "review_count": 73,
      "url": "https://www.yelp.com/biz/fish-and-bone-boston?adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ssWONR4BhYiARowH3vsVEA",
...
```

You'll need to do some programming and set up authentication (basically an API password):
* https://www.yelp.com/developers/documentation/v3/get_started

Good luck, and please file another issue if you get stuck!

**Comment by cendelinova** [comment]
Thank so much. I am looking at the website. Some of them are available in the Czech Republic. Great!!

**Comment by cendelinova** [comment]
When its written next to category all what does it mean? Is it available for whole countries or am I supposed to understand? Thanks
