### ISSUE TITLE
Bad search results compared to Yelp website

### ISSUE THREAD

**Issue by tonybadguy** [Yelp/yelp-fusion#99]
Hi I noticed that the search results from the API were not as good as the website. Not sure why that is.

I  did a search for
```
{
    term:'san diego zoo',
    location: 'San Diego, CA',
    sort_by:'best_match'
}
```

The top result that I get back from the API is ```comfort-inn-and-suites-san-diego-zoo-seaworld-area-san-diego```, which is way off.

I do the same search from the Yelp website with the same term, location, and sort by and got ```san-diego-zoo-san-diego``` which is spot on.

Any idea why? Am I missing some parameters?

**Comment by mittonk** [comment]
This looks like another example of our name-match woes in #75 .

**Comment by mittonk** [comment]
Looks like this sorted itself out,
* https://api.yelp.com/v3/businesses/search?term=san+diego+zoo&location=San+Diego,+CA&sort_by=best_match

now shows `san-diego-zoo-san-diego` as the top match.

Not a very satisfying explanation (could have been a sporadic indexing issue, or location oddness, etc), but at least the response is correct --- closing.
